/**
 * Phase 3H — Draw Runtime (capability-local public surface).
 * Integrator owns root competition-core/index.js re-exports — do not edit that here.
 */

export {
  createDrawResolver,
  DrawResolver,
} from "./DrawResolver.js";

export {
  createLegacyDrawAdapter,
  LegacyDrawAdapter,
  DRAW_CERTIFICATION_ERROR_CODE,
  DRAW_CERTIFICATION_ERROR_CODE_VALUES,
  isDrawCertificationErrorCode,
  createDrawCertificationError,
  createDrawCertificationOk,
  MODE_MAPPING_STATUS,
  LEGACY_TO_PHASE3H_MODE_MATRIX,
  findModeMappingRow,
  mapLegacyModeToPhase3h,
  mapCertificationInputToDrawResolveRequest,
  groupNumberToLabel,
  mapCanonicalResultToLegacyGroups,
  membershipByLabel,
  runCertificationResolve,
  SEEDED_GROUPING_ADAPTER_ID,
  runSeededGroupingAdapter,
  OPEN_CONDITIONAL_ADAPTER_ID,
  runOpenConditionalAdapter,
  TEAM_TOURNAMENT_GROUPING_ADAPTER_ID,
  runTeamTournamentGroupingAdapter,
  CONSTRAINT_GROUPING_ADAPTER_ID,
  runConstraintGroupingAdapter,
  CC04_COMPAT_BRIDGE_ID,
  CC04_BRIDGE_POLICY,
  runCc04CompatibilityBridge,
} from "./adapters/index.js";

export {
  createDrawResolveRequest,
  createDrawRequest,
  createDrawResolveResult,
  drawResolveOk,
  drawResolveFail,
  createDrawResult,
  DRAW_ADAPTER_ID,
  isDrawAdapter,
  DRAW_IDENTITY_KIND,
  DRAW_CANDIDATE_IDENTITY_KIND,
  DRAW_GROUP_IDENTITY_KIND,
  DRAW_BRACKET_IDENTITY_KIND,
  DRAW_SLOT_IDENTITY_KIND,
  DRAW_PLACEMENT_IDENTITY_KIND,
  DRAW_BYE_IDENTITY_KIND,
  buildDrawIdentityKey,
  buildCandidateIdentityKey,
  buildGroupIdentityKey,
  buildBracketIdentityKey,
  buildSlotIdentityKey,
  buildPlacementIdentityKey,
  buildByeIdentityKey,
  createDrawIdentity,
  createDrawCandidate,
  createDrawSeedReference,
  mapSeedAssignmentToReference,
  createDrawPlacement,
  createDrawGroup,
  createDrawBracket,
  createDrawBye,
  createDrawSnapshot,
  createDrawPolicyResult,
  isDrawPolicy,
} from "./contracts/index.js";

export {
  DRAW_RUNTIME_ERROR_CODE,
  DRAW_RUNTIME_ERROR_CODE_VALUES,
  isDrawRuntimeErrorCode,
  DrawRuntimeError,
  isDrawRuntimeError,
  createDrawRuntimeError,
} from "./errors/index.js";

export {
  DRAW_MODE,
  DRAW_MODE_VALUES,
  isDrawMode,
  GROUP_DRAW_MODES,
  BRACKET_DRAW_MODES,
  LAYOUT_TYPE,
  LAYOUT_TYPE_VALUES,
  isLayoutType,
  PLACEMENT_TYPE,
  PLACEMENT_TYPE_VALUES,
  isPlacementType,
  PLACEMENT_REASON,
  PLACEMENT_REASON_VALUES,
  isPlacementReason,
  CANDIDATE_TYPE,
  CANDIDATE_TYPE_VALUES,
  isCandidateType,
} from "./enums/index.js";

export {
  isLegacyDrawSource,
  mapLegacyDrawToCandidates,
} from "./mappers/index.js";

export {
  DRAW_PERSISTENCE_PORT_METHODS,
  matchesDrawPersistencePort,
  createInMemoryDrawPersistencePort,
  createNoopDrawPersistencePort,
  matchesConstraintResolver,
  normalizeConstraintResolver,
  freezeConstraintResolveInput,
} from "./ports/index.js";

export {
  createNoopDrawPolicy,
  NOOP_DRAW_POLICY_ID,
} from "./policies/index.js";

export {
  createDrawIdentityLookup,
  requireDrawIdentity,
  normalizeCandidates,
  mergeCandidatesAndSeeds,
  validateCandidates,
  validateGroupParams,
  validateBracketParams,
  validateManualAndProtected,
  isPowerOfTwo,
  orderByIdentity,
  orderBySeedNumber,
  orderCandidatesForDraw,
  deterministicOrdering,
  hashStringToUint32,
  createMulberry32,
  createDeterministicRandomFromSeed,
  deterministicShuffle,
  buildGroups,
  attachPlacementsToGroups,
  getSnakeGroupIndex,
  getSerpentineGroupIndex,
  getSeededGroupIndex,
  assignSnakeGroups,
  assignSerpentineGroups,
  assignSeededGroups,
  assignPotGroups,
  assignOpenRandomGroups,
  assignOpenShuffledSnakeGroups,
  assignManualGroupsOnly,
  buildSeededBracketSlotOrder,
  calculateByeCount,
  selectByeSlots,
  assignBracketSlots,
  assignByes,
  validateConstraintResolutionOutput,
  applyConstraintResolverHook,
} from "./services/index.js";
