import { PERMISSIONS } from "./permissions.js";

/** Phạm vi kiểm tra khi authorize. */
export const PERMISSION_SCOPE = Object.freeze({
  GLOBAL: "global",
  VENUE: "venue",
  CLUB: "club",
  SELF: "self",
});

/** Scope mặc định (một scope) cho permission. */
export const PERMISSION_META = Object.freeze({
  [PERMISSIONS.ROLE_MANAGE]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.USER_MANAGE]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.SUBSCRIPTION_VIEW]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.SUBSCRIPTION_UPDATE]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_VIEW]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_MANAGE]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_INVOICE_VIEW]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_INVOICE_CREATE]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_INVOICE_MARK_PAID]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_PAYMENT_VIEW]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_PAYMENT_MANAGE]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_SUBSCRIPTION_VIEW]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_SUBSCRIPTION_MANAGE]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_PLAN_VIEW]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_PLAN_MANAGE]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_TENANT_LOCK]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_TENANT_UNLOCK]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.BILLING_AUDIT_VIEW]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.CLUB_CREATE]: PERMISSION_SCOPE.VENUE,

  [PERMISSIONS.COURT_VIEW]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.COURT_CREATE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.COURT_UPDATE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.COURT_DELETE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.BOOKING_VIEW]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.BOOKING_CREATE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.BOOKING_UPDATE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.BOOKING_DELETE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.CUSTOMER_VIEW]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.CUSTOMER_CREATE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.CUSTOMER_UPDATE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.CUSTOMER_DELETE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.FINANCE_VIEW]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.FINANCE_EDIT]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.VENUE_VIEW]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.VENUE_UPDATE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.MATCH_UPDATE]: PERMISSION_SCOPE.VENUE,

  [PERMISSIONS.CLUB_VIEW]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.CLUB_UPDATE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.CLUB_DELETE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.SEASON_UPDATE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.LEAGUE_UPDATE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.PLAYER_CREATE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.PLAYER_DELETE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.TOURNAMENT_CREATE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.TOURNAMENT_UPDATE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.TOURNAMENT_DELETE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.DIRECTOR_USE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.SCHEDULING_VIEW]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.SCHEDULING_RUN]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.STATISTICS_EXPORT]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.SETTINGS_VIEW]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.SYSTEM_SETTING]: PERMISSION_SCOPE.VENUE,

  [PERMISSIONS.PLAYER_VIEW]: PERMISSION_SCOPE.SELF,
  [PERMISSIONS.PLAYER_UPDATE]: PERMISSION_SCOPE.SELF,
  [PERMISSIONS.TOURNAMENT_VIEW]: PERMISSION_SCOPE.SELF,
  [PERMISSIONS.STATISTICS_VIEW]: PERMISSION_SCOPE.SELF,
});

/** Permission có thể khớp qua nhiều scope (OR). */
export const PERMISSION_SCOPE_LIST = Object.freeze({
  [PERMISSIONS.PLAYER_VIEW]: [PERMISSION_SCOPE.CLUB, PERMISSION_SCOPE.SELF],
  [PERMISSIONS.PLAYER_UPDATE]: [PERMISSION_SCOPE.CLUB, PERMISSION_SCOPE.SELF],
  [PERMISSIONS.TOURNAMENT_VIEW]: [PERMISSION_SCOPE.CLUB, PERMISSION_SCOPE.SELF],
  [PERMISSIONS.STATISTICS_VIEW]: [PERMISSION_SCOPE.CLUB, PERMISSION_SCOPE.SELF],
  [PERMISSIONS.TOURNAMENT_CREATE]: [PERMISSION_SCOPE.CLUB, PERMISSION_SCOPE.SELF],
  [PERMISSIONS.VENUE_VIEW]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.VENUE_UPDATE]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.SUBSCRIPTION_VIEW]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.SUBSCRIPTION_UPDATE]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_VIEW]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_MANAGE]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_INVOICE_VIEW]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_INVOICE_CREATE]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_INVOICE_MARK_PAID]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_PAYMENT_VIEW]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_PAYMENT_MANAGE]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_SUBSCRIPTION_VIEW]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_SUBSCRIPTION_MANAGE]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_PLAN_VIEW]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_PLAN_MANAGE]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_TENANT_LOCK]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_TENANT_UNLOCK]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.BILLING_AUDIT_VIEW]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
  [PERMISSIONS.MATCH_UPDATE]: [PERMISSION_SCOPE.VENUE, PERMISSION_SCOPE.CLUB],
  [PERMISSIONS.USER_MANAGE]: [PERMISSION_SCOPE.GLOBAL, PERMISSION_SCOPE.VENUE],
});

export function getPermissionScopes(permission) {
  if (PERMISSION_SCOPE_LIST[permission]) {
    return PERMISSION_SCOPE_LIST[permission];
  }

  const single = PERMISSION_META[permission];
  return single ? [single] : [PERMISSION_SCOPE.GLOBAL];
}

export function getPermissionScope(permission) {
  return getPermissionScopes(permission)[0] || PERMISSION_SCOPE.GLOBAL;
}
