/**
 * E2E-01 — Competition Integration Foundation constants.
 * Composition-root ownership only. Does not reopen Core/CM.
 */

export const E2E01_INTEGRATION_VERSION = "e2e-01-integration-foundation-v1";

export const INTEGRATION_ERROR_CODE = Object.freeze({
  MISSING_IDENTITY: "INTEGRATION_MISSING_IDENTITY",
  MISSING_TENANT: "INTEGRATION_MISSING_TENANT",
  MISSING_VENUE: "INTEGRATION_MISSING_VENUE",
  MISSING_CLUB: "INTEGRATION_MISSING_CLUB",
  PERMISSION_DENIED: "INTEGRATION_PERMISSION_DENIED",
  CROSS_TENANT_REJECTED: "INTEGRATION_CROSS_TENANT_REJECTED",
  PLAYER_MAPPING_MISSING: "INTEGRATION_PLAYER_MAPPING_MISSING",
  CLUB_MAPPING_MISSING: "INTEGRATION_CLUB_MAPPING_MISSING",
  RATING_UNAVAILABLE: "INTEGRATION_RATING_UNAVAILABLE",
  VENUE_RESOLUTION_FAILED: "INTEGRATION_VENUE_RESOLUTION_FAILED",
  ADAPTER_FAILURE: "INTEGRATION_ADAPTER_FAILURE",
  INVALID_REQUEST: "INTEGRATION_INVALID_REQUEST",
  CANONICAL_MUTATION_FORBIDDEN: "INTEGRATION_CANONICAL_MUTATION_FORBIDDEN",
});

export const INTEGRATION_ERROR_CODE_VALUES = Object.freeze(
  Object.values(INTEGRATION_ERROR_CODE)
);

export const ADAPTER_STATUS = Object.freeze({
  READY_TO_REUSE: "READY_TO_REUSE",
  CONTRACT_ONLY: "CONTRACT_ONLY",
  PARTIAL: "PARTIAL",
  DEFERRED_TO_LATER_E2E_WORKSTREAM: "DEFERRED_TO_LATER_E2E_WORKSTREAM",
  BLOCKING_WITH_EVIDENCE: "BLOCKING_WITH_EVIDENCE",
  IMPLEMENTED_IN_E2E_01: "IMPLEMENTED_IN_E2E_01",
});

export const RATING_COMPLETENESS = Object.freeze({
  COMPLETE: "COMPLETE",
  PARTIAL: "PARTIAL",
  EMPTY: "EMPTY",
});

export const INTEGRATION_SOURCE = Object.freeze({
  IDENTITY: "identity",
  PLAYER: "player",
  CLUB: "club",
  PLAYER_RATING_READ: "player-rating-read",
  VENUE_COURT: "venue-court",
  COMPETITION_ENGINE_INTEGRATION: "competition-engine-integration",
});
