/**
 * Duplicate candidate match signals (CUSTOMER-06).
 * Deterministic, rule-based evidence only — never auto-merge.
 */

export const CUSTOMER_DUPLICATE_SIGNAL_STRENGTH = Object.freeze({
  STRONG: "STRONG",
  MODERATE: "MODERATE",
  WEAK: "WEAK",
});

export const CUSTOMER_DUPLICATE_SIGNAL = Object.freeze({
  SAME_ACTIVE_IDENTITY: "SAME_ACTIVE_IDENTITY",
  SAME_ACTIVE_PLAYER: "SAME_ACTIVE_PLAYER",
  SAME_TRUSTED_CRM_REF: "SAME_TRUSTED_CRM_REF",
  EMAIL_PLUS_CORROBORATION: "EMAIL_PLUS_CORROBORATION",
  PHONE_PLUS_CORROBORATION: "PHONE_PLUS_CORROBORATION",
  SAME_NORMALIZED_EMAIL: "SAME_NORMALIZED_EMAIL",
  SAME_NORMALIZED_PHONE: "SAME_NORMALIZED_PHONE",
  SAME_LEGAL_NAME: "SAME_LEGAL_NAME",
  SAME_DISPLAY_NAME: "SAME_DISPLAY_NAME",
  SAME_ORG_NAME: "SAME_ORG_NAME",
  SAME_ADDRESS_KEY: "SAME_ADDRESS_KEY",
  PARTIAL_NAME: "PARTIAL_NAME",
  SAME_LOCALE: "SAME_LOCALE",
});

export const CUSTOMER_DUPLICATE_SIGNAL_VALUES = Object.freeze(
  Object.values(CUSTOMER_DUPLICATE_SIGNAL)
);

export const CUSTOMER_STRONG_DUPLICATE_SIGNALS = Object.freeze([
  CUSTOMER_DUPLICATE_SIGNAL.SAME_ACTIVE_IDENTITY,
  CUSTOMER_DUPLICATE_SIGNAL.SAME_ACTIVE_PLAYER,
  CUSTOMER_DUPLICATE_SIGNAL.SAME_TRUSTED_CRM_REF,
  CUSTOMER_DUPLICATE_SIGNAL.EMAIL_PLUS_CORROBORATION,
  CUSTOMER_DUPLICATE_SIGNAL.PHONE_PLUS_CORROBORATION,
]);

export const CUSTOMER_MODERATE_DUPLICATE_SIGNALS = Object.freeze([
  CUSTOMER_DUPLICATE_SIGNAL.SAME_NORMALIZED_EMAIL,
  CUSTOMER_DUPLICATE_SIGNAL.SAME_NORMALIZED_PHONE,
  CUSTOMER_DUPLICATE_SIGNAL.SAME_LEGAL_NAME,
  CUSTOMER_DUPLICATE_SIGNAL.SAME_DISPLAY_NAME,
  CUSTOMER_DUPLICATE_SIGNAL.SAME_ORG_NAME,
  CUSTOMER_DUPLICATE_SIGNAL.SAME_ADDRESS_KEY,
]);

export const CUSTOMER_WEAK_DUPLICATE_SIGNALS = Object.freeze([
  CUSTOMER_DUPLICATE_SIGNAL.PARTIAL_NAME,
  CUSTOMER_DUPLICATE_SIGNAL.SAME_LOCALE,
]);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isCustomerDuplicateSignal(value) {
  return CUSTOMER_DUPLICATE_SIGNAL_VALUES.includes(String(value || ""));
}

/**
 * @param {string} signal
 * @returns {string}
 */
export function duplicateSignalStrength(signal) {
  const s = String(signal || "");
  if (CUSTOMER_STRONG_DUPLICATE_SIGNALS.includes(s)) {
    return CUSTOMER_DUPLICATE_SIGNAL_STRENGTH.STRONG;
  }
  if (CUSTOMER_MODERATE_DUPLICATE_SIGNALS.includes(s)) {
    return CUSTOMER_DUPLICATE_SIGNAL_STRENGTH.MODERATE;
  }
  if (CUSTOMER_WEAK_DUPLICATE_SIGNALS.includes(s)) {
    return CUSTOMER_DUPLICATE_SIGNAL_STRENGTH.WEAK;
  }
  return CUSTOMER_DUPLICATE_SIGNAL_STRENGTH.WEAK;
}
