/**
 * Communication eligibility reason codes (CUSTOMER-04).
 * These are projection reasons — not thrown CustomerError codes.
 */

export const CUSTOMER_ELIGIBILITY_REASON = Object.freeze({
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  CONTACT_POINT_NOT_FOUND: "CONTACT_POINT_NOT_FOUND",
  CONTACT_POINT_INACTIVE: "CONTACT_POINT_INACTIVE",
  CONTACT_POINT_UNVERIFIED: "CONTACT_POINT_UNVERIFIED",
  PREFERENCE_OPTED_OUT: "PREFERENCE_OPTED_OUT",
  PREFERENCE_UNSPECIFIED: "PREFERENCE_UNSPECIFIED",
  CONSENT_DENIED: "CONSENT_DENIED",
  CONSENT_REVOKED: "CONSENT_REVOKED",
  CONSENT_EXPIRED: "CONSENT_EXPIRED",
  CONSENT_NOT_RECORDED: "CONSENT_NOT_RECORDED",
  UNSUPPORTED_COMMUNICATION_CHANNEL: "UNSUPPORTED_COMMUNICATION_CHANNEL",
  UNSUPPORTED_COMMUNICATION_PURPOSE: "UNSUPPORTED_COMMUNICATION_PURPOSE",
  REQUIRES_GOVERNANCE_POLICY: "REQUIRES_GOVERNANCE_POLICY",
  CHANNEL_CONTACT_MISMATCH: "CHANNEL_CONTACT_MISMATCH",
});

export const CUSTOMER_ELIGIBILITY_REASON_VALUES = Object.freeze(
  Object.values(CUSTOMER_ELIGIBILITY_REASON)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isCustomerEligibilityReason(value) {
  return CUSTOMER_ELIGIBILITY_REASON_VALUES.includes(String(value || ""));
}
