/**
 * Stable reason codes for runtime control decisions (Phase 3A.1).
 */

export const RUNTIME_DECISION_CODE = Object.freeze({
  GLOBAL_KILL_SWITCH: "GLOBAL_KILL_SWITCH",
  GLOBAL_DISABLED: "GLOBAL_DISABLED",
  ROLLBACK_ACTIVE: "ROLLBACK_ACTIVE",
  COMPETITION_DISABLED: "COMPETITION_DISABLED",
  TENANT_DISABLED: "TENANT_DISABLED",
  FORMAT_DISABLED: "FORMAT_DISABLED",
  CAPABILITY_DISABLED: "CAPABILITY_DISABLED",
  SHADOW_DISABLED: "SHADOW_DISABLED",
  INVALID_CONTEXT: "INVALID_CONTEXT",
  INVALID_FLAG_SNAPSHOT: "INVALID_FLAG_SNAPSHOT",
  INVALID_OVERRIDE: "INVALID_OVERRIDE",
  UNSUPPORTED_RUNTIME_MODE: "UNSUPPORTED_RUNTIME_MODE",
  DEFAULT_LEGACY_ONLY: "DEFAULT_LEGACY_ONLY",
  CANONICAL_NOT_AVAILABLE: "CANONICAL_NOT_AVAILABLE",
  COMPETITION_KILL_SWITCH: "COMPETITION_KILL_SWITCH",
  TENANT_KILL_SWITCH: "TENANT_KILL_SWITCH",
  FORMAT_KILL_SWITCH: "FORMAT_KILL_SWITCH",
  CAPABILITY_KILL_SWITCH: "CAPABILITY_KILL_SWITCH",
});

export const RUNTIME_DECISION_CODE_VALUES = Object.freeze(
  Object.values(RUNTIME_DECISION_CODE)
);

export function isRuntimeDecisionCode(value) {
  return RUNTIME_DECISION_CODE_VALUES.includes(value);
}
