/**
 * Stable shadow infrastructure reason codes (Phase 3A.2).
 * Namespace: SHADOW_* / COMPARISON_* / PLAN_* — no free-form strings in resolvers.
 */

export const SHADOW_REASON_CODE = Object.freeze({
  SHADOW_DISABLED: "SHADOW_DISABLED",
  SHADOW_NOT_ALLOWED: "SHADOW_NOT_ALLOWED",
  CANONICAL_NOT_ALLOWED: "CANONICAL_NOT_ALLOWED",
  KILL_SWITCH_ACTIVE: "KILL_SWITCH_ACTIVE",
  CAPABILITY_NOT_ALLOWED: "CAPABILITY_NOT_ALLOWED",
  OPERATION_NOT_ALLOWED: "OPERATION_NOT_ALLOWED",
  INVALID_REQUEST: "INVALID_REQUEST",
  SAMPLE_EXCLUDED: "SAMPLE_EXCLUDED",
  PLAN_CREATED: "PLAN_CREATED",
  PLAN_SKIPPED: "PLAN_SKIPPED",
  COMPARISON_EQUIVALENT: "COMPARISON_EQUIVALENT",
  COMPARISON_DIVERGED: "COMPARISON_DIVERGED",
  COMPARISON_NOT_COMPARABLE: "COMPARISON_NOT_COMPARABLE",
  COMPARISON_PARTIAL: "COMPARISON_PARTIAL",
  COMPARISON_SKIPPED: "COMPARISON_SKIPPED",
  LEGACY_ERROR: "LEGACY_ERROR",
  CANONICAL_ERROR: "CANONICAL_ERROR",
  BOTH_ERROR: "BOTH_ERROR",
  ELIGIBLE: "ELIGIBLE",
});

export const SHADOW_REASON_CODE_VALUES = Object.freeze(
  Object.values(SHADOW_REASON_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isShadowReasonCode(value) {
  return SHADOW_REASON_CODE_VALUES.includes(value);
}
