/**
 * Phase 1H-B — Admin verification queue read constants.
 */
import { IDENTITY_VERIFICATION_STATUS } from "./verification.js";

/** Default queue filter — actionable review items only. */
export const VERIFICATION_QUEUE_DEFAULT_STATUS =
  IDENTITY_VERIFICATION_STATUS.PENDING;

export const VERIFICATION_QUEUE_DEFAULT_LIMIT = 50;

/** Hard cap — prevents unbounded profile reads. */
export const VERIFICATION_QUEUE_MAX_LIMIT = 100;

export const VERIFICATION_QUEUE_SUPPORTED_STATUSES = Object.freeze([
  IDENTITY_VERIFICATION_STATUS.PENDING,
  IDENTITY_VERIFICATION_STATUS.UNVERIFIED,
  IDENTITY_VERIFICATION_STATUS.REJECTED,
  IDENTITY_VERIFICATION_STATUS.VERIFIED,
]);

export const VERIFICATION_QUEUE_ERROR_CODES = Object.freeze({
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNSUPPORTED_STATUS: "UNSUPPORTED_STATUS",
  PERSISTENCE_ERROR: "PERSISTENCE_ERROR",
  PERSISTENCE_UNAVAILABLE: "PERSISTENCE_UNAVAILABLE",
});
