/**
 * Core-03 — eligibility check type taxonomy.
 * Orchestration owns these codes; Core-01 may evaluate rule payloads behind RuleEvaluationPort.
 */

export const ELIGIBILITY_CHECK_TYPE = Object.freeze({
  REGISTRATION_WINDOW: "REGISTRATION_WINDOW",
  PARTICIPANT_STATUS: "PARTICIPANT_STATUS",
  AGE_REQUIREMENT: "AGE_REQUIREMENT",
  GENDER_REQUIREMENT: "GENDER_REQUIREMENT",
  RATING_RANGE: "RATING_RANGE",
  RANKING_REQUIREMENT: "RANKING_REQUIREMENT",
  DIVISION_COMPATIBILITY: "DIVISION_COMPATIBILITY",
  MEMBERSHIP_REQUIREMENT: "MEMBERSHIP_REQUIREMENT",
  TEAM_ROSTER_REQUIREMENT: "TEAM_ROSTER_REQUIREMENT",
  DOCUMENT_REQUIREMENT: "DOCUMENT_REQUIREMENT",
  PAYMENT_REQUIREMENT: "PAYMENT_REQUIREMENT",
  DUPLICATE_REGISTRATION: "DUPLICATE_REGISTRATION",
  ENTRY_LIMIT: "ENTRY_LIMIT",
  COMPETITION_CAPACITY: "COMPETITION_CAPACITY",
  DIVISION_CAPACITY: "DIVISION_CAPACITY",
  SUSPENSION_OR_SANCTION: "SUSPENSION_OR_SANCTION",
  MANUAL_APPROVAL: "MANUAL_APPROVAL",
});

/** @type {ReadonlySet<string>} */
export const ELIGIBILITY_CHECK_TYPE_VALUES = new Set(
  Object.values(ELIGIBILITY_CHECK_TYPE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isEligibilityCheckType(value) {
  return typeof value === "string" && ELIGIBILITY_CHECK_TYPE_VALUES.has(value);
}
