import { GLOSSARY_VERSION } from "./versions.js";

/**
 * Canonical bilingual glossary — SSOT for all user-facing rating terminology.
 * UI format: English term (chú thích tiếng Việt)
 */
export const RATING_GLOSSARY = Object.freeze({
  serve: {
    code: "serve",
    term_en: "Serve",
    term_vi: "giao bóng",
    short_description_vi: "Kỹ năng giao bóng vào sân đối phương",
    long_description_vi: "Giao bóng hợp lệ, độ sâu và hướng bóng theo chiến thuật.",
    aliases: ["giao bóng", "service"],
    glossary_version: GLOSSARY_VERSION,
  },
  return: {
    code: "return",
    term_en: "Return",
    term_vi: "trả giao bóng",
    short_description_vi: "Trả giao bóng an toàn và có chủ đích",
    long_description_vi: "Return sâu, thấp, hạn chế bị attack ngay sau giao.",
    aliases: ["trả giao", "return of serve"],
    glossary_version: GLOSSARY_VERSION,
  },
  groundstroke: {
    code: "groundstroke",
    term_en: "Groundstroke",
    term_vi: "cú đánh từ baseline",
    short_description_vi: "Forehand/backhand từ cuối sân",
    long_description_vi: "Drive và rally từ baseline với kiểm soát hướng và độ sâu.",
    aliases: [],
    glossary_version: GLOSSARY_VERSION,
  },
  drive: {
    code: "drive",
    term_en: "Drive",
    term_vi: "cú đánh mạnh (drive)",
    short_description_vi: "Đánh bóng nhanh, sâu",
    long_description_vi: "Cú drive từ baseline hoặc transition với pace và depth.",
    aliases: [],
    glossary_version: GLOSSARY_VERSION,
  },
  rally: {
    code: "rally",
    term_en: "Rally",
    term_vi: "pha bóng liên tiếp",
    short_description_vi: "Trao bóng qua lại",
    long_description_vi: "Chuỗi đánh bóng liên tiếp giữa các bên.",
    aliases: [],
    glossary_version: GLOSSARY_VERSION,
  },
  forehand: {
    code: "forehand",
    term_en: "Forehand",
    term_vi: "cú thuận tay",
    short_description_vi: "Đánh thuận",
    long_description_vi: "Forehand drive và kiểm soát từ baseline.",
    aliases: ["thuận tay"],
    glossary_version: GLOSSARY_VERSION,
  },
  backhand: {
    code: "backhand",
    term_en: "Backhand",
    term_vi: "cú trái tay",
    short_description_vi: "Đánh trái",
    long_description_vi: "Backhand drive và ổn định từ baseline.",
    aliases: ["trái tay"],
    glossary_version: GLOSSARY_VERSION,
  },
  baseline: {
    code: "baseline",
    term_en: "Baseline",
    term_vi: "cuối sân",
    short_description_vi: "Vị trí cuối sân",
    long_description_vi: "Đường baseline — vùng đánh groundstroke.",
    aliases: ["cuối sân"],
    glossary_version: GLOSSARY_VERSION,
  },
  crosscourt: {
    code: "crosscourt",
    term_en: "Crosscourt",
    term_vi: "đánh chéo sân",
    short_description_vi: "Góc chéo",
    long_description_vi: "Đánh bóng chéo qua sân.",
    aliases: ["cross-court", "chéo sân"],
    glossary_version: GLOSSARY_VERSION,
  },
  down_the_line: {
    code: "down_the_line",
    term_en: "Down the line",
    term_vi: "đánh dọc đường biên",
    short_description_vi: "Theo line",
    long_description_vi: "Đánh bóng dọc theo đường biên.",
    aliases: ["dọc line"],
    glossary_version: GLOSSARY_VERSION,
  },
  pop_up: {
    code: "pop_up",
    term_en: "Pop-up",
    term_vi: "bóng bật cao",
    short_description_vi: "Bóng quá cao dễ bị attack",
    long_description_vi: "Lỗi pop-up tại kitchen hoặc khi dink.",
    aliases: ["pop-up", "popup"],
    glossary_version: GLOSSARY_VERSION,
  },
  counterattack: {
    code: "counterattack",
    term_en: "Counterattack",
    term_vi: "phản công",
    short_description_vi: "Phản đòn sau block",
    long_description_vi: "Counter sau speed-up hoặc attack đối phương.",
    aliases: ["counter-attack", "counter"],
    glossary_version: GLOSSARY_VERSION,
  },
  unforced_error: {
    code: "unforced_error",
    term_en: "Unforced error",
    term_vi: "lỗi không ép buộc",
    short_description_vi: "Lỗi tự gây ra",
    long_description_vi: "Mất điểm do lỗi khi không bị ép buộc.",
    aliases: ["lỗi không ép buộc"],
    glossary_version: GLOSSARY_VERSION,
  },
  shot_selection: {
    code: "shot_selection",
    term_en: "Shot selection",
    term_vi: "lựa chọn cú đánh",
    short_description_vi: "Chọn cú phù hợp",
    long_description_vi: "Quyết định drive/dink/lob theo tình huống.",
    aliases: ["lựa chọn cú"],
    glossary_version: GLOSSARY_VERSION,
  },
  recovery_position: {
    code: "recovery_position",
    term_en: "Recovery position",
    term_vi: "vị trí phục hồi",
    short_description_vi: "Về vị trí sau cú đánh",
    long_description_vi: "Recovery về ready position sau mỗi pha.",
    aliases: ["phục hồi vị trí"],
    glossary_version: GLOSSARY_VERSION,
  },
  dink_soft_game: {
    code: "dink_soft_game",
    term_en: "Dink",
    term_vi: "cú đánh mềm gần vùng cấm vô-lê",
    short_description_vi: "Soft game tại kitchen",
    long_description_vi: "Dink thấp qua lưới, giữ nhịp và kiểm soát tốc độ bóng ở kitchen.",
    aliases: ["dink", "soft game"],
    glossary_version: GLOSSARY_VERSION,
  },
  third_shot: {
    code: "third_shot",
    term_en: "Third shot",
    term_vi: "cú đánh thứ ba",
    short_description_vi: "Lượt đánh thứ ba sau return",
    long_description_vi: "Third shot — lựa chọn drop, drive hoặc chiến thuật sau return.",
    aliases: ["third shot", "third-shot"],
    glossary_version: GLOSSARY_VERSION,
  },
  third_shot_drop: {
    code: "third_shot_drop",
    term_en: "Third-shot drop",
    term_vi: "cú thả bóng mềm ở lượt đánh thứ ba",
    short_description_vi: "Drop vào kitchen",
    long_description_vi: "Third-shot drop — đưa bóng mềm vào kitchen đối phương.",
    aliases: ["third shot drop"],
    glossary_version: GLOSSARY_VERSION,
  },
  third_shot_drive: {
    code: "third_shot_drive",
    term_en: "Third-shot drive",
    term_vi: "cú đánh mạnh ở lượt đánh thứ ba",
    short_description_vi: "Drive third shot",
    long_description_vi: "Third-shot drive — tấn công sau return khi có cơ hội.",
    aliases: ["third shot drive"],
    glossary_version: GLOSSARY_VERSION,
  },
  transition: {
    code: "transition",
    term_en: "Transition",
    term_vi: "chuyển tiếp từ baseline lên kitchen",
    short_description_vi: "Di chuyển lên/lùi đúng thời điểm",
    long_description_vi: "Transition từ baseline vào kitchen và xử lý vùng chuyển tiếp.",
    aliases: ["transition zone", "lên kitchen"],
    glossary_version: GLOSSARY_VERSION,
  },
  transition_zone: {
    code: "transition_zone",
    term_en: "Transition zone",
    term_vi: "vùng chuyển tiếp",
    short_description_vi: "Vùng giữa baseline và kitchen",
    long_description_vi: "No-man's land — vùng dễ bị attack nếu đứng lại quá lâu.",
    aliases: ["no-man's land", "no mans land"],
    glossary_version: GLOSSARY_VERSION,
  },
  volley: {
    code: "volley",
    term_en: "Volley",
    term_vi: "cú đánh volley",
    short_description_vi: "Đánh bóng trên không",
    long_description_vi: "Volley punch, put-away và volley phòng thủ tại kitchen line.",
    aliases: ["volley punch"],
    glossary_version: GLOSSARY_VERSION,
  },
  block_reset: {
    code: "block_reset",
    term_en: "Block",
    term_vi: "chặn bóng",
    short_description_vi: "Block và reset",
    long_description_vi: "Block drive đối phương; Reset (làm mềm bóng để đưa pha bóng về trạng thái trung hòa).",
    aliases: ["block", "reset"],
    glossary_version: GLOSSARY_VERSION,
  },
  reset: {
    code: "reset",
    term_en: "Reset",
    term_vi: "làm mềm bóng để đưa pha bóng về trạng thái trung hòa",
    short_description_vi: "Đưa rally về trung tính",
    long_description_vi: "Reset sau khi bị attack để lấy lại nhịp.",
    aliases: [],
    glossary_version: GLOSSARY_VERSION,
  },
  footwork: {
    code: "footwork",
    term_en: "Footwork",
    term_vi: "kỹ năng di chuyển chân",
    short_description_vi: "Split-step và recovery",
    long_description_vi: "Di chuyển chân, split-step và phục hồi vị trí sau mỗi cú.",
    aliases: ["di chuyển chân"],
    glossary_version: GLOSSARY_VERSION,
  },
  doubles_positioning: {
    code: "doubles_positioning",
    term_en: "Positioning",
    term_vi: "khả năng giữ vị trí",
    short_description_vi: "Vị trí đánh đôi",
    long_description_vi: "Stagger, che middle/line và phối hợp với đồng đội.",
    aliases: ["positioning", "vị trí"],
    glossary_version: GLOSSARY_VERSION,
  },
  communication: {
    code: "communication",
    term_en: "Communication",
    term_vi: "giao tiếp trên sân",
    short_description_vi: "Mine/yours, switch",
    long_description_vi: "Giao tiếp với đồng đội trong đánh đôi.",
    aliases: ["giao tiếp"],
    glossary_version: GLOSSARY_VERSION,
  },
  tactical_decision: {
    code: "tactical_decision",
    term_en: "Tactical decision",
    term_vi: "quyết định chiến thuật",
    short_description_vi: "Chọn cú đánh theo tình huống",
    long_description_vi: "Lựa chọn drive/dink/lob và thời điểm tấn công/phòng thủ.",
    aliases: ["chiến thuật", "tactics"],
    glossary_version: GLOSSARY_VERSION,
  },
  consistency: {
    code: "consistency",
    term_en: "Consistency",
    term_vi: "độ ổn định",
    short_description_vi: "Giữ nhịp và ít lỗi",
    long_description_vi: "Duy trì rally và lối chơi ổn định theo thời gian.",
    aliases: ["ổn định"],
    glossary_version: GLOSSARY_VERSION,
  },
  pressure_execution: {
    code: "pressure_execution",
    term_en: "Pressure execution",
    term_vi: "thực thi dưới áp lực",
    short_description_vi: "Giữ lối chơi khi điểm quan trọng",
    long_description_vi: "Thực hiện kỹ thuật tốt trong điểm quyết định.",
    aliases: ["áp lực"],
    glossary_version: GLOSSARY_VERSION,
  },
  rules: {
    code: "rules",
    term_en: "Rules",
    term_vi: "luật tình huống",
    short_description_vi: "Kitchen/vôi, giao bóng",
    long_description_vi: "Nắm và áp dụng luật pickleball trong thi đấu.",
    aliases: ["luật", "kitchen rule"],
    glossary_version: GLOSSARY_VERSION,
  },
  rally_consistency: {
    code: "rally_consistency",
    term_en: "Rally consistency",
    term_vi: "độ ổn định rally",
    short_description_vi: "Giữ rally baseline",
    long_description_vi: "Duy trì rally groundstroke với ít lỗi không ép buộc.",
    aliases: ["rally"],
    glossary_version: GLOSSARY_VERSION,
  },
  error_control: {
    code: "error_control",
    term_en: "Error control",
    term_vi: "kiểm soát lỗi",
    short_description_vi: "Hạn chế lỗi không ép buộc",
    long_description_vi: "Tránh pop-up, vôi và lỗi sớm trong rally.",
    aliases: ["lỗi không ép buộc"],
    glossary_version: GLOSSARY_VERSION,
  },
  kitchen: {
    code: "kitchen",
    term_en: "Kitchen",
    term_vi: "vùng cấm vô-lê",
    short_description_vi: "Non-volley zone (NVZ)",
    long_description_vi: "Vùng 7 feet hai bên lưới — không volley trong vùi.",
    aliases: ["vôi", "NVZ", "non-volley zone"],
    glossary_version: GLOSSARY_VERSION,
  },
  poach: {
    code: "poach",
    term_en: "Poach",
    term_vi: "băng cắt bóng",
    short_description_vi: "Cắt bóng giữa sân",
    long_description_vi: "Đồng đội băng sang cắt bóng ở giữa.",
    aliases: ["băng cắt"],
    glossary_version: GLOSSARY_VERSION,
  },
  stack: {
    code: "stack",
    term_en: "Stack",
    term_vi: "chiến thuật xếp vị trí",
    short_description_vi: "Stacking formation",
    long_description_vi: "Xếp vị trí để tối ưu tay thuận khi return.",
    aliases: ["stacking"],
    glossary_version: GLOSSARY_VERSION,
  },
  ernie: {
    code: "ernie",
    term_en: "Erne",
    term_vi: "cú đánh ngoài vùng cấm vô-lê sát lưới",
    short_description_vi: "Attack từ ngoài kitchen",
    long_description_vi: "Chạy ra ngoài kitchen để attack sát lưới.",
    aliases: [],
    glossary_version: GLOSSARY_VERSION,
  },
  atp: {
    code: "atp",
    term_en: "ATP – Around the Post",
    term_vi: "đánh bóng vòng ngoài cột lưới",
    short_description_vi: "Around the post shot",
    long_description_vi: "Đánh bóng vòng qua cột lưới khi bóng đi ra ngoài.",
    aliases: ["around the post"],
    glossary_version: GLOSSARY_VERSION,
  },
  lob: {
    code: "lob",
    term_en: "Lob",
    term_vi: "cú lob phòng thủ",
    short_description_vi: "Bóng cao qua đối thủ",
    long_description_vi: "Lob defensive khi bị ép tại kitchen.",
    aliases: [],
    glossary_version: GLOSSARY_VERSION,
  },
  speed_up: {
    code: "speed_up",
    term_en: "Speed-up",
    term_vi: "tăng tốc bóng từ kitchen",
    short_description_vi: "Đánh nhanh từ dink",
    long_description_vi: "Đột ngột tăng pace từ pha dink.",
    aliases: ["speedup"],
    glossary_version: GLOSSARY_VERSION,
  },
  put_away: {
    code: "put_away",
    term_en: "Put-away",
    term_vi: "cú kết thúc điểm",
    short_description_vi: "Volley kết thúc pha",
    long_description_vi: "Put-away volley khi bóng cao để thắng điểm.",
    aliases: ["put away", "putaway"],
    glossary_version: GLOSSARY_VERSION,
  },
  foot_fault: {
    code: "foot_fault",
    term_en: "Foot fault",
    term_vi: "lỗi chân khi giao",
    short_description_vi: "Vi phạm vị trí giao",
    long_description_vi: "Foot fault — chạm vạch hoặc bước quá khi giao.",
    aliases: ["foot-fault"],
    glossary_version: GLOSSARY_VERSION,
  },
  match_up: {
    code: "match_up",
    term_en: "Match-up",
    term_vi: "cặp đấu / đối sủ",
    short_description_vi: "So khớp đối thủ",
    long_description_vi: "Đọc match-up — điểm mạnh/yếu theo cặp đấu.",
    aliases: ["match-up", "matchup"],
    glossary_version: GLOSSARY_VERSION,
  },
  court_coverage: {
    code: "court_coverage",
    term_en: "Court coverage",
    term_vi: "khả năng bao quát sân",
    short_description_vi: "Singles — V5-B.1",
    long_description_vi: "Khả năng phủ sân trong đánh đơn.",
    aliases: [],
    glossary_version: GLOSSARY_VERSION,
  },
  reliability_score: {
    code: "reliability_score",
    term_en: "Reliability score",
    term_vi: "điểm độ tin cậy",
    short_description_vi: "0–100",
    long_description_vi: "Mức tin cậy vào rating dựa trên bằng chứng và volume.",
    aliases: ["reliability"],
    glossary_version: GLOSSARY_VERSION,
  },
  provisional_rating: {
    code: "provisional_rating",
    term_en: "Provisional rating",
    term_vi: "điểm trình độ tạm tính",
    short_description_vi: "Chưa đủ verified",
    long_description_vi: "Rating tạm từ questionnaire hoặc open track.",
    aliases: ["provisional"],
    glossary_version: GLOSSARY_VERSION,
  },
  verified_rating: {
    code: "verified_rating",
    term_en: "Verified rating",
    term_vi: "điểm trình độ đã xác minh",
    short_description_vi: "Evidence level 4–5",
    long_description_vi: "Rating từ trận/giải/HLV đã xác thực.",
    aliases: ["verified"],
    glossary_version: GLOSSARY_VERSION,
  },
  display_rating: {
    code: "display_rating",
    term_en: "Display rating",
    term_vi: "điểm trình độ hiển thị",
    short_description_vi: "Làm tròn 0.1",
    long_description_vi: "Rating công khai sau resolver open/verified.",
    aliases: [],
    glossary_version: GLOSSARY_VERSION,
  },
  contradiction: {
    code: "contradiction",
    term_en: "Contradiction",
    term_vi: "mâu thuẫn câu trả lời",
    short_description_vi: "Consistency check",
    long_description_vi: "Câu trả lời không nhất quán giữa các domain liên quan.",
    aliases: ["mâu thuẫn"],
    glossary_version: GLOSSARY_VERSION,
  },
});

export const GLOSSARY_CODES = Object.freeze(Object.keys(RATING_GLOSSARY));

export function getGlossaryEntry(code) {
  return RATING_GLOSSARY[code] ?? null;
}
