export const LOGICAL_SERVICE_SIDE = Object.freeze({
  LEFT_SERVICE_COURT: "LEFT_SERVICE_COURT",
  RIGHT_SERVICE_COURT: "RIGHT_SERVICE_COURT",
});

export const OPPOSITE_SERVICE_SIDE = Object.freeze({
  [LOGICAL_SERVICE_SIDE.LEFT_SERVICE_COURT]: LOGICAL_SERVICE_SIDE.RIGHT_SERVICE_COURT,
  [LOGICAL_SERVICE_SIDE.RIGHT_SERVICE_COURT]: LOGICAL_SERVICE_SIDE.LEFT_SERVICE_COURT,
});

export function flipLogicalServiceSide(side) {
  return OPPOSITE_SERVICE_SIDE[side] || side;
}
