export const MATCH_EVENT_TYPE = Object.freeze({
  START_MATCH: "START_MATCH",
  TEAM_A_WON_RALLY: "TEAM_A_WON_RALLY",
  TEAM_B_WON_RALLY: "TEAM_B_WON_RALLY",
  SWITCH_ENDS: "SWITCH_ENDS",
  UNDO_LAST_EVENT: "UNDO_LAST_EVENT",
  START_TIMEOUT: "START_TIMEOUT",
  END_TIMEOUT: "END_TIMEOUT",
  PAUSE_MATCH: "PAUSE_MATCH",
  RESUME_MATCH: "RESUME_MATCH",
  DECLARE_FORFEIT: "DECLARE_FORFEIT",
  EVENT_REVERTED: "EVENT_REVERTED",
});

export const DOMAIN_EVENT_TYPE = Object.freeze({
  POINT_AWARDED: "POINT_AWARDED",
  PLAYERS_SWITCHED: "PLAYERS_SWITCHED",
  SECOND_SERVER_ACTIVATED: "SECOND_SERVER_ACTIVATED",
  SIDE_OUT: "SIDE_OUT",
  SERVE_CHANGED: "SERVE_CHANGED",
  ENDS_SWITCHED: "ENDS_SWITCHED",
  GAME_COMPLETED: "GAME_COMPLETED",
  MATCH_COMPLETED: "MATCH_COMPLETED",
});

export const MATCH_STATUS = Object.freeze({
  NOT_STARTED: "not_started",
  IN_PROGRESS: "in_progress",
  PAUSED: "paused",
  LOCKED: "locked",
  COMPLETED: "completed",
});
