export const VIEW_MODE = Object.freeze({
  REFEREE_PHYSICAL_VIEW: "REFEREE_PHYSICAL_VIEW",
  TEAM_FIXED_VIEW: "TEAM_FIXED_VIEW",
});

export const SCREEN_POSITION = Object.freeze({
  SCREEN_TOP_LEFT: "SCREEN_TOP_LEFT",
  SCREEN_TOP_RIGHT: "SCREEN_TOP_RIGHT",
  SCREEN_BOTTOM_LEFT: "SCREEN_BOTTOM_LEFT",
  SCREEN_BOTTOM_RIGHT: "SCREEN_BOTTOM_RIGHT",
});
