import { PERMISSIONS } from "../../auth/permissions.js";
import { ROLES } from "../../auth/roles.js";
import { FEATURE_STATUS, menuFolder, menuLeaf } from "./menuBuilders.js";

export const CLUB_COACHING_MENU_ROOT = menuFolder({
  key: "club-coaching-root",
  icon: "club-list",
  text: "CLB & Huấn luyện",
  children: [
    menuLeaf({
      key: "club-activity",
      icon: "club-schedule",
      text: "Vận hành CLB",
      path: "/club",
      match: "club-settings",
      permissions: [PERMISSIONS.CLUB_VIEW],
      excludeRoles: [ROLES.PLAYER],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "my-club",
      icon: "my-club",
      text: "CLB của tôi",
      path: "/my-club",
      match: "my-club",
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "discover-clubs",
      icon: "club-list",
      text: "Khám phá CLB",
      path: "/discover-clubs",
      match: "discover-clubs",
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "club-create",
      icon: "club-list",
      text: "Tạo CLB",
      path: "/manage/clubs",
      match: "manage-clubs",
      permissions: [PERMISSIONS.CLUB_CREATE],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "club-membership-requests",
      icon: "groups",
      text: "Yêu cầu gia nhập",
      path: "/my-club/requests",
      match: "club-membership-requests",
      permissions: [PERMISSIONS.CLUB_MEMBERSHIP_REVIEW],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "club-governance-manage",
      icon: "club-list",
      text: "Quản trị CLB",
      path: "/manage/clubs",
      match: "manage-clubs",
      permissions: [PERMISSIONS.CLUB_VIEW],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "club-platform-all",
      icon: "groups",
      text: "Tất cả CLB",
      path: "/platform/clubs",
      match: "platform-clubs",
      roles: [ROLES.PLATFORM_ADMIN, ROLES.SUPER_ADMIN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "club-list",
      icon: "club-list",
      text: "Quản lý CLB",
      path: "/manage/clubs",
      match: "manage-clubs",
      permissions: [PERMISSIONS.CLUB_VIEW],
      excludeRoles: [ROLES.PLAYER],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "club-daily-play",
      icon: "club-internal",
      text: "Vui chơi mỗi ngày",
      path: "/daily-play",
      match: "daily-play",
      permissions: [PERMISSIONS.TOURNAMENT_VIEW],
      excludeRoles: [ROLES.PLAYER],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-list-player",
      icon: "coaches",
      text: "Danh sách huấn luyện viên",
      path: "/coaching/coach-list",
      match: "coaching-coach-list",
      roles: [ROLES.PLAYER, ROLES.CUSTOMER],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-package-register",
      icon: "billing",
      text: "Đăng ký gói học",
      path: "/coaching/register",
      match: "coaching-register",
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coaches",
      icon: "coaches",
      text: "Danh sách huấn luyện viên",
      path: "/coaching/coaches",
      match: "coaching-coaches",
      permissions: [PERMISSIONS.CUSTOMER_VIEW],
      excludeRoles: [ROLES.PLAYER, ROLES.CUSTOMER],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-students",
      icon: "players",
      text: "Học viên",
      path: "/coaching/students",
      match: "coaching-students",
      permissions: [PERMISSIONS.CUSTOMER_VIEW],
      excludeRoles: [ROLES.PLAYER],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-classes",
      icon: "groups",
      text: "Lớp học",
      path: "/coaching/classes",
      match: "coaching-classes",
      permissions: [PERMISSIONS.CUSTOMER_VIEW],
      excludeRoles: [ROLES.PLAYER],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-schedule",
      icon: "calendar",
      text: "Lịch huấn luyện",
      path: "/coaching/schedule",
      match: "coaching-schedule",
      permissions: [PERMISSIONS.BOOKING_VIEW],
      excludeRoles: [ROLES.PLAYER],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-packages",
      icon: "billing",
      text: "Gói học",
      path: "/coaching/packages",
      match: "coaching-packages",
      permissions: [PERMISSIONS.CUSTOMER_VIEW],
      excludeRoles: [ROLES.PLAYER],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-attendance",
      icon: "check-in",
      text: "Điểm danh",
      path: "/coaching/attendance",
      match: "coaching-attendance",
      permissions: [PERMISSIONS.CUSTOMER_VIEW],
      excludeRoles: [ROLES.PLAYER],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-evaluations",
      icon: "reports",
      text: "Đánh giá học viên",
      path: "/coaching/evaluations",
      match: "coaching-evaluations",
      permissions: [PERMISSIONS.CUSTOMER_VIEW],
      excludeRoles: [ROLES.PLAYER],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
  ],
});
