import { PERMISSIONS } from "../../auth/permissions.js";
import { FEATURE_STATUS, menuFolder, menuLeaf } from "./menuBuilders.js";

export const CLUB_COACHING_MENU_ROOT = menuFolder({
  key: "club-coaching-root",
  icon: "club-list",
  text: "CLB & Huấn luyện",
  children: [
    menuLeaf({
      key: "club-list",
      icon: "club-list",
      text: "Danh sách CLB",
      path: "/clubs",
      match: "clubs",
      permissions: [PERMISSIONS.CLUB_VIEW],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "club-daily-play",
      icon: "club-internal",
      text: "Vui chơi mỗi ngày",
      path: "/daily-play",
      match: "daily-play",
      permissions: [PERMISSIONS.TOURNAMENT_VIEW],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coaches",
      icon: "coaches",
      text: "Huấn luyện viên",
      path: "/coaching/coaches",
      match: "coaching-coaches",
      permissions: [PERMISSIONS.CUSTOMER_VIEW],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-students",
      icon: "players",
      text: "Học viên",
      path: "/coaching/students",
      match: "coaching-students",
      permissions: [PERMISSIONS.CUSTOMER_VIEW],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-classes",
      icon: "groups",
      text: "Lớp học",
      path: "/coaching/classes",
      match: "coaching-classes",
      permissions: [PERMISSIONS.CUSTOMER_VIEW],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-schedule",
      icon: "calendar",
      text: "Lịch huấn luyện",
      path: "/coaching/schedule",
      match: "coaching-schedule",
      permissions: [PERMISSIONS.BOOKING_VIEW],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-packages",
      icon: "billing",
      text: "Gói học",
      path: "/coaching/packages",
      match: "coaching-packages",
      permissions: [PERMISSIONS.CUSTOMER_VIEW],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-attendance",
      icon: "check-in",
      text: "Điểm danh",
      path: "/coaching/attendance",
      match: "coaching-attendance",
      permissions: [PERMISSIONS.CUSTOMER_VIEW],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "coach-evaluations",
      icon: "reports",
      text: "Đánh giá học viên",
      path: "/coaching/evaluations",
      match: "coaching-evaluations",
      permissions: [PERMISSIONS.CUSTOMER_VIEW],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
  ],
});
