import { PERMISSIONS } from "../../auth/permissions.js";
import { ROLES } from "../../auth/roles.js";
import { FEATURE_STATUS, menuFolder, menuLeaf } from "./menuBuilders.js";

/** Menu Kỹ thuật viên hệ thống — V5.1 */
export const SYSTEM_TECHNICIAN_MENU_ROOT = menuFolder({
  key: "system-tech-root",
  icon: "settings",
  text: "Kỹ thuật hệ thống",
  roles: [ROLES.SYSTEM_TECHNICIAN],
  children: [
    menuLeaf({
      key: "tech-overview",
      icon: "dashboard",
      text: "Tổng quan kỹ thuật",
      path: "/dashboard",
      permissions: [PERMISSIONS.SYSTEM_HEALTH_VIEW],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-system-admin",
      icon: "settings",
      text: "Quản trị hệ thống",
      path: "/admin/hours",
      permissions: [PERMISSIONS.SYSTEM_CONFIG_VIEW],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-tenants",
      icon: "tenants",
      text: "Đơn vị / Cơ sở",
      path: "/admin/tenants",
      permissions: [PERMISSIONS.TENANT_VIEW, PERMISSIONS.VENUE_VIEW],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-court-clusters",
      icon: "courts",
      text: "Cụm sân",
      path: "/admin/court-clusters",
      match: "admin-court-clusters",
      permissions: [PERMISSIONS.CLUSTER_MANAGE],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-users",
      icon: "users",
      text: "Người dùng",
      path: "/users",
      permissions: [PERMISSIONS.USER_VIEW],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-skill-level-requests",
      icon: "users",
      text: "Duyệt trình độ VĐV",
      path: "/admin/skill-level-requests",
      permissions: [PERMISSIONS.SKILL_LEVEL_APPROVE],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-tournament-certifications",
      icon: "trophy",
      text: "Duyệt giải VPR",
      path: "/admin/tournament-certifications",
      permissions: [PERMISSIONS.TOURNAMENT_CERTIFY],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-rankings",
      icon: "statistics",
      text: "Quản trị VPR",
      path: "/dashboard/rankings",
      permissions: [PERMISSIONS.RANKING_VIEW],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-roles",
      icon: "roles",
      text: "Vai trò & Quyền",
      path: "/admin/roles",
      match: "admin-roles",
      permissions: [PERMISSIONS.ROLE_VIEW, PERMISSIONS.PERMISSION_VIEW],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-integrations",
      icon: "integrations",
      text: "Tích hợp",
      path: "/settings/integrations",
      permissions: [PERMISSIONS.INTEGRATION_VIEW],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-activity-log",
      icon: "history",
      text: "Nhật ký hoạt động",
      path: "/audit",
      permissions: [PERMISSIONS.ACTIVITY_LOG_VIEW],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-error-log",
      icon: "history",
      text: "Nhật ký lỗi",
      path: "/coming-soon/tech-error-log",
      permissions: [PERMISSIONS.SYSTEM_LOG_VIEW],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-config",
      icon: "settings",
      text: "Cấu hình kỹ thuật",
      path: "/settings",
      permissions: [PERMISSIONS.SYSTEM_CONFIG_VIEW],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-support-tickets",
      icon: "support",
      text: "Yêu cầu hỗ trợ",
      path: "/support",
      permissions: [PERMISSIONS.SUPPORT_TICKET_MANAGE],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-diagnostics",
      icon: "ai",
      text: "Kiểm tra lỗi",
      path: "/coming-soon/tech-diagnostics",
      permissions: [PERMISSIONS.DATA_DIAGNOSTIC_VIEW],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
    menuLeaf({
      key: "tech-support-history",
      icon: "history",
      text: "Lịch sử xử lý",
      path: "/coming-soon/tech-support-history",
      permissions: [PERMISSIONS.MIGRATION_STATUS_VIEW],
      roles: [ROLES.SYSTEM_TECHNICIAN],
      featureStatus: FEATURE_STATUS.LIVE,
    }),
  ],
});
