/**
 * E2E-04 Referee Competition Operations — constants.
 */

export const E2E04_REFEREE_OPERATIONS_VERSION = "e2e-04-referee-operations-v1";
export const E2E04_REFEREE_OPERATIONS_PHASE = "E2E-04";

export const REFEREE_ACTION = Object.freeze({
  ASSIGNMENT_READ: "referee.assignment.read",
  ASSIGNMENT_ACK: "referee.assignment.acknowledge",
  MATCH_OPEN: "referee.match.open",
  MATCH_SUSPEND: "referee.match.suspend",
  MATCH_RESUME: "referee.match.resume",
  SCORE_SESSION: "referee.score.session",
  SCORE_SUBMIT: "referee.score.submit",
  RESULT_SUBMIT: "referee.result.submit",
  RESULT_CORRECT: "referee.result.correct",
  RESULT_READ: "referee.result.read",
});

export const REFEREE_ACTION_VALUES = Object.freeze(Object.values(REFEREE_ACTION));

export const REFEREE_ASSIGNMENT_OPS_STATUS = Object.freeze({
  ASSIGNED: "ASSIGNED",
  ACKNOWLEDGED: "ACKNOWLEDGED",
  READY: "READY",
  REASSIGNED: "REASSIGNED",
  RELEASED: "RELEASED",
});

export const REFEREE_VALIDATION_OPS_STATUS = Object.freeze({
  NONE: "NONE",
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  CORRECTION_REQUIRED: "CORRECTION_REQUIRED",
  SUPERSEDED: "SUPERSEDED",
  VOID: "VOID",
});

export const REFEREE_BLOCKER_CODE = Object.freeze({
  MISSING_IDENTITY: "MISSING_IDENTITY",
  MISSING_TENANT: "MISSING_TENANT",
  MISSING_COMPETITION: "MISSING_COMPETITION",
  MISSING_VENUE: "MISSING_VENUE",
  MISSING_MATCH: "MISSING_MATCH",
  NOT_ASSIGNED: "NOT_ASSIGNED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  CROSS_TENANT: "CROSS_TENANT",
  MATCH_NOT_ACTIVE: "MATCH_NOT_ACTIVE",
  SCORE_ENTRY_NOT_READY: "SCORE_ENTRY_NOT_READY",
  VALIDATION_PRECONDITION: "VALIDATION_PRECONDITION",
  CORRECTION_NOT_REQUIRED: "CORRECTION_NOT_REQUIRED",
});

export const REFEREE_ERROR_CODE = Object.freeze({
  MISSING_IDENTITY: "E2E04_REFEREE_MISSING_IDENTITY",
  MISSING_TENANT: "E2E04_REFEREE_MISSING_TENANT",
  MISSING_COMPETITION: "E2E04_REFEREE_MISSING_COMPETITION",
  MISSING_VENUE: "E2E04_REFEREE_MISSING_VENUE",
  MISSING_MATCH: "E2E04_REFEREE_MISSING_MATCH",
  NOT_ASSIGNED: "E2E04_REFEREE_NOT_ASSIGNED",
  PERMISSION_DENIED: "E2E04_REFEREE_PERMISSION_DENIED",
  CROSS_TENANT_REJECTED: "E2E04_REFEREE_CROSS_TENANT_REJECTED",
  INVALID_STATE: "E2E04_REFEREE_INVALID_STATE",
  INVALID_INPUT: "E2E04_REFEREE_INVALID_INPUT",
  PRECONDITION_FAILED: "E2E04_REFEREE_PRECONDITION_FAILED",
  MATCH_NOT_ACTIVE: "E2E04_REFEREE_MATCH_NOT_ACTIVE",
  SCORE_ENTRY_NOT_READY: "E2E04_REFEREE_SCORE_ENTRY_NOT_READY",
  INVALID_SCORE: "E2E04_REFEREE_INVALID_SCORE",
  VALIDATION_PRECONDITION: "E2E04_REFEREE_VALIDATION_PRECONDITION",
  CORRECTION_NOT_REQUIRED: "E2E04_REFEREE_CORRECTION_NOT_REQUIRED",
  CLIENT_GRANT_TRUST_REJECTED: "E2E04_REFEREE_CLIENT_GRANT_TRUST_REJECTED",
  CANONICAL_CALL_FAILED: "E2E04_REFEREE_CANONICAL_CALL_FAILED",
  UNKNOWN: "E2E04_REFEREE_UNKNOWN",
});

export const REFEREE_ERROR_CODE_VALUES = Object.freeze(
  Object.values(REFEREE_ERROR_CODE)
);
