export const OFFICIAL_COURT_RPC = Object.freeze({
  RESERVE_COURTS: "official_tournament_reserve_courts",
  COMMIT_GROUP_SCHEDULE: "official_tournament_commit_group_schedule",
});

export const OFFICIAL_COURT_CODE = Object.freeze({
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  TOURNAMENT_NOT_FOUND: "TOURNAMENT_NOT_FOUND",
  TOURNAMENT_MODE_INVALID: "TOURNAMENT_MODE_INVALID",
  TOURNAMENT_STATE_INVALID: "TOURNAMENT_STATE_INVALID",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  COURT_NOT_FOUND: "COURT_NOT_FOUND",
  COURT_FORBIDDEN: "COURT_FORBIDDEN",
  COURT_OCCUPIED: "COURT_OCCUPIED",
  INVALID_WINDOW: "INVALID_WINDOW",
  RESERVATION_ALREADY_STARTED: "RESERVATION_ALREADY_STARTED",
  SCHEDULE_RESERVATION_REQUIRED: "SCHEDULE_RESERVATION_REQUIRED",
  SCHEDULE_MATCH_UNKNOWN: "SCHEDULE_MATCH_UNKNOWN",
  SCHEDULE_COURT_OUTSIDE_RESERVATION: "SCHEDULE_COURT_OUTSIDE_RESERVATION",
  SCHEDULE_TIME_OUTSIDE_RESERVATION: "SCHEDULE_TIME_OUTSIDE_RESERVATION",
  SCHEDULE_COURT_CONFLICT: "SCHEDULE_COURT_CONFLICT",
  SCHEDULE_PAIR_CONFLICT: "SCHEDULE_PAIR_CONFLICT",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  CLOUD_UNAVAILABLE: "CLOUD_UNAVAILABLE",
  TENANT_FORBIDDEN: "TENANT_FORBIDDEN",
  FORBIDDEN: "FORBIDDEN",
});

export const OFFICIAL_COURT_MESSAGES = Object.freeze({
  [OFFICIAL_COURT_CODE.NOT_AUTHENTICATED]: "Chưa đăng nhập.",
  [OFFICIAL_COURT_CODE.TOURNAMENT_NOT_FOUND]: "Không tìm thấy giải.",
  [OFFICIAL_COURT_CODE.TOURNAMENT_MODE_INVALID]: "Giải này không phải Official Open.",
  [OFFICIAL_COURT_CODE.TOURNAMENT_STATE_INVALID]: "Trạng thái giải không cho phép khóa sân.",
  [OFFICIAL_COURT_CODE.VERSION_CONFLICT]: "Giải vừa được cập nhật. Hãy tải lại rồi thử lại.",
  [OFFICIAL_COURT_CODE.COURT_NOT_FOUND]: "Không tìm thấy sân trong danh mục CLB.",
  [OFFICIAL_COURT_CODE.COURT_FORBIDDEN]: "Sân không thuộc CLB được phép.",
  [OFFICIAL_COURT_CODE.COURT_OCCUPIED]: "Sân đang bị chiếm trong khung giờ này.",
  [OFFICIAL_COURT_CODE.INVALID_WINDOW]: "Khung giờ sân không hợp lệ.",
  [OFFICIAL_COURT_CODE.RESERVATION_ALREADY_STARTED]:
    "Lịch sân đã bắt đầu. Không đổi khung giờ đang diễn ra.",
  [OFFICIAL_COURT_CODE.SCHEDULE_RESERVATION_REQUIRED]:
    "Hãy khóa sân trên lịch booking trước khi xếp lịch vòng bảng.",
  [OFFICIAL_COURT_CODE.SCHEDULE_MATCH_UNKNOWN]: "Trận không thuộc vòng bảng hiện có.",
  [OFFICIAL_COURT_CODE.SCHEDULE_COURT_OUTSIDE_RESERVATION]:
    "Sân trận không nằm trong danh sách sân đã khóa.",
  [OFFICIAL_COURT_CODE.SCHEDULE_TIME_OUTSIDE_RESERVATION]:
    "Giờ trận nằm ngoài khung sân đã khóa.",
  [OFFICIAL_COURT_CODE.SCHEDULE_COURT_CONFLICT]: "Hai trận trùng sân cùng giờ.",
  [OFFICIAL_COURT_CODE.SCHEDULE_PAIR_CONFLICT]: "Một cặp thi đấu bị trùng giờ.",
  [OFFICIAL_COURT_CODE.IDEMPOTENCY_CONFLICT]:
    "Cùng khóa lệnh nhưng nội dung khác. Không ghi trùng.",
  [OFFICIAL_COURT_CODE.IDEMPOTENCY_KEY_REQUIRED]: "Thiếu idempotency key.",
  [OFFICIAL_COURT_CODE.CLOUD_UNAVAILABLE]: "Không gọi được lệnh khóa sân trên máy chủ.",
  [OFFICIAL_COURT_CODE.TENANT_FORBIDDEN]: "Sai đơn vị (tenant).",
  [OFFICIAL_COURT_CODE.FORBIDDEN]: "Không có quyền quản lý giải này.",
});
