/**
 * CM-03 Competition Versioning — stable typed error codes.
 * Module-local; not registered in API_ERROR_CODES in this phase.
 */

export const COMPETITION_VERSION_ERROR_CODE = Object.freeze({
  INVALID_CONTRACT: "CM03_INVALID_CONTRACT",
  MISSING_TENANT: "CM03_MISSING_TENANT",
  MISSING_COMPETITION: "CM03_MISSING_COMPETITION",
  INVALID_IDENTIFIER: "CM03_INVALID_IDENTIFIER",
  TENANT_MISMATCH: "CM03_TENANT_MISMATCH",
  COMPETITION_MISMATCH: "CM03_COMPETITION_MISMATCH",
  INVALID_DEFINITION: "CM03_INVALID_DEFINITION",
  STALE_DEFINITION_REVISION: "CM03_STALE_DEFINITION_REVISION",
  MISSING_EXPECTED_PARENT: "CM03_MISSING_EXPECTED_PARENT",
  STALE_PARENT_VERSION: "CM03_STALE_PARENT_VERSION",
  STALE_LATEST_VERSION: "CM03_STALE_LATEST_VERSION",
  PARENT_NOT_FOUND: "CM03_PARENT_NOT_FOUND",
  PARENT_TENANT_MISMATCH: "CM03_PARENT_TENANT_MISMATCH",
  PARENT_COMPETITION_MISMATCH: "CM03_PARENT_COMPETITION_MISMATCH",
  DUPLICATE_VERSION: "CM03_DUPLICATE_VERSION",
  IDEMPOTENCY_CONFLICT: "CM03_IDEMPOTENCY_CONFLICT",
  VERSION_NOT_FOUND: "CM03_VERSION_NOT_FOUND",
  CROSS_TENANT_DENIED: "CM03_CROSS_TENANT_DENIED",
  CROSS_COMPETITION_COMPARE: "CM03_CROSS_COMPETITION_COMPARE",
  INVALID_RESTORE_TARGET: "CM03_INVALID_RESTORE_TARGET",
  IMMUTABLE_IDENTITY_RESTORE_CONFLICT: "CM03_IMMUTABLE_IDENTITY_RESTORE_CONFLICT",
  REPOSITORY_CONFLICT: "CM03_REPOSITORY_CONFLICT",
  MALFORMED_SNAPSHOT: "CM03_MALFORMED_SNAPSHOT",
  INVALID_VERSION_NUMBER: "CM03_INVALID_VERSION_NUMBER",
  INVALID_LINEAGE: "CM03_INVALID_LINEAGE",
  PORT_OPERATION_UNIMPLEMENTED: "CM03_PORT_OPERATION_UNIMPLEMENTED",
});
