/**
 * Phase 3D — Team / Roster Runtime error codes (capability-local).
 * Shared error-registry export is Integrator-owned — handoff only.
 */

export const TEAM_RUNTIME_ERROR_CODE = Object.freeze({
  TEAM_NOT_FOUND: "TEAM_NOT_FOUND",
  INVALID_TEAM: "INVALID_TEAM",
  INVALID_TEAM_SOURCE: "INVALID_TEAM_SOURCE",
  INVALID_TEAM_MAPPING: "INVALID_TEAM_MAPPING",
  UNSUPPORTED_TEAM_SOURCE: "UNSUPPORTED_TEAM_SOURCE",
  UNSUPPORTED_TEAM_STATUS: "UNSUPPORTED_TEAM_STATUS",
  TEAM_IDENTITY_COLLISION: "TEAM_IDENTITY_COLLISION",
  ROSTER_NOT_FOUND: "ROSTER_NOT_FOUND",
  INVALID_ROSTER: "INVALID_ROSTER",
  INVALID_ROSTER_SOURCE: "INVALID_ROSTER_SOURCE",
  INVALID_ROSTER_MAPPING: "INVALID_ROSTER_MAPPING",
  UNSUPPORTED_ROSTER_SOURCE: "UNSUPPORTED_ROSTER_SOURCE",
  UNSUPPORTED_ROSTER_STATUS: "UNSUPPORTED_ROSTER_STATUS",
  ROSTER_IDENTITY_COLLISION: "ROSTER_IDENTITY_COLLISION",
  ROSTER_MEMBER_IDENTITY_COLLISION: "ROSTER_MEMBER_IDENTITY_COLLISION",
  MISSING_PARTICIPANT_REF: "MISSING_PARTICIPANT_REF",
  INVALID_PARTICIPANT_REFERENCE: "INVALID_PARTICIPANT_REFERENCE",
  ROSTER_LOCKED_DIRECT_MUTATION: "ROSTER_LOCKED_DIRECT_MUTATION",
});

/** @type {ReadonlySet<string>} */
export const TEAM_RUNTIME_ERROR_CODE_VALUES = new Set(
  Object.values(TEAM_RUNTIME_ERROR_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isTeamRuntimeErrorCode(value) {
  return typeof value === "string" && TEAM_RUNTIME_ERROR_CODE_VALUES.has(value);
}
