/**
 * Phase 3D — Team / Roster Runtime error codes (capability-local).
 * Shared error-registry export is Integrator-owned — handoff only.
 */

export const TEAM_RUNTIME_ERROR_CODE = Object.freeze({
  TEAM_NOT_FOUND: "TEAM_NOT_FOUND",
  INVALID_TEAM: "INVALID_TEAM",
  INVALID_TEAM_SOURCE: "INVALID_TEAM_SOURCE",
  INVALID_TEAM_MAPPING: "INVALID_TEAM_MAPPING",
  UNSUPPORTED_TEAM_SOURCE: "UNSUPPORTED_TEAM_SOURCE",
  UNSUPPORTED_TEAM_STATUS: "UNSUPPORTED_TEAM_STATUS",
  TEAM_IDENTITY_COLLISION: "TEAM_IDENTITY_COLLISION",
  ROSTER_NOT_FOUND: "ROSTER_NOT_FOUND",
  INVALID_ROSTER: "INVALID_ROSTER",
  INVALID_ROSTER_SOURCE: "INVALID_ROSTER_SOURCE",
  INVALID_ROSTER_MAPPING: "INVALID_ROSTER_MAPPING",
  UNSUPPORTED_ROSTER_SOURCE: "UNSUPPORTED_ROSTER_SOURCE",
  UNSUPPORTED_ROSTER_STATUS: "UNSUPPORTED_ROSTER_STATUS",
  ROSTER_IDENTITY_COLLISION: "ROSTER_IDENTITY_COLLISION",
  ROSTER_MEMBER_IDENTITY_COLLISION: "ROSTER_MEMBER_IDENTITY_COLLISION",
  MISSING_PARTICIPANT_REF: "MISSING_PARTICIPANT_REF",
  INVALID_PARTICIPANT_REFERENCE: "INVALID_PARTICIPANT_REFERENCE",
  ROSTER_LOCKED_DIRECT_MUTATION: "ROSTER_LOCKED_DIRECT_MUTATION",
  // Core-05 management
  ENTRY_ID_REQUIRED: "ENTRY_ID_REQUIRED",
  ROSTER_LOCKED: "ROSTER_LOCKED",
  TEAM_ROSTER_UNLOCK_DENIED: "TEAM_ROSTER_UNLOCK_DENIED",
  AUTHORIZATION_DENIED: "AUTHORIZATION_DENIED",
  CROSS_TEAM_MEMBERSHIP: "CROSS_TEAM_MEMBERSHIP",
  DUPLICATE_ACTIVE_MEMBER: "DUPLICATE_ACTIVE_MEMBER",
  ROSTER_SIZE_VIOLATION: "ROSTER_SIZE_VIOLATION",
  CAPTAIN_NOT_ON_ROSTER: "CAPTAIN_NOT_ON_ROSTER",
  TENANT_MISMATCH: "TENANT_MISMATCH",
  COMPETITION_MISMATCH: "COMPETITION_MISMATCH",
  DIVISION_MISMATCH: "DIVISION_MISMATCH",
  MISSING_REQUIRED_CONTEXT: "MISSING_REQUIRED_CONTEXT",
  ELIGIBILITY_REQUIRED: "ELIGIBILITY_REQUIRED",
  ELIGIBILITY_DENIED: "ELIGIBILITY_DENIED",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  TEAM_ALREADY_EXISTS: "TEAM_ALREADY_EXISTS",
  INVALID_OPERATION: "INVALID_OPERATION",
});

/** @type {ReadonlySet<string>} */
export const TEAM_RUNTIME_ERROR_CODE_VALUES = new Set(
  Object.values(TEAM_RUNTIME_ERROR_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isTeamRuntimeErrorCode(value) {
  return typeof value === "string" && TEAM_RUNTIME_ERROR_CODE_VALUES.has(value);
}
