/**
 * CORE-16 — typed scoring error codes (capability-local).
 * Lifecycle denial reuses CORE-15 MatchRuntimeError codes — do not redefine them here.
 */

export const SCORING_ERROR_CODE = Object.freeze({
  SCORING_INVALID_FORMAT: "SCORING_INVALID_FORMAT",
  SCORING_INVALID_STATE: "SCORING_INVALID_STATE",
  SCORING_INVALID_COMMAND: "SCORING_INVALID_COMMAND",
  SCORING_INVALID_SIDE: "SCORING_INVALID_SIDE",
  SCORING_MATCH_ALREADY_COMPLETE: "SCORING_MATCH_ALREADY_COMPLETE",
  SCORING_INVALID_PROGRESSION: "SCORING_INVALID_PROGRESSION",
  SCORING_INVALID_CORRECTION_TARGET: "SCORING_INVALID_CORRECTION_TARGET",
  SCORING_DUPLICATE_SEQUENCE: "SCORING_DUPLICATE_SEQUENCE",
  SCORING_DUPLICATE_EVENT: "SCORING_DUPLICATE_EVENT",
  SCORING_REPLAY_INCONSISTENT: "SCORING_REPLAY_INCONSISTENT",
  SCORING_EVENT_ALREADY_SUPERSEDED: "SCORING_EVENT_ALREADY_SUPERSEDED",
  SCORING_CLOCK_REQUIRED: "SCORING_CLOCK_REQUIRED",
  SCORING_ID_FACTORY_REQUIRED: "SCORING_ID_FACTORY_REQUIRED",
});

/** @type {ReadonlySet<string>} */
export const SCORING_ERROR_CODE_VALUES = new Set(
  Object.values(SCORING_ERROR_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isScoringErrorCode(value) {
  return typeof value === "string" && SCORING_ERROR_CODE_VALUES.has(value);
}
