/**
 * Core-03 registration & eligibility error codes.
 */

export const REGISTRATION_ELIGIBILITY_ERROR_CODE = Object.freeze({
  REQUIRED: "REG_ELIG_REQUIRED",
  INVALID_STATUS: "REG_ELIG_INVALID_STATUS",
  INVALID_TRANSITION: "REG_ELIG_INVALID_TRANSITION",
  TERMINAL_STATUS: "REG_ELIG_TERMINAL_STATUS",
  MISSING_IDENTIFIER: "REG_ELIG_MISSING_IDENTIFIER",
  DUPLICATE_IDEMPOTENCY: "REG_ELIG_DUPLICATE_IDEMPOTENCY",
  IDEMPOTENCY_CONFLICT: "REG_ELIG_IDEMPOTENCY_CONFLICT",
  INVALID_TARGET: "REG_ELIG_INVALID_TARGET",
  INVALID_DECISION: "REG_ELIG_INVALID_DECISION",
  PORT_REQUIRED: "REG_ELIG_PORT_REQUIRED",
  FAIL_CLOSED: "REG_ELIG_FAIL_CLOSED",
  REGISTRATION_NOT_FOUND: "REG_ELIG_REGISTRATION_NOT_FOUND",
  AUDIT_APPEND_FAILED: "REG_ELIG_AUDIT_APPEND_FAILED",
  DUPLICATE_REGISTRATION: "REG_ELIG_DUPLICATE_REGISTRATION",
});

/** @type {ReadonlySet<string>} */
export const REGISTRATION_ELIGIBILITY_ERROR_CODE_VALUES = new Set(
  Object.values(REGISTRATION_ELIGIBILITY_ERROR_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isRegistrationEligibilityErrorCode(value) {
  return typeof value === "string" && REGISTRATION_ELIGIBILITY_ERROR_CODE_VALUES.has(value);
}
