/**
 * Reporting & Analytics — public facade (REPORTING-01).
 *
 * REPORTING-01: Ownership & Operational Reporting Domain Foundation.
 *
 * Consumers must import from this index — not from internal file paths.
 *
 * Does NOT export / does NOT do:
 * - Dashboard UI / Statistics UI / Experience Channels rendering
 * - Metric registry / analytical query runtime / historical intelligence
 * - SQL / migrations / Supabase / Staging / Production
 * - browser storage durable adapters
 * - production export file generation
 * - silent live→mock fallback success
 */

export { REPORTING_ANALYTICS_PHASE } from "./constants/index.js";

export {
  REPORT_TYPE,
  REPORT_TYPE_VALUES,
  isReportType,
  REPORT_SCOPE_KIND,
  REPORT_SCOPE_KIND_VALUES,
  isReportScopeKind,
  REPORT_AVAILABILITY,
  REPORT_AVAILABILITY_VALUES,
  isReportAvailability,
  REPORT_PROVENANCE,
  REPORT_PROVENANCE_VALUES,
  isReportProvenance,
  REPORT_SOURCE_KIND,
  REPORT_SOURCE_KIND_VALUES,
  isReportSourceKind,
  REPORT_PARAMETER_TYPE,
  REPORT_PARAMETER_TYPE_VALUES,
  isReportParameterType,
  REPORT_FILTER_OPERATOR,
  REPORT_FILTER_OPERATOR_VALUES,
  isReportFilterOperator,
  REPORT_SORT_DIRECTION,
  REPORT_SORT_DIRECTION_VALUES,
  isReportSortDirection,
  REPORT_EXPORT_FORMAT,
  REPORT_EXPORT_FORMAT_VALUES,
  isReportExportFormat,
  REPORTING_PERMISSIONS,
  REPORTING_PERMISSION_VALUES,
  isReportingPermission,
} from "./constants/index.js";

export {
  REPORTING_ERROR_CODE,
  REPORTING_ERROR_CODE_VALUES,
  ReportingError,
  isReportingError,
  isReportingErrorCode,
  throwReportingError,
  reportingFailure,
} from "./errors/index.js";

export {
  requireOpaqueId,
  createReportDefinitionId,
  createSavedReportId,
  createSavedFilterId,
  createExecutionId,
  createExportJobId,
  createExportRecordId,
  createReportScope,
  reportScopesEqual,
  createReportSourceReference,
  createIntelligenceProjectionReference,
  createStatisticsSourceReference,
  createDashboardAdapterSourceReference,
  createParameterDefinition,
  validateParameterValues,
  createFilterDefinition,
  validateFilterValues,
  createSortClause,
  validateSorting,
  createGroupingClause,
  validateGrouping,
  createColumnDefinition,
  orderColumnsDeterministically,
  validateColumnSelection,
  createProvenanceMetadata,
  assertNoSilentLiveToMockFallback,
  createReportDefinition,
  createSavedFilterConfiguration,
  createSavedReportConfiguration,
  createReportExecutionRequest,
  createReportExecutionResult,
  createTypedExecutionFailure,
  createExportRequest,
  createExportJobResult,
  createReportExecutionRecord,
  createExportJobRecord,
} from "./contracts/index.js";

export {
  requireReportingActor,
  authorizeReporting,
  authorizeReportingResource,
  authorizeSensitiveFields,
  authorizeExport,
  authorizeSaveReport,
  authorizeSaveFilter,
  authorizeDashboardView,
  authorizeExecuteReport,
  requireReportingScope,
  assertReportingScopeMatch,
} from "./authorization/index.js";

export {
  CLOCK_PORT_METHODS,
  ID_PROVIDER_PORT_METHODS,
  matchesClockPort,
  matchesIdProviderPort,
  createUnimplementedClockPort,
  createUnimplementedIdProviderPort,
  createFixedClockPort,
  createSequentialIdProviderPort,
  REPORT_DEFINITION_REPOSITORY_METHODS,
  SAVED_REPORT_REPOSITORY_METHODS,
  SAVED_FILTER_REPOSITORY_METHODS,
  REPORT_EXECUTION_REPOSITORY_METHODS,
  EXPORT_JOB_REPOSITORY_METHODS,
  REPORT_DATA_SOURCE_PORT_METHODS,
  EXPORT_EXECUTOR_PORT_METHODS,
  REPORTING_REPOSITORY_PORTS,
  matchesReportDefinitionRepositoryPort,
  matchesSavedReportRepositoryPort,
  matchesSavedFilterRepositoryPort,
  matchesReportExecutionRepositoryPort,
  matchesExportJobRepositoryPort,
  matchesReportDataSourcePort,
  matchesExportExecutorPort,
  createUnimplementedReportDefinitionRepositoryPort,
  createUnimplementedSavedReportRepositoryPort,
  createUnimplementedSavedFilterRepositoryPort,
  createUnimplementedReportExecutionRepositoryPort,
  createUnimplementedExportJobRepositoryPort,
  createUnimplementedReportDataSourcePort,
  createUnimplementedExportExecutorPort,
} from "./ports/index.js";

export { createInMemoryReportingRepositories } from "./repositories/index.js";

export {
  createDurableReportingRepositories,
  createFakeReportingDatabaseClient,
  requireReportingDatabaseClientPort,
  REPORTING_02_TABLES,
} from "./persistence/index.js";

export {
  REPORT_EXECUTION_STATUS,
  REPORT_EXECUTION_STATUS_VALUES,
  REPORT_EXPORT_JOB_STATUS,
  REPORT_EXPORT_JOB_STATUS_VALUES,
  REPORT_EXECUTION_STATUS_TRANSITIONS,
  REPORT_EXPORT_JOB_STATUS_TRANSITIONS,
  isAllowedLifecycleTransition,
  isReportExecutionStatus,
  isReportExportJobStatus,
} from "./lifecycle/index.js";

export {
  escapeCsvCell,
  renderCsvFromPresentationRows,
  renderJsonFromPresentationRows,
  renderPresentationExport,
  ARTIFACT_STORAGE_PORT_METHODS,
  matchesArtifactStoragePort,
  createUnimplementedArtifactStoragePort,
  createInMemoryArtifactStoragePort,
  createPresentationExportExecutor,
} from "./export/index.js";

export {
  createReportingAnalyticsFacade,
  reportingAnalyticsFacade,
  REPORTING_ANALYTICS_FACADE_METHODS,
} from "./application/index.js";

export {
  REPORTING_ANALYTICS_PLATFORM_ADAPTER_ERROR,
  reportingOk,
  reportingFail,
  reportingFailFromCaught,
  projectReportingAnalyticsActor,
  projectReportingAnalyticsTenantScope,
  projectReportingOperationInstant,
  assertReportingAnalyticsPlatformSurface,
  isOk,
  isFail,
} from "./platform/index.js";

export {
  classifyDashboardPayloadProvenance,
  MOCK_DASHBOARD_DATA_CLASSIFICATION,
  composeMixedProvenance,
  createUnavailableIntelligenceProjectionResult,
  IA_PUBLIC_PROJECTION_EXECUTION_CONTRACT,
  createIntelligenceProjectionDataSourcePort,
} from "./adapters/index.js";

export {
  REPORTING_PRESENTATION_SOURCE_STATE,
  REPORTING_PRESENTATION_SOURCE_STATE_VALUES,
  REPORTING_PRESENTATION_SOURCE_STATE_LABELS,
  isReportingPresentationSourceState,
  getReportingPresentationSourceStateLabel,
  createReportingPresentationSourceState,
  mapProvenanceToPresentationSourceState,
  mapAvailabilityToPresentationSourceState,
  resolveDashboardPresentationSourceState,
  resolveReportingPermissionVisibility,
  actorHasReportingPermission,
  REPORTING_PERMISSION_VISIBILITY_KEYS,
  REPORTING_RUNTIME_STATUS,
  createUnavailableReportingRuntime,
  createReportingRuntimeFromFacade,
  resolveReportingAnalyticsRuntime,
  injectReportingAnalyticsRuntime,
  clearReportingAnalyticsRuntime,
  getReportingAnalyticsRuntimeSnapshot,
  createExecutionLifecycleViewModel,
  createExportLifecycleViewModel,
  isValidExportOutputReference,
} from "./presentation/index.js";

export { createReportsWorkspaceController } from "./presentation/reportsWorkspaceController.js";

export const REPORTING_ANALYTICS_PUBLIC_EXPORTS = Object.freeze([
  "REPORTING_ANALYTICS_PHASE",
  "REPORT_TYPE",
  "REPORT_TYPE_VALUES",
  "isReportType",
  "REPORT_SCOPE_KIND",
  "REPORT_SCOPE_KIND_VALUES",
  "isReportScopeKind",
  "REPORT_AVAILABILITY",
  "REPORT_AVAILABILITY_VALUES",
  "isReportAvailability",
  "REPORT_PROVENANCE",
  "REPORT_PROVENANCE_VALUES",
  "isReportProvenance",
  "REPORT_SOURCE_KIND",
  "REPORT_SOURCE_KIND_VALUES",
  "isReportSourceKind",
  "REPORT_PARAMETER_TYPE",
  "REPORT_PARAMETER_TYPE_VALUES",
  "isReportParameterType",
  "REPORT_FILTER_OPERATOR",
  "REPORT_FILTER_OPERATOR_VALUES",
  "isReportFilterOperator",
  "REPORT_SORT_DIRECTION",
  "REPORT_SORT_DIRECTION_VALUES",
  "isReportSortDirection",
  "REPORT_EXPORT_FORMAT",
  "REPORT_EXPORT_FORMAT_VALUES",
  "isReportExportFormat",
  "REPORTING_PERMISSIONS",
  "REPORTING_PERMISSION_VALUES",
  "isReportingPermission",
  "REPORTING_ERROR_CODE",
  "REPORTING_ERROR_CODE_VALUES",
  "ReportingError",
  "isReportingError",
  "isReportingErrorCode",
  "throwReportingError",
  "reportingFailure",
  "requireOpaqueId",
  "createReportDefinitionId",
  "createSavedReportId",
  "createSavedFilterId",
  "createExecutionId",
  "createExportJobId",
  "createExportRecordId",
  "createReportScope",
  "reportScopesEqual",
  "createReportSourceReference",
  "createIntelligenceProjectionReference",
  "createStatisticsSourceReference",
  "createDashboardAdapterSourceReference",
  "createParameterDefinition",
  "validateParameterValues",
  "createFilterDefinition",
  "validateFilterValues",
  "createSortClause",
  "validateSorting",
  "createGroupingClause",
  "validateGrouping",
  "createColumnDefinition",
  "orderColumnsDeterministically",
  "validateColumnSelection",
  "createProvenanceMetadata",
  "assertNoSilentLiveToMockFallback",
  "createReportDefinition",
  "createSavedFilterConfiguration",
  "createSavedReportConfiguration",
  "createReportExecutionRequest",
  "createReportExecutionResult",
  "createTypedExecutionFailure",
  "createExportRequest",
  "createExportJobResult",
  "createReportExecutionRecord",
  "createExportJobRecord",
  "requireReportingActor",
  "authorizeReporting",
  "authorizeReportingResource",
  "authorizeSensitiveFields",
  "authorizeExport",
  "authorizeSaveReport",
  "authorizeSaveFilter",
  "authorizeDashboardView",
  "authorizeExecuteReport",
  "requireReportingScope",
  "assertReportingScopeMatch",
  "CLOCK_PORT_METHODS",
  "ID_PROVIDER_PORT_METHODS",
  "matchesClockPort",
  "matchesIdProviderPort",
  "createUnimplementedClockPort",
  "createUnimplementedIdProviderPort",
  "createFixedClockPort",
  "createSequentialIdProviderPort",
  "REPORT_DEFINITION_REPOSITORY_METHODS",
  "SAVED_REPORT_REPOSITORY_METHODS",
  "SAVED_FILTER_REPOSITORY_METHODS",
  "REPORT_EXECUTION_REPOSITORY_METHODS",
  "EXPORT_JOB_REPOSITORY_METHODS",
  "REPORT_DATA_SOURCE_PORT_METHODS",
  "EXPORT_EXECUTOR_PORT_METHODS",
  "REPORTING_REPOSITORY_PORTS",
  "matchesReportDefinitionRepositoryPort",
  "matchesSavedReportRepositoryPort",
  "matchesSavedFilterRepositoryPort",
  "matchesReportExecutionRepositoryPort",
  "matchesExportJobRepositoryPort",
  "matchesReportDataSourcePort",
  "matchesExportExecutorPort",
  "createUnimplementedReportDefinitionRepositoryPort",
  "createUnimplementedSavedReportRepositoryPort",
  "createUnimplementedSavedFilterRepositoryPort",
  "createUnimplementedReportExecutionRepositoryPort",
  "createUnimplementedExportJobRepositoryPort",
  "createUnimplementedReportDataSourcePort",
  "createUnimplementedExportExecutorPort",
  "createInMemoryReportingRepositories",
  "createDurableReportingRepositories",
  "createFakeReportingDatabaseClient",
  "requireReportingDatabaseClientPort",
  "REPORTING_02_TABLES",
  "REPORT_EXECUTION_STATUS",
  "REPORT_EXECUTION_STATUS_VALUES",
  "REPORT_EXPORT_JOB_STATUS",
  "REPORT_EXPORT_JOB_STATUS_VALUES",
  "REPORT_EXECUTION_STATUS_TRANSITIONS",
  "REPORT_EXPORT_JOB_STATUS_TRANSITIONS",
  "isAllowedLifecycleTransition",
  "isReportExecutionStatus",
  "isReportExportJobStatus",
  "escapeCsvCell",
  "renderCsvFromPresentationRows",
  "renderJsonFromPresentationRows",
  "renderPresentationExport",
  "ARTIFACT_STORAGE_PORT_METHODS",
  "matchesArtifactStoragePort",
  "createUnimplementedArtifactStoragePort",
  "createInMemoryArtifactStoragePort",
  "createPresentationExportExecutor",
  "createReportingAnalyticsFacade",
  "reportingAnalyticsFacade",
  "REPORTING_ANALYTICS_FACADE_METHODS",
  "REPORTING_ANALYTICS_PLATFORM_ADAPTER_ERROR",
  "reportingOk",
  "reportingFail",
  "reportingFailFromCaught",
  "projectReportingAnalyticsActor",
  "projectReportingAnalyticsTenantScope",
  "projectReportingOperationInstant",
  "assertReportingAnalyticsPlatformSurface",
  "isOk",
  "isFail",
  "classifyDashboardPayloadProvenance",
  "MOCK_DASHBOARD_DATA_CLASSIFICATION",
  "composeMixedProvenance",
  "createUnavailableIntelligenceProjectionResult",
  "IA_PUBLIC_PROJECTION_EXECUTION_CONTRACT",
  "createIntelligenceProjectionDataSourcePort",
  "REPORTING_PRESENTATION_SOURCE_STATE",
  "REPORTING_PRESENTATION_SOURCE_STATE_VALUES",
  "REPORTING_PRESENTATION_SOURCE_STATE_LABELS",
  "isReportingPresentationSourceState",
  "getReportingPresentationSourceStateLabel",
  "createReportingPresentationSourceState",
  "mapProvenanceToPresentationSourceState",
  "mapAvailabilityToPresentationSourceState",
  "resolveDashboardPresentationSourceState",
  "resolveReportingPermissionVisibility",
  "actorHasReportingPermission",
  "REPORTING_PERMISSION_VISIBILITY_KEYS",
  "REPORTING_RUNTIME_STATUS",
  "createUnavailableReportingRuntime",
  "createReportingRuntimeFromFacade",
  "resolveReportingAnalyticsRuntime",
  "injectReportingAnalyticsRuntime",
  "clearReportingAnalyticsRuntime",
  "getReportingAnalyticsRuntimeSnapshot",
  "createExecutionLifecycleViewModel",
  "createExportLifecycleViewModel",
  "isValidExportOutputReference",
  "createReportsWorkspaceController",
  "REPORTING_ANALYTICS_PUBLIC_EXPORTS",
]);
