/**
 * CORE-10 Phase 1C-B1 — candidate-evaluation failure codes.
 * Distinct from run-level OPTIMIZATION_FAILURE_CODE and Phase 1C-A
 * OBJECTIVE_EVALUATION_FAILURE_CODE. Never mapped to INFEASIBLE.
 */

export const CANDIDATE_EVALUATION_FAILURE_CODE = Object.freeze({
  INVALID_CANDIDATE_INPUT: "INVALID_CANDIDATE_INPUT",
  UNKNOWN_DECISION_VARIABLE: "UNKNOWN_DECISION_VARIABLE",
  ASSIGNMENT_OUTSIDE_DOMAIN: "ASSIGNMENT_OUTSIDE_DOMAIN",
  MISSING_ASSIGNMENT: "MISSING_ASSIGNMENT",
  DUPLICATE_ASSIGNMENT: "DUPLICATE_ASSIGNMENT",
  OPERATION_MISMATCH: "OPERATION_MISMATCH",
  TENANT_SCOPE_MISMATCH: "TENANT_SCOPE_MISMATCH",
  COMPETITION_SCOPE_MISMATCH: "COMPETITION_SCOPE_MISMATCH",
  INVALID_SNAPSHOT_BINDING: "INVALID_SNAPSHOT_BINDING",
  CONSTRAINT_PORT_INVALID: "CONSTRAINT_PORT_INVALID",
  CONSTRAINT_PORT_UNAVAILABLE: "CONSTRAINT_PORT_UNAVAILABLE",
  CONSTRAINT_PORT_EXCEPTION: "CONSTRAINT_PORT_EXCEPTION",
  ASYNC_CONSTRAINT_PORT_UNSUPPORTED: "ASYNC_CONSTRAINT_PORT_UNSUPPORTED",
  INVALID_CONSTRAINT_PORT_RESULT: "INVALID_CONSTRAINT_PORT_RESULT",
  DUPLICATE_HARD_VIOLATION: "DUPLICATE_HARD_VIOLATION",
  HARD_VIOLATION_MAGNITUDE_CONFLICT: "HARD_VIOLATION_MAGNITUDE_CONFLICT",
  INVALID_HARD_VIOLATION: "INVALID_HARD_VIOLATION",
  INVALID_CANDIDATE_EVALUATION_DEPENDENCIES:
    "INVALID_CANDIDATE_EVALUATION_DEPENDENCIES",
});
