export {
  CORE10_ENGINE_ID,
  CORE10_ENGINE_VERSION,
  CORE10_SCHEMA_VERSION,
  CORE10_COMPARATOR_VERSION,
  CORE10_FINGERPRINT_VERSION,
  CORE10_CANONICAL_SERIALIZATION_VERSION,
  CORE10_PRNG_VERSION,
  CORE10_DETERMINISM_POLICY_ID,
  CORE10_IDENTITY,
} from "./versions.js";
