/**
 * PLATFORM-HARD-CUTOVER-01 — canonical runtime authority matrix.
 * One active authority per domain. Forbidden fallbacks are explicit.
 *
 * Expanded for pre-Staging capability remediation.
 * Domains with activationFlag remain fail-closed until Owner enables them.
 */

export const HARD_CUTOVER_FLAG = "VITE_PLATFORM_HARD_CUTOVER_ENABLED";
export const COMPETITION_REMOTE_SSOT_FLAG = "VITE_COMPETITION_REMOTE_SSOT_ENABLED";

/**
 * @param {Record<string, unknown>|undefined|null} [env]
 */
export function readEnvFlag(key, env) {
  const source =
    env && typeof env === "object"
      ? env
      : typeof import.meta !== "undefined"
        ? import.meta.env
        : {};
  return String(source?.[key] ?? "false").toLowerCase() === "true";
}

export function isPlatformHardCutoverEnabled(env) {
  return readEnvFlag(HARD_CUTOVER_FLAG, env);
}

export function isCompetitionRemoteSsotEnabled(env) {
  return readEnvFlag(COMPETITION_REMOTE_SSOT_FLAG, env);
}

/**
 * @typedef {{
 *   domain: string,
 *   productionAdapter: string,
 *   canonicalReader: string,
 *   canonicalWriter: string,
 *   allowedFlag: string|null,
 *   forbiddenFallback: string[],
 *   expectedBackend: string,
 *   failClosedError: string,
 *   reseedRequirement: string,
 *   stagingAcceptanceTest: string,
 *   productionReadiness: string,
 *   verificationTest: string,
 * }} RuntimeAuthorityEntry
 */

/** @type {ReadonlyArray<RuntimeAuthorityEntry>} */
export const RUNTIME_AUTHORITY_MATRIX = Object.freeze([
  {
    domain: "identity_auth",
    productionAdapter: "Supabase Auth session + profiles",
    canonicalReader: "auth.users / public.profiles (JWT)",
    canonicalWriter: "Supabase Auth APIs (no SPA table write)",
    allowedFlag: null,
    forbiddenFallback: ["localStorage auth SoT", "mock session"],
    expectedBackend: "auth.users + public.profiles",
    failClosedError: "IDENTITY_AUTH_UNAVAILABLE",
    reseedRequirement: "VERIFY_ONLY — never invent Auth users",
    stagingAcceptanceTest: "Owner login + session restore",
    productionReadiness: "PROTECTED_CANONICAL",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "rbac_catalog",
    productionAdapter: "roles / permissions / role_permissions + route guards",
    canonicalReader: "RBAC helpers / user_has_permission",
    canonicalWriter: "identity admin RPCs (SUPER_ADMIN)",
    allowedFlag: "VITE_RBAC_ENABLED",
    forbiddenFallback: ["client-invented role grants", "silent allow when RBAC off under HC"],
    expectedBackend: "public.roles, permissions, role_permissions",
    failClosedError: "RBAC_CATALOG_UNAVAILABLE",
    reseedRequirement: "VERIFY_ONLY — catalog protected from wipe",
    stagingAcceptanceTest: "SUPER_ADMIN + unauthorized denial",
    productionReadiness: "PROTECTED_CANONICAL",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "tenant_binding",
    productionAdapter: "venues + tenant_members + user_venue_id()",
    canonicalReader: "user_venue_id() / tenant_members",
    canonicalWriter: "tenant admin RPCs (no wipe of Owner tenant)",
    allowedFlag: null,
    forbiddenFallback: ["cross-tenant silent widen", "localStorage tenant SoT"],
    expectedBackend: "public.venues, tenant_members",
    failClosedError: "TENANT_BINDING_UNAVAILABLE",
    reseedRequirement: "VERIFY_ONLY — Owner tenant preserved",
    stagingAcceptanceTest: "Owner tenant binding intact post-wipe",
    productionReadiness: "PROTECTED_CANONICAL",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "club_cloud",
    productionAdapter: "club_data_v3 sync (cloudSync.syncClubToCloud)",
    canonicalReader: "club_* RPC / club_data_v3",
    canonicalWriter: "club_* security-definer RPC",
    allowedFlag: null,
    forbiddenFallback: ["club_ai_data", "pickleball-cloud-db-v1", "mergeLegacyClubAiToV3"],
    expectedBackend: "supabase.club_data_v3",
    failClosedError: "CLUB_CLOUD_AUTHORITY_UNAVAILABLE",
    reseedRequirement: "club_create / club blob first-use",
    stagingAcceptanceTest: "Club create/list via RPC; no club_ai_data",
    productionReadiness: "CANONICAL_WITH_RESEED",
    verificationTest: "tests/platform-hard-cutover-01-phase-04-authority.test.js",
  },
  {
    domain: "club_blob_local",
    productionAdapter: "cache-only under hard cutover (not SoT)",
    canonicalReader: "cache-only",
    canonicalWriter: "forbidden as SoT under HC",
    allowedFlag: HARD_CUTOVER_FLAG,
    forbiddenFallback: ["localStorage writable SoT"],
    expectedBackend: "supabase.club_data_v3",
    failClosedError: "LOCALSTORAGE_AUTHORITY_FORBIDDEN",
    reseedRequirement: "N/A — not SoT",
    stagingAcceptanceTest: "LS club blob writes blocked under HC",
    productionReadiness: "FAIL_CLOSED_UNDER_HC",
    verificationTest: "tests/platform-hard-cutover-01-phase-04-authority.test.js",
  },
  {
    domain: "club_governance",
    productionAdapter: "club_members / governance RPCs",
    canonicalReader: "club_list_members / governance RPCs",
    canonicalWriter: "club membership review RPCs",
    allowedFlag: null,
    forbiddenFallback: ["local member list as Prod SoT"],
    expectedBackend: "club_members, club_governance*, membership request tables",
    failClosedError: "CLUB_GOVERNANCE_UNAVAILABLE",
    reseedRequirement: "membership first-use after club seed",
    stagingAcceptanceTest: "membership request/review path",
    productionReadiness: "CANONICAL_WITH_RESEED",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "court_runtime",
    productionAdapter: "court-engine/runtime durable",
    canonicalReader: "court_engine_stores / active_sessions",
    canonicalWriter: "court-engine durable adapters",
    allowedFlag: "VITE_COURT_RUNTIME_AUTHORITY=durable",
    forbiddenFallback: ["local court store as Prod SoT", "infer local from RPC failure"],
    expectedBackend: "court_engine_stores / court_engine_active_sessions",
    failClosedError: "COURT_RUNTIME_LOCAL_MODE_NOT_EXPLICIT",
    reseedRequirement: "court_clusters + courts inventory",
    stagingAcceptanceTest: "durable court runtime under HC",
    productionReadiness: "ACTIVATION_REQUIRED",
    verificationTest: "tests/platform-hard-cutover-01-phase-04-authority.test.js",
  },
  {
    domain: "customer",
    productionAdapter: "customer management RPC/tables",
    canonicalReader: "customers* select via RLS/RPC",
    canonicalWriter: "customer security-definer RPC",
    allowedFlag: null,
    forbiddenFallback: ["localStorage customer SoT", "mock customer list"],
    expectedBackend: "customers* (Staging families / docs customer-management)",
    failClosedError: "CUSTOMER_AUTHORITY_UNAVAILABLE",
    reseedRequirement: "customer first-use seed",
    stagingAcceptanceTest: "customer CRUD after reseed",
    productionReadiness: "STAGING_AHEAD_ACTIVATION_REQUIRED",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "finance",
    productionAdapter: "finance_* ledger RPC/tables",
    canonicalReader: "finance_* select",
    canonicalWriter: "finance RPC writers",
    allowedFlag: null,
    forbiddenFallback: [
      "billing tables as finance ledger substitute",
      "mock finance",
      "localStorage finance ledger",
      "demo-club finance fallback",
    ],
    expectedBackend: "finance_*",
    failClosedError: "FINANCE_AUTHORITY_UNAVAILABLE",
    reseedRequirement: "finance first-use seed",
    stagingAcceptanceTest: "finance read/write after reseed",
    productionReadiness: "STAGING_AHEAD_ACTIVATION_REQUIRED",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-finance-crm.test.js",
  },
  {
    domain: "crm",
    productionAdapter: "crm_* RPC/tables",
    canonicalReader: "crm_* select",
    canonicalWriter: "crm claim/release RPCs",
    allowedFlag: null,
    forbiddenFallback: [
      "mock CRM",
      "local CRM blob",
      "localStorage CRM services",
      "demo-club CRM fallback",
    ],
    expectedBackend: "crm_*",
    failClosedError: "CRM_AUTHORITY_UNAVAILABLE",
    reseedRequirement: "crm first-use seed",
    stagingAcceptanceTest: "CRM lead/message path after reseed",
    productionReadiness: "STAGING_AHEAD_ACTIVATION_REQUIRED",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-finance-crm.test.js",
  },
  {
    domain: "reporting",
    productionAdapter: "reporting_02 tables + presentation adapters",
    canonicalReader: "reporting_* projections",
    canonicalWriter: "reporting projection jobs/RPC (no SPA invent)",
    allowedFlag: null,
    forbiddenFallback: ["invented report rows", "mock warehouse as live"],
    expectedBackend: "reporting_*",
    failClosedError: "REPORTING_AUTHORITY_UNAVAILABLE",
    reseedRequirement: "reporting projection rebuild after biz seed",
    stagingAcceptanceTest: "reports hub typed empty/unavailable under HC",
    productionReadiness: "STAGING_AHEAD_ACTIVATION_REQUIRED",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "coaching",
    productionAdapter:
      "createDefaultCoachingRuntime → durable coaching_* RPC (UNAVAILABLE if deps missing under HC)",
    canonicalReader: "coaching_* durable repos/RPC",
    canonicalWriter: "createDurableCoachingAdapter only under HC",
    allowedFlag: HARD_CUTOVER_FLAG,
    forbiddenFallback: [
      "createLegacyCoachingAdapter",
      "coachingService localStorage SoT (pickleball-coaching-v1)",
      "silent durable→legacy fallback",
    ],
    expectedBackend: "coaching_* (docs/coaching-training/coaching-02|04)",
    failClosedError: "COACHING_LOCALSTORAGE_AUTHORITY_FORBIDDEN",
    reseedRequirement: "coaching first-use (see sql/reseed/17_COACHING_FIRST_USE.md)",
    stagingAcceptanceTest: "coaching durable or typed unavailable under HC",
    productionReadiness: "FAIL_CLOSED_UNDER_HC_UNTIL_DURABLE_ACTIVATED",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-coaching.test.js",
  },
  {
    domain: "vpr_ranking",
    productionAdapter: "vpr_* tables/RPC",
    canonicalReader: "vpr_list_* / leaderboard",
    canonicalWriter: "vpr ledger RPC",
    allowedFlag: null,
    forbiddenFallback: ["local ranking invent", "Elo-as-VPR"],
    expectedBackend: "vpr_*",
    failClosedError: "VPR_AUTHORITY_UNAVAILABLE",
    reseedRequirement: "vpr athlete/ledger first-use optional",
    stagingAcceptanceTest: "rankings page fail-closed or seeded",
    productionReadiness: "ACTIVATION_REQUIRED",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "notifications",
    productionAdapter: "notifications / push_subscriptions tables",
    canonicalReader: "notification list RPC/UI store",
    canonicalWriter: "notification insert RPC / service",
    allowedFlag: null,
    forbiddenFallback: ["mock notification SoT"],
    expectedBackend: "notifications, notification_logs, push_subscriptions",
    failClosedError: "NOTIFICATIONS_AUTHORITY_UNAVAILABLE",
    reseedRequirement: "optional after wipe",
    stagingAcceptanceTest: "notifications center loads without mock invent",
    productionReadiness: "PARTIAL_ACTIVATION",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "competition_match_result",
    productionAdapter: "competition_ssot_finalize_match_result",
    canonicalReader: "competition_ssot_finalized_results",
    canonicalWriter: "competition_ssot_finalize_match_result RPC only",
    allowedFlag: COMPETITION_REMOTE_SSOT_FLAG,
    forbiddenFallback: [
      "direct tournament_match_live write",
      "in-memory Prod claim",
      "team tournament dual finalize",
      "silent blob fallback",
    ],
    expectedBackend: "competition_ssot_finalized_results via RPC",
    failClosedError: "COMPETITION_SSOT_UNAVAILABLE",
    reseedRequirement: "competition + match + finalize via SSOT RPC",
    stagingAcceptanceTest: "Competition E2E finalize single writer",
    productionReadiness: "ACTIVATION_REQUIRED_AFTER_M8_APPLY",
    verificationTest: "tests/platform-hard-cutover-01-phase-04-competition-ssot.test.js",
  },
  {
    domain: "team_tournament",
    productionAdapter: "team_tournament_* RPC/SSOT",
    canonicalReader: "team_tournament get_setup / visible lineups",
    canonicalWriter: "team_tournament command RPCs",
    allowedFlag: null,
    forbiddenFallback: ["local TT blob as Prod SoT"],
    expectedBackend: "team_tournament_*",
    failClosedError: "TEAM_TOURNAMENT_AUTHORITY_UNAVAILABLE",
    reseedRequirement: "TT first-use after wipe",
    stagingAcceptanceTest: "TT setup/lineup RPC path",
    productionReadiness: "STAGING_AHEAD_PARTIAL",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "referee",
    productionAdapter: "referee V5 RPC pipeline",
    canonicalReader: "referee match RPC",
    canonicalWriter: "referee_update_* / SSOT finalize handoff",
    allowedFlag: null,
    forbiddenFallback: ["anon direct tournament_match_live"],
    expectedBackend: "referee V5 RPCs + competition SSOT finalize",
    failClosedError: "REFEREE_AUTHORITY_UNAVAILABLE",
    reseedRequirement: "optional after competition seed",
    stagingAcceptanceTest: "referee score → SSOT finalize boundary",
    productionReadiness: "STAGING_AHEAD_PARTIAL",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "player_rating",
    productionAdapter: "player-rating/foundation → V5 durable",
    canonicalReader: "player_rating_* / rating_v5_*",
    canonicalWriter: "rating V5 RPC with idempotency",
    allowedFlag: "VITE_PICK_VN_RATING_V5_ENABLED",
    forbiddenFallback: [
      "club blob rating verified write",
      "local assessment as SSOT",
      "competition Elo as public rating",
    ],
    expectedBackend: "player_rating_* / rating_v5_idempotency",
    failClosedError: "PLAYER_RATING_DURABLE_UNAVAILABLE",
    reseedRequirement: "rating profile first-use",
    stagingAcceptanceTest: "Rating V5 idempotency",
    productionReadiness: "ACTIVATION_REQUIRED",
    verificationTest: "tests/platform-hard-cutover-01-phase-04-rating.test.js",
  },
  {
    domain: "public_news",
    productionAdapter: "news public RPC live",
    canonicalReader: "news_public_content_query_public",
    canonicalWriter: "news admin RPC",
    allowedFlag: "VITE_PUBLIC_NEWS_SOURCE=live",
    forbiddenFallback: ["MOCK_NEWS silent fallback"],
    expectedBackend: "news_* + public RPC",
    failClosedError: "PUBLIC_NEWS_LIVE_UNAVAILABLE",
    reseedRequirement: "news first-use seed",
    stagingAcceptanceTest: "public news live or typed unavailable",
    productionReadiness: "ACTIVATION_REQUIRED",
    verificationTest: "tests/platform-hard-cutover-01-phase-04-authority.test.js",
  },
  {
    domain: "public_catalog",
    productionAdapter: "public_catalog_list_* RPCs",
    canonicalReader: "public_catalog_list_clubs/courts/tournaments/rankings",
    canonicalWriter: "catalog projection republish (no anon write)",
    allowedFlag: null,
    forbiddenFallback: ["mock catalog", "direct anon table invent"],
    expectedBackend: "public_catalog_* + list RPCs",
    failClosedError: "PUBLIC_CATALOG_UNAVAILABLE",
    reseedRequirement: "catalog projection republish after club/court seed",
    stagingAcceptanceTest: "Public Catalog post-reseed",
    productionReadiness: "CANONICAL_WITH_RESEED",
    verificationTest: "tests/public-catalog-01-privacy-tenant-isolation.test.js",
  },
  {
    domain: "billing_subscription",
    productionAdapter: "plans/plan_limits + tenant_subscriptions",
    canonicalReader: "billing UI / plans catalog",
    canonicalWriter: "billing RPCs (plans catalog protected)",
    allowedFlag: null,
    forbiddenFallback: [
      "mock plan invent",
      "localStorage billing authority",
      "silent durable→local billing fallback",
      "fake manual/mock payment success",
    ],
    expectedBackend: "plans, plan_limits, tenant_subscriptions, invoices, payments",
    failClosedError: "BILLING_AUTHORITY_UNAVAILABLE",
    reseedRequirement: "VERIFY plans; optional subscription first-use",
    stagingAcceptanceTest: "billing UI reads plan catalog",
    productionReadiness: "PROTECTED_CATALOG_PLUS_BIZ_RESEED",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "marketplace",
    productionAdapter: "marketplace_products/orders",
    canonicalReader: "marketplace UI",
    canonicalWriter: "marketplace RPC/tables",
    allowedFlag: "VITE_MARKETPLACE_ENABLED",
    forbiddenFallback: ["mock marketplace SoT"],
    expectedBackend: "marketplace_products, marketplace_orders",
    failClosedError: "MARKETPLACE_AUTHORITY_UNAVAILABLE",
    reseedRequirement: "optional",
    stagingAcceptanceTest: "marketplace flag-off or seeded fail-closed",
    productionReadiness: "ACTIVATION_REQUIRED",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "messaging",
    productionAdapter:
      "bootstrapCommunicationRuntime → PRODUCTION trusted backend / UNAVAILABLE under HC",
    canonicalReader: "communication_* repos / trusted gateway",
    canonicalWriter: "trusted backend + communication_* RPC",
    allowedFlag: HARD_CUTOVER_FLAG,
    forbiddenFallback: [
      "createDemoMessagingExperienceGateway",
      "inMemoryCommunity as Prod SoT",
      "DEV_OR_PREVIEW_DEFAULT_DEMO under hard cutover",
    ],
    expectedBackend:
      "communication_* + communication_allocate_message_position / communication_advance_read_cursor",
    failClosedError: "MESSAGING_DEMO_AUTHORITY_FORBIDDEN",
    reseedRequirement: "optional conversation first-use after activation",
    stagingAcceptanceTest: "messaging UNAVAILABLE or PRODUCTION — never DEMO under HC",
    productionReadiness: "FAIL_CLOSED_UNDER_HC_UNTIL_ACTIVATION",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-messaging.test.js",
  },
  {
    domain: "ai_assistant",
    productionAdapter: "ai-assistant engine (flagged)",
    canonicalReader: "ai_suggestions / checklist read",
    canonicalWriter: "ai suggestion RPC/tables",
    allowedFlag: "VITE_ENABLE_AI_ENGINE",
    forbiddenFallback: ["silent invent as durable advice SoT"],
    expectedBackend: "ai_suggestions, ai_workflow_checklists",
    failClosedError: "AI_ASSISTANT_UNAVAILABLE",
    reseedRequirement: "optional",
    stagingAcceptanceTest: "AI assistant flag-off or fail-closed",
    productionReadiness: "ACTIVATION_REQUIRED",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-authority.test.js",
  },
  {
    domain: "dashboard_analytics",
    productionAdapter: "getDashboardAnalytics → reporting projections or typed UNAVAILABLE",
    canonicalReader: "reporting_* / empty UNAVAILABLE presentation",
    canonicalWriter: "none (read-only dashboard; no biz mutation)",
    allowedFlag: HARD_CUTOVER_FLAG,
    forbiddenFallback: [
      "buildMockDashboardPayload",
      "mode=demo|preview silent invention",
      "localStorage club blob metrics as Prod analytics SoT",
    ],
    expectedBackend: "reporting_* or typed UNAVAILABLE",
    failClosedError: "DASHBOARD_ANALYTICS_MOCK_FORBIDDEN",
    reseedRequirement: "reporting projections after biz seed (or UNAVAILABLE OK)",
    stagingAcceptanceTest: "dashboard UNAVAILABLE/empty under HC — no mock invent",
    productionReadiness: "FAIL_CLOSED_UNDER_HC",
    verificationTest: "tests/platform-hard-cutover-01-pre-staging-dashboard.test.js",
  },
  {
    domain: "private_pairing_rules",
    productionAdapter:
      "privatePairingRulesRepository → security-definer RPC only; live load via private_pairing_get_active_rules_for_scope",
    canonicalReader: "private_pairing_get_* / list / audit RPC",
    canonicalWriter: "PRIVATE_PAIRING_RPC.* only",
    allowedFlag: HARD_CUTOVER_FLAG,
    forbiddenFallback: [
      "legacy_blob picker (loadPlayersForClub / registry)",
      "localStorage rule SoT",
      "mock rule persistence",
      "direct SPA writes to private_pairing_* tables",
      "silent rating=3.5 default under hard cutover",
    ],
    expectedBackend:
      "private_pairing_rule_sets / private_pairing_rules / private_pairing_rule_targets / private_pairing_rule_audit_logs via RPC",
    failClosedError: "PRIVATE_PAIRING_LEGACY_PICKER_FORBIDDEN",
    reseedRequirement: "SUPER_ADMIN first-use rule sets after wipe",
    stagingAcceptanceTest: "Private Pairing A1–A7",
    productionReadiness: "CANONICAL_WITH_HC_GATES",
    verificationTest: "tests/private-pairing-hard-cutover-01.test.js",
  },
]);

export function listRuntimeAuthorityDomains() {
  return RUNTIME_AUTHORITY_MATRIX.map((row) => row.domain);
}

export function getRuntimeAuthorityEntry(domain) {
  return RUNTIME_AUTHORITY_MATRIX.find((row) => row.domain === domain) || null;
}

/** Expected expanded domain count for pre-Staging remediation. */
export const RUNTIME_AUTHORITY_DOMAIN_COUNT = RUNTIME_AUTHORITY_MATRIX.length;
