/**
 * NEWS-03 — Staging rollout constants (no secrets).
 */

export const NEWS_03_STAGING_PROJECT_REF = "qyewbxjsiiyufanzcjcq";

export const NEWS_03_STAGING_PROJECT_REF_ALLOWLIST = Object.freeze([
  NEWS_03_STAGING_PROJECT_REF,
]);

export const NEWS_03_PRODUCTION_PROJECT_REF_BLOCKLIST = Object.freeze([
  "expuvcohlcjzvrrauvud",
]);

export const NEWS_03_PRODUCTION_DOMAIN_BLOCKLIST = Object.freeze([
  "pickvn.app",
]);

export const NEWS_03_ENVIRONMENT_LABEL = "staging";

export const NEWS_03_APPLY_CONFIRM_PHRASE = "NEWS_03_OWNER_GO_STAGING_ONLY";

export const NEWS_03_ROLLBACK_CONFIRM_PHRASE =
  "NEWS_03_OWNER_GO_ROLLBACK_STAGING_ONLY";

export const NEWS_03_MODES = Object.freeze({
  PREFLIGHT: "preflight",
  PLAN: "plan",
  APPLY: "apply",
  VERIFY: "verify",
  ROLLBACK: "rollback",
});

export const NEWS_03_PREFLIGHT_STATES = Object.freeze({
  NOT_APPLIED: "NOT_APPLIED",
  PARTIALLY_APPLIED: "PARTIALLY_APPLIED",
  FULLY_APPLIED_UNVERIFIED: "FULLY_APPLIED_UNVERIFIED",
  FULLY_APPLIED_VERIFIED: "FULLY_APPLIED_VERIFIED",
  STATE_UNKNOWN: "STATE_UNKNOWN",
});

export const NEWS_03_PERMISSION_KEYS = Object.freeze([
  "news.view",
  "news.edit",
  "news.review",
  "news.approve",
  "news.publish",
  "news.admin",
]);

export const NEWS_03_EVIDENCE_DIR_RELATIVE =
  "docs/news-public-content/news-03/evidence";

export const NEWS_03_BACKUP_CLASSIFICATION = "ROLLBACK_SQL_ONLY";

export const NEWS_03_ENV_NAMES = Object.freeze({
  STAGING_SUPABASE_URL: "STAGING_SUPABASE_URL",
  VITE_SUPABASE_URL: "VITE_SUPABASE_URL",
  SUPABASE_URL: "SUPABASE_URL",
  STAGING_ANON_KEY: "STAGING_SUPABASE_ANON_KEY",
  VITE_ANON_KEY: "VITE_SUPABASE_ANON_KEY",
  STAGING_SERVICE_ROLE_KEY: "STAGING_SUPABASE_SERVICE_ROLE_KEY",
  ACCESS_TOKEN: "SUPABASE_ACCESS_TOKEN",
  STAGING_ENV_FILE: "NEWS_03_STAGING_ENV_FILE",
  VITE_APP_ENV: "VITE_APP_ENV",
});

export const NEWS_03_VERDICTS = Object.freeze({
  READ_ONLY_OK: "NEWS_03_READ_ONLY_OK",
  APPLY_BLOCKED: "NEWS_03_APPLY_BLOCKED",
  APPLY_OK: "NEWS_03_APPLY_OK",
  APPLY_PARTIAL_STOPPED: "NEWS_03_APPLY_PARTIAL_STOPPED",
  ROLLBACK_BLOCKED: "NEWS_03_ROLLBACK_BLOCKED",
  ROLLBACK_OK: "NEWS_03_ROLLBACK_OK",
  VERIFY_OK: "NEWS_03_VERIFY_OK",
  VERIFY_FAILED: "NEWS_03_VERIFY_FAILED",
  BLOCKED_PRODUCTION: "NEWS_03_BLOCKED_PRODUCTION",
  BLOCKED_ENVIRONMENT: "NEWS_03_BLOCKED_ENVIRONMENT",
});
