/**
 * Batch C action matrix. Class A = exact existing authority,
 * B = partial existing, C = none. No silent writers.
 */
export const BATCH_C_ACTION_MATRIX = Object.freeze([
  {
    screen: "07",
    action: "Điều hành / Trình chiếu",
    referenceAction: "Điều hành / Trình chiếu",
    currentProductionAuthority: "Visual layout only",
    class: "A",
    enabled: true,
    why: "Chỉ đổi bố cục xem. Không ghi hồ sơ.",
    mutationPath: null,
  },
  {
    screen: "07",
    action: "Hoàn tác",
    referenceAction: "Hoàn tác",
    currentProductionAuthority: "None",
    class: "C",
    enabled: false,
    why: "Chưa có lịch sử bốc thăm có thể hoàn tác.",
    mutationPath: null,
  },
  {
    screen: "07",
    action: "Bốc tiếp",
    referenceAction: "Bốc tiếp",
    currentProductionAuthority: "None — no pair-draw writer",
    class: "C",
    enabled: false,
    why: "Chưa có bốc thăm ghép cặp trên hệ thống này.",
    mutationPath: null,
  },
  {
    screen: "07",
    action: "Khóa kết quả bốc thăm",
    referenceAction: "Khóa kết quả bốc thăm",
    currentProductionAuthority: "None — pair-draw lock not implemented",
    class: "C",
    enabled: false,
    why: "Khóa bốc thăm ghép cặp chưa có trên hệ thống này.",
    mutationPath: null,
  },
  {
    screen: "07",
    action: "Sang bốc thăm chia bảng",
    referenceAction: "Sang bốc thăm chia bảng",
    currentProductionAuthority: "Requires pair-draw locked state",
    class: "C",
    enabled: false,
    why: "Chưa có trạng thái khóa bốc thăm ghép cặp.",
    mutationPath: null,
  },
  {
    screen: "08",
    action: "Bốc cặp tiếp theo",
    referenceAction: "Bốc cặp tiếp theo",
    currentProductionAuthority: "Draw generation lives on existing setup/engine",
    class: "B",
    enabled: false,
    why: "Không bốc từng cặp trên màn này. Dùng thiết lập đầy đủ hiện có nếu cần.",
    mutationPath: null,
  },
  {
    screen: "08",
    action: "Hoàn tác",
    referenceAction: "Hoàn tác",
    currentProductionAuthority: "None on this screen",
    class: "C",
    enabled: false,
    why: "Hoàn tác bốc thăm chia bảng chưa có trên màn này.",
    mutationPath: null,
  },
  {
    screen: "08",
    action: "Khóa kết quả bốc thăm",
    referenceAction: "Khóa kết quả bốc thăm",
    currentProductionAuthority: "lockDraw is tournament-level, not per Nội dung",
    class: "B",
    enabled: false,
    why: "Khóa bốc thăm hiện áp dụng cả giải, không khóa từng nội dung trên màn này.",
    mutationPath: null,
  },
  {
    screen: "08",
    action: "Sang vòng bảng",
    referenceAction: "Sang vòng bảng",
    currentProductionAuthority: "Per-content lock does not exist",
    class: "C",
    enabled: false,
    why: "Chưa có khóa bốc thăm theo nội dung. Không dùng khóa cả giải để mở vòng bảng.",
    mutationPath: null,
  },
  {
    screen: "09",
    action: "Chốt BXH",
    referenceAction: "Chốt BXH",
    currentProductionAuthority: "None per Nội dung",
    class: "C",
    enabled: false,
    why: "Chốt bảng xếp hạng nội dung chưa có trên hệ thống này.",
    mutationPath: null,
  },
  {
    screen: "09",
    action: "Ghi điểm",
    referenceAction: "Complete Match / +1",
    currentProductionAuthority: "Referee/director scoring, not this screen",
    class: "C",
    enabled: false,
    why: "Màn này chỉ đọc tỷ số. Ghi điểm thuộc luồng trọng tài / điều hành hiện có.",
    mutationPath: null,
  },
]);

export const MULTI_CONTENT_LIMITATION =
  "Khóa / công bố bốc thăm hiện có trên hồ sơ giải, không khóa từng nội dung.";
