/**
 * Capability-local static catalog seeds (CM-02).
 * NOT a production catalog. Deterministic IDs. No random. No DB.
 */

import {
  COMPETITION_TYPE,
  COMPETITION_SCOPE,
  COMPETITION_VISIBILITY,
  COMPETITION_OWNER_TYPE,
} from "../../competition-definition/index.js";
import {
  COMPETITION_TEMPLATE_SCOPE,
  COMPETITION_TEMPLATE_AVAILABILITY,
  COMPETITION_TEMPLATE_PARTICIPANT_MODE,
  COMPETITION_TEMPLATE_INITIAL_VERSION,
} from "../constants/index.js";

/**
 * Stable capability-local template seeds used for tests and dormant commands.
 * @returns {object[]}
 */
export function createStaticCatalogSeeds() {
  return [
    {
      templateId: "cm-global-daily-play",
      templateVersion: COMPETITION_TEMPLATE_INITIAL_VERSION,
      templateScope: COMPETITION_TEMPLATE_SCOPE.GLOBAL,
      tenantId: null,
      name: "Daily Play",
      description: "Global baseline for daily play competitions.",
      supportedCompetitionTypes: [COMPETITION_TYPE.DAILY_PLAY],
      supportedScopes: [
        COMPETITION_SCOPE.CLUB,
        COMPETITION_SCOPE.TENANT,
      ],
      participantMode: COMPETITION_TEMPLATE_PARTICIPANT_MODE.INDIVIDUAL,
      availability: COMPETITION_TEMPLATE_AVAILABILITY.AVAILABLE,
      requirements: {
        requiresVenue: false,
        requiresClub: false,
        allowedOwnerTypes: [],
        requiresRegistrationWindow: false,
        requiresPlannedPeriod: false,
        allowedVisibilities: [],
        requiredCapabilities: [],
      },
      defaults: {
        visibility: COMPETITION_VISIBILITY.CLUB,
        ruleSet: { ruleSetId: "competition-core-default" },
        divisionBlueprintId: null,
        formatBlueprintId: "daily_play",
        scheduleBlueprintId: null,
        scoringBlueprintId: null,
        standingsBlueprintId: null,
        registrationDefaults: { mode: "open_session" },
      },
      capabilityTags: ["daily_play"],
      metadata: { legacyMode: "daily_play" },
    },
    {
      templateId: "cm-global-internal-tournament",
      templateVersion: COMPETITION_TEMPLATE_INITIAL_VERSION,
      templateScope: COMPETITION_TEMPLATE_SCOPE.GLOBAL,
      tenantId: null,
      name: "Internal Tournament",
      description: "Global baseline for internal club tournaments.",
      supportedCompetitionTypes: [COMPETITION_TYPE.INTERNAL_TOURNAMENT],
      supportedScopes: [COMPETITION_SCOPE.CLUB, COMPETITION_SCOPE.MULTI_CLUB],
      participantMode: COMPETITION_TEMPLATE_PARTICIPANT_MODE.INDIVIDUAL,
      availability: COMPETITION_TEMPLATE_AVAILABILITY.AVAILABLE,
      requirements: {
        requiresVenue: false,
        requiresClub: true,
        allowedOwnerTypes: [
          COMPETITION_OWNER_TYPE.USER,
          COMPETITION_OWNER_TYPE.CLUB,
          COMPETITION_OWNER_TYPE.ORGANIZATION,
        ],
        requiresRegistrationWindow: false,
        requiresPlannedPeriod: false,
        allowedVisibilities: [
          COMPETITION_VISIBILITY.PRIVATE,
          COMPETITION_VISIBILITY.CLUB,
          COMPETITION_VISIBILITY.TENANT,
        ],
        requiredCapabilities: ["registration", "draw", "scoring"],
      },
      defaults: {
        visibility: COMPETITION_VISIBILITY.CLUB,
        ruleSet: { ruleSetId: "competition-core-default" },
        divisionBlueprintId: "internal-default-divisions",
        formatBlueprintId: "internal_tournament",
        scheduleBlueprintId: null,
        scoringBlueprintId: null,
        standingsBlueprintId: null,
        registrationDefaults: { mode: "entry_approval" },
      },
      capabilityTags: ["internal_tournament", "individual"],
      metadata: { legacyMode: "internal_tournament" },
    },
    {
      templateId: "cm-global-official-tournament",
      templateVersion: COMPETITION_TEMPLATE_INITIAL_VERSION,
      templateScope: COMPETITION_TEMPLATE_SCOPE.GLOBAL,
      tenantId: null,
      name: "Official Tournament",
      description:
        "Global baseline for official tournaments. Official sub-modes (open / AI balance) remain CM-04 configuration.",
      supportedCompetitionTypes: [COMPETITION_TYPE.OFFICIAL_TOURNAMENT],
      supportedScopes: [
        COMPETITION_SCOPE.MULTI_CLUB,
        COMPETITION_SCOPE.TENANT,
        COMPETITION_SCOPE.OPEN,
      ],
      participantMode: COMPETITION_TEMPLATE_PARTICIPANT_MODE.INDIVIDUAL,
      availability: COMPETITION_TEMPLATE_AVAILABILITY.AVAILABLE,
      requirements: {
        requiresVenue: false,
        requiresClub: false,
        allowedOwnerTypes: [
          COMPETITION_OWNER_TYPE.ORGANIZATION,
          COMPETITION_OWNER_TYPE.CLUB,
          COMPETITION_OWNER_TYPE.USER,
        ],
        requiresRegistrationWindow: true,
        requiresPlannedPeriod: true,
        allowedVisibilities: [
          COMPETITION_VISIBILITY.TENANT,
          COMPETITION_VISIBILITY.PUBLIC,
        ],
        requiredCapabilities: [
          "registration",
          "seeding",
          "draw",
          "schedule",
          "scoring",
          "standings",
        ],
      },
      defaults: {
        visibility: COMPETITION_VISIBILITY.PUBLIC,
        ruleSet: { ruleSetId: "competition-core-default" },
        divisionBlueprintId: "official-default-divisions",
        formatBlueprintId: "official_tournament",
        scheduleBlueprintId: "official-default-schedule",
        scoringBlueprintId: null,
        standingsBlueprintId: null,
        registrationDefaults: { mode: "open_registration" },
      },
      capabilityTags: ["official_tournament"],
      metadata: { legacyMode: "official_tournament" },
    },
    {
      templateId: "cm-global-team-tournament-mlp4",
      templateVersion: COMPETITION_TEMPLATE_INITIAL_VERSION,
      templateScope: COMPETITION_TEMPLATE_SCOPE.GLOBAL,
      tenantId: null,
      name: "Team Tournament (MLP-4)",
      description:
        "Global team tournament template seeded from legacy FORMAT_PRESET.mlp_4.",
      supportedCompetitionTypes: [COMPETITION_TYPE.TEAM_TOURNAMENT],
      supportedScopes: [
        COMPETITION_SCOPE.CLUB,
        COMPETITION_SCOPE.MULTI_CLUB,
        COMPETITION_SCOPE.TENANT,
      ],
      participantMode: COMPETITION_TEMPLATE_PARTICIPANT_MODE.TEAM,
      availability: COMPETITION_TEMPLATE_AVAILABILITY.AVAILABLE,
      requirements: {
        requiresVenue: false,
        requiresClub: false,
        allowedOwnerTypes: [],
        requiresRegistrationWindow: false,
        requiresPlannedPeriod: false,
        allowedVisibilities: [],
        requiredCapabilities: ["teams", "roster", "scoring", "standings"],
      },
      defaults: {
        visibility: COMPETITION_VISIBILITY.CLUB,
        ruleSet: { ruleSetId: "competition-core-default" },
        divisionBlueprintId: null,
        formatBlueprintId: "mlp_4",
        scheduleBlueprintId: null,
        scoringBlueprintId: "mlp_4_scoring",
        standingsBlueprintId: "mlp_4_standings",
        registrationDefaults: { mode: "team_entry" },
      },
      capabilityTags: ["team_tournament", "mlp_4"],
      metadata: { legacyMode: "team_tournament", legacyFormatPreset: "mlp_4" },
    },
    {
      templateId: "cm-global-disabled-sample",
      templateVersion: COMPETITION_TEMPLATE_INITIAL_VERSION,
      templateScope: COMPETITION_TEMPLATE_SCOPE.GLOBAL,
      tenantId: null,
      name: "Disabled Sample",
      description: "Capability-local disabled template for rejection tests.",
      supportedCompetitionTypes: [COMPETITION_TYPE.INTERNAL_TOURNAMENT],
      supportedScopes: [COMPETITION_SCOPE.CLUB],
      participantMode: COMPETITION_TEMPLATE_PARTICIPANT_MODE.INDIVIDUAL,
      availability: COMPETITION_TEMPLATE_AVAILABILITY.DISABLED,
      requirements: {
        requiresVenue: false,
        requiresClub: true,
        allowedOwnerTypes: [],
        requiresRegistrationWindow: false,
        requiresPlannedPeriod: false,
        allowedVisibilities: [],
        requiredCapabilities: [],
      },
      defaults: {
        visibility: null,
        ruleSet: null,
        divisionBlueprintId: null,
        formatBlueprintId: null,
        scheduleBlueprintId: null,
        scoringBlueprintId: null,
        standingsBlueprintId: null,
        registrationDefaults: null,
      },
      capabilityTags: ["disabled_sample"],
      metadata: {},
    },
    {
      templateId: "cm-tenant-club-cup",
      templateVersion: COMPETITION_TEMPLATE_INITIAL_VERSION,
      templateScope: COMPETITION_TEMPLATE_SCOPE.TENANT,
      tenantId: "tenant-1",
      name: "Tenant Club Cup",
      description: "Tenant-scoped sample template for isolation tests.",
      supportedCompetitionTypes: [COMPETITION_TYPE.INTERNAL_TOURNAMENT],
      supportedScopes: [COMPETITION_SCOPE.CLUB],
      participantMode: COMPETITION_TEMPLATE_PARTICIPANT_MODE.INDIVIDUAL,
      availability: COMPETITION_TEMPLATE_AVAILABILITY.AVAILABLE,
      requirements: {
        requiresVenue: true,
        requiresClub: true,
        allowedOwnerTypes: [COMPETITION_OWNER_TYPE.CLUB],
        requiresRegistrationWindow: false,
        requiresPlannedPeriod: false,
        allowedVisibilities: [COMPETITION_VISIBILITY.CLUB],
        requiredCapabilities: ["draw"],
      },
      defaults: {
        visibility: COMPETITION_VISIBILITY.CLUB,
        ruleSet: { ruleSetId: "competition-core-default" },
        divisionBlueprintId: "tenant-club-cup-divisions",
        formatBlueprintId: "internal_tournament",
        scheduleBlueprintId: null,
        scoringBlueprintId: null,
        standingsBlueprintId: null,
        registrationDefaults: null,
      },
      capabilityTags: ["tenant", "club_cup"],
      metadata: { sample: true },
    },
  ];
}

/** Stable identity for legacy mode → template mapping (safe only). */
export const LEGACY_MODE_TO_TEMPLATE_ID = Object.freeze({
  daily_play: "cm-global-daily-play",
  internal_tournament: "cm-global-internal-tournament",
  official_tournament: "cm-global-official-tournament",
  team_tournament_mlp_4: "cm-global-team-tournament-mlp4",
});
