/**
 * CORE-13 shared Competition referee assignment command surface — constants.
 * Decision authority: CORE-13. Persistence executes validated commands only.
 */

export const CORE13_ASSIGNMENT_COMMAND_VERSION =
  "core13-canonical-assignment-command-v1";

export const CORE13_AUTHORITATIVE_EXECUTION_LOCATION = "TRUSTED_SERVER";

export const COMPETITION_REFEREE_ASSIGNMENT_EDGE_FUNCTION =
  "competition-referee-assignment";

export const ASSIGNMENT_COMMAND = Object.freeze({
  ASSIGN: "assignReferee",
  REPLACE: "replaceReferee",
  UNASSIGN: "unassignReferee",
});

export const ASSIGNMENT_COMMAND_VALUES = Object.freeze(
  Object.values(ASSIGNMENT_COMMAND)
);

export const ASSIGNMENT_OPERATION = Object.freeze({
  ASSIGN: "ASSIGN",
  REPLACE: "REPLACE",
  UNASSIGN: "UNASSIGN",
});

/** Owner-approved match lifecycle states for assignment mutation gates. */
export const ASSIGNMENT_LIFECYCLE_STATE = Object.freeze({
  PRE_MATCH: "PRE_MATCH",
  IN_PROGRESS: "IN_PROGRESS",
  SCORING_ACTIVE: "SCORING_ACTIVE",
  LOCKED: "LOCKED",
  COMPLETED: "COMPLETED",
});

export const ASSIGNMENT_LIFECYCLE_STATE_VALUES = Object.freeze(
  Object.values(ASSIGNMENT_LIFECYCLE_STATE)
);

export const ASSIGNMENT_COMMAND_ERROR_CODE = Object.freeze({
  INVALID_INPUT: "CORE13_ASSIGNMENT_INVALID_INPUT",
  CANONICAL_REFEREE_ID_REQUIRED: "CORE13_CANONICAL_REFEREE_ID_REQUIRED",
  DISPLAY_NAME_IDENTITY_DENIED: "CORE13_DISPLAY_NAME_IDENTITY_DENIED",
  EMAIL_AS_AUTHORITY_DENIED: "CORE13_EMAIL_AS_AUTHORITY_DENIED",
  PHONE_AS_AUTHORITY_DENIED: "CORE13_PHONE_AS_AUTHORITY_DENIED",
  CROSS_TENANT_DENIED: "CORE13_CROSS_TENANT_DENIED",
  CROSS_TOURNAMENT_DENIED: "CORE13_CROSS_TOURNAMENT_DENIED",
  UNAUTHORIZED_ACTOR: "CORE13_UNAUTHORIZED_ACTOR",
  CLIENT_GRANT_TRUST_REJECTED: "CORE13_CLIENT_GRANT_TRUST_REJECTED",
  STALE_WRITE: "CORE13_STALE_WRITE",
  IDEMPOTENCY_CONFLICT: "CORE13_IDEMPOTENCY_CONFLICT",
  IDEMPOTENCY_KEY_REQUIRED: "CORE13_IDEMPOTENCY_KEY_REQUIRED",
  EXPECTED_VERSION_REQUIRED: "CORE13_EXPECTED_VERSION_REQUIRED",
  LIFECYCLE_DENIED: "CORE13_LIFECYCLE_DENIED",
  EMERGENCY_REPLACEMENT_REQUIRED: "CORE13_EMERGENCY_REPLACEMENT_REQUIRED",
  EMERGENCY_UNAUTHORIZED: "CORE13_EMERGENCY_UNAUTHORIZED",
  UNASSIGN_WITHOUT_REPLACEMENT_DENIED:
    "CORE13_UNASSIGN_WITHOUT_REPLACEMENT_DENIED",
  CORE13_VALIDATION_REJECTED: "CORE13_VALIDATION_REJECTED",
  PERSISTENCE_REQUIRED: "CORE13_PERSISTENCE_REQUIRED",
  IN_MEMORY_PRODUCTION_FORBIDDEN: "CORE13_IN_MEMORY_PRODUCTION_FORBIDDEN",
  SEED_BYPASS_DENIED: "CORE13_SEED_BYPASS_DENIED",
  DAILY_PLAY_NOT_APPLICABLE: "CORE13_DAILY_PLAY_NOT_APPLICABLE",
  FOREIGN_REFEREE_DENIED: "CORE13_FOREIGN_REFEREE_DENIED",
  STALE_TENANT_CONTEXT: "CORE13_STALE_TENANT_CONTEXT",
  STALE_CLUB_CONTEXT: "CORE13_STALE_CLUB_CONTEXT",
  NOT_CONFIGURED: "CORE13_NOT_CONFIGURED",
  SERVICE_ROLE_REQUIRED: "CORE13_SERVICE_ROLE_REQUIRED",
  ORIGINATING_ACTOR_REQUIRED: "CORE13_ORIGINATING_ACTOR_REQUIRED",
  CANONICAL_REFEREE_EVIDENCE_REQUIRED:
    "CORE13_CANONICAL_REFEREE_EVIDENCE_REQUIRED",
  TRUSTED_SERVER_REQUIRED: "CORE13_TRUSTED_SERVER_REQUIRED",
  MALFORMED_ASSIGNMENT_RESULT: "CORE13_MALFORMED_ASSIGNMENT_RESULT",
  ACTIVE_ASSIGNMENT_EXISTS: "CORE13_ACTIVE_ASSIGNMENT_EXISTS",
});

export const ASSIGNMENT_COMMAND_ERROR_CODE_VALUES = Object.freeze(
  Object.values(ASSIGNMENT_COMMAND_ERROR_CODE)
);

export const DURABLE_ASSIGNMENT_PERSISTENCE_CLASSIFICATION = "DURABLE";
export const TEST_DOUBLE_ASSIGNMENT_PERSISTENCE_CLASSIFICATION =
  "TEST_DOUBLE_ONLY";

/** Modes that may invoke the shared assignment command when referee feature applies. */
export const ASSIGNMENT_COMPETITION_MODE = Object.freeze({
  INTERNAL: "INTERNAL",
  OFFICIAL_OPEN: "OFFICIAL_OPEN",
  TEAM: "TEAM",
  DAILY_PLAY: "DAILY_PLAY",
});
