export const BATCH_E_ACTION_MATRIX = Object.freeze([
  {
    screen: "15",
    action: "Mở trận",
    authoritySource: "Navigate to existing match center read path",
    class: "A",
    enabled: true,
    stateRule: "Luôn mở danh sách trận đã lưu. Không ghi tỷ số.",
    mutationPath: null,
  },
  {
    screen: "15",
    action: "Mở trọng tài",
    authoritySource: "Existing /referee/:token when token present",
    class: "B",
    enabled: "token",
    stateRule: "Chỉ mở khi trận có mã trọng tài sẵn. Không ghi điểm tại màn này.",
    mutationPath: null,
  },
  {
    screen: "15",
    action: "Xem sân",
    authoritySource: "Navigate to Screen 16 tournament court board",
    class: "A",
    enabled: true,
    stateRule: "Chỉ điều hướng trong trải nghiệm giải. Không mở /court-engine.",
    mutationPath: null,
  },
  {
    screen: "15",
    action: "Xử lý chậm / chuyển sân / tạm dừng",
    authoritySource: "None on this screen",
    class: "C",
    enabled: false,
    stateRule: "Chưa hỗ trợ thao tác này trong nội dung hiện tại.",
    mutationPath: null,
  },
  {
    screen: "15",
    action: "Thông báo nhanh",
    authoritySource: "None",
    class: "C",
    enabled: false,
    stateRule: "Chưa gửi thông báo vận hành từ màn này.",
    mutationPath: null,
  },
  {
    screen: "15",
    action: "Ghi điểm / hoàn tất trận",
    authoritySource: "Denied — scoring stays on existing director/referee paths",
    class: "C",
    enabled: false,
    stateRule: "Màn điều hành này không ghi tỷ số.",
    mutationPath: null,
  },
  {
    screen: "16",
    action: "Xem sân / xem trận trên sân",
    authoritySource: "Read derived court occupancy from event.matches",
    class: "A",
    enabled: true,
    stateRule: "Chỉ đọc sân vật lý và trận đã gán.",
    mutationPath: null,
  },
  {
    screen: "16",
    action: "Đổi trạng thái sân / bảo trì",
    authoritySource: "None",
    class: "C",
    enabled: false,
    stateRule: "Không ghi trạng thái sân trên màn này.",
    mutationPath: null,
  },
  {
    screen: "17",
    action: "Xem phân công",
    authoritySource: "Read match.referee and settings.refereeRoster",
    class: "A",
    enabled: true,
    stateRule: "Chỉ đọc phân công hiện có.",
    mutationPath: null,
  },
  {
    screen: "17",
    action: "Gán / thay trọng tài",
    authoritySource: "Existing assignment writers not bound here",
    class: "C",
    enabled: false,
    stateRule: "Chưa hỗ trợ gán trọng tài trên màn này.",
    mutationPath: null,
  },
  {
    screen: "17",
    action: "Mở bảng điểm trọng tài",
    authoritySource: "Existing /referee/:token when token present",
    class: "B",
    enabled: "token",
    stateRule: "Chỉ mở luồng trọng tài hiện có. Không nhúng bảng điểm.",
    mutationPath: null,
  },
  {
    screen: "18",
    action: "Xem sự cố",
    authoritySource: "Derived from postponed/forfeit/desync/unassigned reads",
    class: "A",
    enabled: true,
    stateRule: "Chỉ đọc ngoại lệ đã có trên hồ sơ trận.",
    mutationPath: null,
  },
  {
    screen: "18",
    action: "Xử lý / nâng cấp / bỏ cuộc / điều chỉnh / mở lại",
    authoritySource: "None",
    class: "C",
    enabled: false,
    stateRule: "Chưa hỗ trợ thao tác này trong nội dung hiện tại.",
    mutationPath: null,
  },
]);
