/**
 * ECO-01/ECO-02 — provider-neutral catalogues (immutable).
 * No vendor SDK codes as connector runtime keys.
 * No secret values — names and classifications only.
 */

export const ECOSYSTEM_INTEGRATIONS_PHASE = Object.freeze({
  id: "ECO-02b",
  name: "legacy-vite-secret-cutover",
  priorPhase: "ECO-02",
  wiredToProductionRuntime: false,
  hasRealProviders: false,
  hasNetworkClients: false,
  hasCredentialStorage: false,
  hasProductionWebhooks: false,
  hasSecretBoundary: true,
  hasLiveCredentialResolver: false,
  hasLegacySecretCutover: true,
  structureComplete: true,
  productionBlocked: true,
});

export const CONNECTOR_KIND = Object.freeze({
  PAYMENT: "PAYMENT",
  NOTIFICATION: "NOTIFICATION",
  IDENTITY: "IDENTITY",
  CALENDAR: "CALENDAR",
  IMPORT_EXPORT: "IMPORT_EXPORT",
  WEBHOOK: "WEBHOOK",
  GENERIC: "GENERIC",
});

export const CONNECTOR_KIND_VALUES = Object.freeze(Object.values(CONNECTOR_KIND));

export const CONNECTOR_DIRECTION = Object.freeze({
  INBOUND: "INBOUND",
  OUTBOUND: "OUTBOUND",
  BIDIRECTIONAL: "BIDIRECTIONAL",
});

export const CONNECTOR_DIRECTION_VALUES = Object.freeze(
  Object.values(CONNECTOR_DIRECTION)
);

export const CONNECTOR_ENVIRONMENT = Object.freeze({
  TEST: "TEST",
  SANDBOX: "SANDBOX",
  STAGING: "STAGING",
  PRODUCTION: "PRODUCTION",
});

export const CONNECTOR_ENVIRONMENT_VALUES = Object.freeze(
  Object.values(CONNECTOR_ENVIRONMENT)
);

export const CONNECTOR_LIFECYCLE = Object.freeze({
  DECLARED: "DECLARED",
  CONFIGURED: "CONFIGURED",
  READY: "READY",
  DEGRADED: "DEGRADED",
  DISABLED: "DISABLED",
  RETIRED: "RETIRED",
});

export const CONNECTOR_LIFECYCLE_VALUES = Object.freeze(
  Object.values(CONNECTOR_LIFECYCLE)
);

export const INVOCATION_MODE = Object.freeze({
  SYNC: "SYNC",
  ASYNC: "ASYNC",
  WEBHOOK: "WEBHOOK",
  BATCH: "BATCH",
});

export const INVOCATION_MODE_VALUES = Object.freeze(Object.values(INVOCATION_MODE));

export const CREDENTIAL_REQUIREMENT = Object.freeze({
  NONE: "NONE",
  REQUIRED: "REQUIRED",
  OPTIONAL: "OPTIONAL",
});

export const CREDENTIAL_REQUIREMENT_VALUES = Object.freeze(
  Object.values(CREDENTIAL_REQUIREMENT)
);

export const INTEGRATION_ERROR_CODE = Object.freeze({
  CONFIGURATION: "INTEGRATION_CONFIGURATION",
  AUTHENTICATION: "INTEGRATION_AUTHENTICATION",
  AUTHORIZATION: "INTEGRATION_AUTHORIZATION",
  VALIDATION: "INTEGRATION_VALIDATION",
  UNSUPPORTED_CAPABILITY: "INTEGRATION_UNSUPPORTED_CAPABILITY",
  RATE_LIMITED: "INTEGRATION_RATE_LIMITED",
  TRANSIENT_PROVIDER: "INTEGRATION_TRANSIENT_PROVIDER",
  TIMEOUT: "INTEGRATION_TIMEOUT",
  NETWORK: "INTEGRATION_NETWORK",
  CONFLICT_DUPLICATE: "INTEGRATION_CONFLICT_DUPLICATE",
  PERMANENT_PROVIDER_REJECTION: "INTEGRATION_PERMANENT_PROVIDER_REJECTION",
  MALFORMED_PROVIDER_RESPONSE: "INTEGRATION_MALFORMED_PROVIDER_RESPONSE",
  INTERNAL_INTEGRATION_FAILURE: "INTEGRATION_INTERNAL_FAILURE",
});

export const INTEGRATION_ERROR_CODE_VALUES = Object.freeze(
  Object.values(INTEGRATION_ERROR_CODE)
);

export const WEBHOOK_VERIFICATION_OUTCOME = Object.freeze({
  VERIFIED: "VERIFIED",
  MISSING: "MISSING",
  MALFORMED: "MALFORMED",
  INVALID: "INVALID",
  EXPIRED: "EXPIRED",
  REPLAY_SUSPECTED: "REPLAY_SUSPECTED",
});

export const WEBHOOK_VERIFICATION_OUTCOME_VALUES = Object.freeze(
  Object.values(WEBHOOK_VERIFICATION_OUTCOME)
);

export const IDEMPOTENCY_OUTCOME = Object.freeze({
  NEW: "NEW",
  DUPLICATE: "DUPLICATE",
  CONFLICT: "CONFLICT",
});

export const IDEMPOTENCY_OUTCOME_VALUES = Object.freeze(
  Object.values(IDEMPOTENCY_OUTCOME)
);

export const OPERATIONAL_STATUS = Object.freeze({
  READY: "READY",
  NOT_READY: "NOT_READY",
  DEGRADED: "DEGRADED",
  UNAVAILABLE: "UNAVAILABLE",
});

export const OPERATIONAL_STATUS_VALUES = Object.freeze(
  Object.values(OPERATIONAL_STATUS)
);

export const ENVELOPE_VERSION = "eco-envelope-1";

export const CONNECTOR_DESCRIPTOR_VERSION = "eco-connector-1";

export const PROVIDER_CAPABILITY_VERSION = "eco-capability-1";

/** ECO-02 — secret / environment boundary catalogues */

export const ENVIRONMENT_CLASS = Object.freeze({
  CLIENT_SAFE_CONFIGURATION: "CLIENT_SAFE_CONFIGURATION",
  SERVER_ONLY_SECRET: "SERVER_ONLY_SECRET",
  BROWSER_EXPOSED_SECRET_RISK: "BROWSER_EXPOSED_SECRET_RISK",
  MOCK_ONLY: "MOCK_ONLY",
  LEGACY: "LEGACY",
  CANONICAL_BOUNDARY: "CANONICAL_BOUNDARY",
  DIRECT_ENV_ACCESS: "DIRECT_ENV_ACCESS",
  UNSAFE_LOGGING: "UNSAFE_LOGGING",
  ENVIRONMENT_DRIFT: "ENVIRONMENT_DRIFT",
  REQUIRES_OWNER_GO: "REQUIRES_OWNER_GO",
  DEFERRED: "DEFERRED",
});

export const ENVIRONMENT_CLASS_VALUES = Object.freeze(
  Object.values(ENVIRONMENT_CLASS)
);

export const SECRET_REFERENCE_SOURCE = Object.freeze({
  ENV_NAME: "ENV_NAME",
  VAULT_PATH: "VAULT_PATH",
  TEST_DOUBLE: "TEST_DOUBLE",
});

export const SECRET_REFERENCE_SOURCE_VALUES = Object.freeze(
  Object.values(SECRET_REFERENCE_SOURCE)
);

export const CREDENTIAL_PRESENCE = Object.freeze({
  PRESENT: "PRESENT",
  ABSENT: "ABSENT",
  UNKNOWN: "UNKNOWN",
  REDACTED: "REDACTED",
});

export const CREDENTIAL_PRESENCE_VALUES = Object.freeze(
  Object.values(CREDENTIAL_PRESENCE)
);

export const ENDPOINT_CLASS = Object.freeze({
  PUBLIC: "PUBLIC",
  SANDBOX: "SANDBOX",
  STAGING: "STAGING",
  PRODUCTION: "PRODUCTION",
  INTERNAL: "INTERNAL",
  MOCK: "MOCK",
});

export const ENDPOINT_CLASS_VALUES = Object.freeze(Object.values(ENDPOINT_CLASS));

export const SECRET_BOUNDARY_READINESS = Object.freeze({
  READY: "READY",
  NOT_READY: "NOT_READY",
  BLOCKED_ENVIRONMENT: "BLOCKED_ENVIRONMENT",
  MISSING_CREDENTIAL: "MISSING_CREDENTIAL",
  CLASSIFICATION_UNSAFE: "CLASSIFICATION_UNSAFE",
  DEGRADED: "DEGRADED",
});

export const SECRET_BOUNDARY_READINESS_VALUES = Object.freeze(
  Object.values(SECRET_BOUNDARY_READINESS)
);

export const SECRET_REFERENCE_VERSION = "eco-secret-ref-1";
export const CREDENTIAL_REQUIREMENT_DESCRIPTOR_VERSION =
  "eco-credential-requirement-1";
export const CLIENT_SAFE_PUBLIC_CONFIG_VERSION = "eco-client-safe-config-1";
export const SERVER_ONLY_CREDENTIAL_BOUNDARY_VERSION =
  "eco-server-only-boundary-1";
