/**
 * Phase 3C — Registration Runtime error codes (capability-local).
 * Shared error-registry export is Integrator-owned — handoff only.
 */

export const REGISTRATION_RUNTIME_ERROR_CODE = Object.freeze({
  REGISTRATION_NOT_FOUND: "REGISTRATION_NOT_FOUND",
  INVALID_REGISTRATION: "INVALID_REGISTRATION",
  UNSUPPORTED_REGISTRATION_SOURCE: "UNSUPPORTED_REGISTRATION_SOURCE",
  UNSUPPORTED_REGISTRATION_KIND: "UNSUPPORTED_REGISTRATION_KIND",
  UNSUPPORTED_REGISTRATION_STATUS: "UNSUPPORTED_REGISTRATION_STATUS",
  REGISTRATION_IDENTITY_COLLISION: "REGISTRATION_IDENTITY_COLLISION",
  INVALID_PARTICIPANT_REFERENCE: "INVALID_PARTICIPANT_REFERENCE",
  DUPLICATE_REGISTRATION: "DUPLICATE_REGISTRATION",
  INVALID_REGISTRATION_MAPPING: "INVALID_REGISTRATION_MAPPING",
});

/** @type {ReadonlySet<string>} */
export const REGISTRATION_RUNTIME_ERROR_CODE_VALUES = new Set(
  Object.values(REGISTRATION_RUNTIME_ERROR_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isRegistrationRuntimeErrorCode(value) {
  return typeof value === "string" && REGISTRATION_RUNTIME_ERROR_CODE_VALUES.has(value);
}
