-- Daily Play end-to-end canonical remediation.
-- LOCAL PACKAGE ONLY. DO NOT APPLY WITHOUT OWNER GO STAGING.
-- Court inventory remains public.club_data_v3.data->'courts'.

BEGIN;

CREATE TABLE public.daily_play_court_leases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL CHECK (length(trim(tenant_id)) > 0),
  club_id text NOT NULL CHECK (length(trim(club_id)) > 0),
  tournament_id uuid NOT NULL
    REFERENCES public.canonical_tournaments(id) ON DELETE CASCADE,
  match_id text NOT NULL CHECK (length(trim(match_id)) > 0),
  court_id text NOT NULL CHECK (length(trim(court_id)) > 0),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'released')),
  leased_at timestamptz NOT NULL DEFAULT now(),
  released_at timestamptz,
  CHECK (
    (status = 'active' AND released_at IS NULL)
    OR (status = 'released' AND released_at IS NOT NULL)
  )
);

CREATE UNIQUE INDEX daily_play_court_leases_one_active_court_uidx
  ON public.daily_play_court_leases (tenant_id, club_id, court_id)
  WHERE status = 'active';

CREATE INDEX daily_play_court_leases_tournament_idx
  ON public.daily_play_court_leases (tenant_id, tournament_id, status);

CREATE TABLE public.daily_play_command_ledger (
  tenant_id text NOT NULL CHECK (length(trim(tenant_id)) > 0),
  tournament_id uuid NOT NULL
    REFERENCES public.canonical_tournaments(id) ON DELETE CASCADE,
  command text NOT NULL CHECK (length(trim(command)) > 0),
  idempotency_key text NOT NULL CHECK (length(trim(idempotency_key)) > 0),
  result jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, tournament_id, command, idempotency_key)
);

ALTER TABLE public.daily_play_court_leases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_play_command_ledger ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.daily_play_court_leases FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.daily_play_command_ledger FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.daily_play_version_conflict(
  p_expected integer, p_actual integer
) RETURNS jsonb
LANGUAGE sql IMMUTABLE
AS $$
  SELECT jsonb_build_object(
    'ok', false, 'code', 'VERSION_CONFLICT',
    'expectedVersion', p_expected, 'actualVersion', p_actual
  )
$$;

CREATE OR REPLACE FUNCTION public.daily_play_begin_command(
  p_tenant_id text, p_tournament_id uuid, p_command text, p_idempotency_key text
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_result jsonb;
BEGIN
  IF nullif(trim(coalesce(p_idempotency_key, '')), '') IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'code', 'IDEMPOTENCY_KEY_REQUIRED');
  END IF;

  -- Serialize equal command keys without leaving poisoned ledger rows when a
  -- validation/CAS attempt returns an error before command completion.
  PERFORM pg_advisory_xact_lock(hashtextextended(
    p_tenant_id || ':' || p_tournament_id::text || ':' || p_command || ':' || p_idempotency_key, 0
  ));

  SELECT result INTO v_result
  FROM public.daily_play_command_ledger
  WHERE tenant_id = p_tenant_id AND tournament_id = p_tournament_id
    AND command = p_command AND idempotency_key = p_idempotency_key;

  IF FOUND THEN
    RETURN jsonb_build_object('ok', true, 'replay', true, 'result', v_result);
  END IF;
  RETURN jsonb_build_object('ok', true, 'replay', false);
END
$$;

CREATE OR REPLACE FUNCTION public.daily_play_finish_command(
  p_tenant_id text, p_tournament_id uuid, p_command text,
  p_idempotency_key text, p_result jsonb
) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.daily_play_command_ledger(
    tenant_id, tournament_id, command, idempotency_key, result
  ) VALUES (p_tenant_id, p_tournament_id, p_command, p_idempotency_key, p_result)
  ON CONFLICT (tenant_id, tournament_id, command, idempotency_key)
  DO UPDATE SET result = EXCLUDED.result;
END
$$;

CREATE OR REPLACE FUNCTION public.daily_play_match_player_ids(p_match jsonb)
RETURNS jsonb
LANGUAGE sql IMMUTABLE
AS $$
  SELECT coalesce(jsonb_agg(to_jsonb(s.player_id) ORDER BY s.player_id), '[]'::jsonb)
  FROM (
    SELECT DISTINCT nullif(trim(x.player_id), '') AS player_id
    FROM (
      SELECT value #>> '{}' AS player_id
      FROM jsonb_array_elements(coalesce(p_match->'playerIds', '[]'::jsonb))
      WHERE jsonb_typeof(value) IN ('string', 'number')
      UNION ALL
      SELECT value #>> '{}'
      FROM jsonb_array_elements(coalesce(p_match->'teamAPlayerIds', '[]'::jsonb))
      WHERE jsonb_typeof(value) IN ('string', 'number')
      UNION ALL
      SELECT value #>> '{}'
      FROM jsonb_array_elements(coalesce(p_match->'teamBPlayerIds', '[]'::jsonb))
      WHERE jsonb_typeof(value) IN ('string', 'number')
      UNION ALL
      SELECT coalesce(value->>'playerId', value->>'id', value #>> '{}')
      FROM jsonb_array_elements(coalesce(p_match->'players', '[]'::jsonb))
      UNION ALL
      SELECT coalesce(value->>'playerId', value->>'id', value #>> '{}')
      FROM jsonb_array_elements(coalesce(p_match->'teamA', '[]'::jsonb))
      UNION ALL
      SELECT coalesce(value->>'playerId', value->>'id', value #>> '{}')
      FROM jsonb_array_elements(coalesce(p_match->'teamB', '[]'::jsonb))
    ) x
  ) s
  WHERE s.player_id IS NOT NULL
$$;

CREATE OR REPLACE FUNCTION public.daily_play_read_courts(
  p_club_id text, p_enabled_court_ids jsonb DEFAULT NULL
) RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT coalesce(jsonb_agg(c.court ORDER BY c.ord), '[]'::jsonb)
  FROM public.club_data_v3 d
  CROSS JOIN LATERAL jsonb_array_elements(
    CASE WHEN jsonb_typeof(d.data->'courts') = 'array'
      THEN d.data->'courts' ELSE '[]'::jsonb END
  ) WITH ORDINALITY AS c(court, ord)
  WHERE d.club_id = p_club_id
    AND nullif(trim(coalesce(c.court->>'id', c.court->>'courtId', '')), '') IS NOT NULL
    AND lower(coalesce(c.court->>'active', 'true')) NOT IN ('false', '0', 'no')
    AND lower(coalesce(c.court->>'status', 'active')) NOT IN ('locked', 'maintenance')
    AND (
      -- NULL or [] => all usable courts (legacy Daily Play default).
      -- Non-empty array => explicit allow-list.
      p_enabled_court_ids IS NULL
      OR jsonb_typeof(p_enabled_court_ids) IS DISTINCT FROM 'array'
      OR jsonb_array_length(p_enabled_court_ids) = 0
      OR EXISTS (
        SELECT 1 FROM jsonb_array_elements_text(p_enabled_court_ids) e(id)
        WHERE e.id = coalesce(c.court->>'id', c.court->>'courtId')
      )
    )
$$;

CREATE OR REPLACE FUNCTION public.daily_play_replace_match(
  p_matches jsonb, p_match_id text, p_replacement jsonb
) RETURNS jsonb
LANGUAGE sql IMMUTABLE
AS $$
  SELECT coalesce(jsonb_agg(
    CASE WHEN coalesce(m.match->>'id', m.match->>'matchId') = p_match_id
      THEN p_replacement ELSE m.match END ORDER BY m.ord
  ), '[]'::jsonb)
  FROM jsonb_array_elements(coalesce(p_matches, '[]'::jsonb))
    WITH ORDINALITY AS m(match, ord)
$$;

CREATE OR REPLACE FUNCTION public.daily_play_write_state(
  p_tournament_id uuid, p_expected integer, p_state jsonb
) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_rows integer;
BEGIN
  UPDATE public.canonical_tournaments t
  SET payload = jsonb_set(
        coalesce(t.payload, '{}'::jsonb),
        '{settings}',
        coalesce(t.payload->'settings', '{}'::jsonb)
          || jsonb_build_object('dailyPlay', p_state),
        true
      ),
      updated_at = now()
  WHERE t.id = p_tournament_id
    AND coalesce(
      CASE WHEN (t.payload#>>'{settings,dailyPlay,revision}') ~ '^[0-9]+$'
        THEN (t.payload#>>'{settings,dailyPlay,revision}')::integer END, 0
    ) = p_expected;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  RETURN v_rows = 1;
END
$$;

CREATE OR REPLACE FUNCTION public.daily_play_snapshot(
  p_tenant_id text, p_club_id text, p_tournament_id uuid
) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_t public.canonical_tournaments%ROWTYPE;
  v_state jsonb;
  v_courts jsonb;
  v_leases jsonb;
BEGIN
  SELECT * INTO v_t FROM public.canonical_tournaments
  WHERE id = p_tournament_id AND tenant_id = p_tenant_id
    AND club_id = p_club_id AND mode = 'daily_play';
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'code', 'TOURNAMENT_NOT_FOUND');
  END IF;

  v_state := coalesce(v_t.payload#>'{settings,dailyPlay}', '{}'::jsonb);
  v_state := jsonb_set(v_state, '{revision}', to_jsonb(coalesce(
    CASE WHEN (v_state->>'revision') ~ '^[0-9]+$'
      THEN (v_state->>'revision')::integer END, 0
  )), true);
  v_state := jsonb_set(v_state, '{checkedInPlayerIds}',
    CASE WHEN jsonb_typeof(v_state->'checkedInPlayerIds') = 'array'
      THEN v_state->'checkedInPlayerIds' ELSE '[]'::jsonb END, true);
  v_state := jsonb_set(v_state, '{matches}',
    CASE WHEN jsonb_typeof(v_state->'matches') = 'array'
      THEN v_state->'matches' ELSE '[]'::jsonb END, true);

  v_courts := public.daily_play_read_courts(
    p_club_id,
    CASE WHEN v_state ? 'enabledCourtIds' THEN v_state->'enabledCourtIds' ELSE NULL END
  );
  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'matchId', l.match_id, 'courtId', l.court_id, 'leasedAt', l.leased_at
  ) ORDER BY l.leased_at), '[]'::jsonb)
  INTO v_leases
  FROM public.daily_play_court_leases l
  WHERE l.tenant_id = p_tenant_id AND l.club_id = p_club_id
    AND l.tournament_id = p_tournament_id AND l.status = 'active';

  RETURN jsonb_build_object(
    'ok', true, 'tournamentId', p_tournament_id, 'state', v_state,
    'courts', v_courts, 'activeLeases', v_leases
  );
END
$$;

CREATE OR REPLACE FUNCTION public.daily_play_get_state(
  p_tenant_id text, p_club_id text, p_tournament_id uuid
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  PERFORM public.canonical_tournament_assert_tenant(p_tenant_id);
  PERFORM public.canonical_tournament_assert_permission('tournament.view');
  RETURN public.daily_play_snapshot(p_tenant_id, p_club_id, p_tournament_id);
END
$$;

CREATE OR REPLACE FUNCTION public.daily_play_check_in(
  p_tenant_id text, p_club_id text, p_tournament_id uuid, p_player_id text,
  p_expected_version integer, p_idempotency_key text
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_t public.canonical_tournaments%ROWTYPE; v_s jsonb; v_cmd jsonb; v_result jsonb;
  v_actual integer; v_ids jsonb; v_pid text := nullif(trim(coalesce(p_player_id, '')), '');
BEGIN
  PERFORM public.canonical_tournament_assert_tenant(p_tenant_id);
  PERFORM public.canonical_tournament_assert_permission('tournament.update');
  SELECT * INTO v_t FROM public.canonical_tournaments
  WHERE id=p_tournament_id AND tenant_id=p_tenant_id AND club_id=p_club_id AND mode='daily_play'
  FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'code','TOURNAMENT_NOT_FOUND'); END IF;
  IF v_pid IS NULL THEN RETURN jsonb_build_object('ok',false,'code','PLAYER_ID_REQUIRED'); END IF;
  v_cmd := public.daily_play_begin_command(p_tenant_id,p_tournament_id,'check_in',p_idempotency_key);
  IF NOT coalesce((v_cmd->>'ok')::boolean,false) THEN RETURN v_cmd; END IF;
  IF (v_cmd->>'replay')::boolean THEN RETURN v_cmd->'result'; END IF;
  v_s := coalesce(v_t.payload#>'{settings,dailyPlay}','{}'::jsonb);
  v_actual := coalesce(CASE WHEN (v_s->>'revision')~'^[0-9]+$' THEN (v_s->>'revision')::int END,0);
  IF p_expected_version IS DISTINCT FROM v_actual THEN
    RETURN public.daily_play_version_conflict(p_expected_version,v_actual);
  END IF;
  v_ids := CASE WHEN jsonb_typeof(v_s->'checkedInPlayerIds')='array'
    THEN v_s->'checkedInPlayerIds' ELSE '[]'::jsonb END;
  IF NOT v_ids @> jsonb_build_array(v_pid) THEN v_ids := v_ids || jsonb_build_array(v_pid); END IF;
  v_s := jsonb_set(v_s,'{checkedInPlayerIds}',v_ids,true);
  v_s := jsonb_set(v_s,'{revision}',to_jsonb(v_actual+1),true);
  PERFORM public.daily_play_write_state(p_tournament_id,v_actual,v_s);
  v_result := jsonb_build_object('ok',true,'revision',v_actual+1,'state',v_s);
  PERFORM public.daily_play_finish_command(p_tenant_id,p_tournament_id,'check_in',p_idempotency_key,v_result);
  RETURN v_result;
END
$$;

CREATE OR REPLACE FUNCTION public.daily_play_check_out(
  p_tenant_id text, p_club_id text, p_tournament_id uuid, p_player_id text,
  p_expected_version integer, p_idempotency_key text
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_t public.canonical_tournaments%ROWTYPE; v_s jsonb; v_cmd jsonb; v_result jsonb;
  v_actual integer; v_ids jsonb; v_matches jsonb; v_pid text := nullif(trim(coalesce(p_player_id,'')),'');
BEGIN
  PERFORM public.canonical_tournament_assert_tenant(p_tenant_id);
  PERFORM public.canonical_tournament_assert_permission('tournament.update');
  SELECT * INTO v_t FROM public.canonical_tournaments
  WHERE id=p_tournament_id AND tenant_id=p_tenant_id AND club_id=p_club_id AND mode='daily_play'
  FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'code','TOURNAMENT_NOT_FOUND'); END IF;
  IF v_pid IS NULL THEN RETURN jsonb_build_object('ok',false,'code','PLAYER_ID_REQUIRED'); END IF;
  v_cmd := public.daily_play_begin_command(p_tenant_id,p_tournament_id,'check_out',p_idempotency_key);
  IF NOT coalesce((v_cmd->>'ok')::boolean,false) THEN RETURN v_cmd; END IF;
  IF (v_cmd->>'replay')::boolean THEN RETURN v_cmd->'result'; END IF;
  v_s := coalesce(v_t.payload#>'{settings,dailyPlay}','{}'::jsonb);
  v_actual := coalesce(CASE WHEN (v_s->>'revision')~'^[0-9]+$' THEN (v_s->>'revision')::int END,0);
  IF p_expected_version IS DISTINCT FROM v_actual THEN
    RETURN public.daily_play_version_conflict(p_expected_version,v_actual);
  END IF;
  v_matches := CASE WHEN jsonb_typeof(v_s->'matches')='array' THEN v_s->'matches' ELSE '[]'::jsonb END;
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(v_matches) m
    WHERE coalesce(m->>'status','waiting') IN ('waiting','assigned','playing')
      AND public.daily_play_match_player_ids(m) @> jsonb_build_array(v_pid)
  ) THEN RETURN jsonb_build_object('ok',false,'code','CHECKOUT_PLAYER_ACTIVE'); END IF;
  SELECT coalesce(jsonb_agg(value ORDER BY ord),'[]'::jsonb) INTO v_ids
  FROM jsonb_array_elements(CASE WHEN jsonb_typeof(v_s->'checkedInPlayerIds')='array'
    THEN v_s->'checkedInPlayerIds' ELSE '[]'::jsonb END) WITH ORDINALITY x(value,ord)
  WHERE value #>> '{}' <> v_pid;
  v_s := jsonb_set(v_s,'{checkedInPlayerIds}',v_ids,true);
  v_s := jsonb_set(v_s,'{revision}',to_jsonb(v_actual+1),true);
  PERFORM public.daily_play_write_state(p_tournament_id,v_actual,v_s);
  v_result := jsonb_build_object('ok',true,'revision',v_actual+1,'state',v_s);
  PERFORM public.daily_play_finish_command(p_tenant_id,p_tournament_id,'check_out',p_idempotency_key,v_result);
  RETURN v_result;
END
$$;

CREATE OR REPLACE FUNCTION public.daily_play_create_matches(
  p_tenant_id text, p_club_id text, p_tournament_id uuid, p_matches jsonb,
  p_eligible_player_count integer, p_expected_version integer, p_idempotency_key text
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_t public.canonical_tournaments%ROWTYPE; v_s jsonb; v_cmd jsonb; v_result jsonb;
  v_actual integer; v_eligible_actual integer; v_existing jsonb; v_courts jsonb; v_new jsonb := '[]'::jsonb;
  v_m jsonb; v_nm jsonb; v_mid text; v_players jsonb; v_court jsonb; v_cid text;
BEGIN
  PERFORM public.canonical_tournament_assert_tenant(p_tenant_id);
  PERFORM public.canonical_tournament_assert_permission('tournament.update');
  SELECT * INTO v_t FROM public.canonical_tournaments
  WHERE id=p_tournament_id AND tenant_id=p_tenant_id AND club_id=p_club_id AND mode='daily_play'
  FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'code','TOURNAMENT_NOT_FOUND'); END IF;
  v_cmd := public.daily_play_begin_command(p_tenant_id,p_tournament_id,'create_matches',p_idempotency_key);
  IF NOT coalesce((v_cmd->>'ok')::boolean,false) THEN RETURN v_cmd; END IF;
  IF (v_cmd->>'replay')::boolean THEN RETURN v_cmd->'result'; END IF;
  IF jsonb_typeof(p_matches) IS DISTINCT FROM 'array' OR jsonb_array_length(p_matches)=0 THEN
    RETURN jsonb_build_object('ok',false,'code','MATCHES_REQUIRED');
  END IF;
  v_s := coalesce(v_t.payload#>'{settings,dailyPlay}','{}'::jsonb);
  v_actual := coalesce(CASE WHEN (v_s->>'revision')~'^[0-9]+$' THEN (v_s->>'revision')::int END,0);
  IF p_expected_version IS DISTINCT FROM v_actual THEN
    RETURN public.daily_play_version_conflict(p_expected_version,v_actual);
  END IF;
  v_existing := CASE WHEN jsonb_typeof(v_s->'matches')='array' THEN v_s->'matches' ELSE '[]'::jsonb END;
  SELECT count(*)::integer INTO v_eligible_actual
  FROM jsonb_array_elements(CASE
    WHEN jsonb_typeof(v_s->'checkedInPlayerIds')='array' THEN v_s->'checkedInPlayerIds'
    ELSE '[]'::jsonb END) p
  WHERE NOT EXISTS (
    SELECT 1 FROM jsonb_array_elements(v_existing) m
    WHERE coalesce(m->>'status','waiting') IN ('waiting','assigned','playing')
      AND public.daily_play_match_player_ids(m) @> jsonb_build_array(p)
  );
  IF v_eligible_actual < 4 THEN
    RETURN jsonb_build_object('ok',false,'code','NOT_ENOUGH_PLAYERS');
  END IF;
  -- p_eligible_player_count is advisory for clients; server recomputes eligibility.
  IF p_eligible_player_count IS NOT NULL AND p_eligible_player_count < 0 THEN
    RETURN jsonb_build_object('ok',false,'code','VALIDATION','error','eligiblePlayerCount invalid');
  END IF;
  v_courts := public.daily_play_read_courts(
    p_club_id, CASE WHEN v_s?'enabledCourtIds' THEN v_s->'enabledCourtIds' ELSE NULL END);
  IF jsonb_array_length(v_courts)=0 THEN
    RETURN jsonb_build_object('ok',false,'code','NO_COURT_CAPABILITY');
  END IF;

  -- Validate the whole batch before acquiring any lease. A later invalid match
  -- therefore cannot leave leases created for an earlier match in the batch.
  FOR v_m IN SELECT value FROM jsonb_array_elements(p_matches) LOOP
    v_mid := nullif(trim(coalesce(v_m->>'id',v_m->>'matchId','')),'');
    v_players := public.daily_play_match_player_ids(v_m);
    IF v_mid IS NULL OR jsonb_array_length(v_players)<2 THEN
      RETURN jsonb_build_object('ok',false,'code','INVALID_MATCH');
    END IF;
    IF EXISTS (SELECT 1 FROM jsonb_array_elements(v_existing||v_new) x
      WHERE coalesce(x->>'id',x->>'matchId')=v_mid) THEN
      RETURN jsonb_build_object('ok',false,'code','MATCH_ALREADY_EXISTS','matchId',v_mid);
    END IF;
    IF EXISTS (
      SELECT 1 FROM jsonb_array_elements(v_players) p
      WHERE NOT (CASE WHEN jsonb_typeof(v_s->'checkedInPlayerIds')='array'
        THEN v_s->'checkedInPlayerIds' ELSE '[]'::jsonb END) @> jsonb_build_array(p)
    ) THEN RETURN jsonb_build_object('ok',false,'code','PLAYER_NOT_CHECKED_IN','matchId',v_mid); END IF;
    IF EXISTS (
      SELECT 1 FROM jsonb_array_elements(v_existing||v_new) x
      WHERE coalesce(x->>'status','waiting') IN ('waiting','assigned','playing')
        AND EXISTS (SELECT 1 FROM jsonb_array_elements(v_players) p
          WHERE public.daily_play_match_player_ids(x) @> jsonb_build_array(p))
    ) THEN RETURN jsonb_build_object('ok',false,'code','PLAYER_ALREADY_ACTIVE','matchId',v_mid); END IF;
    v_new := v_new || jsonb_build_array(
      jsonb_build_object('id',v_mid,'playerIds',v_players,'status','waiting')
    );
  END LOOP;
  v_new := '[]'::jsonb;

  FOR v_m IN SELECT value FROM jsonb_array_elements(p_matches) LOOP
    v_mid := nullif(trim(coalesce(v_m->>'id',v_m->>'matchId','')),'');
    v_players := public.daily_play_match_player_ids(v_m);
    IF v_mid IS NULL OR jsonb_array_length(v_players)<2 THEN
      RETURN jsonb_build_object('ok',false,'code','INVALID_MATCH');
    END IF;
    IF EXISTS (SELECT 1 FROM jsonb_array_elements(v_existing||v_new) x
      WHERE coalesce(x->>'id',x->>'matchId')=v_mid) THEN
      RETURN jsonb_build_object('ok',false,'code','MATCH_ALREADY_EXISTS','matchId',v_mid);
    END IF;
    IF EXISTS (
      SELECT 1 FROM jsonb_array_elements(v_players) p
      WHERE NOT (CASE WHEN jsonb_typeof(v_s->'checkedInPlayerIds')='array'
        THEN v_s->'checkedInPlayerIds' ELSE '[]'::jsonb END) @> jsonb_build_array(p)
    ) THEN RETURN jsonb_build_object('ok',false,'code','PLAYER_NOT_CHECKED_IN','matchId',v_mid); END IF;
    IF EXISTS (
      SELECT 1 FROM jsonb_array_elements(v_existing||v_new) x
      WHERE coalesce(x->>'status','waiting') IN ('waiting','assigned','playing')
        AND EXISTS (SELECT 1 FROM jsonb_array_elements(v_players) p
          WHERE public.daily_play_match_player_ids(x) @> jsonb_build_array(p))
    ) THEN RETURN jsonb_build_object('ok',false,'code','PLAYER_ALREADY_ACTIVE','matchId',v_mid); END IF;

    v_nm := jsonb_set(v_m,'{id}',to_jsonb(v_mid),true);
    v_nm := jsonb_set(v_nm,'{playerIds}',v_players,true);
    v_nm := jsonb_set(v_nm,'{status}','"waiting"'::jsonb,true);
    v_nm := jsonb_set(v_nm,'{courtId}','null'::jsonb,true);
    v_cid := NULL;
    FOR v_court IN SELECT value FROM jsonb_array_elements(v_courts) LOOP
      v_cid := coalesce(v_court->>'id',v_court->>'courtId');
      BEGIN
        INSERT INTO public.daily_play_court_leases(
          tenant_id,club_id,tournament_id,match_id,court_id
        ) VALUES (p_tenant_id,p_club_id,p_tournament_id,v_mid,v_cid);
        v_nm := jsonb_set(v_nm,'{status}','"assigned"'::jsonb,true);
        v_nm := jsonb_set(v_nm,'{courtId}',to_jsonb(v_cid),true);
        EXIT;
      EXCEPTION WHEN unique_violation THEN v_cid := NULL;
      END;
    END LOOP;
    v_new := v_new || jsonb_build_array(v_nm);
  END LOOP;

  v_s := jsonb_set(v_s,'{matches}',v_existing||v_new,true);
  v_s := jsonb_set(v_s,'{revision}',to_jsonb(v_actual+1),true);
  PERFORM public.daily_play_write_state(p_tournament_id,v_actual,v_s);
  v_result := jsonb_build_object('ok',true,'revision',v_actual+1,'matches',v_new,'state',v_s);
  PERFORM public.daily_play_finish_command(p_tenant_id,p_tournament_id,'create_matches',p_idempotency_key,v_result);
  RETURN v_result;
END
$$;

CREATE OR REPLACE FUNCTION public.daily_play_assign_court(
  p_tenant_id text, p_club_id text, p_tournament_id uuid, p_match_id text,
  p_court_id text, p_expected_version integer, p_idempotency_key text
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_t public.canonical_tournaments%ROWTYPE; v_s jsonb; v_cmd jsonb; v_result jsonb;
  v_actual int; v_matches jsonb; v_m jsonb; v_mid text:=nullif(trim(coalesce(p_match_id,'')),'');
  v_cid text:=nullif(trim(coalesce(p_court_id,'')),''); v_courts jsonb;
BEGIN
  PERFORM public.canonical_tournament_assert_tenant(p_tenant_id);
  PERFORM public.canonical_tournament_assert_permission('tournament.update');
  SELECT * INTO v_t FROM public.canonical_tournaments WHERE id=p_tournament_id
    AND tenant_id=p_tenant_id AND club_id=p_club_id AND mode='daily_play' FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'code','TOURNAMENT_NOT_FOUND'); END IF;
  v_cmd:=public.daily_play_begin_command(p_tenant_id,p_tournament_id,'assign_court',p_idempotency_key);
  IF NOT coalesce((v_cmd->>'ok')::boolean,false) THEN RETURN v_cmd; END IF;
  IF (v_cmd->>'replay')::boolean THEN RETURN v_cmd->'result'; END IF;
  v_s:=coalesce(v_t.payload#>'{settings,dailyPlay}','{}'); v_actual:=coalesce(
    CASE WHEN (v_s->>'revision')~'^[0-9]+$' THEN (v_s->>'revision')::int END,0);
  IF p_expected_version IS DISTINCT FROM v_actual THEN RETURN public.daily_play_version_conflict(p_expected_version,v_actual); END IF;
  v_matches:=CASE WHEN jsonb_typeof(v_s->'matches')='array' THEN v_s->'matches' ELSE '[]' END;
  SELECT value INTO v_m FROM jsonb_array_elements(v_matches) WHERE coalesce(value->>'id',value->>'matchId')=v_mid;
  IF v_m IS NULL THEN RETURN jsonb_build_object('ok',false,'code','MATCH_NOT_FOUND'); END IF;
  IF coalesce(v_m->>'status','waiting') IN ('completed','cancelled') THEN RETURN jsonb_build_object('ok',false,'code','MATCH_IMMUTABLE'); END IF;
  IF v_cid IS NOT NULL THEN
    v_courts:=public.daily_play_read_courts(p_club_id,CASE WHEN v_s?'enabledCourtIds' THEN v_s->'enabledCourtIds' ELSE NULL END);
    IF NOT EXISTS (SELECT 1 FROM jsonb_array_elements(v_courts) c WHERE coalesce(c->>'id',c->>'courtId')=v_cid)
      THEN RETURN jsonb_build_object('ok',false,'code','COURT_NOT_AVAILABLE'); END IF;
    IF coalesce(v_m->>'courtId','')<>v_cid THEN
      BEGIN
        INSERT INTO public.daily_play_court_leases(tenant_id,club_id,tournament_id,match_id,court_id)
        VALUES(p_tenant_id,p_club_id,p_tournament_id,v_mid,v_cid);
      EXCEPTION WHEN unique_violation THEN RETURN jsonb_build_object('ok',false,'code','COURT_BUSY','courtId',v_cid);
      END;
      UPDATE public.daily_play_court_leases SET status='released',released_at=now()
      WHERE tenant_id=p_tenant_id AND club_id=p_club_id AND tournament_id=p_tournament_id
        AND match_id=v_mid AND status='active' AND court_id<>v_cid;
    END IF;
    v_m:=jsonb_set(v_m,'{courtId}',to_jsonb(v_cid),true);
    v_m:=jsonb_set(v_m,'{status}','"assigned"',true);
  ELSE
    UPDATE public.daily_play_court_leases SET status='released',released_at=now()
    WHERE tenant_id=p_tenant_id AND club_id=p_club_id AND tournament_id=p_tournament_id
      AND match_id=v_mid AND status='active';
    v_m:=jsonb_set(v_m,'{courtId}','null',true); v_m:=jsonb_set(v_m,'{status}','"waiting"',true);
  END IF;
  v_s:=jsonb_set(v_s,'{matches}',public.daily_play_replace_match(v_matches,v_mid,v_m),true);
  v_s:=jsonb_set(v_s,'{revision}',to_jsonb(v_actual+1),true);
  PERFORM public.daily_play_write_state(p_tournament_id,v_actual,v_s);
  v_result:=jsonb_build_object('ok',true,'revision',v_actual+1,'match',v_m);
  PERFORM public.daily_play_finish_command(p_tenant_id,p_tournament_id,'assign_court',p_idempotency_key,v_result);
  RETURN v_result;
END
$$;

CREATE OR REPLACE FUNCTION public.daily_play_submit_score(
  p_tenant_id text, p_club_id text, p_tournament_id uuid, p_match_id text,
  p_score_a integer, p_score_b integer, p_expected_version integer, p_idempotency_key text
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_t public.canonical_tournaments%ROWTYPE; v_s jsonb; v_cmd jsonb; v_result jsonb;
  v_actual int; v_matches jsonb; v_m jsonb; v_mid text:=nullif(trim(coalesce(p_match_id,'')),'');
BEGIN
  PERFORM public.canonical_tournament_assert_tenant(p_tenant_id);
  PERFORM public.canonical_tournament_assert_permission('tournament.update');
  SELECT * INTO v_t FROM public.canonical_tournaments WHERE id=p_tournament_id
    AND tenant_id=p_tenant_id AND club_id=p_club_id AND mode='daily_play' FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'code','TOURNAMENT_NOT_FOUND'); END IF;
  v_cmd:=public.daily_play_begin_command(p_tenant_id,p_tournament_id,'submit_score',p_idempotency_key);
  IF NOT coalesce((v_cmd->>'ok')::boolean,false) THEN RETURN v_cmd; END IF;
  IF (v_cmd->>'replay')::boolean THEN RETURN v_cmd->'result'; END IF;
  IF p_score_a IS NULL OR p_score_b IS NULL OR p_score_a<0 OR p_score_b<0 OR p_score_a=p_score_b
    THEN RETURN jsonb_build_object('ok',false,'code','INVALID_SCORE'); END IF;
  v_s:=coalesce(v_t.payload#>'{settings,dailyPlay}','{}'); v_actual:=coalesce(
    CASE WHEN (v_s->>'revision')~'^[0-9]+$' THEN (v_s->>'revision')::int END,0);
  v_matches:=CASE WHEN jsonb_typeof(v_s->'matches')='array' THEN v_s->'matches' ELSE '[]' END;
  SELECT value INTO v_m FROM jsonb_array_elements(v_matches) WHERE coalesce(value->>'id',value->>'matchId')=v_mid;
  IF v_m IS NULL THEN RETURN jsonb_build_object('ok',false,'code','MATCH_NOT_FOUND'); END IF;
  IF v_m->>'status'='completed' THEN
    IF v_m->>'scoreA'=p_score_a::text AND v_m->>'scoreB'=p_score_b::text THEN
      v_result:=jsonb_build_object('ok',true,'revision',v_actual,'match',v_m,'replay',true);
      PERFORM public.daily_play_finish_command(p_tenant_id,p_tournament_id,'submit_score',p_idempotency_key,v_result);
      RETURN v_result;
    END IF;
    RETURN jsonb_build_object('ok',false,'code','SCORE_CONFLICT');
  END IF;
  IF v_m->>'status'='cancelled' THEN RETURN jsonb_build_object('ok',false,'code','MATCH_IMMUTABLE'); END IF;
  IF p_expected_version IS DISTINCT FROM v_actual THEN RETURN public.daily_play_version_conflict(p_expected_version,v_actual); END IF;
  v_m:=jsonb_set(v_m,'{scoreA}',to_jsonb(p_score_a),true);
  v_m:=jsonb_set(v_m,'{scoreB}',to_jsonb(p_score_b),true);
  v_m:=jsonb_set(v_m,'{winner}',to_jsonb(CASE WHEN p_score_a>p_score_b THEN 'A' ELSE 'B' END),true);
  v_m:=jsonb_set(v_m,'{status}','"completed"',true);
  v_m:=jsonb_set(v_m,'{completedAt}',to_jsonb(now()),true);
  UPDATE public.daily_play_court_leases SET status='released',released_at=now()
  WHERE tenant_id=p_tenant_id AND club_id=p_club_id AND tournament_id=p_tournament_id
    AND match_id=v_mid AND status='active';
  v_s:=jsonb_set(v_s,'{matches}',public.daily_play_replace_match(v_matches,v_mid,v_m),true);
  v_s:=jsonb_set(v_s,'{revision}',to_jsonb(v_actual+1),true);
  PERFORM public.daily_play_write_state(p_tournament_id,v_actual,v_s);
  v_result:=jsonb_build_object('ok',true,'revision',v_actual+1,'match',v_m);
  PERFORM public.daily_play_finish_command(p_tenant_id,p_tournament_id,'submit_score',p_idempotency_key,v_result);
  RETURN v_result;
END
$$;

CREATE OR REPLACE FUNCTION public.daily_play_cancel_match(
  p_tenant_id text, p_club_id text, p_tournament_id uuid, p_match_id text,
  p_expected_version integer, p_idempotency_key text
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_t public.canonical_tournaments%ROWTYPE; v_s jsonb; v_cmd jsonb; v_result jsonb;
  v_actual int; v_matches jsonb; v_m jsonb; v_mid text:=nullif(trim(coalesce(p_match_id,'')),'');
BEGIN
  PERFORM public.canonical_tournament_assert_tenant(p_tenant_id);
  PERFORM public.canonical_tournament_assert_permission('tournament.update');
  SELECT * INTO v_t FROM public.canonical_tournaments WHERE id=p_tournament_id
    AND tenant_id=p_tenant_id AND club_id=p_club_id AND mode='daily_play' FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'code','TOURNAMENT_NOT_FOUND'); END IF;
  v_cmd:=public.daily_play_begin_command(p_tenant_id,p_tournament_id,'cancel_match',p_idempotency_key);
  IF NOT coalesce((v_cmd->>'ok')::boolean,false) THEN RETURN v_cmd; END IF;
  IF (v_cmd->>'replay')::boolean THEN RETURN v_cmd->'result'; END IF;
  v_s:=coalesce(v_t.payload#>'{settings,dailyPlay}','{}'); v_actual:=coalesce(
    CASE WHEN (v_s->>'revision')~'^[0-9]+$' THEN (v_s->>'revision')::int END,0);
  v_matches:=CASE WHEN jsonb_typeof(v_s->'matches')='array' THEN v_s->'matches' ELSE '[]' END;
  SELECT value INTO v_m FROM jsonb_array_elements(v_matches) WHERE coalesce(value->>'id',value->>'matchId')=v_mid;
  IF v_m IS NULL THEN RETURN jsonb_build_object('ok',false,'code','MATCH_NOT_FOUND'); END IF;
  IF v_m->>'status'='completed' THEN RETURN jsonb_build_object('ok',false,'code','MATCH_COMPLETED_IMMUTABLE'); END IF;
  IF p_expected_version IS DISTINCT FROM v_actual THEN RETURN public.daily_play_version_conflict(p_expected_version,v_actual); END IF;
  v_m:=jsonb_set(v_m,'{status}','"cancelled"',true); v_m:=jsonb_set(v_m,'{cancelledAt}',to_jsonb(now()),true);
  UPDATE public.daily_play_court_leases SET status='released',released_at=now()
  WHERE tenant_id=p_tenant_id AND club_id=p_club_id AND tournament_id=p_tournament_id
    AND match_id=v_mid AND status='active';
  v_s:=jsonb_set(v_s,'{matches}',public.daily_play_replace_match(v_matches,v_mid,v_m),true);
  v_s:=jsonb_set(v_s,'{revision}',to_jsonb(v_actual+1),true);
  PERFORM public.daily_play_write_state(p_tournament_id,v_actual,v_s);
  v_result:=jsonb_build_object('ok',true,'revision',v_actual+1,'match',v_m);
  PERFORM public.daily_play_finish_command(p_tenant_id,p_tournament_id,'cancel_match',p_idempotency_key,v_result);
  RETURN v_result;
END
$$;

CREATE OR REPLACE FUNCTION public.daily_play_change_court(
  p_tenant_id text, p_club_id text, p_tournament_id uuid, p_match_id text,
  p_court_id text, p_expected_version integer, p_idempotency_key text
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_t public.canonical_tournaments%ROWTYPE; v_s jsonb; v_cmd jsonb; v_result jsonb;
  v_actual int; v_matches jsonb; v_m jsonb; v_courts jsonb;
  v_mid text:=nullif(trim(coalesce(p_match_id,'')),''); v_cid text:=nullif(trim(coalesce(p_court_id,'')),'');
BEGIN
  PERFORM public.canonical_tournament_assert_tenant(p_tenant_id);
  PERFORM public.canonical_tournament_assert_permission('tournament.update');
  SELECT * INTO v_t FROM public.canonical_tournaments WHERE id=p_tournament_id
    AND tenant_id=p_tenant_id AND club_id=p_club_id AND mode='daily_play' FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'code','TOURNAMENT_NOT_FOUND'); END IF;
  IF v_cid IS NULL THEN RETURN jsonb_build_object('ok',false,'code','COURT_ID_REQUIRED'); END IF;
  v_cmd:=public.daily_play_begin_command(p_tenant_id,p_tournament_id,'change_court',p_idempotency_key);
  IF NOT coalesce((v_cmd->>'ok')::boolean,false) THEN RETURN v_cmd; END IF;
  IF (v_cmd->>'replay')::boolean THEN RETURN v_cmd->'result'; END IF;
  v_s:=coalesce(v_t.payload#>'{settings,dailyPlay}','{}'); v_actual:=coalesce(
    CASE WHEN (v_s->>'revision')~'^[0-9]+$' THEN (v_s->>'revision')::int END,0);
  IF p_expected_version IS DISTINCT FROM v_actual THEN RETURN public.daily_play_version_conflict(p_expected_version,v_actual); END IF;
  v_matches:=CASE WHEN jsonb_typeof(v_s->'matches')='array' THEN v_s->'matches' ELSE '[]' END;
  SELECT value INTO v_m FROM jsonb_array_elements(v_matches) WHERE coalesce(value->>'id',value->>'matchId')=v_mid;
  IF v_m IS NULL THEN RETURN jsonb_build_object('ok',false,'code','MATCH_NOT_FOUND'); END IF;
  IF coalesce(v_m->>'status','waiting') IN ('completed','cancelled') THEN RETURN jsonb_build_object('ok',false,'code','MATCH_IMMUTABLE'); END IF;
  v_courts:=public.daily_play_read_courts(p_club_id,CASE WHEN v_s?'enabledCourtIds' THEN v_s->'enabledCourtIds' ELSE NULL END);
  IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(v_courts)c WHERE coalesce(c->>'id',c->>'courtId')=v_cid)
    THEN RETURN jsonb_build_object('ok',false,'code','COURT_NOT_AVAILABLE'); END IF;
  IF coalesce(v_m->>'courtId','')<>v_cid THEN
    BEGIN
      INSERT INTO public.daily_play_court_leases(tenant_id,club_id,tournament_id,match_id,court_id)
      VALUES(p_tenant_id,p_club_id,p_tournament_id,v_mid,v_cid);
    EXCEPTION WHEN unique_violation THEN
      RETURN jsonb_build_object('ok',false,'code','COURT_BUSY','courtId',v_cid);
    END;
    UPDATE public.daily_play_court_leases SET status='released',released_at=now()
    WHERE tenant_id=p_tenant_id AND club_id=p_club_id AND tournament_id=p_tournament_id
      AND match_id=v_mid AND status='active' AND court_id<>v_cid;
  END IF;
  v_m:=jsonb_set(v_m,'{courtId}',to_jsonb(v_cid),true);
  v_m:=jsonb_set(v_m,'{status}','"assigned"',true);
  v_s:=jsonb_set(v_s,'{matches}',public.daily_play_replace_match(v_matches,v_mid,v_m),true);
  v_s:=jsonb_set(v_s,'{revision}',to_jsonb(v_actual+1),true);
  PERFORM public.daily_play_write_state(p_tournament_id,v_actual,v_s);
  v_result:=jsonb_build_object('ok',true,'revision',v_actual+1,'match',v_m);
  PERFORM public.daily_play_finish_command(p_tenant_id,p_tournament_id,'change_court',p_idempotency_key,v_result);
  RETURN v_result;
END
$$;

-- Helpers are internal. Public RPCs are authenticated-only.
REVOKE ALL ON FUNCTION public.daily_play_version_conflict(integer,integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.daily_play_begin_command(text,uuid,text,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.daily_play_finish_command(text,uuid,text,text,jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.daily_play_match_player_ids(jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.daily_play_read_courts(text,jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.daily_play_replace_match(jsonb,text,jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.daily_play_write_state(uuid,integer,jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.daily_play_snapshot(text,text,uuid) FROM PUBLIC, anon, authenticated;

REVOKE ALL ON FUNCTION public.daily_play_get_state(text,text,uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.daily_play_check_in(text,text,uuid,text,integer,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.daily_play_check_out(text,text,uuid,text,integer,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.daily_play_create_matches(text,text,uuid,jsonb,integer,integer,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.daily_play_assign_court(text,text,uuid,text,text,integer,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.daily_play_submit_score(text,text,uuid,text,integer,integer,integer,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.daily_play_cancel_match(text,text,uuid,text,integer,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.daily_play_change_court(text,text,uuid,text,text,integer,text) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.daily_play_get_state(text,text,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.daily_play_check_in(text,text,uuid,text,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.daily_play_check_out(text,text,uuid,text,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.daily_play_create_matches(text,text,uuid,jsonb,integer,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.daily_play_assign_court(text,text,uuid,text,text,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.daily_play_submit_score(text,text,uuid,text,integer,integer,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.daily_play_cancel_match(text,text,uuid,text,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.daily_play_change_court(text,text,uuid,text,text,integer,text) TO authenticated;

COMMIT;
