/**
 * CM-06 Competition Publication — stable typed error codes.
 * Module-local; not registered in API_ERROR_CODES in this phase.
 */

export const COMPETITION_PUBLICATION_ERROR_CODE = Object.freeze({
  INVALID_CONTRACT: "CM06_INVALID_CONTRACT",
  MISSING_TENANT: "CM06_MISSING_TENANT",
  MISSING_COMPETITION: "CM06_MISSING_COMPETITION",
  INVALID_IDENTIFIER: "CM06_INVALID_IDENTIFIER",
  TENANT_MISMATCH: "CM06_TENANT_MISMATCH",
  COMPETITION_MISMATCH: "CM06_COMPETITION_MISMATCH",

  // Profile
  MISSING_PROFILE_ID: "CM06_MISSING_PROFILE_ID",
  UNKNOWN_PROFILE: "CM06_UNKNOWN_PROFILE",

  // Channel
  INVALID_CHANNEL: "CM06_INVALID_CHANNEL",
  CHANNEL_VISIBILITY_REJECTED: "CM06_CHANNEL_VISIBILITY_REJECTED",

  // CM-01 definition / CM-03 version source
  INVALID_DEFINITION: "CM06_INVALID_DEFINITION",
  STALE_DEFINITION_REVISION: "CM06_STALE_DEFINITION_REVISION",
  INVALID_COMPETITION_VERSION: "CM06_INVALID_COMPETITION_VERSION",
  VERSION_SOURCE_MISMATCH: "CM06_VERSION_SOURCE_MISMATCH",
  DEFINITION_VERSION_MISMATCH: "CM06_DEFINITION_VERSION_MISMATCH",
  UNVERSIONED_SOURCE_REJECTED: "CM06_UNVERSIONED_SOURCE_REJECTED",

  // CM-04 configuration (optional but explicit presence)
  MISSING_CONFIGURATION_PRESENCE: "CM06_MISSING_CONFIGURATION_PRESENCE",
  CONFIGURATION_PRESENCE_MISMATCH: "CM06_CONFIGURATION_PRESENCE_MISMATCH",
  INVALID_CONFIGURATION: "CM06_INVALID_CONFIGURATION",
  STALE_CONFIGURATION_REVISION: "CM06_STALE_CONFIGURATION_REVISION",

  // CM-05 branding (required for STANDARD profile)
  MISSING_BRANDING: "CM06_MISSING_BRANDING",
  INVALID_BRANDING: "CM06_INVALID_BRANDING",
  STALE_BRANDING_REVISION: "CM06_STALE_BRANDING_REVISION",
  BRANDING_NOT_READY: "CM06_BRANDING_NOT_READY",

  // Readiness / fail-closed gate
  READINESS_FAILED: "CM06_READINESS_FAILED",
  EXTERNAL_LIFECYCLE_BLOCKED: "CM06_EXTERNAL_LIFECYCLE_BLOCKED",

  // Publication identity / lineage / concurrency
  MISSING_IDEMPOTENCY_KEY: "CM06_MISSING_IDEMPOTENCY_KEY",
  IDEMPOTENCY_CONFLICT: "CM06_IDEMPOTENCY_CONFLICT",
  MISSING_EXPECTED_CURRENT_REVISION: "CM06_MISSING_EXPECTED_CURRENT_REVISION",
  STALE_CURRENT_PUBLICATION_REVISION: "CM06_STALE_CURRENT_PUBLICATION_REVISION",
  CURRENT_PUBLICATION_MISMATCH: "CM06_CURRENT_PUBLICATION_MISMATCH",
  MISSING_CURRENT_PUBLICATION_REFERENCE: "CM06_MISSING_CURRENT_PUBLICATION_REFERENCE",
  PUBLICATION_NOT_FOUND: "CM06_PUBLICATION_NOT_FOUND",
  DUPLICATE_PUBLICATION: "CM06_DUPLICATE_PUBLICATION",
  SAME_SOURCE_REPUBLISH: "CM06_SAME_SOURCE_REPUBLISH",

  // Public reference / slug
  INVALID_SLUG: "CM06_INVALID_SLUG",
  DUPLICATE_PUBLIC_REFERENCE: "CM06_DUPLICATE_PUBLIC_REFERENCE",

  // Structural / repository
  MALFORMED_PUBLICATION: "CM06_MALFORMED_PUBLICATION",
  MALFORMED_MANIFEST: "CM06_MALFORMED_MANIFEST",
  MALFORMED_PLAN: "CM06_MALFORMED_PLAN",
  MALFORMED_LEGACY_PUBLICATION: "CM06_MALFORMED_LEGACY_PUBLICATION",
  AMBIGUOUS_LEGACY_MAPPING: "CM06_AMBIGUOUS_LEGACY_MAPPING",
  REPOSITORY_CONFLICT: "CM06_REPOSITORY_CONFLICT",
  NO_OP: "CM06_NO_OP",
  PORT_OPERATION_UNIMPLEMENTED: "CM06_PORT_OPERATION_UNIMPLEMENTED",
});
