export const SCHEDULING_ENGINE_VERSION = "cc09-v1";

/** @typedef {import('./schedulingTypes.js').SchedulingStrategyValue} SchedulingStrategyValue */
/** @typedef {import('./schedulingTypes.js').SchedulingConflictTypeValue} SchedulingConflictTypeValue */
/** @typedef {import('./schedulingTypes.js').ConflictSeverityValue} ConflictSeverityValue */

export const SCHEDULING_STRATEGY = Object.freeze({
  ROUND_ROBIN: "ROUND_ROBIN",
  GROUP_STAGE: "GROUP_STAGE",
  KNOCKOUT: "KNOCKOUT",
  DOUBLE_ELIMINATION: "DOUBLE_ELIMINATION",
  SWISS: "SWISS",
  TEAM_TOURNAMENT: "TEAM_TOURNAMENT",
  COURT_FIRST: "COURT_FIRST",
  TIME_FIRST: "TIME_FIRST",
  BALANCED: "BALANCED",
  MANUAL: "MANUAL",
  HYBRID: "HYBRID",
  CUSTOM: "CUSTOM",
});

export const SCHEDULING_SCOPE = Object.freeze({
  GROUP_STAGE: "group_stage",
  TEAM_TOURNAMENT: "team_tournament",
  TOURNAMENT_ENGINE: "tournament_engine",
  SESSION: "session",
});

export const CONFLICT_TYPE = Object.freeze({
  PLAYER_TIME_CONFLICT: "PLAYER_TIME_CONFLICT",
  TEAM_TIME_CONFLICT: "TEAM_TIME_CONFLICT",
  COURT_TIME_CONFLICT: "COURT_TIME_CONFLICT",
  VENUE_TIME_CONFLICT: "VENUE_TIME_CONFLICT",
  REFEREE_TIME_CONFLICT: "REFEREE_TIME_CONFLICT",
  INSUFFICIENT_REST: "INSUFFICIENT_REST",
  COURT_UNAVAILABLE: "COURT_UNAVAILABLE",
  VENUE_UNAVAILABLE: "VENUE_UNAVAILABLE",
  INVALID_ROUND_ORDER: "INVALID_ROUND_ORDER",
  DUPLICATE_MATCH_ASSIGNMENT: "DUPLICATE_MATCH_ASSIGNMENT",
  UNASSIGNED_MATCH: "UNASSIGNED_MATCH",
  INVALID_BYE_ASSIGNMENT: "INVALID_BYE_ASSIGNMENT",
  MANUAL_OVERRIDE_CONFLICT: "MANUAL_OVERRIDE_CONFLICT",
  DEPENDENCY_NOT_COMPLETED: "DEPENDENCY_NOT_COMPLETED",
  UNKNOWN_PARTICIPANT: "UNKNOWN_PARTICIPANT",
  UNKNOWN_COURT: "UNKNOWN_COURT",
  UNKNOWN_SLOT: "UNKNOWN_SLOT",
});

export const CONFLICT_SEVERITY = Object.freeze({
  HARD: "HARD",
  SOFT: "SOFT",
  INFO: "INFO",
});

export const ASSIGNMENT_STATUS = Object.freeze({
  SCHEDULED: "SCHEDULED",
  BYE: "BYE",
  PENDING_DEPENDENCY: "PENDING_DEPENDENCY",
  UNASSIGNED: "UNASSIGNED",
  WITHDRAWN: "WITHDRAWN",
  FORFEIT_ADVANCE: "FORFEIT_ADVANCE",
  CANCELLED: "CANCELLED",
  MANUAL_LOCK: "MANUAL_LOCK",
});

export const BYE_PARTICIPANT_ID = "__BYE__";
export const PENDING_WINNER_PREFIX = "__PENDING_WINNER__";
export const PENDING_LOSER_PREFIX = "__PENDING_LOSER__";

export const HARD_CONFLICT_TYPES = Object.freeze([
  CONFLICT_TYPE.DUPLICATE_MATCH_ASSIGNMENT,
  CONFLICT_TYPE.UNKNOWN_PARTICIPANT,
  CONFLICT_TYPE.INVALID_BYE_ASSIGNMENT,
]);
