/**
 * CM-08 archive / unarchive reason codes.
 * Stable codes only — unknown codes are rejected (no silent normalize).
 */

export const COMPETITION_ARCHIVE_REASON_CODE = Object.freeze({
  COMPETITION_COMPLETED: "COMPETITION_COMPLETED",
  COMPETITION_CANCELLED: "COMPETITION_CANCELLED",
  ORGANIZER_REQUEST: "ORGANIZER_REQUEST",
  DUPLICATE_RECORD: "DUPLICATE_RECORD",
  COMPLIANCE_RETENTION: "COMPLIANCE_RETENTION",
  TENANT_ADMIN_DECISION: "TENANT_ADMIN_DECISION",
  OTHER: "OTHER",
});

export const COMPETITION_ARCHIVE_REASON_CODE_VALUES = Object.freeze(
  Object.values(COMPETITION_ARCHIVE_REASON_CODE)
);

export const COMPETITION_ARCHIVE_REASON_CATEGORY = Object.freeze({
  COMPLETION: "COMPLETION",
  CANCELLATION: "CANCELLATION",
  ORGANIZER: "ORGANIZER",
  DUPLICATE: "DUPLICATE",
  COMPLIANCE: "COMPLIANCE",
  ADMIN: "ADMIN",
  OTHER: "OTHER",
});

export const COMPETITION_ARCHIVE_REASON_CATEGORY_BY_CODE = Object.freeze({
  [COMPETITION_ARCHIVE_REASON_CODE.COMPETITION_COMPLETED]:
    COMPETITION_ARCHIVE_REASON_CATEGORY.COMPLETION,
  [COMPETITION_ARCHIVE_REASON_CODE.COMPETITION_CANCELLED]:
    COMPETITION_ARCHIVE_REASON_CATEGORY.CANCELLATION,
  [COMPETITION_ARCHIVE_REASON_CODE.ORGANIZER_REQUEST]:
    COMPETITION_ARCHIVE_REASON_CATEGORY.ORGANIZER,
  [COMPETITION_ARCHIVE_REASON_CODE.DUPLICATE_RECORD]:
    COMPETITION_ARCHIVE_REASON_CATEGORY.DUPLICATE,
  [COMPETITION_ARCHIVE_REASON_CODE.COMPLIANCE_RETENTION]:
    COMPETITION_ARCHIVE_REASON_CATEGORY.COMPLIANCE,
  [COMPETITION_ARCHIVE_REASON_CODE.TENANT_ADMIN_DECISION]:
    COMPETITION_ARCHIVE_REASON_CATEGORY.ADMIN,
  [COMPETITION_ARCHIVE_REASON_CODE.OTHER]:
    COMPETITION_ARCHIVE_REASON_CATEGORY.OTHER,
});

export const COMPETITION_UNARCHIVE_REASON_CODE = Object.freeze({
  ADMINISTRATIVE_CORRECTION: "ADMINISTRATIVE_CORRECTION",
  COMPETITION_REACTIVATION_APPROVED: "COMPETITION_REACTIVATION_APPROVED",
  ARCHIVED_IN_ERROR: "ARCHIVED_IN_ERROR",
  LEGAL_OR_COMPLIANCE_REQUEST: "LEGAL_OR_COMPLIANCE_REQUEST",
  OTHER: "OTHER",
});

export const COMPETITION_UNARCHIVE_REASON_CODE_VALUES = Object.freeze(
  Object.values(COMPETITION_UNARCHIVE_REASON_CODE)
);

export const COMPETITION_UNARCHIVE_REASON_CATEGORY = Object.freeze({
  ADMIN: "ADMIN",
  REACTIVATION: "REACTIVATION",
  CORRECTION: "CORRECTION",
  COMPLIANCE: "COMPLIANCE",
  OTHER: "OTHER",
});

export const COMPETITION_UNARCHIVE_REASON_CATEGORY_BY_CODE = Object.freeze({
  [COMPETITION_UNARCHIVE_REASON_CODE.ADMINISTRATIVE_CORRECTION]:
    COMPETITION_UNARCHIVE_REASON_CATEGORY.ADMIN,
  [COMPETITION_UNARCHIVE_REASON_CODE.COMPETITION_REACTIVATION_APPROVED]:
    COMPETITION_UNARCHIVE_REASON_CATEGORY.REACTIVATION,
  [COMPETITION_UNARCHIVE_REASON_CODE.ARCHIVED_IN_ERROR]:
    COMPETITION_UNARCHIVE_REASON_CATEGORY.CORRECTION,
  [COMPETITION_UNARCHIVE_REASON_CODE.LEGAL_OR_COMPLIANCE_REQUEST]:
    COMPETITION_UNARCHIVE_REASON_CATEGORY.COMPLIANCE,
  [COMPETITION_UNARCHIVE_REASON_CODE.OTHER]:
    COMPETITION_UNARCHIVE_REASON_CATEGORY.OTHER,
});

export const COMPETITION_ARCHIVE_REASON_SUMMARY_MAX_LENGTH = 240;
export const COMPETITION_ARCHIVE_REASON_DETAIL_MAX_LENGTH = 2000;
export const COMPETITION_ARCHIVE_REASON_OTHER_MIN_DETAIL_LENGTH = 12;

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isCompetitionArchiveReasonCode(value) {
  return (
    typeof value === "string" &&
    COMPETITION_ARCHIVE_REASON_CODE_VALUES.includes(value)
  );
}

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isCompetitionUnarchiveReasonCode(value) {
  return (
    typeof value === "string" &&
    COMPETITION_UNARCHIVE_REASON_CODE_VALUES.includes(value)
  );
}
