/**
 * Canonical shared Court Resource contract.
 * Physical court id is authority; labels and cluster ids are not reservable ids.
 */
export const COURT_RESOURCE_CONTRACT_VERSION = "1.0.0";

export const RESERVATION_OWNER_TYPE = Object.freeze({
  TOURNAMENT: "tournament",
  CUSTOMER: "customer",
  MAINTENANCE: "maintenance",
  DAILY_PLAY: "daily_play",
  UNKNOWN: "unknown",
});

export const OWNERSHIP_STATUS = Object.freeze({
  OWN_RESERVATION: "OWN_RESERVATION",
  UNRESERVED: "UNRESERVED",
  FOREIGN: "FOREIGN",
});

export const COURT_RESOURCE_CODE = Object.freeze({
  OK: "OK",
  MISSING_CLUB_ID: "MISSING_CLUB_ID",
  MISSING_COURT_ID: "MISSING_COURT_ID",
  MISSING_OWNER: "MISSING_OWNER",
  MISSING_WINDOW: "MISSING_WINDOW",
  INVALID_TIME_RANGE: "INVALID_TIME_RANGE",
  COURT_NOT_FOUND: "COURT_NOT_FOUND",
  CLUSTER_MISMATCH: "CLUSTER_MISMATCH",
  TENANT_MISMATCH: "TENANT_MISMATCH",
  CLUB_MISMATCH: "CLUB_MISMATCH",
  VENUE_MISMATCH: "VENUE_MISMATCH",
  COURT_INACTIVE: "COURT_INACTIVE",
  COURT_MAINTENANCE: "COURT_MAINTENANCE",
  COURT_LOCKED: "COURT_LOCKED",
  COURT_NOT_IN_OWNER_SCOPE: "COURT_NOT_IN_OWNER_SCOPE",
  FOREIGN_RESERVATION_CONFLICT: "FOREIGN_RESERVATION_CONFLICT",
  CUSTOMER_BOOKING_CONFLICT: "CUSTOMER_BOOKING_CONFLICT",
  MAINTENANCE_CONFLICT: "MAINTENANCE_CONFLICT",
  TOURNAMENT_BOOKING_CONFLICT: "TOURNAMENT_BOOKING_CONFLICT",
  BOOKING_CONFLICT: "BOOKING_CONFLICT",
  SYNTHETIC_COURT_DENIED: "SYNTHETIC_COURT_DENIED",
  WHOLE_CLUSTER_DENIED: "WHOLE_CLUSTER_DENIED",
  DATA_UNAVAILABLE: "DATA_UNAVAILABLE",
  AMBIGUOUS_CLUB_BLOB: "AMBIGUOUS_CLUB_BLOB",
  SUPABASE_NOT_CONFIGURED: "SUPABASE_NOT_CONFIGURED",
  CLUB_BLOB_MISSING: "CLUB_BLOB_MISSING",
  TENANT_FORBIDDEN: "TENANT_FORBIDDEN",
  PARTIAL_FAILURE: "PARTIAL_FAILURE",
  ASSIGNMENT_VALID: "ASSIGNMENT_VALID",
});

export const CANONICAL_INVENTORY_SOURCE = "club_data_v3";
export const CLUB_DATA_V3_TABLE = "club_data_v3";
