/**
 * Official/Open Tournament — ĐẦU B (canonical adapter adoption).
 *
 * Translates / composes / orchestrates. Does not own Competition engines.
 */

export const OFFICIAL_OPEN_ADAPTER_B_ID = "official-open-adapter-b";

export const OFFICIAL_OPEN_ADAPTER_B_VERSION = "1.0.0";

export const SHARED_CONTRACT_CAPABILITY_GAP = "SHARED_CONTRACT_CAPABILITY_GAP";

export const SHARED_REFEREE_CONTRACT_CAPABILITY_GAP =
  "SHARED_REFEREE_CONTRACT_CAPABILITY_GAP";

export const COURT_SHARED_RUNTIME_GAP = "COURT_SHARED_RUNTIME_GAP";

export const EXTERNAL_DEPENDENCY = "EXTERNAL_DEPENDENCY";

export const TEMPORARY_COMPATIBILITY_NONCANONICAL =
  "TEMPORARY_COMPATIBILITY_NONCANONICAL";

export const ADAPTER_B_STATUS = Object.freeze({
  CANONICAL_BOUND: "CANONICAL_BOUND",
  ADAPTER_BOUND_COMPATIBILITY_SINK: "ADAPTER_BOUND_COMPATIBILITY_SINK",
  NOT_CONFIGURED: "NOT_CONFIGURED",
  SHARED_CONTRACT_CAPABILITY_GAP: SHARED_CONTRACT_CAPABILITY_GAP,
  CONDITIONAL_INACTIVE: "CONDITIONAL_INACTIVE",
  NOT_REQUIRED: "NOT_REQUIRED",
});

export const BYPASS_CLASSIFICATION = Object.freeze({
  CANONICAL_VIA_ADAPTER_B: "CANONICAL_VIA_ADAPTER_B",
  TEMPORARY_COMPATIBILITY_BEHIND_CANONICAL_BOUNDARY:
    "TEMPORARY_COMPATIBILITY_BEHIND_CANONICAL_BOUNDARY",
  TEMPORARY_COMPATIBILITY_NONCANONICAL,
  NOT_CONFIGURED: "NOT_CONFIGURED",
  NOT_REQUIRED: "NOT_REQUIRED",
  VALID_INTERNAL_DEPENDENCY: "VALID_INTERNAL_DEPENDENCY",
  FORBIDDEN_BYPASS: "FORBIDDEN_BYPASS",
});

export const FORBIDDEN_TENANT_IDS = Object.freeze(["default-tenant", "default"]);

export const OFFICIAL_OPEN_MANAGE_PERMISSION = "tournament.update";
