/**
 * Official/Open Tournament — ĐẦU B (canonical adapter adoption).
 *
 * Translates / composes / orchestrates. Does not own Competition engines.
 */

export const OFFICIAL_OPEN_ADAPTER_B_ID = "official-open-adapter-b";

export const OFFICIAL_OPEN_ADAPTER_B_VERSION = "1.0.0";

export const SHARED_CONTRACT_CAPABILITY_GAP = "SHARED_CONTRACT_CAPABILITY_GAP";

export const ADAPTER_B_STATUS = Object.freeze({
  CANONICAL_BOUND: "CANONICAL_BOUND",
  ADAPTER_BOUND_COMPATIBILITY_SINK: "ADAPTER_BOUND_COMPATIBILITY_SINK",
  EXISTING_ADOPTION_REUSED: "EXISTING_ADOPTION_REUSED",
  NOT_CONFIGURED: "NOT_CONFIGURED",
  SHARED_CONTRACT_CAPABILITY_GAP: SHARED_CONTRACT_CAPABILITY_GAP,
  CONDITIONAL_INACTIVE: "CONDITIONAL_INACTIVE",
});

export const BYPASS_CLASSIFICATION = Object.freeze({
  ALREADY_CANONICAL: "ALREADY_CANONICAL",
  NEEDS_ADOPTION: "NEEDS_ADOPTION",
  LEGACY_TO_REMOVE: "LEGACY_TO_REMOVE",
  VALID_INTERNAL_DEPENDENCY: "VALID_INTERNAL_DEPENDENCY",
  NOT_REQUIRED: "NOT_REQUIRED",
});

export const FORBIDDEN_TENANT_IDS = Object.freeze(["default-tenant", "default"]);

export const OFFICIAL_OPEN_MANAGE_PERMISSION = "tournament.update";
