/**
 * Phase 3G — Seeding Runtime error codes (capability-local).
 * Shared error-registry export is Integrator-owned — handoff only.
 */

export const SEEDING_RUNTIME_ERROR_CODE = Object.freeze({
  SEEDING_INVALID_INPUT: "SEEDING_INVALID_INPUT",
  SEEDING_NOT_FOUND: "SEEDING_NOT_FOUND",
  SEEDING_INVALID_SOURCE: "SEEDING_INVALID_SOURCE",
  SEEDING_UNSUPPORTED_SOURCE: "SEEDING_UNSUPPORTED_SOURCE",
  SEEDING_IDENTITY_MISMATCH: "SEEDING_IDENTITY_MISMATCH",
  SEEDING_IDENTITY_COLLISION: "SEEDING_IDENTITY_COLLISION",
  SEEDING_COMPETITION_MISMATCH: "SEEDING_COMPETITION_MISMATCH",
  SEEDING_CONTEXT_MISMATCH: "SEEDING_CONTEXT_MISMATCH",
  SEEDING_CANDIDATE_REQUIRED: "SEEDING_CANDIDATE_REQUIRED",
  SEEDING_CANDIDATE_DUPLICATE: "SEEDING_CANDIDATE_DUPLICATE",
  SEEDING_CANDIDATE_INELIGIBLE: "SEEDING_CANDIDATE_INELIGIBLE",
  SEEDING_MANUAL_SEED_INVALID: "SEEDING_MANUAL_SEED_INVALID",
  SEEDING_MANUAL_SEED_DUPLICATE: "SEEDING_MANUAL_SEED_DUPLICATE",
  SEEDING_SEED_NUMBER_INVALID: "SEEDING_SEED_NUMBER_INVALID",
  SEEDING_ASSIGNMENT_DUPLICATE: "SEEDING_ASSIGNMENT_DUPLICATE",
  SEEDING_RANKING_REQUIRED: "SEEDING_RANKING_REQUIRED",
  SEEDING_RATING_INVALID: "SEEDING_RATING_INVALID",
  SEEDING_POLICY_REJECTED: "SEEDING_POLICY_REJECTED",
  SEEDING_NON_DETERMINISTIC: "SEEDING_NON_DETERMINISTIC",
  SEEDING_DEPENDENCY_FAILED: "SEEDING_DEPENDENCY_FAILED",
  SEEDING_ADAPTER_FAILED: "SEEDING_ADAPTER_FAILED",
  SEEDING_PERSISTENCE_DISABLED: "SEEDING_PERSISTENCE_DISABLED",
});

/** @type {ReadonlySet<string>} */
export const SEEDING_RUNTIME_ERROR_CODE_VALUES = new Set(
  Object.values(SEEDING_RUNTIME_ERROR_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isSeedingRuntimeErrorCode(value) {
  return typeof value === "string" && SEEDING_RUNTIME_ERROR_CODE_VALUES.has(value);
}
