/**
 * CORE-07 Phase 1C — frozen error / reason codes (doc 13).
 * Phase 3G runtime codes remain in runtimeErrorCodes.js.
 */

export const SEEDING_ERROR_CATEGORY = Object.freeze({
  VALIDATION: "VALIDATION",
  BUSINESS_EXCLUSION: "BUSINESS_EXCLUSION",
  REJECTED_OVERRIDE: "REJECTED_OVERRIDE",
  WARNING: "WARNING",
  INFRASTRUCTURE: "INFRASTRUCTURE",
});

export const SEEDING_ERROR_CODE = Object.freeze({
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_SCOPE: "INVALID_SCOPE",
  DUPLICATE_CANDIDATE: "DUPLICATE_CANDIDATE",
  INVALID_CANDIDATE: "INVALID_CANDIDATE",
  ELIGIBILITY_REQUIRED: "ELIGIBILITY_REQUIRED",
  ENTRY_INELIGIBLE: "ENTRY_INELIGIBLE",
  SNAPSHOT_REQUIRED: "SNAPSHOT_REQUIRED",
  SNAPSHOT_INCOMPLETE: "SNAPSHOT_INCOMPLETE",
  POLICY_REQUIRED: "POLICY_REQUIRED",
  POLICY_VERSION_MISMATCH: "POLICY_VERSION_MISMATCH",
  INVALID_TIE_BREAK: "INVALID_TIE_BREAK",
  MISSING_STABLE_IDENTIFIER: "MISSING_STABLE_IDENTIFIER",
  DUPLICATE_SEED_NUMBER: "DUPLICATE_SEED_NUMBER",
  OVERRIDE_CONFLICT: "OVERRIDE_CONFLICT",
  OVERRIDE_UNAUTHORIZED: "OVERRIDE_UNAUTHORIZED",
  RESULT_FINALIZED: "RESULT_FINALIZED",
  NON_DETERMINISTIC_INPUT: "NON_DETERMINISTIC_INPUT",
  INTERNAL_PORT_FAILURE: "INTERNAL_PORT_FAILURE",
});

/** @type {ReadonlySet<string>} */
export const SEEDING_ERROR_CODE_VALUES = new Set(
  Object.values(SEEDING_ERROR_CODE)
);

/** @type {ReadonlySet<string>} */
export const SEEDING_ERROR_CATEGORY_VALUES = new Set(
  Object.values(SEEDING_ERROR_CATEGORY)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isSeedingErrorCode(value) {
  return typeof value === "string" && SEEDING_ERROR_CODE_VALUES.has(value);
}

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isSeedingErrorCategory(value) {
  return typeof value === "string" && SEEDING_ERROR_CATEGORY_VALUES.has(value);
}

/** Default category for each frozen code (doc 13 §2–3). */
export const SEEDING_ERROR_CODE_CATEGORY = Object.freeze({
  [SEEDING_ERROR_CODE.INVALID_REQUEST]: SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.INVALID_SCOPE]: SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.DUPLICATE_CANDIDATE]: SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.INVALID_CANDIDATE]: SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.ELIGIBILITY_REQUIRED]: SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.ENTRY_INELIGIBLE]:
    SEEDING_ERROR_CATEGORY.BUSINESS_EXCLUSION,
  [SEEDING_ERROR_CODE.SNAPSHOT_REQUIRED]: SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.SNAPSHOT_INCOMPLETE]: SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.POLICY_REQUIRED]: SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.POLICY_VERSION_MISMATCH]:
    SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.INVALID_TIE_BREAK]: SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.MISSING_STABLE_IDENTIFIER]:
    SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.DUPLICATE_SEED_NUMBER]:
    SEEDING_ERROR_CATEGORY.REJECTED_OVERRIDE,
  [SEEDING_ERROR_CODE.OVERRIDE_CONFLICT]:
    SEEDING_ERROR_CATEGORY.REJECTED_OVERRIDE,
  [SEEDING_ERROR_CODE.OVERRIDE_UNAUTHORIZED]:
    SEEDING_ERROR_CATEGORY.REJECTED_OVERRIDE,
  [SEEDING_ERROR_CODE.RESULT_FINALIZED]: SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.NON_DETERMINISTIC_INPUT]:
    SEEDING_ERROR_CATEGORY.VALIDATION,
  [SEEDING_ERROR_CODE.INTERNAL_PORT_FAILURE]:
    SEEDING_ERROR_CATEGORY.INFRASTRUCTURE,
});
