export {
  COMPETITION_VERSION_STATE,
  COMPETITION_VERSION_STATE_VALUES,
  isCompetitionVersionState,
  COMPETITION_VERSION_INITIAL_NUMBER,
  isValidCompetitionVersionNumber,
  nextCompetitionVersionNumber,
  COMPETITION_VERSION_CHANGE_TYPE,
  COMPETITION_VERSION_CHANGE_TYPE_VALUES,
  isCompetitionVersionChangeType,
  COMPETITION_VERSION_FINGERPRINT_ALGORITHM,
  COMPETITION_VERSION_IMMUTABLE_DEFINITION_FIELDS,
} from "./versioning.js";
