/**
 * RATING-V5-CUTOVER-02 Gate A3c — controlled Staging fixture preparation constants.
 */

export const FIXTURE_PREP_VERSION = "a3c-v1";

export const FIXTURE_COHORT_LABEL =
  "rating-v5-cutover-02-staging-rehearsal-wave-a";

export const PHASE4_PILOT_COHORT_LABEL = "phase4-owner-acceptance";

export const FIXTURE_PREP_OUTCOME = Object.freeze({
  PREPARED: "PREPARED",
  ALREADY_PREPARED: "ALREADY_PREPARED",
  PARTIAL_STATE_BLOCKED: "PARTIAL_STATE_BLOCKED",
  COLLISION_BLOCKED: "COLLISION_BLOCKED",
  TARGET_NOT_APPROVED: "TARGET_NOT_APPROVED",
  WRONG_PROJECT: "WRONG_PROJECT",
  UNAUTHORIZED_CALLER: "UNAUTHORIZED_CALLER",
  SCORE_OUTPUT_MISMATCH: "SCORE_OUTPUT_MISMATCH",
  MUTATION_BUDGET_EXCEEDED: "MUTATION_BUDGET_EXCEEDED",
  INTERNAL_ERROR_ROLLED_BACK: "INTERNAL_ERROR_ROLLED_BACK",
  FEATURE_DISABLED: "FEATURE_DISABLED",
  INVALID_V2_VALUE: "INVALID_V2_VALUE",
  INVALID_V5_FIXTURE_INPUT: "INVALID_V5_FIXTURE_INPUT",
  WRONG_COHORT: "WRONG_COHORT",
});

export const FIXTURE_CALIBRATION_PERMISSION = "rating_v5.calibration_manage";

export const MAPPING_STATUS = "UNAPPROVED";
export const NORMALIZED_EQUIVALENCE = "DISABLED";

export const V2_SCALE_ID = "pick_vn_v2_display";
export const V5_SCALE_ID = "pick_vn_v5_display";

/** Hard write ceilings — not Staging execution approval. */
export const MUTATION_BUDGET = Object.freeze({
  AUTH_USER_CREATIONS: 0,
  PROFILE_CREATIONS: 0,
  ROLLOUT_CONFIG_CHANGES: 0,
  CURRENT_PHASE4_PILOT_CHANGES: 0,
  ENROLLMENT_ROWS_MAX: 5,
  V2_PRIMARY_ROWS_MAX: 5,
  V5_PROFILE_ROWS_MAX: 5,
  V5_ASSESSMENT_EVENT_EVIDENCE_ROWS_MAX: 25,
  TOTAL_DURABLE_WRITE_CEILING: 40,
  MUTATION_BUDGET_REQUIRES_OWNER_REVISION: false,
});

export const ROLLBACK_TARGETS_EXACT_FIVE_CANDIDATES = true;

export const SELECTED_ARCHITECTURE = "A_EDGE_ORCHESTRATION_PLUS_SERVICE_ROLE_RPC";

export const DIRECT_RPC_BYPASS_STATUS = Object.freeze({
  BROWSER_AUTHENTICATED: "DENIED",
  ANON: "DENIED",
  SERVICE_ROLE_WITHOUT_CALLER: "DENIED_BY_RPC_GUARD",
  SERVICE_ROLE_WITH_CALLER_ON_STAGING:
    "BOUNDED_ALLOWLIST_ONLY_SAME_AS_EXISTING_PERSIST_PATTERN",
  UNRESOLVED_RESIDUAL:
    "Anyone holding Staging service_role can invoke service RPCs; mitigated by project/cohort/allowlist/caller/budget guards inside RPC. Not a browser bypass.",
});
