/**
 * CM-01 Competition Definition — stable typed error codes.
 * Module-local; not registered in API_ERROR_CODES in this phase.
 */

export const COMPETITION_DEFINITION_ERROR_CODE = Object.freeze({
  INVALID_CONTRACT: "CM01_INVALID_CONTRACT",
  INVALID_IDENTIFIER: "CM01_INVALID_IDENTIFIER",
  INVALID_COMPETITION_TYPE: "CM01_INVALID_COMPETITION_TYPE",
  INVALID_SCOPE: "CM01_INVALID_SCOPE",
  INVALID_VISIBILITY: "CM01_INVALID_VISIBILITY",
  INVALID_STATUS: "CM01_INVALID_STATUS",
  INVALID_OWNER_REFERENCE: "CM01_INVALID_OWNER_REFERENCE",
  INVALID_VENUE_REFERENCE: "CM01_INVALID_VENUE_REFERENCE",
  INVALID_CLUB_REFERENCE: "CM01_INVALID_CLUB_REFERENCE",
  INVALID_TEMPLATE_REFERENCE: "CM01_INVALID_TEMPLATE_REFERENCE",
  INVALID_RULE_SET_REFERENCE: "CM01_INVALID_RULE_SET_REFERENCE",
  INVALID_REGISTRATION_WINDOW: "CM01_INVALID_REGISTRATION_WINDOW",
  INVALID_PLANNED_PERIOD: "CM01_INVALID_PLANNED_PERIOD",
  REGISTRATION_PERIOD_CONFLICT: "CM01_REGISTRATION_PERIOD_CONFLICT",
  SCOPE_ASSOCIATION_CONFLICT: "CM01_SCOPE_ASSOCIATION_CONFLICT",
  EMPTY_NAME: "CM01_EMPTY_NAME",
  INVALID_DESCRIPTION: "CM01_INVALID_DESCRIPTION",
  INVALID_REVISION: "CM01_INVALID_REVISION",
  IMMUTABLE_FIELD_CHANGE: "CM01_IMMUTABLE_FIELD_CHANGE",
  TENANT_MISMATCH: "CM01_TENANT_MISMATCH",
  NOT_DRAFT: "CM01_NOT_DRAFT",
  CROSS_TENANT_DENIED: "CM01_CROSS_TENANT_DENIED",
  LEGACY_INCOMPATIBLE: "CM01_LEGACY_INCOMPATIBLE",
  PORT_OPERATION_UNIMPLEMENTED: "CM01_PORT_OPERATION_UNIMPLEMENTED",
});
