/**
 * I&A-11 — Privacy, tenant isolation and access certification enums.
 */

export const ANALYTICS_DATA_CLASSIFICATION = Object.freeze({
  PUBLIC: "PUBLIC",
  INTERNAL: "INTERNAL",
  TENANT_CONFIDENTIAL: "TENANT_CONFIDENTIAL",
  RESTRICTED: "RESTRICTED",
  SENSITIVE_PERSONAL: "SENSITIVE_PERSONAL",
  SENSITIVE_FINANCIAL: "SENSITIVE_FINANCIAL",
  PRIVILEGED_OPERATIONAL: "PRIVILEGED_OPERATIONAL",
});

/** Most-restrictive rank (higher = more restrictive). Unknown fails closed. */
export const ANALYTICS_DATA_CLASSIFICATION_RANK = Object.freeze({
  PUBLIC: 0,
  INTERNAL: 1,
  TENANT_CONFIDENTIAL: 2,
  RESTRICTED: 3,
  SENSITIVE_PERSONAL: 4,
  SENSITIVE_FINANCIAL: 5,
  PRIVILEGED_OPERATIONAL: 6,
});

export const ANALYTICS_ACCESS_DECISION = Object.freeze({
  ALLOW: "ALLOW",
  DENY: "DENY",
  REDACT: "REDACT",
  OMIT: "OMIT",
  SUPPRESS: "SUPPRESS",
});

export const ANALYTICS_PRIVACY_PAYLOAD_STATE = Object.freeze({
  ALLOWED: "ALLOWED",
  DENIED: "DENIED",
  SUPPRESSED: "SUPPRESSED",
  REDACTED: "REDACTED",
  OMITTED: "OMITTED",
  EMPTY: "EMPTY",
  ERROR: "ERROR",
});

export const ANALYTICS_ENTITY_SCOPE_KIND = Object.freeze({
  COMPETITION: "competition",
  VENUE: "venue",
  COURT: "court",
  CLUB: "club",
  CUSTOMER: "customer",
  PLAYER: "player",
  TEAM: "team",
  FINANCE: "finance",
  RANKING_SYSTEM: "rankingSystem",
  RATING_SYSTEM: "ratingSystem",
});

export const ANALYTICS_PRIVACY_REASON_CODE = Object.freeze({
  TRUSTED_CONTEXT_ACCEPTED: "TRUSTED_CONTEXT_ACCEPTED",
  MISSING_TENANT: "MISSING_TENANT",
  MISSING_TRUSTED_SOURCE: "MISSING_TRUSTED_SOURCE",
  MALFORMED_POLICY_VERSION: "MALFORMED_POLICY_VERSION",
  UNKNOWN_CLASSIFICATION: "UNKNOWN_CLASSIFICATION",
  METRIC_ALLOWED: "METRIC_ALLOWED",
  METRIC_DENIED_NO_GRANT: "METRIC_DENIED_NO_GRANT",
  METRIC_VERSION_MISMATCH: "METRIC_VERSION_MISMATCH",
  DIMENSION_DENIED: "DIMENSION_DENIED",
  DIMENSION_ALLOWED: "DIMENSION_ALLOWED",
  TENANT_MISMATCH: "TENANT_MISMATCH",
  TENANT_CONTAMINATION: "TENANT_CONTAMINATION",
  ENTITY_MISMATCH: "ENTITY_MISMATCH",
  ENTITY_CONTAMINATION: "ENTITY_CONTAMINATION",
  PARENT_CHILD_MISMATCH: "PARENT_CHILD_MISMATCH",
  NO_ENTITY_FALLBACK: "NO_ENTITY_FALLBACK",
  SMALL_COHORT_SUPPRESSED: "SMALL_COHORT_SUPPRESSED",
  COHORT_ALLOWED: "COHORT_ALLOWED",
  REDACTION_APPLIED: "REDACTION_APPLIED",
  OMISSION_APPLIED: "OMISSION_APPLIED",
  ACCESS_DENIED: "ACCESS_DENIED",
  POLICY_SOURCE_FAILURE: "POLICY_SOURCE_FAILURE",
  CERTIFICATION_PASSED: "CERTIFICATION_PASSED",
  CERTIFICATION_FAILED: "CERTIFICATION_FAILED",
});

export const PRIVACY_ACCESS_CERTIFICATION_METHOD_VERSION = "1.0.0";

export const PRIVACY_ACCESS_CERTIFICATION_COMPLETENESS = Object.freeze({
  COMPLETE: "COMPLETE",
  PARTIAL: "PARTIAL",
  FAILED: "FAILED",
});

/**
 * @param {unknown} value
 * @param {Readonly<Record<string, string>>} enumObject
 * @returns {boolean}
 */
export function isPrivacyEnumValue(value, enumObject) {
  return typeof value === "string" && Object.values(enumObject).includes(value);
}
