/**
 * Public Catalog — module-local typed error codes (PUBLIC-CATALOG-01).
 * Not registered in API_ERROR_CODES (same pattern as NEWS / COMMS).
 */

export const PUBLIC_CATALOG_ERROR_CODE = Object.freeze({
  INVALID_CONTRACT: "PUBLIC_CATALOG_INVALID_CONTRACT",
  INVALID_PAGINATION: "PUBLIC_CATALOG_INVALID_PAGINATION",
  INVALID_FILTER: "PUBLIC_CATALOG_INVALID_FILTER",
  INVALID_SORT: "PUBLIC_CATALOG_INVALID_SORT",
  NOT_PUBLIC: "PUBLIC_CATALOG_NOT_PUBLIC",
  ARCHIVED_OR_PRIVATE: "PUBLIC_CATALOG_ARCHIVED_OR_PRIVATE",
  PROVENANCE_MISMATCH: "PUBLIC_CATALOG_PROVENANCE_MISMATCH",
  PERSISTENCE_UNAVAILABLE: "PUBLIC_CATALOG_PERSISTENCE_UNAVAILABLE",
  NETWORK_FAILURE: "PUBLIC_CATALOG_NETWORK_FAILURE",
  RPC_FAILURE: "PUBLIC_CATALOG_RPC_FAILURE",
  MALFORMED_RESPONSE: "PUBLIC_CATALOG_MALFORMED_RESPONSE",
  CLIENT_UNAVAILABLE: "PUBLIC_CATALOG_CLIENT_UNAVAILABLE",
  FORBIDDEN_FIELD: "PUBLIC_CATALOG_FORBIDDEN_FIELD",
  PORT_OPERATION_UNIMPLEMENTED: "PUBLIC_CATALOG_PORT_OPERATION_UNIMPLEMENTED",
  MUTATION_FORBIDDEN: "PUBLIC_CATALOG_MUTATION_FORBIDDEN",
});

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isPublicCatalogErrorCode(value) {
  return Object.values(PUBLIC_CATALOG_ERROR_CODE).includes(value);
}
