/**
 * Phase 3E — Lineup Runtime error codes (capability-local).
 * Shared error-registry export is Integrator-owned — handoff only.
 */

export const LINEUP_RUNTIME_ERROR_CODE = Object.freeze({
  LINEUP_NOT_FOUND: "LINEUP_NOT_FOUND",
  INVALID_LINEUP: "INVALID_LINEUP",
  INVALID_LINEUP_SOURCE: "INVALID_LINEUP_SOURCE",
  INVALID_LINEUP_MAPPING: "INVALID_LINEUP_MAPPING",
  UNSUPPORTED_LINEUP_SOURCE: "UNSUPPORTED_LINEUP_SOURCE",
  UNSUPPORTED_LINEUP_STATUS: "UNSUPPORTED_LINEUP_STATUS",
  LINEUP_IDENTITY_COLLISION: "LINEUP_IDENTITY_COLLISION",
  LINEUP_IDENTITY_MISMATCH: "LINEUP_IDENTITY_MISMATCH",
  LINEUP_TEAM_MISMATCH: "LINEUP_TEAM_MISMATCH",
  LINEUP_ROSTER_MISMATCH: "LINEUP_ROSTER_MISMATCH",
  LINEUP_PARTICIPANT_NOT_IN_ROSTER: "LINEUP_PARTICIPANT_NOT_IN_ROSTER",
  LINEUP_DUPLICATE_PARTICIPANT: "LINEUP_DUPLICATE_PARTICIPANT",
  LINEUP_SLOT_REQUIRED: "LINEUP_SLOT_REQUIRED",
  LINEUP_SLOT_DUPLICATE: "LINEUP_SLOT_DUPLICATE",
  LINEUP_SLOT_INELIGIBLE: "LINEUP_SLOT_INELIGIBLE",
  LINEUP_STATE_TRANSITION_INVALID: "LINEUP_STATE_TRANSITION_INVALID",
  LINEUP_LOCKED: "LINEUP_LOCKED",
  LINEUP_ALREADY_PUBLISHED: "LINEUP_ALREADY_PUBLISHED",
  LINEUP_DEPENDENCY_FAILED: "LINEUP_DEPENDENCY_FAILED",
  LINEUP_ADAPTER_FAILED: "LINEUP_ADAPTER_FAILED",
  LINEUP_PERSISTENCE_DISABLED: "LINEUP_PERSISTENCE_DISABLED",
  INVALID_PARTICIPANT_REFERENCE: "INVALID_PARTICIPANT_REFERENCE",
});

/** @type {ReadonlySet<string>} */
export const LINEUP_RUNTIME_ERROR_CODE_VALUES = new Set(
  Object.values(LINEUP_RUNTIME_ERROR_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isLineupRuntimeErrorCode(value) {
  return typeof value === "string" && LINEUP_RUNTIME_ERROR_CODE_VALUES.has(value);
}
