export const BATCH_D_ACTION_MATRIX = Object.freeze([
  {
    screen: "10",
    action: "Công bố lịch",
    referenceAction: "Công bố lịch",
    currentProductionAuthority: "publishSchedule is tournament-level and first-event via engine adapter",
    class: "C",
    enabled: false,
    why: "Không công bố lịch theo nội dung đã chọn trên màn này.",
    mutationPath: null,
  },
  {
    screen: "10",
    action: "Phân bổ sân theo nội dung",
    referenceAction: "Assign court / allocation toggle",
    currentProductionAuthority: "Tournament court lock only",
    class: "C",
    enabled: false,
    why: "Chưa có phân bổ sân theo nội dung. Không ghi sân trên màn này.",
    mutationPath: null,
  },
  {
    screen: "10",
    action: "Sửa giờ trận / xử lý xung đột",
    referenceAction: "Edit match time / resolve conflict",
    currentProductionAuthority: "None on this screen",
    class: "C",
    enabled: false,
    why: "Không sửa lịch hay xung đột trên màn này.",
    mutationPath: null,
  },
  {
    screen: "10",
    action: "Mở bảng sân vận hành",
    referenceAction: "Open court board",
    currentProductionAuthority: "/court-engine is a different product",
    class: "C",
    enabled: false,
    why: "Không dùng bảng sân vận hành làm lịch giải.",
    mutationPath: null,
  },
  {
    screen: "11",
    action: "Chọn / xem trận",
    referenceAction: "Select / inspect",
    currentProductionAuthority: "Read projection from event.matches",
    class: "A",
    enabled: true,
    why: "Chỉ đọc danh sách trận đã lưu.",
    mutationPath: null,
  },
  {
    screen: "11",
    action: "Mở bảng điểm trọng tài",
    referenceAction: "Open referee scoring",
    currentProductionAuthority: "Existing /referee/:token when token present",
    class: "B",
    enabled: "token",
    why: "Chỉ mở luồng trọng tài hiện có. Không ghi điểm tại màn này.",
    mutationPath: null,
  },
  {
    screen: "11",
    action: "Ghi điểm / hoàn tất trận",
    referenceAction: "+1 / Undo / Complete / Finalize",
    currentProductionAuthority: "Denied on Match Center",
    class: "C",
    enabled: false,
    why: "Màn này không ghi tỷ số.",
    mutationPath: null,
  },
  {
    screen: "12",
    action: "Chọn nội dung / lọc BXH",
    referenceAction: "Event/group filters",
    currentProductionAuthority: "Read standings from existing ranking helper",
    class: "A",
    enabled: true,
    why: "Chỉ đọc.",
    mutationPath: null,
  },
  {
    screen: "12",
    action: "Khóa BXH",
    referenceAction: "Khóa BXH / Chốt BXH",
    currentProductionAuthority: "None per Nội dung",
    class: "C",
    enabled: false,
    why: "Chốt bảng xếp hạng nội dung chưa có trên hệ thống này.",
    mutationPath: null,
  },
  {
    screen: "13",
    action: "Xem theo vòng",
    referenceAction: "Round filter",
    currentProductionAuthority: "Read event.bracket / event.matches",
    class: "A",
    enabled: true,
    why: "Chỉ đọc.",
    mutationPath: null,
  },
  {
    screen: "13",
    action: "Tạo nhánh / ghi điểm",
    referenceAction: "Generate bracket / score",
    currentProductionAuthority: "Existing engines not bound here",
    class: "C",
    enabled: false,
    why: "Không tạo nhánh và không ghi điểm trên màn này.",
    mutationPath: null,
  },
  {
    screen: "14",
    action: "Điều hướng vòng / xem nút",
    referenceAction: "Round nav / inspect nodes",
    currentProductionAuthority: "Read bracket",
    class: "A",
    enabled: true,
    why: "Chỉ đọc sơ đồ.",
    mutationPath: null,
  },
  {
    screen: "14",
    action: "Ghi người thắng / tạo nhánh",
    referenceAction: "Set winner / generate",
    currentProductionAuthority: "Denied",
    class: "C",
    enabled: false,
    why: "Không ghi nhánh đấu trên màn này.",
    mutationPath: null,
  },
]);
