/**
 * E2E-03 Organizer Operations — constants and lifecycle enums.
 * Permission strings resolve to Identity catalog (no parallel taxonomy).
 */

export const E2E03_OPERATIONS_VERSION = "e2e-03-organizer-operations-v1";
export const E2E03_OPERATIONS_PHASE = "E2E-03";

/**
 * Organizer command action IDs (local orchestration vocabulary).
 * Mapped to Identity permissions via organizerActionMap — not a new permission catalog.
 */
export const ORGANIZER_ACTION = Object.freeze({
  OPERATIONS_READ: "organizer.operations.read",
  PREPARE_OPERATIONS: "organizer.operations.prepare",
  PARTICIPANTS_LOCK: "organizer.participants.lock",
  DRAW_PREPARE: "organizer.draw.prepare",
  SCHEDULE_PREPARE: "organizer.schedule.prepare",
  COURTS_CONFIRM: "organizer.courts.confirm",
  CHECKIN_MANAGE: "organizer.checkin.manage",
  MATCHES_CONTROL: "organizer.matches.control",
  KNOCKOUT_ACTIVATE: "organizer.knockout.activate",
  PUBLISH: "organizer.publish",
  COMPLETE: "organizer.complete",
  ARCHIVE_PREPARE: "organizer.archive.prepare",
});

export const ORGANIZER_ACTION_VALUES = Object.freeze(
  Object.values(ORGANIZER_ACTION)
);

export const ORGANIZER_LIFECYCLE_STATE = Object.freeze({
  UNINITIALIZED: "UNINITIALIZED",
  PREPARED: "PREPARED",
  PARTICIPANTS_LOCKED: "PARTICIPANTS_LOCKED",
  POOL_READY: "POOL_READY",
  SCHEDULE_READY: "SCHEDULE_READY",
  COURTS_CONFIRMED: "COURTS_CONFIRMED",
  OPERATIONAL_PLAN_PUBLISHED: "OPERATIONAL_PLAN_PUBLISHED",
  CHECKIN_OPEN: "CHECKIN_OPEN",
  CHECKIN_CLOSED: "CHECKIN_CLOSED",
  MATCH_OPS_OPEN: "MATCH_OPS_OPEN",
  MATCH_OPS_SUSPENDED: "MATCH_OPS_SUSPENDED",
  KNOCKOUT_ACTIVE: "KNOCKOUT_ACTIVE",
  COMPLETED: "COMPLETED",
  FINAL_RESULT_PUBLISHED: "FINAL_RESULT_PUBLISHED",
  ARCHIVE_READY: "ARCHIVE_READY",
});

export const ORGANIZER_LIFECYCLE_STATE_VALUES = Object.freeze(
  Object.values(ORGANIZER_LIFECYCLE_STATE)
);

export const PARTICIPANT_FIELD_STATE = Object.freeze({
  OPEN: "OPEN",
  LOCKED: "LOCKED",
});

export const CHECKIN_STATE = Object.freeze({
  NOT_OPENED: "NOT_OPENED",
  OPEN: "OPEN",
  CLOSED: "CLOSED",
});

export const MATCH_OPS_STATE = Object.freeze({
  CLOSED: "CLOSED",
  OPEN: "OPEN",
  SUSPENDED: "SUSPENDED",
});

export const PUBLICATION_OPS_STATE = Object.freeze({
  NONE: "NONE",
  OPERATIONAL_PLAN_PUBLISHED: "OPERATIONAL_PLAN_PUBLISHED",
  FINAL_RESULT_PUBLISHED: "FINAL_RESULT_PUBLISHED",
});

export const ENTRY_OPS_STATUS = Object.freeze({
  PENDING: "PENDING",
  ELIGIBLE: "ELIGIBLE",
  INELIGIBLE: "INELIGIBLE",
  WITHDRAWN: "WITHDRAWN",
  WAITLISTED: "WAITLISTED",
  INVALID: "INVALID",
});

export const ORGANIZER_BLOCKER_CODE = Object.freeze({
  MISSING_IDENTITY: "MISSING_IDENTITY",
  MISSING_TENANT: "MISSING_TENANT",
  MISSING_COMPETITION: "MISSING_COMPETITION",
  MISSING_VENUE: "MISSING_VENUE",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  CROSS_TENANT: "CROSS_TENANT",
  INVALID_STATE: "INVALID_STATE",
  PARTICIPANT_FIELD_INCOMPLETE: "PARTICIPANT_FIELD_INCOMPLETE",
  ELIGIBILITY_UNRESOLVED: "ELIGIBILITY_UNRESOLVED",
  POOL_COMPOSITION_MISSING: "POOL_COMPOSITION_MISSING",
  SCHEDULE_INCOMPLETE: "SCHEDULE_INCOMPLETE",
  SCHEDULE_UNCERTIFIED: "SCHEDULE_UNCERTIFIED",
  COURT_ASSIGNMENT_INCOMPLETE: "COURT_ASSIGNMENT_INCOMPLETE",
  COURT_SNAPSHOT_MISSING: "COURT_SNAPSHOT_MISSING",
  CHECKIN_NOT_OPEN: "CHECKIN_NOT_OPEN",
  CHECKIN_REQUIRED_MISSING: "CHECKIN_REQUIRED_MISSING",
  MATCH_OPS_NOT_OPEN: "MATCH_OPS_NOT_OPEN",
  ACTIVE_MATCHES: "ACTIVE_MATCHES",
  INCOMPLETE_MATCHES: "INCOMPLETE_MATCHES",
  STANDINGS_UNRESOLVED: "STANDINGS_UNRESOLVED",
  QUALIFICATION_NOT_READY: "QUALIFICATION_NOT_READY",
  UNRESOLVED_TIE: "UNRESOLVED_TIE",
  KNOCKOUT_INCOMPLETE: "KNOCKOUT_INCOMPLETE",
  COMPLETION_REQUIRED: "COMPLETION_REQUIRED",
  FINAL_PUBLICATION_REQUIRED: "FINAL_PUBLICATION_REQUIRED",
  DUPLICATE_PARTICIPANT: "DUPLICATE_PARTICIPANT",
  DUPLICATE_COMMAND: "DUPLICATE_COMMAND",
});

export const ORGANIZER_ERROR_CODE = Object.freeze({
  MISSING_IDENTITY: "E2E03_MISSING_IDENTITY",
  MISSING_TENANT: "E2E03_MISSING_TENANT",
  MISSING_COMPETITION: "E2E03_MISSING_COMPETITION",
  MISSING_VENUE: "E2E03_MISSING_VENUE",
  PERMISSION_DENIED: "E2E03_PERMISSION_DENIED",
  CROSS_TENANT_REJECTED: "E2E03_CROSS_TENANT_REJECTED",
  INVALID_STATE: "E2E03_INVALID_STATE",
  INVALID_INPUT: "E2E03_INVALID_INPUT",
  PRECONDITION_FAILED: "E2E03_PRECONDITION_FAILED",
  PARTICIPANT_FIELD_INCOMPLETE: "E2E03_PARTICIPANT_FIELD_INCOMPLETE",
  DUPLICATE_PARTICIPANT: "E2E03_DUPLICATE_PARTICIPANT",
  POOL_COMPOSITION_MISSING: "E2E03_POOL_COMPOSITION_MISSING",
  SCHEDULE_UNCERTIFIED: "E2E03_SCHEDULE_UNCERTIFIED",
  SCHEDULE_INCOMPLETE: "E2E03_SCHEDULE_INCOMPLETE",
  COURT_ASSIGNMENT_INCOMPLETE: "E2E03_COURT_ASSIGNMENT_INCOMPLETE",
  COURT_SNAPSHOT_MISSING: "E2E03_COURT_SNAPSHOT_MISSING",
  CHECKIN_NOT_OPEN: "E2E03_CHECKIN_NOT_OPEN",
  CHECKIN_ALREADY_OPEN: "E2E03_CHECKIN_ALREADY_OPEN",
  CHECKIN_ALREADY_CLOSED: "E2E03_CHECKIN_ALREADY_CLOSED",
  CHECKIN_REQUIRED_MISSING: "E2E03_CHECKIN_REQUIRED_MISSING",
  MATCH_OPS_BLOCKED: "E2E03_MATCH_OPS_BLOCKED",
  ACTIVE_MATCHES: "E2E03_ACTIVE_MATCHES",
  INCOMPLETE_MATCHES: "E2E03_INCOMPLETE_MATCHES",
  QUALIFICATION_NOT_READY: "E2E03_QUALIFICATION_NOT_READY",
  UNRESOLVED_TIE: "E2E03_UNRESOLVED_TIE",
  COMPLETION_REQUIRED: "E2E03_COMPLETION_REQUIRED",
  FINAL_PUBLICATION_REQUIRED: "E2E03_FINAL_PUBLICATION_REQUIRED",
  CANONICAL_CALL_FAILED: "E2E03_CANONICAL_CALL_FAILED",
  CLIENT_GRANT_TRUST_REJECTED: "E2E03_CLIENT_GRANT_TRUST_REJECTED",
  UNKNOWN: "E2E03_UNKNOWN",
});

export const ORGANIZER_ERROR_CODE_VALUES = Object.freeze(
  Object.values(ORGANIZER_ERROR_CODE)
);
