/**
 * CORE-14 Phase 1F — local CC-09 legacy conflict code mirror (shape-only).
 * Capability-local constants only; no adjacent module imports.
 * Values match historical CC-09 CONFLICT_TYPE string vocabulary.
 */

export const LEGACY_CC09_CONFLICT_CODE = Object.freeze({
  PLAYER_TIME_CONFLICT: "PLAYER_TIME_CONFLICT",
  TEAM_TIME_CONFLICT: "TEAM_TIME_CONFLICT",
  COURT_TIME_CONFLICT: "COURT_TIME_CONFLICT",
  VENUE_TIME_CONFLICT: "VENUE_TIME_CONFLICT",
  REFEREE_TIME_CONFLICT: "REFEREE_TIME_CONFLICT",
  INSUFFICIENT_REST: "INSUFFICIENT_REST",
  COURT_UNAVAILABLE: "COURT_UNAVAILABLE",
  VENUE_UNAVAILABLE: "VENUE_UNAVAILABLE",
  INVALID_ROUND_ORDER: "INVALID_ROUND_ORDER",
  DUPLICATE_MATCH_ASSIGNMENT: "DUPLICATE_MATCH_ASSIGNMENT",
  UNASSIGNED_MATCH: "UNASSIGNED_MATCH",
  INVALID_BYE_ASSIGNMENT: "INVALID_BYE_ASSIGNMENT",
  MANUAL_OVERRIDE_CONFLICT: "MANUAL_OVERRIDE_CONFLICT",
  DEPENDENCY_NOT_COMPLETED: "DEPENDENCY_NOT_COMPLETED",
  UNKNOWN_PARTICIPANT: "UNKNOWN_PARTICIPANT",
  UNKNOWN_COURT: "UNKNOWN_COURT",
  UNKNOWN_SLOT: "UNKNOWN_SLOT",
});

export const LEGACY_CC09_CONFLICT_CODE_VALUES = Object.freeze(
  Object.values(LEGACY_CC09_CONFLICT_CODE)
);

/** Workflow / non-resource codes — never mapped as CORE-14 resource conflicts. */
export const LEGACY_CC09_UNMAPPED_WORKFLOW_CODES = Object.freeze([
  LEGACY_CC09_CONFLICT_CODE.UNASSIGNED_MATCH,
  LEGACY_CC09_CONFLICT_CODE.INVALID_BYE_ASSIGNMENT,
  LEGACY_CC09_CONFLICT_CODE.INVALID_ROUND_ORDER,
  LEGACY_CC09_CONFLICT_CODE.DEPENDENCY_NOT_COMPLETED,
  LEGACY_CC09_CONFLICT_CODE.MANUAL_OVERRIDE_CONFLICT,
  LEGACY_CC09_CONFLICT_CODE.DUPLICATE_MATCH_ASSIGNMENT,
  LEGACY_CC09_CONFLICT_CODE.UNKNOWN_PARTICIPANT,
  LEGACY_CC09_CONFLICT_CODE.UNKNOWN_COURT,
  LEGACY_CC09_CONFLICT_CODE.UNKNOWN_SLOT,
]);
