/**
 * Competition Core Draw Engine foundation — CC-04A.
 * Importing this module MUST NOT execute draw algorithms or mutate tournament state.
 */

export {
  DRAW_ENGINE_VERSION,
  DEFAULT_DRAW_RULE_SET_VERSION,
  CANONICAL_DRAW_MODE,
  CANONICAL_DRAW_MODE_VALUES,
  isCanonicalDrawMode,
  DRAW_SEED_SOURCE,
  DRAW_SEED_SOURCE_VALUES,
  isDrawSeedSource,
  DRAW_STRATEGY_KIND,
  DRAW_STRATEGY_KIND_VALUES,
  isDrawStrategyKind,
  DRAW_CONSTRAINT_CATEGORY,
  DRAW_CONSTRAINT_CATEGORY_VALUES,
  isDrawConstraintCategory,
  DRAW_RANDOM_GENERATOR,
  DRAW_RANDOM_GENERATOR_VALUES,
  isDrawRandomGenerator,
} from "./drawConstants.js";

export {
  CC01_DRAW_MODE_TO_CANONICAL,
  LEGACY_DRAW_MODE_MAPPINGS,
  mapLegacyDrawModeToCanonical,
  mapCc01DrawModeToCanonical,
} from "./legacyDrawMapping.js";

export {
  createDrawSeed,
  createDrawGroup,
  createDrawCandidate,
  createDrawConstraint,
  createDrawExplanation,
  createDrawConflict,
  createDrawScoreBreakdown,
  createDrawRandomMetadata,
  createDrawStrategy,
  createDrawMetadata,
  createDrawAudit,
  createDrawRequest,
  createDrawResult,
  createDrawEngineResult,
  validateDrawRequestShape,
  validateDrawResultShape,
  cloneDrawRequest,
  serializeDrawContract,
} from "./drawContracts.js";

export {
  createSeedStrategy,
  createDistributionStrategy,
  createConstraintStrategy,
  createBalancingStrategy,
  createRandomStrategy,
  createAuditStrategy,
  createExplainStrategy,
  createDefaultDrawStrategyBundle,
} from "./drawStrategies.js";

export {
  DRAW_STRATEGY_ENGINE_VERSION,
  DISTRIBUTION_TYPE,
  DISTRIBUTION_TYPE_VALUES,
  isDistributionType,
  CANONICAL_DRAW_STRATEGY_ID,
  CANONICAL_DRAW_STRATEGY_ID_VALUES,
  isCanonicalDrawStrategyId,
  DEFAULT_STRATEGY_CAPABILITIES,
  CANONICAL_DRAW_STRATEGY_CATALOG,
  LEGACY_DRAW_STRATEGY_INVENTORY,
  mapLegacyStrategyKeyToCatalogId,
  getDrawStrategyFromCatalog,
  createDrawStrategyDefinition,
  createStrategyDrawConfiguration,
  createStrategySelection,
  createDistributionPolicy,
  createConstraintPolicy,
  createBalancePolicy,
  createSeedPolicy,
  createDrawPlacement,
  createDistributionStep,
  createStrategyDrawAudit,
  createStrategyDrawRequest,
  createStrategyDrawResult,
  createStrategyDrawExplanation,
  validateStrategyDrawRequestShape,
  validateStrategyDrawResultShape,
  cloneStrategyDrawRequest,
  serializeStrategyDrawContract,
  selectDrawStrategy,
  deriveDefaultPoliciesFromStrategy,
  buildFoundationStrategyDrawResult,
} from "./strategy/index.js";

export {
  DRAW_RUNTIME_ADAPTER_VERSION,
  LEGACY_DRAW_RUNTIME_INVENTORY,
  buildDrawRuntimeCallGraph,
  findDrawRuntimeInventoryByFunction,
  mapLegacyDrawPayloadToDrawRequest,
  mapLegacyDrawPayloadToStrategyDrawRequest,
  mapCompetitionEngineInputToDrawRequest,
  cloneLegacyDrawPayload,
  isLegacyDrawPayloadPreserved,
  mapLegacyGroupToDrawGroup,
  mapLegacyGroupsToDrawGroups,
  mapDrawGroupToLegacyGroup,
  mapDrawGroupsToLegacyGroups,
  mapLegacyDrawResultToDrawResult,
  adaptDrawResultForLegacyConsumer,
  mapDrawResultToStrategyDrawResult,
  isLegacyDrawOutputPreserved,
  createDrawDecisionTrace,
  createDrawDecisionTraceRecord,
  appendDrawDecisionTrace,
  buildDrawDecisionPath,
  summarizeDrawDecisionTrace,
  resolveDrawEnvSource,
  evaluateCanonicalDraw,
  runLegacyDrawWithCanonicalAdapter,
} from "./adapters/index.js";

export {
  createManualDrawSeed,
  createAverageLevelDrawSeed,
  createCompetitionEloDrawSeed,
  createWinRateDrawSeed,
  createPerformanceDrawSeed,
  createProvisionalDrawSeed,
  createNewPlayerDrawSeed,
  createManualAdjustmentDrawSeed,
  normalizeDrawSeeds,
} from "./seedModel.js";
