/**
 * E2E-07 End-to-End Certification constants.
 */

export const E2E07_CERTIFICATION_VERSION =
  "e2e-07-end-to-end-certification-v1";

export const E2E07_CERTIFICATION_PHASE = "E2E-07";

export const CERTIFICATION_LEVEL = Object.freeze({
  STRUCTURAL: "STRUCTURAL",
  LOCAL_RUNTIME: "LOCAL_RUNTIME",
  REMOTE: "REMOTE",
});

export const CERTIFICATION_VERDICT = Object.freeze({
  CERTIFIED_LOCAL_MVP: "CERTIFIED_LOCAL_MVP",
  CERTIFIED_STAGING: "CERTIFIED_STAGING",
  PRODUCTION_READY: "PRODUCTION_READY",
  BLOCKED: "BLOCKED",
  DEGRADED: "DEGRADED",
});

/** 27-step IND Pool+Knockout happy-path stage identifiers. */
export const CERTIFICATION_STAGE = Object.freeze({
  PREPARE_OPERATIONS: "E2E07_STAGE_PREPARE_OPERATIONS",
  LOCK_PARTICIPANT_FIELD: "E2E07_STAGE_LOCK_PARTICIPANT_FIELD",
  PREPARE_POOL_STAGE: "E2E07_STAGE_PREPARE_POOL_STAGE",
  PREPARE_OPERATIONAL_SCHEDULE: "E2E07_STAGE_PREPARE_OPERATIONAL_SCHEDULE",
  CONFIRM_COURT_ASSIGNMENTS: "E2E07_STAGE_CONFIRM_COURT_ASSIGNMENTS",
  PUBLISH_OPERATIONAL_PLAN: "E2E07_STAGE_PUBLISH_OPERATIONAL_PLAN",
  OPEN_CHECK_IN: "E2E07_STAGE_OPEN_CHECK_IN",
  PLAYER_CHECK_IN_ALL: "E2E07_STAGE_PLAYER_CHECK_IN_ALL",
  CLOSE_CHECK_IN: "E2E07_STAGE_CLOSE_CHECK_IN",
  OPEN_MATCH_OPERATIONS: "E2E07_STAGE_OPEN_MATCH_OPERATIONS",
  REFEREE_SEED_ASSIGNMENTS: "E2E07_STAGE_REFEREE_SEED_ASSIGNMENTS",
  REFEREE_OPEN_MATCH: "E2E07_STAGE_REFEREE_OPEN_MATCH",
  REFEREE_SCORE_ENTRY: "E2E07_STAGE_REFEREE_SCORE_ENTRY",
  REFEREE_VALIDATE_RESULT: "E2E07_STAGE_REFEREE_VALIDATE_RESULT",
  BUILD_POOL_STANDINGS: "E2E07_STAGE_BUILD_POOL_STANDINGS",
  ACTIVATE_KNOCKOUT_STAGE: "E2E07_STAGE_ACTIVATE_KNOCKOUT_STAGE",
  SYNC_KNOCKOUT_COMPLETED: "E2E07_STAGE_SYNC_KNOCKOUT_COMPLETED",
  COMPLETE_COMPETITION: "E2E07_STAGE_COMPLETE_COMPETITION",
  PUBLISH_FINAL_RESULT: "E2E07_STAGE_PUBLISH_FINAL_RESULT",
  REQUEST_ARCHIVE_READINESS: "E2E07_STAGE_REQUEST_ARCHIVE_READINESS",
  PUBLIC_PUT_SNAPSHOT: "E2E07_STAGE_PUBLIC_PUT_SNAPSHOT",
  PUBLIC_GET_OVERVIEW: "E2E07_STAGE_PUBLIC_GET_OVERVIEW",
  PUBLIC_GET_STANDINGS: "E2E07_STAGE_PUBLIC_GET_STANDINGS",
  PUBLIC_GET_FINAL: "E2E07_STAGE_PUBLIC_GET_FINAL",
  GOVERNANCE_CERTIFICATION_READINESS: "E2E07_STAGE_GOVERNANCE_CERTIFICATION_READINESS",
  GOVERNANCE_EVIDENCE_MANIFEST: "E2E07_STAGE_GOVERNANCE_EVIDENCE_MANIFEST",
  HAPPY_PATH_CLOSURE: "E2E07_STAGE_HAPPY_PATH_CLOSURE",
});

export const CERTIFICATION_STAGE_VALUES = Object.freeze(
  Object.values(CERTIFICATION_STAGE)
);

export const CERTIFICATION_CHECK = Object.freeze({
  STRUCTURAL_EXPORTS: "E2E07_CHECK_STRUCTURAL_EXPORTS",
  ARCHITECTURE_BANS: "E2E07_CHECK_ARCHITECTURE_BANS",
  NO_PARALLEL_ENGINES: "E2E07_CHECK_NO_PARALLEL_ENGINES",
  HAPPY_PATH_VERTICAL: "E2E07_CHECK_HAPPY_PATH_VERTICAL",
  FAIL_CLOSED_MATRIX: "E2E07_CHECK_FAIL_CLOSED_MATRIX",
  RECOVERY_REPLAY: "E2E07_CHECK_RECOVERY_REPLAY",
  PUBLIC_PRIVACY: "E2E07_CHECK_PUBLIC_PRIVACY",
  GOVERNANCE_HEALTH: "E2E07_CHECK_GOVERNANCE_HEALTH",
  SUSPENSION_ARCHIVE: "E2E07_CHECK_SUSPENSION_ARCHIVE",
  GOV08_BENCHMARK: "E2E07_CHECK_GOV08_BENCHMARK",
  CAPABILITY_TRACEABILITY: "E2E07_CHECK_CAPABILITY_TRACEABILITY",
  EVIDENCE_MANIFEST: "E2E07_CHECK_EVIDENCE_MANIFEST",
});

export const CERTIFICATION_ERROR_CODE = Object.freeze({
  MISSING_TENANT: "E2E07_MISSING_TENANT",
  MISSING_COMPETITION: "E2E07_MISSING_COMPETITION",
  MISSING_SCENARIO: "E2E07_MISSING_SCENARIO",
  STRUCTURAL_FAILURE: "E2E07_STRUCTURAL_FAILURE",
  HAPPY_PATH_BLOCKED: "E2E07_HAPPY_PATH_BLOCKED",
  FAIL_CLOSED_GAP: "E2E07_FAIL_CLOSED_GAP",
  RECOVERY_REPLAY_BLOCKED: "E2E07_RECOVERY_REPLAY_BLOCKED",
  PUBLIC_PRIVACY_BLOCKED: "E2E07_PUBLIC_PRIVACY_BLOCKED",
  GOVERNANCE_BLOCKED: "E2E07_GOVERNANCE_BLOCKED",
  BENCHMARK_REGRESSION: "E2E07_BENCHMARK_REGRESSION",
  CAPABILITY_GAP: "E2E07_CAPABILITY_GAP",
  INVALID_INPUT: "E2E07_INVALID_INPUT",
  UNKNOWN: "E2E07_UNKNOWN",
});

export const CERTIFICATION_FORBIDDEN_KEYS = Object.freeze([
  "token",
  "secret",
  "password",
  "authorization",
  "email",
  "phone",
  "base64",
  "privateKey",
  "accessToken",
  "refreshToken",
  "grantedPermissions",
]);

export const COMPETITION_ENGINE_END_TO_END_CERTIFICATION = Object.freeze({
  id: "competition-engine-end-to-end-certification",
  phase: E2E07_CERTIFICATION_PHASE,
  version: E2E07_CERTIFICATION_VERSION,
  wiredToProductionRuntime: false,
  ownsEngines: false,
});

export const E2E_07_REMOTE_STAGING_OWNER_GO_REQUIRED =
  "E2E_07_REMOTE_STAGING_OWNER_GO_REQUIRED";

/** Substring tokens banned in certification source (scan uses includes, not regex literals). */
export const CERTIFICATION_ARCHITECTURE_BAN_TOKENS = Object.freeze([
  "@supabase",
  "Date.now(",
  "Math.random(",
  "randomUUID(",
]);
