/**
 * Core-03 — Registration & Eligibility
 * (Phase 1A–1D services + Phase 1E sibling adapters + Phase 1F persistence foundation).
 *
 * Capability-local public surface ONLY.
 * Do NOT re-export from competition-core/index.js in this branch
 * (Integrator owns protected barrels).
 *
 * Does not own: Participant/Entry persistence (Core-02), Division/Category (Core-04),
 * Rule Engine implementation (Core-01), UI, or Production SQL apply.
 * Phase 1E adapters depend on injected sibling public facades only (no deep imports).
 * Phase 1F authors persistence adapters + migration SQL but does not apply SQL or connect
 * to Staging/Production databases. Core-02 Entry creation remains DEFERRED_FAIL_CLOSED.
 */

export {
  REGISTRATION_STATUS,
  REGISTRATION_STATUS_VALUES,
  TERMINAL_REGISTRATION_STATUSES,
  isRegistrationStatus,
  isTerminalRegistrationStatus,
  REGISTRATION_TARGET_TYPE,
  REGISTRATION_TARGET_TYPE_VALUES,
  isRegistrationTargetType,
  REGISTRATION_DECISION_TYPE,
  REGISTRATION_DECISION_TYPE_VALUES,
  isRegistrationDecisionType,
  ELIGIBILITY_OUTCOME,
  ELIGIBILITY_OUTCOME_VALUES,
  isEligibilityOutcome,
  ELIGIBILITY_CHECK_TYPE,
  ELIGIBILITY_CHECK_TYPE_VALUES,
  isEligibilityCheckType,
  ELIGIBILITY_REASON_SEVERITY,
  ELIGIBILITY_REASON_SEVERITY_VALUES,
  ELIGIBILITY_REASON_SEVERITY_RANK,
  isEligibilityReasonSeverity,
  COMPETITION_FORMAT_HINT,
  COMPETITION_FORMAT_HINT_VALUES,
  isCompetitionFormatHint,
} from "./enums/index.js";

export {
  REGISTRATION_ELIGIBILITY_ERROR_CODE,
  REGISTRATION_ELIGIBILITY_ERROR_CODE_VALUES,
  isRegistrationEligibilityErrorCode,
  registrationEligibilityError,
  registrationEligibilityWarning,
  registrationEligibilityOk,
  registrationEligibilityFail,
} from "./errors/index.js";

export {
  REGISTRATION_ELIGIBILITY_SCHEMA_VERSION,
  ELIGIBILITY_EVALUATOR_VERSION,
  REGISTRATION_LIFECYCLE_SERVICE_VERSION,
  ELIGIBILITY_EVALUATION_SERVICE_VERSION,
  CAPACITY_WAITLIST_SERVICE_VERSION,
  SIBLING_ADAPTERS_VERSION,
  PERSISTENCE_FOUNDATION_VERSION,
  createAuditMetadata,
  isNonEmptyString,
  requireNonEmptyString,
  cloneJsonSafe,
  createRegistrationTarget,
  assertRegistrationTarget,
  buildRegistrationTargetStableIdentity,
  hasValidRegistrationTarget,
  isRegistrationTarget,
  createRegistrationApplicant,
  createRegistrationDecision,
  mapDecisionTypeToStatus,
  createEligibilityReason,
  orderEligibilityReasons,
  createEligibilityCheckResult,
  createEligibilityPolicy,
  createEligibilityEvaluationContext,
  createEligibilityDecision,
  createEligibilityEvaluationEvidence,
  createCompetitionRegistration,
  buildCompetitionRegistrationIdentityKey,
  createRegistrationEvidence,
  createRegistrationAuditEvent,
  createRegistrationCapacitySnapshot,
  createRegistrationWaitlistPosition,
  createCapacityReservation,
  createWaitlistEntry,
  buildRegistrationIdempotencyKey,
  createRegistrationIdempotencyRecord,
} from "./contracts/index.js";

export {
  REGISTRATION_ALLOWED_TRANSITIONS,
  canTransitionRegistrationStatus,
  validateRegistrationTransition,
  applyRegistrationTransition,
  evaluateIdempotentSubmission,
  createIdempotencyRecordForRegistration,
  buildEvaluationIdempotencyKey,
  buildCanonicalEvaluationRequestFingerprint,
  serializeCanonicalEvaluationRequestFingerprint,
  canonicalEvaluationFingerprintsEqual,
  evaluateIdempotentEvaluation,
  createIdempotencyRecordForEvaluation,
  orderCheckTypesForExecution,
  resolveRequiredCheckTypes,
  validateCapacityCounts,
  computeEffectiveRemaining,
  hasAvailableCapacity,
  normalizePriorityRank,
  buildCapacityScopeKey,
  compareWaitlistEntries,
  sortWaitlistEntries,
  calculateWaitlistPositions,
  CAPACITY_IDEMPOTENCY_NAMESPACE,
  buildCapacityIdempotencyKey,
  buildCanonicalCapacityRequestFingerprint,
  serializeCanonicalCapacityRequestFingerprint,
  canonicalCapacityFingerprintsEqual,
  evaluateIdempotentCapacityRequest,
  createIdempotencyRecordForCapacity,
  CAPACITY_AUTH_PURPOSE,
  validateScopeBoundAuthorization,
  policyExplicitlyRequiresWaitlist,
  resolveWaitlistPlacementPermit,
  validatePromotionAuthorization,
} from "./policies/index.js";

export {
  createNullClockPort,
  createFixedClockPort,
  isClockPort,
  createSequentialIdGeneratorPort,
  createNullIdGeneratorPort,
  isIdGeneratorPort,
  createNullParticipantLookupPort,
  createInMemoryParticipantLookupPort,
  PARTICIPANT_LOOKUP_PORT_METHODS,
  createNullEntryLookupPort,
  createInMemoryEntryLookupPort,
  ENTRY_LOOKUP_PORT_METHODS,
  createNullEntryCreationPort,
  createInMemoryEntryCreationPort,
  ENTRY_CREATION_PORT_METHODS,
  createNullDivisionEligibilityPort,
  createStubDivisionEligibilityPort,
  DIVISION_ELIGIBILITY_PORT_METHODS,
  createNullCompetitionRegistrationPolicyPort,
  createInMemoryCompetitionRegistrationPolicyPort,
  COMPETITION_REGISTRATION_POLICY_PORT_METHODS,
  createNullRuleEvaluationPort,
  createStubRuleEvaluationPort,
  RULE_EVALUATION_PORT_METHODS,
  createNullPaymentStatusPort,
  createStubPaymentStatusPort,
  PAYMENT_STATUS_PORT_METHODS,
  createNullMembershipStatusPort,
  createStubMembershipStatusPort,
  MEMBERSHIP_STATUS_PORT_METHODS,
  createNullTeamRosterValidationPort,
  createStubTeamRosterValidationPort,
  TEAM_ROSTER_VALIDATION_PORT_METHODS,
  REGISTRATION_REPOSITORY_PORT_METHODS,
  matchesRegistrationRepositoryPort,
  createInMemoryRegistrationRepositoryPort,
  createNoopRegistrationRepositoryPort,
  createNullRegistrationAuditPort,
  createInMemoryRegistrationAuditPort,
  REGISTRATION_AUDIT_PORT_METHODS,
  CAPACITY_STATE_REPOSITORY_PORT_METHODS,
  matchesCapacityStateRepositoryPort,
  createInMemoryCapacityStateRepositoryPort,
  createNullCapacityStateRepositoryPort,
  CAPACITY_RESERVATION_REPOSITORY_PORT_METHODS,
  matchesCapacityReservationRepositoryPort,
  createInMemoryCapacityReservationRepositoryPort,
  createNullCapacityReservationRepositoryPort,
  WAITLIST_REPOSITORY_PORT_METHODS,
  matchesWaitlistRepositoryPort,
  createInMemoryWaitlistRepositoryPort,
  createNullWaitlistRepositoryPort,
  ELIGIBILITY_EVIDENCE_LOOKUP_PORT_METHODS,
  matchesEligibilityEvidenceLookupPort,
  createInMemoryEligibilityEvidenceLookupPort,
  createNullEligibilityEvidenceLookupPort,
  CAPACITY_VALID_ELIGIBILITY_OUTCOMES,
} from "./ports/index.js";

export {
  CORE03_FIXTURE_CLOCK,
  createCore03TestFixture,
  fixtureIndividualRegistration,
  fixturePairRegistration,
  fixtureTeamRegistration,
  CORE03_FIXTURE_PARTICIPANTS,
  fixtureDefaultCompetitionPolicy,
  createEligibilityEvaluationTestHarness,
  createCapacityWaitlistTestHarness,
  createFakeSiblingFacades,
} from "./fixtures/index.js";

export {
  REGISTRATION_LIFECYCLE_OPERATION,
  REGISTRATION_LIFECYCLE_OPERATION_VALUES,
  isRegistrationLifecycleOperation,
  REGISTRATION_LIFECYCLE_SYSTEM_ACTOR,
  registrationLifecycleServiceOk,
  registrationLifecycleServiceFail,
  createRegistrationLifecycleService,
  ELIGIBILITY_EVALUATION_OPERATION,
  ELIGIBILITY_EVALUATION_OPERATION_VALUES,
  isEligibilityEvaluationOperation,
  ELIGIBILITY_EVALUATION_SYSTEM_ACTOR,
  eligibilityEvaluationServiceOk,
  eligibilityEvaluationServiceFail,
  createEligibilityEvaluationService,
  CAPACITY_WAITLIST_OPERATION,
  CAPACITY_WAITLIST_OPERATION_VALUES,
  isCapacityWaitlistOperation,
  CAPACITY_WAITLIST_SYSTEM_ACTOR,
  capacityWaitlistServiceOk,
  capacityWaitlistServiceFail,
  createCapacityWaitlistService,
} from "./services/index.js";

export {
  CORE03_SIBLING_ADAPTER_NAME,
  CORE03_SIBLING_CAPABILITY,
  CORE03_SIBLING_ADAPTER_VERSION,
  createSiblingAdapterMetadata,
  RULE_EVALUATION_ADAPTER_CONTRACT_VERSION,
  createCore01RuleEvaluationAdapter,
  PARTICIPANT_LOOKUP_ADAPTER_CONTRACT_VERSION,
  createCore02ParticipantLookupAdapter,
  ENTRY_LOOKUP_ADAPTER_CONTRACT_VERSION,
  CORE02_ACTIVE_ENTRY_STATUSES,
  normalizeCore02EntryStatus,
  createCore02EntryLookupAdapter,
  ENTRY_CREATION_ADAPTER_CONTRACT_VERSION,
  ENTRY_CREATION_COMPATIBILITY_GAP,
  createCore02EntryCreationAdapter,
  DIVISION_ELIGIBILITY_ADAPTER_CONTRACT_VERSION,
  createCore04DivisionEligibilityAdapter,
  TEAM_ROSTER_VALIDATION_ADAPTER_CONTRACT_VERSION,
  TEAM_ROSTER_NOT_APPLICABLE_CODE,
  createCore05TeamRosterValidationAdapter,
  CORE03_SIBLING_COMPATIBILITY_MATRIX,
  getCore03SiblingCompatibilityMatrix,
  createCore03SiblingAdapters,
} from "./adapters/index.js";

export {
  CORE03_PHASE_1F_MIGRATION_STATUS,
  createParameterizedSqlStatement,
  buildInsertRegistrationSql,
  buildSelectRegistrationByIdSql,
  buildInsertAuditEventSql,
  isSafeParameterizedStatement,
  createPersistencePartialSuccess,
  runPersistenceTransaction,
  mapPersistenceError,
  createCore03MemoryPersistenceStore,
  createRegistrationRepositoryAdapter,
  createRegistrationAuditRepositoryAdapter,
  createEligibilityEvidenceRepositoryAdapter,
  createCapacityStateRepositoryAdapter,
  createCapacityReservationRepositoryAdapter,
  createWaitlistRepositoryAdapter,
  createCore03PersistenceRepositories,
} from "./persistence/index.js";
