/**
 * Player Rating Foundation — stable error codes (Phase 1B).
 * Module-local; not registered in API_ERROR_CODES in this phase.
 */

export const PLAYER_RATING_FOUNDATION_ERROR_CODE = Object.freeze({
  INVALID_RATING_CONTRACT: "PLAYER_RATING_INVALID_CONTRACT",
  UNSUPPORTED_RATING_MODE: "PLAYER_RATING_UNSUPPORTED_MODE",
  CANONICAL_PLAYER_ID_UNRESOLVED: "PLAYER_RATING_CANONICAL_PLAYER_ID_UNRESOLVED",
  TENANT_OR_SCOPE_UNRESOLVED: "PLAYER_RATING_TENANT_OR_SCOPE_UNRESOLVED",
  UNAUTHORIZED_VERIFICATION: "PLAYER_RATING_UNAUTHORIZED_VERIFICATION",
  UNAUTHORIZED_MANUAL_ADJUSTMENT: "PLAYER_RATING_UNAUTHORIZED_MANUAL_ADJUSTMENT",
  SNAPSHOT_NOT_FOUND: "PLAYER_RATING_SNAPSHOT_NOT_FOUND",
  DUPLICATE_RATING_APPLICATION: "PLAYER_RATING_DUPLICATE_APPLICATION",
  RATING_APPLICATION_NOT_FOUND_FOR_REVERSAL:
    "PLAYER_RATING_APPLICATION_NOT_FOUND_FOR_REVERSAL",
  MATCH_RESULT_RATING_INTEGRATION_UNAVAILABLE:
    "PLAYER_RATING_MATCH_RESULT_INTEGRATION_UNAVAILABLE",
  PORT_OPERATION_UNIMPLEMENTED: "PLAYER_RATING_PORT_OPERATION_UNIMPLEMENTED",
  HISTORY_MUTATION_FORBIDDEN: "PLAYER_RATING_HISTORY_MUTATION_FORBIDDEN",
  SNAPSHOT_MUTATION_FORBIDDEN: "PLAYER_RATING_SNAPSHOT_MUTATION_FORBIDDEN",
  HISTORY_ENTRY_DUPLICATE: "PLAYER_RATING_HISTORY_ENTRY_DUPLICATE",
  HISTORY_ENTRY_NOT_FOUND: "PLAYER_RATING_HISTORY_ENTRY_NOT_FOUND",
  SNAPSHOT_DUPLICATE: "PLAYER_RATING_SNAPSHOT_DUPLICATE",
  CURRENT_STATE_NOT_FOUND: "PLAYER_RATING_CURRENT_STATE_NOT_FOUND",
  RATING_VERSION_CONFLICT: "PLAYER_RATING_VERSION_CONFLICT",
  RATING_OPERATION_DUPLICATE: "PLAYER_RATING_OPERATION_DUPLICATE",
  RATING_OPERATION_PAYLOAD_CONFLICT: "PLAYER_RATING_OPERATION_PAYLOAD_CONFLICT",
  RATING_SCALE_MISMATCH: "PLAYER_RATING_SCALE_MISMATCH",
  ADJUSTMENT_FIELD_NOT_ALLOWED: "PLAYER_RATING_ADJUSTMENT_FIELD_NOT_ALLOWED",
  ADJUSTMENT_AUDIT_DUPLICATE: "PLAYER_RATING_ADJUSTMENT_AUDIT_DUPLICATE",
});
