/**
 * Communication Foundation — stable error codes (COMMS-01).
 * Module-local; not registered in API_ERROR_CODES in this phase.
 */

export const COMMUNICATION_FOUNDATION_ERROR_CODE = Object.freeze({
  INVALID_CONTRACT: "COMMUNICATION_INVALID_CONTRACT",
  INVALID_IDENTIFIER: "COMMUNICATION_INVALID_IDENTIFIER",
  INVALID_CONVERSATION_TYPE: "COMMUNICATION_INVALID_CONVERSATION_TYPE",
  INVALID_CONVERSATION_STATUS: "COMMUNICATION_INVALID_CONVERSATION_STATUS",
  INVALID_CONVERSATION_TRANSITION:
    "COMMUNICATION_INVALID_CONVERSATION_TRANSITION",
  INVALID_PARTICIPANT_ROLE: "COMMUNICATION_INVALID_PARTICIPANT_ROLE",
  INVALID_PARTICIPANT_STATUS: "COMMUNICATION_INVALID_PARTICIPANT_STATUS",
  INVALID_PARTICIPANT_TRANSITION:
    "COMMUNICATION_INVALID_PARTICIPANT_TRANSITION",
  DUPLICATE_PARTICIPANT: "COMMUNICATION_DUPLICATE_PARTICIPANT",
  PARTICIPANT_NOT_FOUND: "COMMUNICATION_PARTICIPANT_NOT_FOUND",
  UNAUTHORIZED_SENDER: "COMMUNICATION_UNAUTHORIZED_SENDER",
  INVALID_MESSAGE_STATUS: "COMMUNICATION_INVALID_MESSAGE_STATUS",
  INVALID_MESSAGE_TRANSITION: "COMMUNICATION_INVALID_MESSAGE_TRANSITION",
  CROSS_CONVERSATION_REPLY: "COMMUNICATION_CROSS_CONVERSATION_REPLY",
  REPLY_TARGET_NOT_FOUND: "COMMUNICATION_REPLY_TARGET_NOT_FOUND",
  READ_CURSOR_REGRESSION: "COMMUNICATION_READ_CURSOR_REGRESSION",
  INVALID_ATTACHMENT_REF: "COMMUNICATION_INVALID_ATTACHMENT_REF",
  INVALID_REACTION: "COMMUNICATION_INVALID_REACTION",
  INVALID_USER_BLOCK: "COMMUNICATION_INVALID_USER_BLOCK",
  INVALID_MESSAGE_REPORT: "COMMUNICATION_INVALID_MESSAGE_REPORT",
  INVALID_MODERATION_ACTION: "COMMUNICATION_INVALID_MODERATION_ACTION",
  PORT_OPERATION_UNIMPLEMENTED: "COMMUNICATION_PORT_OPERATION_UNIMPLEMENTED",
  // COMMS-02 Direct Messaging
  SELF_CONVERSATION_DENIED: "COMMUNICATION_SELF_CONVERSATION_DENIED",
  DIRECT_PAIR_INVALID: "COMMUNICATION_DIRECT_PAIR_INVALID",
  ACCESS_DENIED: "COMMUNICATION_ACCESS_DENIED",
  BLOCKED_PARTICIPANT: "COMMUNICATION_BLOCKED_PARTICIPANT",
  IDENTITY_INACTIVE: "COMMUNICATION_IDENTITY_INACTIVE",
  DUPLICATE_PENDING_REQUEST: "COMMUNICATION_DUPLICATE_PENDING_REQUEST",
  REQUEST_NOT_FOUND: "COMMUNICATION_REQUEST_NOT_FOUND",
  INVALID_REQUEST_TRANSITION: "COMMUNICATION_INVALID_REQUEST_TRANSITION",
  UNAUTHORIZED_REQUEST_ACTION: "COMMUNICATION_UNAUTHORIZED_REQUEST_ACTION",
  CONVERSATION_NOT_FOUND: "COMMUNICATION_CONVERSATION_NOT_FOUND",
  CONVERSATION_NOT_DIRECT: "COMMUNICATION_CONVERSATION_NOT_DIRECT",
  INACTIVE_PARTICIPANT: "COMMUNICATION_INACTIVE_PARTICIPANT",
  DUPLICATE_DIRECT_CONVERSATION: "COMMUNICATION_DUPLICATE_DIRECT_CONVERSATION",
  REQUEST_REQUIRED: "COMMUNICATION_REQUEST_REQUIRED",
});
