/**
 * CORE-12 Phase 1D-B1 — availability bridge / eligibility projection codes.
 * Capability-local. Not Venue CAA codes; not CORE-14 codes.
 */

export const AVAILABILITY_BRIDGE_CODE = Object.freeze({
  MISSING_AVAILABILITY_PROVIDER: "MISSING_AVAILABILITY_PROVIDER",
  INVALID_AVAILABILITY_QUERY: "INVALID_AVAILABILITY_QUERY",
  INVALID_TIMEZONE: "INVALID_TIMEZONE",
  INVALID_QUERY_WINDOW: "INVALID_QUERY_WINDOW",
  UNSUPPORTED_OVERNIGHT_WINDOW: "UNSUPPORTED_OVERNIGHT_WINDOW",
  MALFORMED_ELIGIBILITY_SNAPSHOT: "MALFORMED_ELIGIBILITY_SNAPSHOT",
  DUPLICATE_ELIGIBLE_COURT_ID: "DUPLICATE_ELIGIBLE_COURT_ID",
  MISSING_CANONICAL_COURT_DESCRIPTOR: "MISSING_CANONICAL_COURT_DESCRIPTOR",
  DUPLICATE_CANONICAL_COURT_DESCRIPTOR: "DUPLICATE_CANONICAL_COURT_DESCRIPTOR",
  MISSING_DESCRIPTOR_AUTHORITY: "MISSING_DESCRIPTOR_AUTHORITY",
  COURT_SCOPE_MISMATCH: "COURT_SCOPE_MISMATCH",
  COURT_NOT_ENABLED: "COURT_NOT_ENABLED",
  /** Inventory/descriptor locked flag — Phase 1D-B1 always fail-closed (no manual-lock override in projection). */
  COURT_DESCRIPTOR_LOCKED: "COURT_DESCRIPTOR_LOCKED",
  COURT_CAPABILITY_UNKNOWN: "COURT_CAPABILITY_UNKNOWN",
  COURT_CAPABILITY_MISMATCH: "COURT_CAPABILITY_MISMATCH",
  ELIGIBILITY_SCOPE_MISMATCH: "ELIGIBILITY_SCOPE_MISMATCH",
  QUERY_FINGERPRINT_MISMATCH: "QUERY_FINGERPRINT_MISMATCH",
  SNAPSHOT_FINGERPRINT_MISMATCH: "SNAPSHOT_FINGERPRINT_MISMATCH",
  EMPTY_ELIGIBILITY_RESULT: "EMPTY_ELIGIBILITY_RESULT",
  PROVIDER_REJECTED: "PROVIDER_REJECTED",
  PROVIDER_RESULT_INVALID: "PROVIDER_RESULT_INVALID",
  /** Phase 1D-B2 Option A — injected Venue eligibility dependency missing. */
  MISSING_ELIGIBILITY_PROVIDER: "MISSING_ELIGIBILITY_PROVIDER",
  /** Phase 1D-B2 Option A — injected canonical descriptor dependency missing. */
  MISSING_DESCRIPTOR_PROVIDER: "MISSING_DESCRIPTOR_PROVIDER",
  /** Phase 1D-B2 Option A — Venue descriptor envelope shape invalid. */
  MALFORMED_DESCRIPTOR_ENVELOPE: "MALFORMED_DESCRIPTOR_ENVELOPE",
  /** Phase 1D-B2 Option A — envelope descriptorAuthority pin mismatch. */
  DESCRIPTOR_AUTHORITY_MISMATCH: "DESCRIPTOR_AUTHORITY_MISMATCH",
  /** Phase 1D-B2 Option A — envelope sourceContractVersion pin mismatch. */
  DESCRIPTOR_CONTRACT_VERSION_MISMATCH: "DESCRIPTOR_CONTRACT_VERSION_MISMATCH",
  /** Phase 1D-B2 Option A — descriptor envelope scope ≠ query scope. */
  DESCRIPTOR_SCOPE_MISMATCH: "DESCRIPTOR_SCOPE_MISMATCH",
  /** Phase 1D-B2 Option A — court lacks authoritative finite priority. */
  PRIORITY_NOT_AUTHORITATIVE: "PRIORITY_NOT_AUTHORITATIVE",
});

export const AVAILABILITY_BRIDGE_CODE_VALUES = Object.freeze(
  Object.values(AVAILABILITY_BRIDGE_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isAvailabilityBridgeCode(value) {
  return AVAILABILITY_BRIDGE_CODE_VALUES.includes(
    /** @type {string} */ (value)
  );
}
