export const BATCH_F_ACTION_MATRIX = Object.freeze([
  {
    screen: "19",
    action: "Tạo thông báo / Gửi ngay / Lên lịch",
    authoritySource: "None — no tournament communication writer",
    class: "C",
    enabled: false,
    stateRule: "Chưa hỗ trợ gửi thông báo từ màn này.",
    mutationPath: null,
  },
  {
    screen: "19",
    action: "Gửi lại / Hủy",
    authoritySource: "None",
    class: "C",
    enabled: false,
    stateRule: "Chưa hỗ trợ thao tác này trong nội dung hiện tại.",
    mutationPath: null,
  },
  {
    screen: "20",
    action: "Bắt đầu / Tạm dừng / Tiếp tục trình chiếu",
    authoritySource: "Local UI session only — not persisted",
    class: "B",
    enabled: "local",
    stateRule: "Chỉ thay đổi trạng thái xem trước trên máy. Không ghi phiên phát sóng.",
    mutationPath: null,
  },
  {
    screen: "20",
    action: "Chuyển nội dung / Toàn màn hình / OBS",
    authoritySource: "Local preview only",
    class: "B",
    enabled: "local",
    stateRule: "Không kết nối thiết bị/OBS thật nếu chưa có trên hồ sơ.",
    mutationPath: null,
  },
  {
    screen: "21",
    action: "Xác nhận kết quả cuối / Công bố giải thưởng",
    authoritySource: "Existing awards engine not bound on this screen",
    class: "C",
    enabled: false,
    stateRule: "Chưa hỗ trợ ghi giải thưởng trên màn này.",
    mutationPath: null,
  },
  {
    screen: "21",
    action: "Xem trước trang công khai",
    authoritySource: "Navigate to public page",
    class: "A",
    enabled: true,
    stateRule: "Chỉ mở trang công khai.",
    mutationPath: null,
  },
  {
    screen: "22",
    action: "Hoàn tất giải đấu",
    authoritySource: "closeTournament exists but not bound here",
    class: "C",
    enabled: false,
    stateRule: "Chưa sẵn sàng hoàn tất hoặc chưa hỗ trợ trên màn này.",
    mutationPath: null,
  },
  {
    screen: "22",
    action: "Hoàn tất nội dung / Mở lại / Điều chỉnh",
    authoritySource: "None",
    class: "C",
    enabled: false,
    stateRule: "Chưa hỗ trợ thao tác này trong nội dung hiện tại.",
    mutationPath: null,
  },
  {
    screen: "23",
    action: "Đăng ký / Xem lịch / BXH / Kết quả",
    authoritySource: "Public read-only navigation",
    class: "A",
    enabled: true,
    stateRule: "Chỉ đọc dữ liệu công khai an toàn.",
    mutationPath: null,
  },
]);
