/**
 * CORE-12 Phase 1C — structured TE adapter mapping / failure codes.
 * Capability-local. No stack traces or host-specific messages.
 */

export const TE_ADAPTER_MAPPING_CODE = Object.freeze({
  MISSING_LEGACY_INPUT: "MISSING_LEGACY_INPUT",
  MISSING_MATCH_ID: "MISSING_MATCH_ID",
  MISSING_SCHEDULED_INTERVAL: "MISSING_SCHEDULED_INTERVAL",
  INVALID_SCHEDULED_INTERVAL: "INVALID_SCHEDULED_INTERVAL",
  TIMEZONE_LESS_INSTANT: "TIMEZONE_LESS_INSTANT",
  INVALID_CALENDAR_INSTANT: "INVALID_CALENDAR_INSTANT",
  MISSING_VENUE_SCOPE: "MISSING_VENUE_SCOPE",
  MISSING_TENANT_SCOPE: "MISSING_TENANT_SCOPE",
  MISSING_CLUB_SCOPE: "MISSING_CLUB_SCOPE",
  MISSING_COMPETITION_SCOPE: "MISSING_COMPETITION_SCOPE",
  MISSING_TIMEZONE: "MISSING_TIMEZONE",
  MISSING_COURT_ID: "MISSING_COURT_ID",
  MISSING_AVAILABILITY_SNAPSHOT: "MISSING_AVAILABILITY_SNAPSHOT",
  /** Court snapshot present but availabilityIntervals missing, null, or []. */
  EMPTY_COURT_AVAILABILITY: "EMPTY_COURT_AVAILABILITY",
  INVALID_AVAILABILITY_INTERVAL: "INVALID_AVAILABILITY_INTERVAL",
  AMBIGUOUS_LOCKED_ASSIGNMENT: "AMBIGUOUS_LOCKED_ASSIGNMENT",
  DUPLICATE_MATCH_ID: "DUPLICATE_MATCH_ID",
  DUPLICATE_COURT_ID: "DUPLICATE_COURT_ID",
  CROSS_SCOPE_DATA: "CROSS_SCOPE_DATA",
  UNSUPPORTED_LEGACY_SHAPE: "UNSUPPORTED_LEGACY_SHAPE",
  CONTRACT_BUILD_FAILED: "CONTRACT_BUILD_FAILED",
});

export const TE_ADAPTER_MAPPING_CODE_VALUES = Object.freeze(
  Object.values(TE_ADAPTER_MAPPING_CODE)
);

/**
 * @param {string} code
 * @param {string} message
 * @param {Record<string, unknown>} [details]
 */
export function createTeAdapterMappingFailure(code, message, details = {}) {
  return Object.freeze({
    code: String(code),
    message: String(message),
    details: Object.freeze({ ...details }),
  });
}
