/**
 * Competition Core public API — CC-01 foundation layer.
 * Importing this module MUST NOT trigger database writes or legacy engine execution.
 */

export {
  COMPETITION_CORE_VERSION,
  DRAW_MODE,
  DRAW_MODE_VALUES,
  isDrawMode,
  COMPETITION_RATING_STATUS,
  COMPETITION_RATING_STATUS_VALUES,
  isCompetitionRatingStatus,
  RATING_SOURCE,
  RATING_SOURCE_VALUES,
  isRatingSource,
  CONSTRAINT_SEVERITY,
  CONSTRAINT_SEVERITY_VALUES,
  isConstraintSeverity,
  CONSTRAINT_SCOPE,
  CONSTRAINT_SCOPE_VALUES,
  isConstraintScope,
  RULE_SET_STATUS,
  RULE_SET_STATUS_VALUES,
  isRuleSetStatus,
  COMPETITION_CONSTRAINT_TYPE,
  COMPETITION_CONSTRAINT_TYPE_VALUES,
  isCompetitionConstraintType,
  COMPETITION_ENGINE_TYPE,
  COMPETITION_ENGINE_TYPE_VALUES,
  isCompetitionEngineType,
  ENGINE_RUN_STATUS,
  ENGINE_RUN_STATUS_VALUES,
  isEngineRunStatus,
  RATING_ELIGIBILITY_STATUS,
  RATING_ELIGIBILITY_STATUS_VALUES,
  isRatingEligibilityStatus,
} from "./constants/index.js";

export {
  COMPETITION_CORE_FLAG_KEYS,
  getCompetitionCoreFeatureFlags,
  isCompetitionCoreEnabled,
  isRatingV2Enabled,
  isConstraintsV2Enabled,
  isRulesV2Enabled,
  isDrawV2Enabled,
  isMatchmakingV2Enabled,
  isStandingsV2Enabled,
} from "./config/featureFlags.js";

export { resolveRulesV2Flag, RULES_V2_ENV_KEYS } from "./config/rulesV2FlagReader.js";

export { parseEnvBoolean, readEnvBoolean, readEnvString } from "./config/envReader.js";

export {
  createEngineValidationResult,
  createEngineScoreBreakdown,
  createEngineExplanation,
  createEngineRunMetadata,
  createCompetitionEngineInput,
  createCompetitionEngineResult,
  createRatingSnapshot,
  createDrawConfiguration,
  createConstraintDefinition,
  createConstraintConflict,
} from "./contracts/engineContracts.js";

export {
  LEGACY_ENGINE_IDS,
  isEngineV2Available,
  isEngineV2FlagEnabled,
  resolveEngineExecutionPlan,
  wrapLegacyEngineResult,
  executeCompetitionEngine,
} from "./adapters/legacyAdapter.js";

export {
  LEGACY_OPEN_TERMINOLOGY,
  findLegacyTerminologyEntry,
  previewCanonicalDrawModeFromLegacy,
} from "./utils/legacyTerminology.js";

export {
  cloneCompetitionEngineInput,
  isBusinessPayloadPreserved,
} from "./utils/inputClone.js";

export {
  mapCompetitionEloToSkill,
  mapSkillToCompetitionElo,
  mapLegacySkillToInitialElo,
  isMatchRatingEligible,
  resolveKFactor,
  getPlayerCompetitionElo,
  buildRatingSnapshotFromPlayer,
  backfillPlayerRatingV2Fields,
  applyCompetitionEloFromMatchRecord,
  backfillClubPlayerRatingsV2,
  assessMonthlyPublicLevelV2,
} from "./rating/index.js";

export {
  RULE_ERROR_CODE,
  RULE_ENGINE_VERSION,
  RULE_SOFT_SCORE,
  DEFAULT_RULE_SET_ID,
  DEFAULT_RULE_SET_VERSION,
  createRuleSet,
  normalizeRuleSet,
  normalizeRuleDefinition,
  detectConstraintConflicts,
  preflightRuleSet,
  evaluateCanonicalRules,
  evaluateCandidate,
  evaluateHardRules,
  validateHardConstraints,
  validateEligibility,
  scoreSoftRules,
  scoreSoftConstraints,
  normalizeInput,
  resolveContext,
  expandApplicableRules,
  selectRuleSetVersion,
  aggregateResult,
  buildExplanation,
  createConstraintExplanation,
  validateRuleSetLifecycle,
  evaluateLegacyRulesBridge,
  evaluateLegacyPairingConstraints,
  evaluateLegacyAiPairScore,
  evaluateLegacyDailyPlayPlayer,
  evaluateLegacyCourtEngineRules,
  createDecisionTrace,
  summarizeDecisionTrace,
} from "./constraints/index.js";

export {
  DRAW_ENGINE_VERSION,
  DEFAULT_DRAW_RULE_SET_VERSION,
  CANONICAL_DRAW_MODE,
  CANONICAL_DRAW_MODE_VALUES,
  isCanonicalDrawMode,
  DRAW_SEED_SOURCE,
  DRAW_SEED_SOURCE_VALUES,
  isDrawSeedSource,
  DRAW_STRATEGY_KIND,
  DRAW_STRATEGY_KIND_VALUES,
  isDrawStrategyKind,
  DRAW_CONSTRAINT_CATEGORY,
  DRAW_CONSTRAINT_CATEGORY_VALUES,
  isDrawConstraintCategory,
  DRAW_RANDOM_GENERATOR,
  DRAW_RANDOM_GENERATOR_VALUES,
  isDrawRandomGenerator,
  CC01_DRAW_MODE_TO_CANONICAL,
  LEGACY_DRAW_MODE_MAPPINGS,
  mapLegacyDrawModeToCanonical,
  mapCc01DrawModeToCanonical,
  createDrawSeed,
  createDrawGroup,
  createDrawCandidate,
  createDrawConstraint,
  createDrawExplanation,
  createDrawConflict,
  createDrawScoreBreakdown,
  createDrawRandomMetadata,
  createDrawStrategy,
  createDrawMetadata,
  createDrawAudit,
  createDrawRequest,
  createDrawResult,
  createDrawEngineResult,
  validateDrawRequestShape,
  validateDrawResultShape,
  cloneDrawRequest,
  serializeDrawContract,
  createSeedStrategy,
  createDistributionStrategy,
  createConstraintStrategy,
  createBalancingStrategy,
  createRandomStrategy,
  createAuditStrategy,
  createExplainStrategy,
  createDefaultDrawStrategyBundle,
  createManualDrawSeed,
  createAverageLevelDrawSeed,
  createCompetitionEloDrawSeed,
  createWinRateDrawSeed,
  createPerformanceDrawSeed,
  createProvisionalDrawSeed,
  createNewPlayerDrawSeed,
  createManualAdjustmentDrawSeed,
  normalizeDrawSeeds,
  DRAW_STRATEGY_ENGINE_VERSION,
  DISTRIBUTION_TYPE,
  DISTRIBUTION_TYPE_VALUES,
  isDistributionType,
  CANONICAL_DRAW_STRATEGY_ID,
  CANONICAL_DRAW_STRATEGY_ID_VALUES,
  isCanonicalDrawStrategyId,
  DEFAULT_STRATEGY_CAPABILITIES,
  CANONICAL_DRAW_STRATEGY_CATALOG,
  LEGACY_DRAW_STRATEGY_INVENTORY,
  mapLegacyStrategyKeyToCatalogId,
  getDrawStrategyFromCatalog,
  createDrawStrategyDefinition,
  createStrategyDrawConfiguration,
  createStrategySelection,
  createDistributionPolicy,
  createConstraintPolicy,
  createBalancePolicy,
  createSeedPolicy,
  createDrawPlacement,
  createDistributionStep,
  createStrategyDrawAudit,
  createStrategyDrawRequest,
  createStrategyDrawResult,
  createStrategyDrawExplanation,
  validateStrategyDrawRequestShape,
  validateStrategyDrawResultShape,
  cloneStrategyDrawRequest,
  serializeStrategyDrawContract,
  selectDrawStrategy,
  deriveDefaultPoliciesFromStrategy,
  buildFoundationStrategyDrawResult,
  DRAW_RUNTIME_ADAPTER_VERSION,
  LEGACY_DRAW_RUNTIME_INVENTORY,
  buildDrawRuntimeCallGraph,
  findDrawRuntimeInventoryByFunction,
  mapLegacyDrawPayloadToDrawRequest,
  mapLegacyDrawPayloadToStrategyDrawRequest,
  mapCompetitionEngineInputToDrawRequest,
  cloneLegacyDrawPayload,
  isLegacyDrawPayloadPreserved,
  mapLegacyGroupToDrawGroup,
  mapLegacyGroupsToDrawGroups,
  mapDrawGroupToLegacyGroup,
  mapDrawGroupsToLegacyGroups,
  mapLegacyDrawResultToDrawResult,
  adaptDrawResultForLegacyConsumer,
  mapDrawResultToStrategyDrawResult,
  isLegacyDrawOutputPreserved,
  createDrawDecisionTrace,
  createDrawDecisionTraceRecord,
  appendDrawDecisionTrace,
  buildDrawDecisionPath,
  summarizeDrawDecisionTrace,
  resolveDrawEnvSource,
  evaluateCanonicalDraw,
  runLegacyDrawWithCanonicalAdapter,
  extractDrawGroupMembership,
  wrapTeamDrawLegacyResult,
  unwrapTeamDrawLegacyResult,
  buildTeamDrawLegacyPayload,
  runTeamDrawWithCanonicalAdapter,
  runDirectTeamDraw,
  compareDrawShadowParity,
  runDrawShadowComparison,
  compareSeedShadowParity,
  buildLegacySeedRowsFromOrder,
  buildCompleteDrawTraceRecord,
  isDrawTraceJsonSerializable,
  validateCompleteDrawTraceRecord,
} from "./draw/index.js";

export {
  SEED_ENGINE_VERSION,
  DEFAULT_SEED_RULE_SET_VERSION,
  CANONICAL_SEED_SOURCE,
  CANONICAL_SEED_SOURCE_VALUES,
  isCanonicalSeedSource,
  SEED_PIPELINE_STAGE,
  SEED_TIEBREAK_KIND,
  SEED_TIEBREAK_KIND_VALUES,
  isSeedTieBreakKind,
  DEFAULT_SEED_SCORE_WEIGHTS,
  DEFAULT_SEED_TIEBREAK_ORDER,
  DRAW_SEED_SOURCE_TO_CANONICAL,
  LEGACY_SEED_SOURCE_MAPPINGS,
  mapLegacySeedSourceToCanonical,
  listLegacySeedSourceKeys,
  computeReferenceSeedScoreComponents,
  resolveReferenceRatingSource,
  buildReferenceSeedReason,
  estimateReferenceSeedConfidence,
  applySeedTieBreakKind,
  compareParticipantsWithTieBreak,
  sortParticipantsForSeedRank,
  normalizeSeedParticipants,
  resolveSeedAdjustments,
  runCanonicalSeedPipeline,
  createSeedAdjustment,
  createSeedScoreComponents,
  createCanonicalSeedObject,
  createSeedComputation,
  createSeedExplanation,
  createSeedTieBreak,
  createSeedAudit,
  createSeedRequest,
  createSeedResult,
  validateSeedRequestShape,
  validateSeedResultShape,
  cloneSeedRequest,
  serializeSeedContract,
} from "./seed/index.js";

export {
  FORMATION_ENGINE_VERSION,
  DEFAULT_FORMATION_RULE_SET_VERSION,
  FORMATION_STRATEGY,
  FORMATION_STRATEGY_VALUES,
  isFormationStrategy,
  FORMATION_CONSTRAINT_KIND,
  FORMATION_CONSTRAINT_KIND_VALUES,
  isFormationConstraintKind,
  DEFAULT_FORMATION_SCORE_WEIGHTS,
  CANONICAL_FORMATION_STRATEGY_CATALOG,
  LEGACY_FORMATION_STRATEGY_INVENTORY,
  mapLegacyFormationStrategyToCanonical,
  getFormationStrategyFromCatalog,
  createFormationStrategyDefinition,
  mapLegacyFormationConstraintKind,
  computeReferenceFormationScoreComponents,
  buildFormationScoreBreakdown,
  createFormationPolicy,
  createFormationConstraint,
  createFormationPair,
  createFormationCourt,
  createFormationRound,
  createFormationExplanation,
  createFormationDecisionExplanation,
  createFormationCandidate,
  createFormationDecisionTraceRecord,
  createFormationDecisionTrace,
  appendFormationDecisionTrace,
  createFormationAudit,
  createFormationRequest,
  createFormationResult,
  validateFormationRequestShape,
  validateFormationResultShape,
  cloneFormationRequest,
  serializeFormationContract,
  resolveFormationStrategyFromRequest,
  buildFoundationFormationResult,
  mapLegacyFormationPayloadToFormationRequest,
  mapCompetitionEngineInputToFormationRequest,
  cloneLegacyFormationPayload,
  isTeamFormationEngineType,
} from "./formation/index.js";
