/**
 * CORE-20 — competition audit event type taxonomy.
 *
 * Workflow types are namespaced `WORKFLOW.*` mappings of CORE-19
 * WORKFLOW_EVENT_TYPE values. CORE-19 vocabulary is not mutated.
 */

export const AUDIT_EVENT_TYPE = Object.freeze({
  WORKFLOW_TRANSITION_REQUESTED: "WORKFLOW.TRANSITION_REQUESTED",
  WORKFLOW_TRANSITION_AUTHORIZED: "WORKFLOW.TRANSITION_AUTHORIZED",
  WORKFLOW_TRANSITION_DENIED: "WORKFLOW.TRANSITION_DENIED",
  WORKFLOW_TRANSITION_STARTED: "WORKFLOW.TRANSITION_STARTED",
  WORKFLOW_TRANSITION_COMPLETED: "WORKFLOW.TRANSITION_COMPLETED",
  WORKFLOW_TRANSITION_FAILED: "WORKFLOW.TRANSITION_FAILED",
  WORKFLOW_PAUSED: "WORKFLOW.WORKFLOW_PAUSED",
  WORKFLOW_RESUMED: "WORKFLOW.WORKFLOW_RESUMED",
  WORKFLOW_RESTARTED: "WORKFLOW.WORKFLOW_RESTARTED",
  WORKFLOW_COMPLETED: "WORKFLOW.WORKFLOW_COMPLETED",
  WORKFLOW_FAILED: "WORKFLOW.WORKFLOW_FAILED",
});

/** @type {ReadonlySet<string>} */
export const AUDIT_EVENT_TYPE_VALUES = new Set(Object.values(AUDIT_EVENT_TYPE));

/**
 * Map CORE-19 WORKFLOW_EVENT_TYPE → CORE-20 AUDIT_EVENT_TYPE.
 * @type {Readonly<Record<string, string>>}
 */
export const WORKFLOW_EVENT_TYPE_TO_AUDIT = Object.freeze({
  TRANSITION_REQUESTED: AUDIT_EVENT_TYPE.WORKFLOW_TRANSITION_REQUESTED,
  TRANSITION_AUTHORIZED: AUDIT_EVENT_TYPE.WORKFLOW_TRANSITION_AUTHORIZED,
  TRANSITION_DENIED: AUDIT_EVENT_TYPE.WORKFLOW_TRANSITION_DENIED,
  TRANSITION_STARTED: AUDIT_EVENT_TYPE.WORKFLOW_TRANSITION_STARTED,
  TRANSITION_COMPLETED: AUDIT_EVENT_TYPE.WORKFLOW_TRANSITION_COMPLETED,
  TRANSITION_FAILED: AUDIT_EVENT_TYPE.WORKFLOW_TRANSITION_FAILED,
  WORKFLOW_PAUSED: AUDIT_EVENT_TYPE.WORKFLOW_PAUSED,
  WORKFLOW_RESUMED: AUDIT_EVENT_TYPE.WORKFLOW_RESUMED,
  WORKFLOW_RESTARTED: AUDIT_EVENT_TYPE.WORKFLOW_RESTARTED,
  WORKFLOW_COMPLETED: AUDIT_EVENT_TYPE.WORKFLOW_COMPLETED,
  WORKFLOW_FAILED: AUDIT_EVENT_TYPE.WORKFLOW_FAILED,
});

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isAuditEventType(value) {
  return typeof value === "string" && AUDIT_EVENT_TYPE_VALUES.has(value);
}

/**
 * @param {unknown} workflowEventType
 * @returns {string|null}
 */
export function mapWorkflowEventTypeToAudit(workflowEventType) {
  if (typeof workflowEventType !== "string") return null;
  return WORKFLOW_EVENT_TYPE_TO_AUDIT[workflowEventType] || null;
}
