import { COMPETITION_CONSTRAINT_TYPE } from "../constants/constraintType.js";
import { CONSTRAINT_SEVERITY } from "../constants/constraintSeverity.js";
import { DEFAULT_SEVERITY_BY_CONSTRAINT_TYPE } from "./ruleConstants.js";

/**
 * Explicit hard evaluation coverage — every hard-severity active rule must hit
 * one of these or emit UNSUPPORTED_CONSTRAINT_EVALUATION (never silent default).
 */
export const SUPPORTED_HARD_CONSTRAINT_TYPES = Object.freeze([
  COMPETITION_CONSTRAINT_TYPE.MUST_PARTNER,
  COMPETITION_CONSTRAINT_TYPE.MUST_NOT_PARTNER,
  COMPETITION_CONSTRAINT_TYPE.PREFER_PARTNER,
  COMPETITION_CONSTRAINT_TYPE.AVOID_PARTNER,
  COMPETITION_CONSTRAINT_TYPE.MUST_OPPONENT,
  COMPETITION_CONSTRAINT_TYPE.MUST_NOT_OPPONENT,
  COMPETITION_CONSTRAINT_TYPE.PREFER_OPPONENT,
  COMPETITION_CONSTRAINT_TYPE.AVOID_OPPONENT,
  COMPETITION_CONSTRAINT_TYPE.GENDER_ELIGIBILITY,
  COMPETITION_CONSTRAINT_TYPE.MIXED_TEAM_COMPOSITION,
  COMPETITION_CONSTRAINT_TYPE.SKILL_CAP,
  COMPETITION_CONSTRAINT_TYPE.TEAM_SKILL_DIFFERENCE,
  COMPETITION_CONSTRAINT_TYPE.CHECKIN_REQUIRED,
  COMPETITION_CONSTRAINT_TYPE.AVAILABILITY_REQUIRED,
  COMPETITION_CONSTRAINT_TYPE.PLAYER_NOT_BUSY,
  COMPETITION_CONSTRAINT_TYPE.LINEUP_VALIDITY,
  COMPETITION_CONSTRAINT_TYPE.ENTRY_ELIGIBILITY,
  COMPETITION_CONSTRAINT_TYPE.SAME_CLUB_SEPARATION,
  COMPETITION_CONSTRAINT_TYPE.SAME_ORGANIZATION_SEPARATION,
  COMPETITION_CONSTRAINT_TYPE.SAME_GROUP,
  COMPETITION_CONSTRAINT_TYPE.DIFFERENT_GROUP,
  COMPETITION_CONSTRAINT_TYPE.SAME_TEAM,
  COMPETITION_CONSTRAINT_TYPE.DIFFERENT_TEAM,
  COMPETITION_CONSTRAINT_TYPE.MAX_PARTNER_REPEAT,
  COMPETITION_CONSTRAINT_TYPE.MAX_OPPONENT_REPEAT,
  COMPETITION_CONSTRAINT_TYPE.MIN_PARTNER_REPEAT,
  COMPETITION_CONSTRAINT_TYPE.MIN_OPPONENT_REPEAT,
  COMPETITION_CONSTRAINT_TYPE.MIN_REST_TIME,
]);

/**
 * Explicit soft scoring coverage — unknown soft types emit a scored note
 * with UNSUPPORTED_CONSTRAINT_EVALUATION (score delta 0, never silent).
 */
export const SUPPORTED_SOFT_CONSTRAINT_TYPES = Object.freeze([
  COMPETITION_CONSTRAINT_TYPE.PREFER_PARTNER,
  COMPETITION_CONSTRAINT_TYPE.AVOID_PARTNER,
  COMPETITION_CONSTRAINT_TYPE.PREFER_OPPONENT,
  COMPETITION_CONSTRAINT_TYPE.AVOID_OPPONENT,
  COMPETITION_CONSTRAINT_TYPE.SKILL_CAP,
  COMPETITION_CONSTRAINT_TYPE.TEAM_SKILL_DIFFERENCE,
  COMPETITION_CONSTRAINT_TYPE.SAME_CLUB_SEPARATION,
  COMPETITION_CONSTRAINT_TYPE.SAME_ORGANIZATION_SEPARATION,
  COMPETITION_CONSTRAINT_TYPE.SAME_GROUP,
  COMPETITION_CONSTRAINT_TYPE.DIFFERENT_GROUP,
  COMPETITION_CONSTRAINT_TYPE.SAME_TEAM,
  COMPETITION_CONSTRAINT_TYPE.DIFFERENT_TEAM,
  COMPETITION_CONSTRAINT_TYPE.MAX_PARTNER_REPEAT,
  COMPETITION_CONSTRAINT_TYPE.MAX_OPPONENT_REPEAT,
  COMPETITION_CONSTRAINT_TYPE.MIN_PARTNER_REPEAT,
  COMPETITION_CONSTRAINT_TYPE.MIN_OPPONENT_REPEAT,
  COMPETITION_CONSTRAINT_TYPE.MIN_REST_TIME,
]);

const HARD_SET = new Set(SUPPORTED_HARD_CONSTRAINT_TYPES);
const SOFT_SET = new Set(SUPPORTED_SOFT_CONSTRAINT_TYPES);

/**
 * @param {string} type
 * @param {string} [severity]
 * @returns {boolean}
 */
export function isConstraintTypeEvaluated(type, severity) {
  const resolved =
    severity ||
    DEFAULT_SEVERITY_BY_CONSTRAINT_TYPE[type] ||
    CONSTRAINT_SEVERITY.SOFT;
  if (resolved === CONSTRAINT_SEVERITY.HARD) {
    return HARD_SET.has(type);
  }
  return SOFT_SET.has(type);
}

/**
 * Types that need match/opponent geometry (two competing sides).
 */
export const OPPONENT_GEOMETRY_TYPES = Object.freeze([
  COMPETITION_CONSTRAINT_TYPE.MUST_OPPONENT,
  COMPETITION_CONSTRAINT_TYPE.MUST_NOT_OPPONENT,
  COMPETITION_CONSTRAINT_TYPE.PREFER_OPPONENT,
  COMPETITION_CONSTRAINT_TYPE.AVOID_OPPONENT,
  COMPETITION_CONSTRAINT_TYPE.MAX_OPPONENT_REPEAT,
  COMPETITION_CONSTRAINT_TYPE.MIN_OPPONENT_REPEAT,
]);

/**
 * Types that need group assignment geometry.
 */
export const GROUP_GEOMETRY_TYPES = Object.freeze([
  COMPETITION_CONSTRAINT_TYPE.SAME_GROUP,
  COMPETITION_CONSTRAINT_TYPE.DIFFERENT_GROUP,
  COMPETITION_CONSTRAINT_TYPE.SAME_CLUB_SEPARATION,
  COMPETITION_CONSTRAINT_TYPE.SAME_ORGANIZATION_SEPARATION,
]);
