/**
 * Phase 2C — production Referee UI constants.
 * Projection / UX only. Not assignment, scoring, or result authority.
 */

export const REFEREE_PRODUCTION_UI_ID = "referee-one-canonical-production-ui-01";

export const COURT_ORIENTATION = Object.freeze({
  STANDARD: "STANDARD",
  SWAPPED: "SWAPPED",
});

export const COURT_SLOT = Object.freeze({
  LEFT_TOP: "leftTop",
  LEFT_BOTTOM: "leftBottom",
  RIGHT_TOP: "rightTop",
  RIGHT_BOTTOM: "rightBottom",
});

export const ASSIGNMENT_CARD_ACTION = Object.freeze({
  ENTER: "ENTER",
  CONTINUE: "CONTINUE",
  VIEW_RESULT: "VIEW_RESULT",
});

export const ASSIGNMENT_CARD_ACTION_LABEL = Object.freeze({
  ENTER: "VÀO TRẬN",
  CONTINUE: "TIẾP TỤC",
  VIEW_RESULT: "XEM KẾT QUẢ",
});

export const RESULT_STATUS = Object.freeze({
  NONE: "NONE",
  CALCULATED_SCORE: "CALCULATED_SCORE",
  MATCH_COMPLETED: "MATCH_COMPLETED",
  PENDING_ACCEPTANCE: "PENDING_ACCEPTANCE",
  ACCEPTED_OFFICIAL: "ACCEPTED_OFFICIAL",
  CORRECTION_REQUIRED: "CORRECTION_REQUIRED",
  REJECTED: "REJECTED",
});

export const CANONICAL_UI_COMMAND = Object.freeze({
  ACKNOWLEDGE: "ACKNOWLEDGE",
  OPEN: "OPEN",
  START_SCORE_SESSION: "START_SCORE_SESSION",
  SUBMIT_POINT: "SUBMIT_POINT",
  UNDO_LAST_SCORING_ACTION: "UNDO_LAST_SCORING_ACTION",
  SUSPEND: "SUSPEND",
  RESUME: "RESUME",
  CHANGE_ENDS: "CHANGE_ENDS",
  SWITCH_POSITIONS: "SWITCH_POSITIONS",
  SUBMIT_RESULT: "SUBMIT_RESULT",
  CORRECT_RESULT: "CORRECT_RESULT",
});

export const REFEREE_UI_ERROR_CODE = Object.freeze({
  DUPLICATE_ACTION_BLOCKED: "REFEREE_UI_DUPLICATE_ACTION_BLOCKED",
  LOCATION_STATE_FORBIDDEN: "REFEREE_UI_LOCATION_STATE_FORBIDDEN",
  FIXTURE_FALLBACK_FORBIDDEN: "REFEREE_UI_FIXTURE_FALLBACK_FORBIDDEN",
  COMMAND_UNAVAILABLE: "REFEREE_UI_COMMAND_UNAVAILABLE",
  MATCH_SCOPE_UNRESOLVED: "REFEREE_UI_MATCH_SCOPE_UNRESOLVED",
  STALE_STATE: "REFEREE_UI_STALE_STATE",
});

export const PRODUCTION_FORBIDDEN_IMPORTS = Object.freeze([
  "refereeV5PrototypeFixtures",
  "refereeV5StagingFixtures",
  "createLiveRpcCanonicalRefereeDurableDriver",
  "getSupabaseAdminClient",
  "SERVICE_ROLE",
]);
