/** Stable validation codes — do not rely on Vietnamese messages in tests. */
export const PRIVATE_PAIRING_VALIDATION_CODE = Object.freeze({
  MISSING_CONSTRAINT_TYPE: "MISSING_CONSTRAINT_TYPE",
  UNSUPPORTED_CONSTRAINT_TYPE: "UNSUPPORTED_CONSTRAINT_TYPE",
  MISSING_PRIMARY_PLAYER: "MISSING_PRIMARY_PLAYER",
  EMPTY_TARGET_LIST: "EMPTY_TARGET_LIST",
  SELF_TARGET_NOT_ALLOWED: "SELF_TARGET_NOT_ALLOWED",
  DUPLICATE_TARGET: "DUPLICATE_TARGET",
  INVALID_SEVERITY: "INVALID_SEVERITY",
  INVALID_WEIGHT: "INVALID_WEIGHT",
  HARD_WEIGHT_SIMULATION_NOT_ALLOWED: "HARD_WEIGHT_SIMULATION_NOT_ALLOWED",
  INVALID_PRIORITY: "INVALID_PRIORITY",
  INVALID_RELATION_MODE: "INVALID_RELATION_MODE",
  RELATION_MODE_NOT_COMPATIBLE: "RELATION_MODE_NOT_COMPATIBLE",
  INVALID_SCOPE_TYPE: "INVALID_SCOPE_TYPE",
  SCOPE_ID_REQUIRED: "SCOPE_ID_REQUIRED",
  INVALID_TIME_RANGE: "INVALID_TIME_RANGE",
  RULE_EXPIRED: "RULE_EXPIRED",
  ALL_OF_EXCEEDS_TEAM_CAPACITY: "ALL_OF_EXCEEDS_TEAM_CAPACITY",
  INVALID_VISIBILITY: "INVALID_VISIBILITY",
  INVALID_REASON_CATEGORY: "INVALID_REASON_CATEGORY",
  REASON_TEXT_REQUIRED: "REASON_TEXT_REQUIRED",
  PLAYER_NOT_IN_SCOPE: "PLAYER_NOT_IN_SCOPE",
  PLAYER_NOT_FOUND: "PLAYER_NOT_FOUND",
  PRIVATE_RULE_NOT_ALLOWED_IN_CERTIFIED_EVENT: "PRIVATE_RULE_NOT_ALLOWED_IN_CERTIFIED_EVENT",
  CONSTRAINT_TYPE_NOT_SUPPORTED_IN_CONTEXT: "CONSTRAINT_TYPE_NOT_SUPPORTED_IN_CONTEXT",
});

/** Stable conflict codes for detector results. */
export const PRIVATE_PAIRING_CONFLICT_CODE = Object.freeze({
  MUST_AND_MUST_NOT_PARTNER: "MUST_AND_MUST_NOT_PARTNER",
  MUST_AND_MUST_NOT_OPPONENT: "MUST_AND_MUST_NOT_OPPONENT",
  PARTNER_AND_OPPONENT_CONFLICT: "PARTNER_AND_OPPONENT_CONFLICT",
  TEAM_CAPACITY_EXCEEDED: "TEAM_CAPACITY_EXCEEDED",
  IMPOSSIBLE_PARTNER_CHAIN: "IMPOSSIBLE_PARTNER_CHAIN",
  HARD_RULE_OVERRIDES_SOFT_RULE: "HARD_RULE_OVERRIDES_SOFT_RULE",
  SOFT_SOFT_OPPOSITE_PREFERENCE: "SOFT_SOFT_OPPOSITE_PREFERENCE",
  OVERLAPPING_RULES: "OVERLAPPING_RULES",
  CERTIFIED_EVENT_POLICY_CONFLICT: "CERTIFIED_EVENT_POLICY_CONFLICT",
  DUPLICATE_RULE_ID: "DUPLICATE_RULE_ID",
});

export const FEATURE_FLAG_KEYS = Object.freeze({
  PRIVATE_PAIRING_RULES: "VITE_PRIVATE_PAIRING_RULES_ENABLED",
  UNIFIED_CONSTRAINT_ENGINE: "VITE_UNIFIED_CONSTRAINT_ENGINE_ENABLED",
});

/**
 * @param {Record<string, unknown>|undefined|null} [envSource]
 * @param {string} key
 * @returns {boolean}
 */
export function readFlag(envSource, key) {
  const source = envSource || (typeof import.meta !== "undefined" ? import.meta.env : {});
  const raw = source?.[key];
  return raw === true || raw === "true" || raw === "1";
}

/**
 * @param {Record<string, unknown>|undefined|null} [envSource]
 * @returns {boolean}
 */
export function isPrivatePairingRulesEnabled(envSource) {
  return readFlag(envSource, FEATURE_FLAG_KEYS.PRIVATE_PAIRING_RULES);
}

/**
 * @param {Record<string, unknown>|undefined|null} [envSource]
 * @returns {boolean}
 */
export function isUnifiedConstraintEngineEnabled(envSource) {
  return readFlag(envSource, FEATURE_FLAG_KEYS.UNIFIED_CONSTRAINT_ENGINE);
}
