import {
  COMPETITION_CONSTRAINT_TYPE,
  isCompetitionConstraintType,
} from "../../competition-core/constants/constraintType.js";

/**
 * Private Pairing Rules V2 uses Competition Core canonical types (no duplicate names).
 * This set is the subset applicable to private pairing configuration.
 */
export const PRIVATE_PAIRING_CONSTRAINT_TYPE = Object.freeze({
  PREFER_PARTNER: COMPETITION_CONSTRAINT_TYPE.PREFER_PARTNER,
  MUST_PARTNER: COMPETITION_CONSTRAINT_TYPE.MUST_PARTNER,
  AVOID_PARTNER: COMPETITION_CONSTRAINT_TYPE.AVOID_PARTNER,
  MUST_NOT_PARTNER: COMPETITION_CONSTRAINT_TYPE.MUST_NOT_PARTNER,
  PREFER_OPPONENT: COMPETITION_CONSTRAINT_TYPE.PREFER_OPPONENT,
  MUST_OPPONENT: COMPETITION_CONSTRAINT_TYPE.MUST_OPPONENT,
  AVOID_OPPONENT: COMPETITION_CONSTRAINT_TYPE.AVOID_OPPONENT,
  MUST_NOT_OPPONENT: COMPETITION_CONSTRAINT_TYPE.MUST_NOT_OPPONENT,
  MAX_PARTNER_REPEAT: COMPETITION_CONSTRAINT_TYPE.MAX_PARTNER_REPEAT,
  MAX_OPPONENT_REPEAT: COMPETITION_CONSTRAINT_TYPE.MAX_OPPONENT_REPEAT,
  MIN_PARTNER_REPEAT: COMPETITION_CONSTRAINT_TYPE.MIN_PARTNER_REPEAT,
  MIN_OPPONENT_REPEAT: COMPETITION_CONSTRAINT_TYPE.MIN_OPPONENT_REPEAT,
  SAME_GROUP: COMPETITION_CONSTRAINT_TYPE.SAME_GROUP,
  DIFFERENT_GROUP: COMPETITION_CONSTRAINT_TYPE.DIFFERENT_GROUP,
  SAME_TEAM: COMPETITION_CONSTRAINT_TYPE.SAME_TEAM,
  DIFFERENT_TEAM: COMPETITION_CONSTRAINT_TYPE.DIFFERENT_TEAM,
});

/** @type {ReadonlySet<string>} */
export const PRIVATE_PAIRING_CONSTRAINT_TYPE_VALUES = new Set(
  Object.values(PRIVATE_PAIRING_CONSTRAINT_TYPE)
);

export const PERSONAL_PREFERENCE_CONSTRAINT_TYPES = Object.freeze([
  PRIVATE_PAIRING_CONSTRAINT_TYPE.PREFER_PARTNER,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MUST_PARTNER,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.PREFER_OPPONENT,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MUST_OPPONENT,
]);

export const TYPES_REQUIRING_PRIMARY_AND_TARGETS = Object.freeze([
  PRIVATE_PAIRING_CONSTRAINT_TYPE.PREFER_PARTNER,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MUST_PARTNER,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.AVOID_PARTNER,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MUST_NOT_PARTNER,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.PREFER_OPPONENT,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MUST_OPPONENT,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.AVOID_OPPONENT,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MUST_NOT_OPPONENT,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.SAME_GROUP,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.DIFFERENT_GROUP,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.SAME_TEAM,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.DIFFERENT_TEAM,
]);

export const PARTNER_RELATION_TYPES = Object.freeze([
  PRIVATE_PAIRING_CONSTRAINT_TYPE.PREFER_PARTNER,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MUST_PARTNER,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.AVOID_PARTNER,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MUST_NOT_PARTNER,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.SAME_TEAM,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.DIFFERENT_TEAM,
]);

export const OPPONENT_RELATION_TYPES = Object.freeze([
  PRIVATE_PAIRING_CONSTRAINT_TYPE.PREFER_OPPONENT,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MUST_OPPONENT,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.AVOID_OPPONENT,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MUST_NOT_OPPONENT,
]);

export const REPEAT_CONSTRAINT_TYPES = Object.freeze([
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MAX_PARTNER_REPEAT,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MAX_OPPONENT_REPEAT,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MIN_PARTNER_REPEAT,
  PRIVATE_PAIRING_CONSTRAINT_TYPE.MIN_OPPONENT_REPEAT,
]);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isPrivatePairingConstraintType(value) {
  return (
    typeof value === "string" &&
    PRIVATE_PAIRING_CONSTRAINT_TYPE_VALUES.has(value) &&
    isCompetitionConstraintType(value)
  );
}
