/**
 * Translator-only: map mode/legacy match status labels → CORE-15 MATCH_STATUS.
 * Does not own lifecycle transitions.
 */

import { MATCH_STATUS } from "../../../../../competition-core/matches/index.js";

const STATUS_MAP = Object.freeze({
  DRAFT: MATCH_STATUS.DRAFT,
  READY: MATCH_STATUS.READY,
  SCHEDULED: MATCH_STATUS.SCHEDULED,
  LINEUPS_PENDING: MATCH_STATUS.LINEUPS_PENDING,
  READY_TO_START: MATCH_STATUS.READY_TO_START,
  IN_PROGRESS: MATCH_STATUS.IN_PROGRESS,
  PAUSED: MATCH_STATUS.PAUSED,
  SUSPENDED: MATCH_STATUS.SUSPENDED,
  COMPLETED: MATCH_STATUS.COMPLETED,
  CANCELLED: MATCH_STATUS.CANCELLED,
  POSTPONED: MATCH_STATUS.POSTPONED,
  // Legacy / mode labels
  WAITING: MATCH_STATUS.READY_TO_START,
  PENDING: MATCH_STATUS.SCHEDULED,
  PLAYING: MATCH_STATUS.IN_PROGRESS,
  ACTIVE: MATCH_STATUS.IN_PROGRESS,
  RUNNING: MATCH_STATUS.IN_PROGRESS,
  STARTED: MATCH_STATUS.IN_PROGRESS,
  INPROGRESS: MATCH_STATUS.IN_PROGRESS,
  DONE: MATCH_STATUS.COMPLETED,
  FINISHED: MATCH_STATUS.COMPLETED,
  PLAYED: MATCH_STATUS.COMPLETED,
  CLOSED: MATCH_STATUS.COMPLETED,
  CANCEL: MATCH_STATUS.CANCELLED,
  CANCELED: MATCH_STATUS.CANCELLED,
});

/**
 * @param {unknown} raw
 * @returns {string}
 */
export function mapModeStatusToCore15(raw) {
  const key = String(raw || "")
    .trim()
    .toUpperCase()
    .replace(/[-\s]+/g, "_");
  if (!key) return MATCH_STATUS.READY_TO_START;
  return STATUS_MAP[key] || MATCH_STATUS.READY_TO_START;
}
