export const API_ERROR_CODES = Object.freeze({
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  FEATURE_DISABLED: "FEATURE_DISABLED",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
  INSUFFICIENT_SCOPE: "INSUFFICIENT_SCOPE",
  TENANT_MISMATCH: "TENANT_MISMATCH",
});
