/**
 * Stable validation error codes for participant domain.
 */

export const PARTICIPANT_ERROR_CODE = Object.freeze({
  REQUIRED: "PARTICIPANT_REQUIRED",
  INVALID_TYPE: "PARTICIPANT_INVALID_TYPE",
  INVALID_STATUS: "PARTICIPANT_INVALID_STATUS",
  INVALID_KIND: "PARTICIPANT_INVALID_KIND",
  INVALID_SCHEMA_VERSION: "PARTICIPANT_INVALID_SCHEMA_VERSION",
  MISSING_COMPETITION_ID: "ENTRY_MISSING_COMPETITION_ID",
  DUPLICATE_ENTRY_SCOPE: "ENTRY_DUPLICATE_ACTIVE_SCOPE",
  WAITLIST_NOT_ACTIVE_ENTRY: "REGISTRATION_WAITLIST_NOT_ACTIVE_ENTRY",
  ROSTER_LOCKED_IMMUTABLE: "ROSTER_LOCKED_IMMUTABLE",
  ROSTER_DUPLICATE_MEMBER: "ROSTER_DUPLICATE_MEMBER",
  LINEUP_REVISION_INVALID: "LINEUP_REVISION_INVALID",
  LINEUP_REVISION_SEQUENCE: "LINEUP_REVISION_SEQUENCE",
  LINEUP_PREVIOUS_REVISION: "LINEUP_PREVIOUS_REVISION_INVALID",
  LINEUP_LOCKED_IMMUTABLE: "LINEUP_LOCKED_IMMUTABLE",
  LINEUP_SLOT_INVALID: "LINEUP_SLOT_INVALID",
  IDENTITY_MIXED: "IDENTITY_KINDS_MUST_NOT_MIX_AS_SAME_ID",
  SNAPSHOT_NOT_JSON_SAFE: "SNAPSHOT_NOT_JSON_SAFE",
  DIVISION_CATEGORY_COLLISION: "DIVISION_CATEGORY_MUST_REMAIN_SEPARATE",
  POLICY_CONTEXT_REQUIRED: "POLICY_CONTEXT_REQUIRED",
});
