/**
 * Phase 3F — Match Runtime error codes (capability-local).
 * Shared error-registry export is Integrator-owned — handoff only.
 */

export const MATCH_RUNTIME_ERROR_CODE = Object.freeze({
  MATCH_NOT_FOUND: "MATCH_NOT_FOUND",
  MATCH_INVALID_INPUT: "MATCH_INVALID_INPUT",
  MATCH_INVALID_SOURCE: "MATCH_INVALID_SOURCE",
  MATCH_UNSUPPORTED_SOURCE: "MATCH_UNSUPPORTED_SOURCE",
  MATCH_UNSUPPORTED_STATUS: "MATCH_UNSUPPORTED_STATUS",
  MATCH_IDENTITY_MISMATCH: "MATCH_IDENTITY_MISMATCH",
  MATCH_IDENTITY_COLLISION: "MATCH_IDENTITY_COLLISION",
  MATCH_CONTEXT_MISMATCH: "MATCH_CONTEXT_MISMATCH",
  MATCH_COMPETITION_MISMATCH: "MATCH_COMPETITION_MISMATCH",
  MATCH_SIDE_REQUIRED: "MATCH_SIDE_REQUIRED",
  MATCH_SIDE_DUPLICATE: "MATCH_SIDE_DUPLICATE",
  MATCH_PARTICIPANT_DUPLICATE: "MATCH_PARTICIPANT_DUPLICATE",
  MATCH_TEAM_DUPLICATE: "MATCH_TEAM_DUPLICATE",
  MATCH_LINEUP_MISMATCH: "MATCH_LINEUP_MISMATCH",
  MATCH_NOT_READY: "MATCH_NOT_READY",
  MATCH_ALREADY_STARTED: "MATCH_ALREADY_STARTED",
  MATCH_NOT_IN_PROGRESS: "MATCH_NOT_IN_PROGRESS",
  MATCH_ALREADY_COMPLETED: "MATCH_ALREADY_COMPLETED",
  MATCH_COMPLETED_IMMUTABLE: "MATCH_COMPLETED_IMMUTABLE",
  MATCH_STATE_TRANSITION_INVALID: "MATCH_STATE_TRANSITION_INVALID",
  MATCH_DEPENDENCY_FAILED: "MATCH_DEPENDENCY_FAILED",
  MATCH_ADAPTER_FAILED: "MATCH_ADAPTER_FAILED",
  MATCH_PERSISTENCE_DISABLED: "MATCH_PERSISTENCE_DISABLED",
});

/** @type {ReadonlySet<string>} */
export const MATCH_RUNTIME_ERROR_CODE_VALUES = new Set(
  Object.values(MATCH_RUNTIME_ERROR_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isMatchRuntimeErrorCode(value) {
  return typeof value === "string" && MATCH_RUNTIME_ERROR_CODE_VALUES.has(value);
}
