export {
  CORE12_ENGINE_ID,
  CORE12_ENGINE_VERSION,
  CORE12_COURT_ASSIGNMENT_SCHEMA_V1,
  CORE12_COMPARATOR_VERSION,
  CORE12_COURT_SELECTION_STRATEGY_VERSION,
  CORE12_FINGERPRINT_VERSION,
  CORE12_CANONICAL_SERIALIZATION_VERSION,
  CORE12_POLICY_VERSION,
  CORE12_IDENTITY,
} from "./versions.js";
