/**
 * E2E-02 typed errors — fail-closed, no silent fallback.
 */

export const E2E02_ERROR_CODE = Object.freeze({
  INVALID_TEMPLATE: "E2E02_INVALID_TEMPLATE",
  INVALID_FORMAT: "E2E02_INVALID_FORMAT",
  INVALID_COMPETITION_TYPE: "E2E02_INVALID_COMPETITION_TYPE",
  INVALID_PARTICIPANT_MODE: "E2E02_INVALID_PARTICIPANT_MODE",
  INVALID_CONFIGURATION: "E2E02_INVALID_CONFIGURATION",
  MISSING_RULE_REFERENCE: "E2E02_MISSING_RULE_REFERENCE",
  MISSING_WORKFLOW_REFERENCE: "E2E02_MISSING_WORKFLOW_REFERENCE",
  INVALID_PARTICIPANT_COUNT: "E2E02_INVALID_PARTICIPANT_COUNT",
  DUPLICATE_PARTICIPANT: "E2E02_DUPLICATE_PARTICIPANT",
  EMPTY_POOL: "E2E02_EMPTY_POOL",
  INVALID_POOL_SIZING: "E2E02_INVALID_POOL_SIZING",
  INVALID_QUALIFIER_COUNT: "E2E02_INVALID_QUALIFIER_COUNT",
  INVALID_BRACKET_SIZE: "E2E02_INVALID_BRACKET_SIZE",
  INVALID_BYE_CONFIGURATION: "E2E02_INVALID_BYE_CONFIGURATION",
  INVALID_STAGE_SEQUENCE: "E2E02_INVALID_STAGE_SEQUENCE",
  POOL_STAGE_INCOMPLETE: "E2E02_POOL_STAGE_INCOMPLETE",
  UNRESOLVED_TIE: "E2E02_UNRESOLVED_TIE",
  INVALID_RESULT: "E2E02_INVALID_RESULT",
  WITHDRAWN_OR_DISQUALIFIED: "E2E02_WITHDRAWN_OR_DISQUALIFIED",
  DUPLICATE_QUALIFIER: "E2E02_DUPLICATE_QUALIFIER",
  ODD_QUALIFIER_UNSUPPORTED: "E2E02_ODD_QUALIFIER_HANDLED",
  MISSING_TENANT: "E2E02_MISSING_TENANT",
  MISSING_COMPETITION_IDENTITY: "E2E02_MISSING_COMPETITION_IDENTITY",
  MISSING_DETERMINISTIC_SEED: "E2E02_MISSING_DETERMINISTIC_SEED",
  MISSING_INTEGRATION_PORTS: "E2E02_MISSING_INTEGRATION_PORTS",
  TEMPLATE_MUTATION_REJECTED: "E2E02_TEMPLATE_MUTATION_REJECTED",
  CORE_GENERATION_FAILED: "E2E02_CORE_GENERATION_FAILED",
  STANDINGS_FAILED: "E2E02_STANDINGS_FAILED",
  CM_INSTANTIATION_FAILED: "E2E02_CM_INSTANTIATION_FAILED",
  UNKNOWN: "E2E02_UNKNOWN",
});

export class E2E02CompositionError extends Error {
  /**
   * @param {string} code
   * @param {string} message
   * @param {Record<string, unknown>} [details]
   */
  constructor(code, message, details = {}) {
    super(message);
    this.name = "E2E02CompositionError";
    this.code =
      typeof code === "string" && code.trim()
        ? code.trim()
        : E2E02_ERROR_CODE.UNKNOWN;
    this.details = Object.freeze({ ...details });
  }
}

/**
 * @param {unknown} err
 * @returns {err is E2E02CompositionError}
 */
export function isE2E02CompositionError(err) {
  return err instanceof E2E02CompositionError;
}

/**
 * @param {string} code
 * @param {string} message
 * @param {Record<string, unknown>} [details]
 * @returns {never}
 */
export function failE2E02(code, message, details) {
  throw new E2E02CompositionError(code, message, details);
}
