/**
 * Canonical Finance error codes (Phase 1B).
 * Persistence-neutral — no HTTP mapping here.
 */

export const FINANCE_ERROR_CODES = Object.freeze({
  INVALID_MONEY: "FINANCE_INVALID_MONEY",
  UNSUPPORTED_CURRENCY: "FINANCE_UNSUPPORTED_CURRENCY",
  CURRENCY_MISMATCH: "FINANCE_CURRENCY_MISMATCH",
  INVALID_FEE_DEFINITION: "FINANCE_INVALID_FEE_DEFINITION",
  INVALID_REFERENCE: "FINANCE_INVALID_REFERENCE",
  INVALID_TRANSITION: "FINANCE_INVALID_TRANSITION",
  DUPLICATE_FINANCIAL_EFFECT: "FINANCE_DUPLICATE_FINANCIAL_EFFECT",
  IDEMPOTENCY_CONFLICT: "FINANCE_IDEMPOTENCY_CONFLICT",
  PAYMENT_EVIDENCE_REQUIRED: "FINANCE_PAYMENT_EVIDENCE_REQUIRED",
  OVERPAYMENT: "FINANCE_OVERPAYMENT",
  INVALID_REFUND_AMOUNT: "FINANCE_INVALID_REFUND_AMOUNT",
  NON_REFUNDABLE_PAYMENT: "FINANCE_NON_REFUNDABLE_PAYMENT",
  IMMUTABLE_RECORD: "FINANCE_IMMUTABLE_RECORD",
  INVALID_EVENT_PAYLOAD: "FINANCE_INVALID_EVENT_PAYLOAD",
  INVALID_INPUT: "FINANCE_INVALID_INPUT",
});

export const FINANCE_ERROR_CODE_VALUES = Object.freeze(
  Object.values(FINANCE_ERROR_CODES)
);

/**
 * @param {string} code
 * @returns {boolean}
 */
export function isFinanceErrorCode(code) {
  return FINANCE_ERROR_CODE_VALUES.includes(code);
}
