/**
 * Canonical Finance error codes (Phase 1B).
 * Persistence-neutral — no HTTP mapping here.
 */

export const FINANCE_ERROR_CODES = Object.freeze({
  INVALID_MONEY: "FINANCE_INVALID_MONEY",
  UNSUPPORTED_CURRENCY: "FINANCE_UNSUPPORTED_CURRENCY",
  CURRENCY_MISMATCH: "FINANCE_CURRENCY_MISMATCH",
  INVALID_FEE_DEFINITION: "FINANCE_INVALID_FEE_DEFINITION",
  INVALID_REFERENCE: "FINANCE_INVALID_REFERENCE",
  INVALID_TRANSITION: "FINANCE_INVALID_TRANSITION",
  DUPLICATE_FINANCIAL_EFFECT: "FINANCE_DUPLICATE_FINANCIAL_EFFECT",
  IDEMPOTENCY_CONFLICT: "FINANCE_IDEMPOTENCY_CONFLICT",
  PAYMENT_EVIDENCE_REQUIRED: "FINANCE_PAYMENT_EVIDENCE_REQUIRED",
  OVERPAYMENT: "FINANCE_OVERPAYMENT",
  INVALID_REFUND_AMOUNT: "FINANCE_INVALID_REFUND_AMOUNT",
  NON_REFUNDABLE_PAYMENT: "FINANCE_NON_REFUNDABLE_PAYMENT",
  IMMUTABLE_RECORD: "FINANCE_IMMUTABLE_RECORD",
  INVALID_EVENT_PAYLOAD: "FINANCE_INVALID_EVENT_PAYLOAD",
  INVALID_INPUT: "FINANCE_INVALID_INPUT",
  /** Tenant-scoped entity was not found. */
  NOT_FOUND: "FINANCE_NOT_FOUND",
  /** Duplicate identity or conflicting write under the same tenant. */
  CONFLICT: "FINANCE_CONFLICT",

  // Phase 1D — provider-neutral payment port
  PROVIDER_UNAVAILABLE: "FINANCE_PROVIDER_UNAVAILABLE",
  PROVIDER_UNSUPPORTED_OPERATION: "FINANCE_PROVIDER_UNSUPPORTED_OPERATION",
  PROVIDER_UNSUPPORTED_CURRENCY: "FINANCE_PROVIDER_UNSUPPORTED_CURRENCY",
  PROVIDER_TIMEOUT: "FINANCE_PROVIDER_TIMEOUT",
  PROVIDER_REJECTED: "FINANCE_PROVIDER_REJECTED",
  PROVIDER_RESPONSE_INVALID: "FINANCE_PROVIDER_RESPONSE_INVALID",
  PROVIDER_REFERENCE_CONFLICT: "FINANCE_PROVIDER_REFERENCE_CONFLICT",
  PROVIDER_EVIDENCE_INVALID: "FINANCE_PROVIDER_EVIDENCE_INVALID",
  PROVIDER_AUTHENTICATION_FAILED: "FINANCE_PROVIDER_AUTHENTICATION_FAILED",
  PROVIDER_RATE_LIMITED: "FINANCE_PROVIDER_RATE_LIMITED",
  PROVIDER_WEBHOOK_INVALID: "FINANCE_PROVIDER_WEBHOOK_INVALID",
  PROVIDER_STATUS_UNKNOWN: "FINANCE_PROVIDER_STATUS_UNKNOWN",

  // Phase 1E — durable persistence contracts
  PERSISTENCE_RECORD_INVALID: "FINANCE_PERSISTENCE_RECORD_INVALID",
  REPOSITORY_NOT_FOUND: "FINANCE_REPOSITORY_NOT_FOUND",
  PERSISTENCE_UNIQUENESS_CONFLICT: "FINANCE_PERSISTENCE_UNIQUENESS_CONFLICT",
  OPTIMISTIC_CONCURRENCY_CONFLICT: "FINANCE_OPTIMISTIC_CONCURRENCY_CONFLICT",
  TENANT_OWNERSHIP_MISMATCH: "FINANCE_TENANT_OWNERSHIP_MISMATCH",
  TRANSACTION_FAILED: "FINANCE_TRANSACTION_FAILED",
  TRANSACTION_ROLLBACK_FAILED: "FINANCE_TRANSACTION_ROLLBACK_FAILED",
  EVENT_APPEND_CONFLICT: "FINANCE_EVENT_APPEND_CONFLICT",
  IDEMPOTENCY_IN_PROGRESS: "FINANCE_IDEMPOTENCY_IN_PROGRESS",
  CORRUPT_FINANCIAL_RECORD: "FINANCE_CORRUPT_FINANCIAL_RECORD",
  PERSISTENCE_CAPABILITY_UNSUPPORTED: "FINANCE_PERSISTENCE_CAPABILITY_UNSUPPORTED",

  // Phase 1G — durable adapter / database error normalization
  PERSISTENCE_PERMISSION_DENIED: "FINANCE_PERSISTENCE_PERMISSION_DENIED",
  PERSISTENCE_CONSTRAINT_VIOLATION: "FINANCE_PERSISTENCE_CONSTRAINT_VIOLATION",
  PERSISTENCE_UNAVAILABLE: "FINANCE_PERSISTENCE_UNAVAILABLE",
  PERSISTENCE_UNKNOWN_FAILURE: "FINANCE_PERSISTENCE_UNKNOWN_FAILURE",

  // Phase 1I — runtime composition foundation
  RUNTIME_DISABLED: "FINANCE_RUNTIME_DISABLED",
  INVALID_RUNTIME_CONFIGURATION: "FINANCE_INVALID_RUNTIME_CONFIGURATION",
  UNSUPPORTED_RUNTIME_MODE: "FINANCE_UNSUPPORTED_RUNTIME_MODE",
  MISSING_RUNTIME_DEPENDENCY: "FINANCE_MISSING_RUNTIME_DEPENDENCY",
  ENVIRONMENT_NOT_AUTHORIZED: "FINANCE_ENVIRONMENT_NOT_AUTHORIZED",
  PERSISTENCE_NOT_READY: "FINANCE_PERSISTENCE_NOT_READY",
  PROVIDER_NOT_CONFIGURED: "FINANCE_PROVIDER_NOT_CONFIGURED",
  TENANT_RESOLUTION_UNAVAILABLE: "FINANCE_TENANT_RESOLUTION_UNAVAILABLE",
  READINESS_PROBE_FAILED: "FINANCE_READINESS_PROBE_FAILED",
  /** Durable adapter present but Phase 1C sync application commands are not bridged. */
  APPLICATION_COMMANDS_UNAVAILABLE: "FINANCE_APPLICATION_COMMANDS_UNAVAILABLE",
});

export const FINANCE_ERROR_CODE_VALUES = Object.freeze(
  Object.values(FINANCE_ERROR_CODES)
);

/**
 * @param {string} code
 * @returns {boolean}
 */
export function isFinanceErrorCode(code) {
  return FINANCE_ERROR_CODE_VALUES.includes(code);
}
