/**
 * News & Public Content — module-local typed error codes (NEWS-01).
 * Not registered in API_ERROR_CODES in this phase (same pattern as COMMS/ECO).
 */

export const NEWS_PUBLIC_CONTENT_ERROR_CODE = Object.freeze({
  INVALID_CONTENT_IDENTITY: "NEWS_INVALID_CONTENT_IDENTITY",
  UNSUPPORTED_CONTENT_TYPE: "NEWS_UNSUPPORTED_CONTENT_TYPE",
  UNSUPPORTED_CONTENT_SCOPE: "NEWS_UNSUPPORTED_CONTENT_SCOPE",
  MISSING_SCOPE_OWNER: "NEWS_MISSING_SCOPE_OWNER",
  INVALID_EDITORIAL_OWNERSHIP: "NEWS_INVALID_EDITORIAL_OWNERSHIP",
  INVALID_CONTENT_FIELD: "NEWS_INVALID_CONTENT_FIELD",
  INVALID_LOCALE: "NEWS_INVALID_LOCALE",
  INVALID_SLUG: "NEWS_INVALID_SLUG",
  INVALID_REVISION_VERSION: "NEWS_INVALID_REVISION_VERSION",
  INVALID_LIFECYCLE_TRANSITION: "NEWS_INVALID_LIFECYCLE_TRANSITION",
  REVIEW_REQUIRED: "NEWS_REVIEW_REQUIRED",
  APPROVAL_REQUIRED: "NEWS_APPROVAL_REQUIRED",
  APPROVAL_REVISION_MISMATCH: "NEWS_APPROVAL_REVISION_MISMATCH",
  INVALID_PUBLICATION_WINDOW: "NEWS_INVALID_PUBLICATION_WINDOW",
  PUBLICATION_NOT_ELIGIBLE: "NEWS_PUBLICATION_NOT_ELIGIBLE",
  CONTENT_NOT_PUBLIC: "NEWS_CONTENT_NOT_PUBLIC",
  ARCHIVED_CONTENT: "NEWS_ARCHIVED_CONTENT",
  VERSION_CONFLICT: "NEWS_VERSION_CONFLICT",
  PROVENANCE_MISMATCH: "NEWS_PROVENANCE_MISMATCH",
  CONTENT_NOT_FOUND: "NEWS_CONTENT_NOT_FOUND",
  PORT_OPERATION_UNIMPLEMENTED: "NEWS_PORT_OPERATION_UNIMPLEMENTED",
  INVALID_CONTRACT: "NEWS_INVALID_CONTRACT",
  INVALID_REFERENCE: "NEWS_INVALID_REFERENCE",
});
