/**
 * CORE-12 — request rejection and conflict codes.
 *
 * Canonical emitted string values only. Compatibility key aliases (if any)
 * must map to the same canonical string and MUST NOT be emitted as alternate
 * surface forms. Prefer reading via COURT_ASSIGNMENT_*_CODE.<CANONICAL>.
 */

export const COURT_ASSIGNMENT_REJECTION_CODE = Object.freeze({
  INVALID_REQUEST: "INVALID_REQUEST",
  SCHEMA_VERSION_MISMATCH: "SCHEMA_VERSION_MISMATCH",
  UNKNOWN_FIELD: "UNKNOWN_FIELD",
  DUPLICATE_MATCH_ID: "DUPLICATE_MATCH_ID",
  DUPLICATE_COURT_ID: "DUPLICATE_COURT_ID",
  INVALID_TIME_WINDOW: "INVALID_TIME_WINDOW",
  INVALID_CIVIL_WINDOW: "INVALID_CIVIL_WINDOW",
  TIMEZONE_REQUIRED: "TIMEZONE_REQUIRED",
  SCOPE_MISMATCH: "SCOPE_MISMATCH",
  CROSS_TENANT_REFERENCE: "CROSS_TENANT_REFERENCE",
  CROSS_VENUE_REFERENCE: "CROSS_VENUE_REFERENCE",
  CROSS_CLUB_REFERENCE: "CROSS_CLUB_REFERENCE",
  LOCK_REFERENCES_UNKNOWN_MATCH: "LOCK_REFERENCES_UNKNOWN_MATCH",
  LOCK_REFERENCES_UNKNOWN_COURT: "LOCK_REFERENCES_UNKNOWN_COURT",
  LOCK_SCOPE_MISMATCH: "LOCK_SCOPE_MISMATCH",
  DUPLICATE_LOCK: "DUPLICATE_LOCK",
  SEED_REQUIRED: "SEED_REQUIRED",
  AVAILABILITY_SNAPSHOT_REQUIRED: "AVAILABILITY_SNAPSHOT_REQUIRED",
  NON_CANONICAL_VALUE: "NON_CANONICAL_VALUE",
  UNSUPPORTED_POLICY_VERSION: "UNSUPPORTED_POLICY_VERSION",
  LOCKS_NOT_ACCEPTED: "LOCKS_NOT_ACCEPTED",
});

/**
 * Lookup-only aliases (never emitted). Map Owner/legacy names → canonical.
 */
export const COURT_ASSIGNMENT_REJECTION_CODE_ALIASES = Object.freeze({
  UNKNOWN_LOCKED_MATCH: COURT_ASSIGNMENT_REJECTION_CODE.LOCK_REFERENCES_UNKNOWN_MATCH,
  UNKNOWN_LOCKED_COURT: COURT_ASSIGNMENT_REJECTION_CODE.LOCK_REFERENCES_UNKNOWN_COURT,
});

export const COURT_ASSIGNMENT_CONFLICT_CODE = Object.freeze({
  COURT_TIME_OVERLAP: "COURT_TIME_OVERLAP",
  COURT_UNAVAILABLE: "COURT_UNAVAILABLE",
  COURT_DISABLED: "COURT_DISABLED",
  COURT_MAINTENANCE: "COURT_MAINTENANCE",
  COURT_LOCKED_INVENTORY: "COURT_LOCKED_INVENTORY",
  CAPABILITY_MISMATCH: "CAPABILITY_MISMATCH",
  WINDOW_INCOMPATIBLE: "WINDOW_INCOMPATIBLE",
  LOCKED_ASSIGNMENT_INFEASIBLE: "LOCKED_ASSIGNMENT_INFEASIBLE",
  LOCKED_ASSIGNMENT_OVERRIDE_DENIED: "LOCKED_ASSIGNMENT_OVERRIDE_DENIED",
  LOCK_COURT_UNAVAILABLE: "LOCK_COURT_UNAVAILABLE",
  LOCK_CAPABILITY_MISMATCH: "LOCK_CAPABILITY_MISMATCH",
  LOCK_OVERLAP: "LOCK_OVERLAP",
  LOCK_SCOPE_MISMATCH: "LOCK_SCOPE_MISMATCH",
  NO_ELIGIBLE_COURT: "NO_ELIGIBLE_COURT",
  BYE_MUST_NOT_CONSUME_COURT: "BYE_MUST_NOT_CONSUME_COURT",
  DUPLICATE_MATCH_ASSIGNMENT: "DUPLICATE_MATCH_ASSIGNMENT",
  AVAILABILITY_DATA_UNAVAILABLE: "AVAILABILITY_DATA_UNAVAILABLE",
  RULE_HARD_VIOLATION: "RULE_HARD_VIOLATION",
  RULE_SOFT_VIOLATION: "RULE_SOFT_VIOLATION",
  PARTIAL_ASSIGNMENT_NOT_ALLOWED: "PARTIAL_ASSIGNMENT_NOT_ALLOWED",
});

/**
 * Lookup-only aliases (never emitted).
 */
export const COURT_ASSIGNMENT_CONFLICT_CODE_ALIASES = Object.freeze({
  COURT_TIME_CONFLICT: COURT_ASSIGNMENT_CONFLICT_CODE.COURT_TIME_OVERLAP,
  COURT_CAPABILITY_MISMATCH: COURT_ASSIGNMENT_CONFLICT_CODE.CAPABILITY_MISMATCH,
});

export const COURT_ASSIGNMENT_REJECTION_CODE_VALUES = Object.freeze(
  Object.values(COURT_ASSIGNMENT_REJECTION_CODE)
);

export const COURT_ASSIGNMENT_CONFLICT_CODE_VALUES = Object.freeze(
  Object.values(COURT_ASSIGNMENT_CONFLICT_CODE)
);

/**
 * Resolve a maybe-alias code to its canonical emitted value.
 * @param {string} code
 * @returns {string}
 */
export function resolveCanonicalRejectionCode(code) {
  if (Object.prototype.hasOwnProperty.call(COURT_ASSIGNMENT_REJECTION_CODE, code)) {
    return COURT_ASSIGNMENT_REJECTION_CODE[code];
  }
  if (Object.prototype.hasOwnProperty.call(COURT_ASSIGNMENT_REJECTION_CODE_ALIASES, code)) {
    return COURT_ASSIGNMENT_REJECTION_CODE_ALIASES[code];
  }
  return String(code);
}

/**
 * @param {string} code
 * @returns {string}
 */
export function resolveCanonicalConflictCode(code) {
  if (Object.prototype.hasOwnProperty.call(COURT_ASSIGNMENT_CONFLICT_CODE, code)) {
    return COURT_ASSIGNMENT_CONFLICT_CODE[code];
  }
  if (Object.prototype.hasOwnProperty.call(COURT_ASSIGNMENT_CONFLICT_CODE_ALIASES, code)) {
    return COURT_ASSIGNMENT_CONFLICT_CODE_ALIASES[code];
  }
  return String(code);
}
