/**
 * CORE-13 Referee Assignment — capability-local public surface (Phase 1B–1F freeze).
 *
 * Phase 1B: contracts, enums, errors, ports, determinism helpers.
 * Phase 1C: eligibility, conflicts, workload, manual validation, diagnostics.
 * Phase 1D: assignReferees planner, replaceRefereeAssignment, plan fingerprints.
 * Phase 1E: SHA-256 digests, fairness cohort, seed/duplicate certification.
 * Phase 1F: final integration certification and public-surface freeze.
 *
 * Integrator owns root competition-core/index.js — do not edit that from CORE-13.
 */

export {
  CORE13_ENGINE_ID,
  CORE13_ENGINE_VERSION,
  CORE13_SCHEMA_VERSION,
  CORE13_DETERMINISM_POLICY_ID,
  CORE13_COMPARATOR_VERSION,
  CORE13_CANONICAL_SERIALIZATION_VERSION,
  CORE13_IDENTITY,
} from "./constants/index.js";

export {
  REFEREE_ROLE_CODE,
  REFEREE_ROLE_CODE_VALUES,
  isRefereeRoleCode,
  normalizeRefereeRoleCode,
  REFEREE_ASSIGNMENT_STATUS,
  REFEREE_ASSIGNMENT_STATUS_VALUES,
  isRefereeAssignmentStatus,
  REFEREE_ASSIGNMENT_SOURCE,
  REFEREE_ASSIGNMENT_SOURCE_VALUES,
  isRefereeAssignmentSource,
  REFEREE_CONFLICT_TYPE,
  REFEREE_CONFLICT_TYPE_VALUES,
  isRefereeConflictType,
  REFEREE_CONSTRAINT_KIND,
  REFEREE_CONSTRAINT_KIND_VALUES,
  isRefereeConstraintKind,
  REFEREE_DIAGNOSTIC_SEVERITY,
  REFEREE_DIAGNOSTIC_SEVERITY_VALUES,
  isRefereeDiagnosticSeverity,
  REFEREE_AVAILABILITY_SOURCE,
  REFEREE_AVAILABILITY_SOURCE_VALUES,
  isRefereeAvailabilitySource,
  REFEREE_AUDIT_ACTION,
  REFEREE_AUDIT_ACTION_VALUES,
  isRefereeAuditAction,
  REFEREE_SNAPSHOT_STATUS,
  REFEREE_SNAPSHOT_STATUS_VALUES,
  isRefereeSnapshotStatus,
  REFEREE_RESOURCE_TYPE,
  REFEREE_SOFT_NOTE_CODE,
  REFEREE_SOFT_NOTE_CODE_VALUES,
  isRefereeSoftNoteCode,
  REFEREE_SOFT_OBJECTIVE_KEY,
  REFEREE_SOFT_OBJECTIVE_KEY_VALUES,
  isRefereeSoftObjectiveKey,
} from "./enums/index.js";

export {
  REFEREE_ASSIGNMENT_DIAGNOSTIC_CODE,
  REFEREE_ASSIGNMENT_DIAGNOSTIC_CODE_VALUES,
  isRefereeAssignmentDiagnosticCode,
  REFEREE_DIAGNOSTIC_DEFAULT_SEVERITY,
  resolveDefaultDiagnosticSeverity,
  RefereeAssignmentContractError,
  isRefereeAssignmentContractError,
} from "./errors/index.js";

export {
  createRefereeCandidate,
  REFEREE_CANDIDATE_FORBIDDEN_PROFILE_FIELDS,
  createRefereeQualification,
  createRefereeAvailabilityWindow,
  createRefereeRoleRequirement,
  createRefereeAssignmentPolicy,
  createSnapshotRef,
  createScheduleWindow,
  createRefereeAssignmentContext,
  createRefereeAssignmentRequest,
  createRefereeConflict,
  createRefereeWorkload,
  createRefereeAssignment,
  createUnassignedRefereeRequirement,
  createRefereeAssignmentFailure,
  createManualAssignmentRejection,
  createRefereeAssignmentPlan,
  createManualRefereeAssignmentRequest,
  createRefereeReplacementRequest,
  createRefereeReplacementResult,
  createRefereeAssignmentAuditRecord,
  createRefereeResourceConflictProjection,
  createHardFailure,
  createSoftNote,
  createRefereeEligibilityResult,
  sortHardFailures,
  collectReasonCodes,
} from "./contracts/index.js";

export {
  compareStableString,
  compareStableId,
  sortStableIds,
  sortedObjectKeys,
  isPlainObject,
  deepFreezeCanonical,
  freezePlainObject,
  assertCanonicalPlainValue,
  normalizeStableId,
  normalizeOptionalStableId,
  normalizeStableIdArray,
  normalizePreferenceTags,
  prepareFingerprintMaterial,
  prepareCanonicalObjectProjection,
  CORE13_DIGEST_VERSION,
  CORE13_FINGERPRINT_VERSION,
  CORE13_DIGEST_DOMAIN,
  CORE13_ID_PREFIX,
  CORE13_ID_DIGEST_HEX_LEN,
  sha256HexUtf8,
  canonicalizeJsonValue,
  serializeCanonical,
  digestCanonical,
  fingerprintValue,
  buildNamespacedId,
  buildAssignmentId,
  buildPlanId,
  buildReplacementId,
  seedExplorationKey,
  normalizePlannerSeed,
} from "./deterministic/index.js";

export {
  createPortResolveResult,
  createMissingSnapshotResult,
  createInvalidSnapshotResult,
  createEmptySnapshotResult,
  createPopulatedSnapshotResult,
  REFEREE_DIRECTORY_PORT_METHODS,
  matchesRefereeDirectoryPort,
  createFailClosedRefereeDirectoryPort,
  createFixedRefereeDirectoryPort,
  REFEREE_QUALIFICATION_PORT_METHODS,
  matchesRefereeQualificationPort,
  createFailClosedRefereeQualificationPort,
  createFixedRefereeQualificationPort,
  REFEREE_AVAILABILITY_PORT_METHODS,
  matchesRefereeAvailabilityPort,
  createFailClosedRefereeAvailabilityPort,
  createFixedRefereeAvailabilityPort,
  EXISTING_ASSIGNMENT_PORT_METHODS,
  matchesExistingAssignmentPort,
  createFailClosedExistingAssignmentPort,
  createFixedExistingAssignmentPort,
  REFEREE_CONFLICT_POLICY_PORT_METHODS,
  matchesRefereeConflictPolicyPort,
  createFailClosedRefereeConflictPolicyPort,
  createFixedRefereeConflictPolicyPort,
  MATCH_SCHEDULE_INPUT_PORT_METHODS,
  matchesMatchScheduleInputPort,
  createMatchScheduleRow,
  createFailClosedMatchScheduleInputPort,
  createFixedMatchScheduleInputPort,
  REFEREE_AUDIT_SINK_PORT_METHODS,
  matchesRefereeAuditSinkPort,
  createFailClosedRefereeAuditSinkPort,
  createFixedRefereeAuditSinkPort,
  REFEREE_WORKLOAD_HISTORY_PORT_METHODS,
  matchesRefereeWorkloadHistoryPort,
  createFailClosedRefereeWorkloadHistoryPort,
  createFixedRefereeWorkloadHistoryPort,
} from "./ports/index.js";

export {
  evaluateRefereeEligibility,
  detectRefereeConflicts,
  calculateRefereeWorkload,
  validateManualRefereeAssignment,
  explainUnassignedMatch,
  parseInstantMs,
  requireHalfOpenWindow,
  tryHalfOpenWindow,
  intervalsOverlapHalfOpen,
  windowFullyCovers,
  durationMinutes,
  normalizeConflictPolicy,
  isActiveAssignmentStatus,
} from "./services/index.js";

export {
  buildReasonCounts,
  stableUniqueReasonCodes,
} from "./diagnostics/index.js";

export { assignReferees, replaceRefereeAssignment } from "./engines/index.js";
