/**
 * P1.2 S1-D/S1-E — setup mutation foundation error / block codes.
 */

export const SETUP_MUTATION_CODES = Object.freeze({
  GATE_OFF: "SETUP_MUTATION_GATE_OFF",
  CONFIRM_REQUIRED: "CONFIRM_REQUIRED",
  PREVIEW_ONLY: "PREVIEW_ONLY",
  DRIFT_WARN: "SETUP_SNAPSHOT_DRIFT_WARN",
  DRIFT_BLOCK: "SETUP_SNAPSHOT_DRIFT",
  ENGINE_VERSION_MISMATCH: "ENGINE_VERSION_MISMATCH",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",
  STALE_RESPONSE: "STALE_RESPONSE",
  RPC_NOT_DEPLOYED: "RPC_GUARD_NOT_DEPLOYED",
  NOT_IMPLEMENTED: "REPOSITORY_NOT_IMPLEMENTED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  HASH_RUNTIME_ERROR: "HASH_RUNTIME_ERROR",
  DUPLICATE_COMMAND: "DUPLICATE_COMMAND_IN_FLIGHT",
  MISSING_ENVELOPE: "MISSING_ENVELOPE",
  BLOB_FALLBACK_FORBIDDEN: "BLOB_FALLBACK_FORBIDDEN",
});

export const SETUP_MUTATION_STATUS = Object.freeze({
  IDLE: "idle",
  PREVIEW: "preview",
  CONFIRMING: "confirming",
  SUCCESS: "success",
  BLOCKED: "blocked",
  CONFLICT: "conflict",
  FAILED: "failed",
});
