/**
 * I&A-13 — Integration Hardening and Final Certification enums.
 */

export const INTEGRATION_HARDENING_FINAL_CERTIFICATION_METHOD_VERSION = "1.0.0";

export const CERTIFICATION_MANIFEST_VERSION = "1.0.0";

export const CERTIFICATION_VERSION = "1.0.0";

export const ANALYTICS_CERTIFICATION_STATUS = Object.freeze({
  PASS: "PASS",
  FAIL: "FAIL",
  BLOCKED: "BLOCKED",
  NOT_APPLICABLE: "NOT_APPLICABLE",
});

export const ANALYTICS_CERTIFICATION_SEVERITY = Object.freeze({
  BLOCKER: "BLOCKER",
  WARNING: "WARNING",
  INFO: "INFO",
});

export const ANALYTICS_CERTIFICATION_DIMENSION_ID = Object.freeze({
  CONTRACT_INTEGRITY: "CONTRACT_INTEGRITY",
  PUBLIC_EXPORT_INTEGRITY: "PUBLIC_EXPORT_INTEGRITY",
  METRIC_REGISTRY_INTEGRITY: "METRIC_REGISTRY_INTEGRITY",
  ERROR_REGISTRY_INTEGRITY: "ERROR_REGISTRY_INTEGRITY",
  QUERY_RUNTIME_COMPATIBILITY: "QUERY_RUNTIME_COMPATIBILITY",
  HISTORICAL_COMPATIBILITY: "HISTORICAL_COMPATIBILITY",
  DASHBOARD_REPORT_COMPATIBILITY: "DASHBOARD_REPORT_COMPATIBILITY",
  TENANT_ISOLATION: "TENANT_ISOLATION",
  ENTITY_ISOLATION: "ENTITY_ISOLATION",
  PRIVACY_ACCESS: "PRIVACY_ACCESS",
  CURRENCY_COMPATIBILITY: "CURRENCY_COMPATIBILITY",
  RANKING_RATING_COMPATIBILITY: "RANKING_RATING_COMPATIBILITY",
  OPERATIONAL_INSIGHT_COMPATIBILITY: "OPERATIONAL_INSIGHT_COMPATIBILITY",
  AI_READINESS_BOUNDARY: "AI_READINESS_BOUNDARY",
  READ_ONLY_GUARANTEE: "READ_ONLY_GUARANTEE",
  NO_WRITE_GUARANTEE: "NO_WRITE_GUARANTEE",
  NO_PRIVATE_IMPORT: "NO_PRIVATE_IMPORT",
  NO_DATABASE_COUPLING: "NO_DATABASE_COUPLING",
  NO_PROVIDER_NETWORK_COUPLING: "NO_PROVIDER_NETWORK_COUPLING",
  NO_SECRET_OR_PII_LEAKAGE: "NO_SECRET_OR_PII_LEAKAGE",
  CI_REGISTRATION: "CI_REGISTRATION",
  OWNERSHIP_LOCK: "OWNERSHIP_LOCK",
  DOCUMENTATION_COMPLETENESS: "DOCUMENTATION_COMPLETENESS",
  REPRODUCIBILITY: "REPRODUCIBILITY",
  FINAL_SCOPE_INTEGRITY: "FINAL_SCOPE_INTEGRITY",
});

export const ANALYTICS_SURFACE_CLASSIFICATION = Object.freeze({
  CANONICAL_AND_STABLE: "CANONICAL_AND_STABLE",
  CERTIFIED: "CERTIFIED",
  LEGACY_BUT_ACTIVE: "LEGACY_BUT_ACTIVE",
  MOCK_OR_CERTIFICATION_ONLY: "MOCK_OR_CERTIFICATION_ONLY",
  DEFERRED_PRODUCTION_ADAPTER: "DEFERRED_PRODUCTION_ADAPTER",
  DUPLICATED: "DUPLICATED",
  INCOMPATIBLE: "INCOMPATIBLE",
  PRIVACY_SENSITIVE: "PRIVACY_SENSITIVE",
  FINANCIAL_SENSITIVE: "FINANCIAL_SENSITIVE",
  PROHIBITED_DEPENDENCY: "PROHIBITED_DEPENDENCY",
  BLOCKING_DEFECT: "BLOCKING_DEFECT",
  NON_BLOCKING_TECHNICAL_DEBT: "NON_BLOCKING_TECHNICAL_DEBT",
});

export const ANALYTICS_CERTIFICATION_COMPLETENESS = Object.freeze({
  COMPLETE: "COMPLETE",
  PARTIAL: "PARTIAL",
  FAILED: "FAILED",
});

export const ANALYTICS_CERTIFICATION_REASON_CODE = Object.freeze({
  CERTIFICATION_PASSED: "CERTIFICATION_PASSED",
  CERTIFICATION_FAILED: "CERTIFICATION_FAILED",
  CERTIFICATION_BLOCKED: "CERTIFICATION_BLOCKED",
  CERTIFICATION_NOT_APPLICABLE: "CERTIFICATION_NOT_APPLICABLE",
  MANIFEST_INVALID: "MANIFEST_INVALID",
  SURFACE_MISSING: "SURFACE_MISSING",
  SURFACE_DUPLICATE: "SURFACE_DUPLICATE",
  SURFACE_VERSION_CONFLICT: "SURFACE_VERSION_CONFLICT",
  EXPORT_MISSING: "EXPORT_MISSING",
  EXPORT_DUPLICATE: "EXPORT_DUPLICATE",
  EXPORT_BROKEN: "EXPORT_BROKEN",
  EXPORT_MUTABLE: "EXPORT_MUTABLE",
  EXPORT_WRITE_CAPABLE: "EXPORT_WRITE_CAPABLE",
  METRIC_CONFLICT: "METRIC_CONFLICT",
  METRIC_MISSING_UNIT: "METRIC_MISSING_UNIT",
  METRIC_REPLACEMENT_BROKEN: "METRIC_REPLACEMENT_BROKEN",
  ERROR_CODE_CONFLICT: "ERROR_CODE_CONFLICT",
  ERROR_UNSAFE_MESSAGE: "ERROR_UNSAFE_MESSAGE",
  ERROR_RAW_LEAKAGE: "ERROR_RAW_LEAKAGE",
  TENANT_MISSING: "TENANT_MISSING",
  TENANT_MIXED: "TENANT_MIXED",
  ENTITY_MISMATCH: "ENTITY_MISMATCH",
  ENTITY_FALLBACK: "ENTITY_FALLBACK",
  PRIVACY_STATE_COLLAPSE: "PRIVACY_STATE_COLLAPSE",
  CURRENCY_MIXED: "CURRENCY_MIXED",
  CURRENCY_CONVERSION: "CURRENCY_CONVERSION",
  RANKING_RECALCULATED: "RANKING_RECALCULATED",
  RATING_RECALCULATED: "RATING_RECALCULATED",
  WRITE_DETECTED: "WRITE_DETECTED",
  PRIVATE_IMPORT: "PRIVATE_IMPORT",
  DATABASE_COUPLING: "DATABASE_COUPLING",
  PROVIDER_NETWORK: "PROVIDER_NETWORK",
  SECRET_OR_PII: "SECRET_OR_PII",
  MOCK_CLAIMS_LIVE: "MOCK_CLAIMS_LIVE",
  SILENT_SUCCESS: "SILENT_SUCCESS",
  SOURCE_UNAVAILABLE: "SOURCE_UNAVAILABLE",
  CI_MISSING: "CI_MISSING",
  DOCS_MISSING: "DOCS_MISSING",
  TEST_MISSING: "TEST_MISSING",
  CLOSURE_BLOCKED: "CLOSURE_BLOCKED",
  SOURCE_CERTIFICATION_ONLY: "SOURCE_CERTIFICATION_ONLY",
});

export const ANALYTICS_ACCESS_STATE_SEMANTICS = Object.freeze({
  DENY: "DENY",
  EMPTY: "EMPTY",
  SUPPRESS: "SUPPRESS",
  ZERO: "ZERO",
  REDACT: "REDACT",
  MISSING: "MISSING",
  OMIT: "OMIT",
  UNAVAILABLE: "UNAVAILABLE",
});

export const INTEGRATION_DEFERRED_SURFACES = Object.freeze([
  "Production analytics source adapters",
  "persistence / ETL / data warehouse",
  "Production privacy-policy adapters and database RLS certification",
  "operational background evaluators and notification delivery",
  "Production AI providers, model hosting, embeddings and RAG",
  "dashboard and Experience Channel UI adoption",
  "operational monitoring",
]);

/**
 * @param {unknown} value
 * @param {Readonly<Record<string, string>>} enumObject
 * @returns {boolean}
 */
export function isCertificationEnumValue(value, enumObject) {
  return typeof value === "string" && Object.values(enumObject).includes(value);
}
