import { NOTIFICATION_TYPES } from "./notificationTypes.js";

/** Canonical mobile notification events (staging-ready). */
export const NOTIFICATION_EVENTS = Object.freeze({
  BOOKING_CREATED: "BookingCreated",
  BOOKING_CANCELLED: "BookingCancelled",
  MATCH_STARTED: "MatchStarted",
  MATCH_FINISHED: "MatchFinished",
  TOURNAMENT_SCHEDULE_UPDATED: "TournamentScheduleUpdated",
  PLAYER_CHECKED_IN: "PlayerCheckedIn",
  PAYMENT_RECEIVED: "PaymentReceived",
  SUBSCRIPTION_EXPIRING: "SubscriptionExpiring",
});

/** Map event → preference type key. */
export const EVENT_TO_PREF_TYPE = Object.freeze({
  [NOTIFICATION_EVENTS.BOOKING_CREATED]: NOTIFICATION_TYPES.BOOKING_NEW,
  [NOTIFICATION_EVENTS.BOOKING_CANCELLED]: NOTIFICATION_TYPES.BOOKING_NEW,
  [NOTIFICATION_EVENTS.MATCH_STARTED]: NOTIFICATION_TYPES.MATCH_UPCOMING,
  [NOTIFICATION_EVENTS.MATCH_FINISHED]: NOTIFICATION_TYPES.MATCH_UPCOMING,
  [NOTIFICATION_EVENTS.TOURNAMENT_SCHEDULE_UPDATED]: NOTIFICATION_TYPES.TOURNAMENT_SCHEDULE_CHANGE,
  [NOTIFICATION_EVENTS.PLAYER_CHECKED_IN]: NOTIFICATION_TYPES.CLUB_ANNOUNCEMENT,
  [NOTIFICATION_EVENTS.PAYMENT_RECEIVED]: NOTIFICATION_TYPES.PAYMENT_REMINDER,
  [NOTIFICATION_EVENTS.SUBSCRIPTION_EXPIRING]: NOTIFICATION_TYPES.PAYMENT_REMINDER,
});

/** Roles that may receive each event (empty = all authenticated in tenant). */
export const EVENT_ROLE_TARGETS = Object.freeze({
  [NOTIFICATION_EVENTS.BOOKING_CREATED]: ["COURT_OWNER", "COURT_MANAGER", "CASHIER"],
  [NOTIFICATION_EVENTS.BOOKING_CANCELLED]: ["COURT_OWNER", "COURT_MANAGER", "CASHIER"],
  [NOTIFICATION_EVENTS.MATCH_STARTED]: ["PLAYER", "REFEREE", "CLUB_OWNER", "COURT_MANAGER"],
  [NOTIFICATION_EVENTS.MATCH_FINISHED]: ["PLAYER", "REFEREE", "CLUB_OWNER", "COURT_MANAGER"],
  [NOTIFICATION_EVENTS.TOURNAMENT_SCHEDULE_UPDATED]: ["PLAYER", "CLUB_OWNER", "REFEREE", "COURT_MANAGER"],
  [NOTIFICATION_EVENTS.PLAYER_CHECKED_IN]: ["COURT_OWNER", "COURT_MANAGER"],
  [NOTIFICATION_EVENTS.PAYMENT_RECEIVED]: ["COURT_OWNER", "CASHIER", "ACCOUNTANT"],
  [NOTIFICATION_EVENTS.SUBSCRIPTION_EXPIRING]: ["COURT_OWNER"],
});
