/**
 * CORE-14 — frozen input diagnostic codes.
 * Every runtime-emitted input diagnostic must use a value from this catalog.
 */

export const INPUT_DIAGNOSTIC_CODE = Object.freeze({
  RESOURCE_ID_MISSING: "RESOURCE_ID_MISSING",
  ASSIGNMENT_ID_MISSING: "ASSIGNMENT_ID_MISSING",
  ACTIVITY_IDENTITY_MISSING: "ACTIVITY_IDENTITY_MISSING",
  TIME_WINDOW_MISSING: "TIME_WINDOW_MISSING",
  INVALID_TIME_INTERVAL: "INVALID_TIME_INTERVAL",
  UNKNOWN_RESOURCE_TYPE: "UNKNOWN_RESOURCE_TYPE",
  DUPLICATE_OCCUPANCY_ID: "DUPLICATE_OCCUPANCY_ID",
  DUPLICATE_ASSIGNMENT: "DUPLICATE_ASSIGNMENT",
  SCOPE_MISSING: "SCOPE_MISSING",
  SCOPE_IDENTITY_MISMATCH: "SCOPE_IDENTITY_MISMATCH",
  AVAILABILITY_DATA_UNAVAILABLE: "AVAILABILITY_DATA_UNAVAILABLE",
  CAPACITY_MISSING: "CAPACITY_MISSING",
  INVALID_CAPACITY: "INVALID_CAPACITY",
  SEVERITY_DOWNGRADE_REJECTED: "SEVERITY_DOWNGRADE_REJECTED",
  SLOT_RESOLUTION_FAILED: "SLOT_RESOLUTION_FAILED",
  OCCUPANCY_ID_MISSING: "OCCUPANCY_ID_MISSING",
  OCCUPANCY_SOURCE_MISSING: "OCCUPANCY_SOURCE_MISSING",
  OCCUPANCY_BOOLEAN_INVALID: "OCCUPANCY_BOOLEAN_INVALID",
  OCCUPANCY_METADATA_INVALID: "OCCUPANCY_METADATA_INVALID",
  UNSUPPORTED_CANONICAL_VALUE: "UNSUPPORTED_CANONICAL_VALUE",
  // Phase 1F adapter / legacy / shadow diagnostics (non-duplicative only).
  // Identity / scope / interval / slot / kind mismatches reuse Phase 1C codes above.
  ADAPTER_RECORD_INVALID: "ADAPTER_RECORD_INVALID",
  ADAPTER_SOURCE_VERSION_MISSING: "ADAPTER_SOURCE_VERSION_MISSING",
  LEGACY_CONFLICT_CODE_UNMAPPED: "LEGACY_CONFLICT_CODE_UNMAPPED",
  LEGACY_EVIDENCE_INSUFFICIENT: "LEGACY_EVIDENCE_INSUFFICIENT",
  ADJACENT_CONTRACT_UNAVAILABLE: "ADJACENT_CONTRACT_UNAVAILABLE",
});

/** Frozen ordered list — do not rely on object insertion order. */
export const INPUT_DIAGNOSTIC_CODE_VALUES = Object.freeze([
  INPUT_DIAGNOSTIC_CODE.RESOURCE_ID_MISSING,
  INPUT_DIAGNOSTIC_CODE.ASSIGNMENT_ID_MISSING,
  INPUT_DIAGNOSTIC_CODE.ACTIVITY_IDENTITY_MISSING,
  INPUT_DIAGNOSTIC_CODE.TIME_WINDOW_MISSING,
  INPUT_DIAGNOSTIC_CODE.INVALID_TIME_INTERVAL,
  INPUT_DIAGNOSTIC_CODE.UNKNOWN_RESOURCE_TYPE,
  INPUT_DIAGNOSTIC_CODE.DUPLICATE_OCCUPANCY_ID,
  INPUT_DIAGNOSTIC_CODE.DUPLICATE_ASSIGNMENT,
  INPUT_DIAGNOSTIC_CODE.SCOPE_MISSING,
  INPUT_DIAGNOSTIC_CODE.SCOPE_IDENTITY_MISMATCH,
  INPUT_DIAGNOSTIC_CODE.AVAILABILITY_DATA_UNAVAILABLE,
  INPUT_DIAGNOSTIC_CODE.CAPACITY_MISSING,
  INPUT_DIAGNOSTIC_CODE.INVALID_CAPACITY,
  INPUT_DIAGNOSTIC_CODE.SEVERITY_DOWNGRADE_REJECTED,
  INPUT_DIAGNOSTIC_CODE.SLOT_RESOLUTION_FAILED,
  INPUT_DIAGNOSTIC_CODE.OCCUPANCY_ID_MISSING,
  INPUT_DIAGNOSTIC_CODE.OCCUPANCY_SOURCE_MISSING,
  INPUT_DIAGNOSTIC_CODE.OCCUPANCY_BOOLEAN_INVALID,
  INPUT_DIAGNOSTIC_CODE.OCCUPANCY_METADATA_INVALID,
  INPUT_DIAGNOSTIC_CODE.UNSUPPORTED_CANONICAL_VALUE,
  INPUT_DIAGNOSTIC_CODE.ADAPTER_RECORD_INVALID,
  INPUT_DIAGNOSTIC_CODE.ADAPTER_SOURCE_VERSION_MISSING,
  INPUT_DIAGNOSTIC_CODE.LEGACY_CONFLICT_CODE_UNMAPPED,
  INPUT_DIAGNOSTIC_CODE.LEGACY_EVIDENCE_INSUFFICIENT,
  INPUT_DIAGNOSTIC_CODE.ADJACENT_CONTRACT_UNAVAILABLE,
]);

const INPUT_DIAGNOSTIC_CODE_SET = new Set(INPUT_DIAGNOSTIC_CODE_VALUES);

/**
 * @param {unknown} value
 * @returns {value is string}
 */
export function isInputDiagnosticCode(value) {
  return typeof value === "string" && INPUT_DIAGNOSTIC_CODE_SET.has(value);
}
