/**
 * CORE-14 — frozen domain / programmer contract error codes.
 * Thrown via ResourceConflictContractError (not input diagnostics).
 */

export const DOMAIN_CONTRACT_ERROR_CODE = Object.freeze({
  INVALID_EVALUATION_STATUS: "INVALID_EVALUATION_STATUS",
  INVALID_PLAN_STATUS: "INVALID_PLAN_STATUS",
  INVALID_AVAILABILITY_CERTIFICATION: "INVALID_AVAILABILITY_CERTIFICATION",
  UNKNOWN_FINDING_CODE: "UNKNOWN_FINDING_CODE",
  UNKNOWN_FINDING_CODE_FOR_SEVERITY: "UNKNOWN_FINDING_CODE_FOR_SEVERITY",
  INVALID_SEVERITY: "INVALID_SEVERITY",
  UNKNOWN_DIAGNOSTIC_CODE: "UNKNOWN_DIAGNOSTIC_CODE",
  DIAGNOSTIC_MESSAGE_REQUIRED: "DIAGNOSTIC_MESSAGE_REQUIRED",
  INVALID_DIAGNOSTIC_DETAILS: "INVALID_DIAGNOSTIC_DETAILS",
  /**
   * create/normalize/serialize wrappers rethrow the first validation diagnostic
   * code when a validate path already produced INPUT_DIAGNOSTIC_CODE values.
   * Prefer calling validate* when collecting diagnostics without throw.
   */
  VALIDATION_FAILED: "VALIDATION_FAILED",
});

export const DOMAIN_CONTRACT_ERROR_CODE_VALUES = Object.freeze([
  DOMAIN_CONTRACT_ERROR_CODE.INVALID_EVALUATION_STATUS,
  DOMAIN_CONTRACT_ERROR_CODE.INVALID_PLAN_STATUS,
  DOMAIN_CONTRACT_ERROR_CODE.INVALID_AVAILABILITY_CERTIFICATION,
  DOMAIN_CONTRACT_ERROR_CODE.UNKNOWN_FINDING_CODE,
  DOMAIN_CONTRACT_ERROR_CODE.UNKNOWN_FINDING_CODE_FOR_SEVERITY,
  DOMAIN_CONTRACT_ERROR_CODE.INVALID_SEVERITY,
  DOMAIN_CONTRACT_ERROR_CODE.UNKNOWN_DIAGNOSTIC_CODE,
  DOMAIN_CONTRACT_ERROR_CODE.DIAGNOSTIC_MESSAGE_REQUIRED,
  DOMAIN_CONTRACT_ERROR_CODE.INVALID_DIAGNOSTIC_DETAILS,
  DOMAIN_CONTRACT_ERROR_CODE.VALIDATION_FAILED,
]);

const DOMAIN_CONTRACT_ERROR_CODE_SET = new Set(DOMAIN_CONTRACT_ERROR_CODE_VALUES);

/**
 * @param {unknown} value
 * @returns {value is string}
 */
export function isDomainContractErrorCode(value) {
  return typeof value === "string" && DOMAIN_CONTRACT_ERROR_CODE_SET.has(value);
}
