/**
 * CORE-14 — frozen resource finding catalog codes.
 */

export const RESOURCE_FINDING_CODE = Object.freeze({
  PLAYER_TIME_OVERLAP: "PLAYER_TIME_OVERLAP",
  TEAM_TIME_OVERLAP: "TEAM_TIME_OVERLAP",
  COURT_TIME_OVERLAP: "COURT_TIME_OVERLAP",
  REFEREE_TIME_OVERLAP: "REFEREE_TIME_OVERLAP",
  RESOURCE_CAPACITY_EXCEEDED: "RESOURCE_CAPACITY_EXCEEDED",
  RESOURCE_UNAVAILABLE: "RESOURCE_UNAVAILABLE",
  MANDATORY_REST_VIOLATION: "MANDATORY_REST_VIOLATION",
  PREFERRED_REST_WARNING: "PREFERRED_REST_WARNING",
  VENUE_CAPACITY_EXCEEDED: "VENUE_CAPACITY_EXCEEDED",
  VENUE_UNAVAILABLE: "VENUE_UNAVAILABLE",
  LOCATION_TIME_OVERLAP: "LOCATION_TIME_OVERLAP",
});

export const RESOURCE_FINDING_CODE_VALUES = Object.freeze([
  RESOURCE_FINDING_CODE.PLAYER_TIME_OVERLAP,
  RESOURCE_FINDING_CODE.TEAM_TIME_OVERLAP,
  RESOURCE_FINDING_CODE.COURT_TIME_OVERLAP,
  RESOURCE_FINDING_CODE.REFEREE_TIME_OVERLAP,
  RESOURCE_FINDING_CODE.RESOURCE_CAPACITY_EXCEEDED,
  RESOURCE_FINDING_CODE.RESOURCE_UNAVAILABLE,
  RESOURCE_FINDING_CODE.MANDATORY_REST_VIOLATION,
  RESOURCE_FINDING_CODE.PREFERRED_REST_WARNING,
  RESOURCE_FINDING_CODE.VENUE_CAPACITY_EXCEEDED,
  RESOURCE_FINDING_CODE.VENUE_UNAVAILABLE,
  RESOURCE_FINDING_CODE.LOCATION_TIME_OVERLAP,
]);

const RESOURCE_FINDING_CODE_SET = new Set(RESOURCE_FINDING_CODE_VALUES);

/**
 * @param {unknown} value
 * @returns {value is string}
 */
export function isResourceFindingCode(value) {
  return typeof value === "string" && RESOURCE_FINDING_CODE_SET.has(value);
}
