/**
 * Canonical Customer Management error codes.
 * CUSTOMER-01 foundation + CUSTOMER-02 profile/contact codes (additive).
 * Persistence-neutral — no HTTP mapping here.
 */

export const CUSTOMER_ERROR_CODES = Object.freeze({
  INVALID_INPUT: "CUSTOMER_INVALID_INPUT",
  INVALID_REFERENCE: "CUSTOMER_INVALID_REFERENCE",
  NOT_FOUND: "CUSTOMER_NOT_FOUND",
  DUPLICATE: "CUSTOMER_DUPLICATE",
  INVALID_TYPE: "CUSTOMER_INVALID_TYPE",
  INVALID_STATUS: "CUSTOMER_INVALID_STATUS",
  INVALID_STATUS_TRANSITION: "CUSTOMER_INVALID_STATUS_TRANSITION",
  INVALID_CONTACT_POINT: "CUSTOMER_INVALID_CONTACT_POINT",
  CONFLICTING_PRIMARY_CONTACT: "CUSTOMER_CONFLICTING_PRIMARY_CONTACT",
  LINKAGE_CONFLICT: "CUSTOMER_LINKAGE_CONFLICT",
  VERSION_CONFLICT: "CUSTOMER_VERSION_CONFLICT",
  TENANT_SCOPE_MISMATCH: "CUSTOMER_TENANT_SCOPE_MISMATCH",
  MISSING_SCOPE: "CUSTOMER_MISSING_SCOPE",
  RUNTIME_NOT_CONFIGURED: "CUSTOMER_RUNTIME_NOT_CONFIGURED",
  CONFLICT: "CUSTOMER_CONFLICT",
  // CUSTOMER-02 additive codes
  INVALID_CUSTOMER_PROFILE: "CUSTOMER_INVALID_CUSTOMER_PROFILE",
  PROFILE_TYPE_MISMATCH: "CUSTOMER_PROFILE_TYPE_MISMATCH",
  INVALID_EMAIL: "CUSTOMER_INVALID_EMAIL",
  INVALID_PHONE: "CUSTOMER_INVALID_PHONE",
  INVALID_ADDRESS: "CUSTOMER_INVALID_ADDRESS",
  DUPLICATE_CONTACT_POINT: "CUSTOMER_DUPLICATE_CONTACT_POINT",
  CONTACT_POINT_NOT_FOUND: "CUSTOMER_CONTACT_POINT_NOT_FOUND",
  PRIMARY_CONTACT_CONFLICT: "CUSTOMER_PRIMARY_CONTACT_CONFLICT",
});

export const CUSTOMER_ERROR_CODE_VALUES = Object.freeze(
  Object.values(CUSTOMER_ERROR_CODES)
);

/**
 * @param {string} code
 * @returns {boolean}
 */
export function isCustomerErrorCode(code) {
  return CUSTOMER_ERROR_CODE_VALUES.includes(code);
}
