/**
 * Canonical Customer Management error codes (CUSTOMER-01 foundation).
 * Persistence-neutral — no HTTP mapping here.
 */

export const CUSTOMER_ERROR_CODES = Object.freeze({
  INVALID_INPUT: "CUSTOMER_INVALID_INPUT",
  INVALID_REFERENCE: "CUSTOMER_INVALID_REFERENCE",
  NOT_FOUND: "CUSTOMER_NOT_FOUND",
  DUPLICATE: "CUSTOMER_DUPLICATE",
  INVALID_TYPE: "CUSTOMER_INVALID_TYPE",
  INVALID_STATUS: "CUSTOMER_INVALID_STATUS",
  INVALID_STATUS_TRANSITION: "CUSTOMER_INVALID_STATUS_TRANSITION",
  INVALID_CONTACT_POINT: "CUSTOMER_INVALID_CONTACT_POINT",
  CONFLICTING_PRIMARY_CONTACT: "CUSTOMER_CONFLICTING_PRIMARY_CONTACT",
  LINKAGE_CONFLICT: "CUSTOMER_LINKAGE_CONFLICT",
  VERSION_CONFLICT: "CUSTOMER_VERSION_CONFLICT",
  TENANT_SCOPE_MISMATCH: "CUSTOMER_TENANT_SCOPE_MISMATCH",
  MISSING_SCOPE: "CUSTOMER_MISSING_SCOPE",
  RUNTIME_NOT_CONFIGURED: "CUSTOMER_RUNTIME_NOT_CONFIGURED",
  CONFLICT: "CUSTOMER_CONFLICT",
});

export const CUSTOMER_ERROR_CODE_VALUES = Object.freeze(
  Object.values(CUSTOMER_ERROR_CODES)
);

/**
 * @param {string} code
 * @returns {boolean}
 */
export function isCustomerErrorCode(code) {
  return CUSTOMER_ERROR_CODE_VALUES.includes(code);
}
