/**
 * Canonical Customer Management error codes.
 * CUSTOMER-01 foundation + CUSTOMER-02 profile/contact + CUSTOMER-03
 * persistence + CUSTOMER-04 consent/preference + CUSTOMER-05 linkage
 * codes (additive). Persistence-neutral — no HTTP mapping here.
 */

export const CUSTOMER_ERROR_CODES = Object.freeze({
  INVALID_INPUT: "CUSTOMER_INVALID_INPUT",
  INVALID_REFERENCE: "CUSTOMER_INVALID_REFERENCE",
  NOT_FOUND: "CUSTOMER_NOT_FOUND",
  DUPLICATE: "CUSTOMER_DUPLICATE",
  INVALID_TYPE: "CUSTOMER_INVALID_TYPE",
  INVALID_STATUS: "CUSTOMER_INVALID_STATUS",
  INVALID_STATUS_TRANSITION: "CUSTOMER_INVALID_STATUS_TRANSITION",
  INVALID_CONTACT_POINT: "CUSTOMER_INVALID_CONTACT_POINT",
  CONFLICTING_PRIMARY_CONTACT: "CUSTOMER_CONFLICTING_PRIMARY_CONTACT",
  LINKAGE_CONFLICT: "CUSTOMER_LINKAGE_CONFLICT",
  VERSION_CONFLICT: "CUSTOMER_VERSION_CONFLICT",
  TENANT_SCOPE_MISMATCH: "CUSTOMER_TENANT_SCOPE_MISMATCH",
  MISSING_SCOPE: "CUSTOMER_MISSING_SCOPE",
  RUNTIME_NOT_CONFIGURED: "CUSTOMER_RUNTIME_NOT_CONFIGURED",
  CONFLICT: "CUSTOMER_CONFLICT",
  // CUSTOMER-02 additive codes
  INVALID_CUSTOMER_PROFILE: "CUSTOMER_INVALID_CUSTOMER_PROFILE",
  PROFILE_TYPE_MISMATCH: "CUSTOMER_PROFILE_TYPE_MISMATCH",
  INVALID_EMAIL: "CUSTOMER_INVALID_EMAIL",
  INVALID_PHONE: "CUSTOMER_INVALID_PHONE",
  INVALID_ADDRESS: "CUSTOMER_INVALID_ADDRESS",
  DUPLICATE_CONTACT_POINT: "CUSTOMER_DUPLICATE_CONTACT_POINT",
  CONTACT_POINT_NOT_FOUND: "CUSTOMER_CONTACT_POINT_NOT_FOUND",
  PRIMARY_CONTACT_CONFLICT: "CUSTOMER_PRIMARY_CONTACT_CONFLICT",
  // CUSTOMER-04 additive codes
  INVALID_CONSENT: "CUSTOMER_INVALID_CONSENT",
  CONSENT_NOT_FOUND: "CUSTOMER_CONSENT_NOT_FOUND",
  CONSENT_ALREADY_REVOKED: "CUSTOMER_CONSENT_ALREADY_REVOKED",
  INVALID_CONSENT_TRANSITION: "CUSTOMER_INVALID_CONSENT_TRANSITION",
  CONSENT_EVIDENCE_REQUIRED: "CUSTOMER_CONSENT_EVIDENCE_REQUIRED",
  INVALID_COMMUNICATION_PREFERENCE: "CUSTOMER_INVALID_COMMUNICATION_PREFERENCE",
  PREFERENCE_CONFLICT: "CUSTOMER_PREFERENCE_CONFLICT",
  PREFERENCE_NOT_FOUND: "CUSTOMER_PREFERENCE_NOT_FOUND",
  UNSUPPORTED_COMMUNICATION_CHANNEL: "CUSTOMER_UNSUPPORTED_COMMUNICATION_CHANNEL",
  UNSUPPORTED_COMMUNICATION_PURPOSE: "CUSTOMER_UNSUPPORTED_COMMUNICATION_PURPOSE",
  SCOPE_MISMATCH: "CUSTOMER_SCOPE_MISMATCH",
  // CUSTOMER-05 additive codes
  INVALID_CUSTOMER_LINKAGE: "CUSTOMER_INVALID_CUSTOMER_LINKAGE",
  UNSUPPORTED_LINKAGE_TYPE: "CUSTOMER_UNSUPPORTED_LINKAGE_TYPE",
  LINKAGE_NOT_FOUND: "CUSTOMER_LINKAGE_NOT_FOUND",
  LINKAGE_ALREADY_EXISTS: "CUSTOMER_LINKAGE_ALREADY_EXISTS",
  LINKAGE_ALREADY_INACTIVE: "CUSTOMER_LINKAGE_ALREADY_INACTIVE",
  IDENTITY_ACCOUNT_NOT_FOUND: "CUSTOMER_IDENTITY_ACCOUNT_NOT_FOUND",
  PLAYER_NOT_FOUND: "CUSTOMER_PLAYER_NOT_FOUND",
  CRM_REFERENCE_NOT_FOUND: "CUSTOMER_CRM_REFERENCE_NOT_FOUND",
  IDENTITY_LINK_CONFLICT: "CUSTOMER_IDENTITY_LINK_CONFLICT",
  PLAYER_LINK_CONFLICT: "CUSTOMER_PLAYER_LINK_CONFLICT",
  CRM_LINK_CONFLICT: "CUSTOMER_CRM_LINK_CONFLICT",
  EXTERNAL_REFERENCE_SCOPE_MISMATCH: "CUSTOMER_EXTERNAL_REFERENCE_SCOPE_MISMATCH",
  LINKAGE_DIRECTORY_UNAVAILABLE: "CUSTOMER_LINKAGE_DIRECTORY_UNAVAILABLE",
  LINKAGE_TRANSFER_REQUIRES_EXPLICIT_ACTION:
    "CUSTOMER_LINKAGE_TRANSFER_REQUIRES_EXPLICIT_ACTION",
});

export const CUSTOMER_ERROR_CODE_VALUES = Object.freeze(
  Object.values(CUSTOMER_ERROR_CODES)
);

/**
 * @param {string} code
 * @returns {boolean}
 */
export function isCustomerErrorCode(code) {
  return CUSTOMER_ERROR_CODE_VALUES.includes(code);
}
