/**
 * CORE-19 — typed workflow error taxonomy (capability-local).
 */

export const WORKFLOW_ERROR_CODE = Object.freeze({
  INVALID_WORKFLOW_DEFINITION: "INVALID_WORKFLOW_DEFINITION",
  UNKNOWN_WORKFLOW: "UNKNOWN_WORKFLOW",
  UNKNOWN_STATE: "UNKNOWN_STATE",
  UNKNOWN_STEP: "UNKNOWN_STEP",
  UNKNOWN_TRANSITION: "UNKNOWN_TRANSITION",
  TRANSITION_NOT_ALLOWED: "TRANSITION_NOT_ALLOWED",
  TRANSITION_UNAUTHORIZED: "TRANSITION_UNAUTHORIZED",
  PREREQUISITE_NOT_SATISFIED: "PREREQUISITE_NOT_SATISFIED",
  GUARD_REJECTED: "GUARD_REJECTED",
  DEPENDENCY_NOT_READY: "DEPENDENCY_NOT_READY",
  DEPENDENCY_REJECTED: "DEPENDENCY_REJECTED",
  TRANSITION_EFFECT_FAILED: "TRANSITION_EFFECT_FAILED",
  INVALID_EFFECT_DEFINITION: "INVALID_EFFECT_DEFINITION",
  EFFECT_NOT_READY: "EFFECT_NOT_READY",
  INVALID_PAUSE_REQUEST: "INVALID_PAUSE_REQUEST",
  INVALID_RESUME_REQUEST: "INVALID_RESUME_REQUEST",
  INVALID_RESTART_REQUEST: "INVALID_RESTART_REQUEST",
  RESTART_NOT_ALLOWED: "RESTART_NOT_ALLOWED",
  DUPLICATE_OPERATION_CONFLICT: "DUPLICATE_OPERATION_CONFLICT",
  WORKFLOW_PAUSED: "WORKFLOW_PAUSED",
  WORKFLOW_COMPLETED: "WORKFLOW_COMPLETED",
  WORKFLOW_FAILED: "WORKFLOW_FAILED",
  WORKFLOW_CANCELLED: "WORKFLOW_CANCELLED",
  DUPLICATE_TRANSITION_REQUEST: "DUPLICATE_TRANSITION_REQUEST",
  DETERMINISTIC_INPUT_VIOLATION: "DETERMINISTIC_INPUT_VIOLATION",
});

/** @type {ReadonlySet<string>} */
export const WORKFLOW_ERROR_CODE_VALUES = new Set(
  Object.values(WORKFLOW_ERROR_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isWorkflowErrorCode(value) {
  return typeof value === "string" && WORKFLOW_ERROR_CODE_VALUES.has(value);
}
