/**
 * CM-07 Competition Suspension / Cancellation — stable typed error codes.
 * Module-local; not registered in API_ERROR_CODES in this phase.
 */

export const COMPETITION_LIFECYCLE_ERROR_CODE = Object.freeze({
  INVALID_CONTRACT: "CM07_INVALID_CONTRACT",
  MISSING_TENANT: "CM07_MISSING_TENANT",
  MISSING_COMPETITION: "CM07_MISSING_COMPETITION",
  TENANT_MISMATCH: "CM07_TENANT_MISMATCH",
  COMPETITION_MISMATCH: "CM07_COMPETITION_MISMATCH",
  CROSS_TENANT_ACCESS: "CM07_CROSS_TENANT_ACCESS",

  INVALID_DEFINITION: "CM07_INVALID_DEFINITION",
  STALE_DEFINITION_REVISION: "CM07_STALE_DEFINITION_REVISION",
  MISSING_LIFECYCLE_CONTEXT: "CM07_MISSING_LIFECYCLE_CONTEXT",
  STALE_LIFECYCLE_REVISION: "CM07_STALE_LIFECYCLE_REVISION",
  MISSING_EXPECTED_LIFECYCLE_REVISION: "CM07_MISSING_EXPECTED_LIFECYCLE_REVISION",

  INVALID_TRANSITION: "CM07_INVALID_TRANSITION",
  ALREADY_SUSPENDED: "CM07_ALREADY_SUSPENDED",
  NOT_SUSPENDED: "CM07_NOT_SUSPENDED",
  ALREADY_CANCELLED: "CM07_ALREADY_CANCELLED",
  CANCELLED_TERMINAL: "CM07_CANCELLED_TERMINAL",
  RESUME_FORBIDDEN: "CM07_RESUME_FORBIDDEN",

  INVALID_SUSPENSION_REASON: "CM07_INVALID_SUSPENSION_REASON",
  INVALID_CANCELLATION_REASON: "CM07_INVALID_CANCELLATION_REASON",
  INVALID_RESUME_REASON: "CM07_INVALID_RESUME_REASON",
  MISSING_REASON_DETAIL: "CM07_MISSING_REASON_DETAIL",
  INVALID_REASON_SUMMARY: "CM07_INVALID_REASON_SUMMARY",
  REASON_CONTROL_CHARACTERS: "CM07_REASON_CONTROL_CHARACTERS",

  INVALID_EFFECTIVE_TIME: "CM07_INVALID_EFFECTIVE_TIME",
  INVALID_INTENDED_RESUME_TIME: "CM07_INVALID_INTENDED_RESUME_TIME",

  MISSING_ACTOR: "CM07_MISSING_ACTOR",
  ACTOR_TENANT_MISMATCH: "CM07_ACTOR_TENANT_MISMATCH",
  AUTHORITY_DENIED: "CM07_AUTHORITY_DENIED",
  MISSING_AUTHORITY_REFERENCE: "CM07_MISSING_AUTHORITY_REFERENCE",

  INVALID_SUSPENSION_POLICY: "CM07_INVALID_SUSPENSION_POLICY",
  INVALID_CANCELLATION_POLICY: "CM07_INVALID_CANCELLATION_POLICY",
  MISSING_PUBLICATION_POLICY: "CM07_MISSING_PUBLICATION_POLICY",
  PUBLICATION_CONTEXT_MISMATCH: "CM07_PUBLICATION_CONTEXT_MISMATCH",
  STALE_PUBLICATION_REVISION: "CM07_STALE_PUBLICATION_REVISION",
  MISSING_PUBLICATION_CONTEXT: "CM07_MISSING_PUBLICATION_CONTEXT",

  MISSING_IDEMPOTENCY_KEY: "CM07_MISSING_IDEMPOTENCY_KEY",
  IDEMPOTENCY_CONFLICT: "CM07_IDEMPOTENCY_CONFLICT",
  DUPLICATE_LIFECYCLE_RECORD: "CM07_DUPLICATE_LIFECYCLE_RECORD",
  REPOSITORY_CONFLICT: "CM07_REPOSITORY_CONFLICT",
  MALFORMED_LIFECYCLE_RECORD: "CM07_MALFORMED_LIFECYCLE_RECORD",
  MALFORMED_EFFECT_PLAN: "CM07_MALFORMED_EFFECT_PLAN",
  MALFORMED_LEGACY_LIFECYCLE: "CM07_MALFORMED_LEGACY_LIFECYCLE",
  AMBIGUOUS_LEGACY_MAPPING: "CM07_AMBIGUOUS_LEGACY_MAPPING",
  PORT_OPERATION_UNIMPLEMENTED: "CM07_PORT_OPERATION_UNIMPLEMENTED",
  MISSING_DATA_RETENTION_ACK: "CM07_MISSING_DATA_RETENTION_ACK",
});
