/**
 * CORE-13 — canonical error / diagnostic codes (single frozen enum).
 */

export const REFEREE_ASSIGNMENT_DIAGNOSTIC_CODE = Object.freeze({
  INVALID_ASSIGNMENT_REQUEST: "INVALID_ASSIGNMENT_REQUEST",
  TENANT_SCOPE_REQUIRED: "TENANT_SCOPE_REQUIRED",
  TOURNAMENT_SCOPE_REQUIRED: "TOURNAMENT_SCOPE_REQUIRED",
  MATCH_SCOPE_REQUIRED: "MATCH_SCOPE_REQUIRED",
  SCHEDULE_WINDOW_REQUIRED: "SCHEDULE_WINDOW_REQUIRED",
  NO_REFEREE_CANDIDATES: "NO_REFEREE_CANDIDATES",
  NO_ELIGIBLE_REFEREE: "NO_ELIGIBLE_REFEREE",
  REFEREE_NOT_FOUND: "REFEREE_NOT_FOUND",
  REFEREE_INACTIVE: "REFEREE_INACTIVE",
  REFEREE_NOT_QUALIFIED: "REFEREE_NOT_QUALIFIED",
  REFEREE_UNAVAILABLE: "REFEREE_UNAVAILABLE",
  REFEREE_ALREADY_ASSIGNED: "REFEREE_ALREADY_ASSIGNED",
  REFEREE_CONFLICT_OF_INTEREST: "REFEREE_CONFLICT_OF_INTEREST",
  REFEREE_ROLE_UNSUPPORTED: "REFEREE_ROLE_UNSUPPORTED",
  MANUAL_ASSIGNMENT_REJECTED: "MANUAL_ASSIGNMENT_REJECTED",
  REQUIRED_REFEREE_ROLE_UNFILLED: "REQUIRED_REFEREE_ROLE_UNFILLED",
  ASSIGNMENT_CAPACITY_EXHAUSTED: "ASSIGNMENT_CAPACITY_EXHAUSTED",
  NON_DETERMINISTIC_INPUT: "NON_DETERMINISTIC_INPUT",
  INVALID_REPLACEMENT_REQUEST: "INVALID_REPLACEMENT_REQUEST",
  REPLACEMENT_REFEREE_REJECTED: "REPLACEMENT_REFEREE_REJECTED",
  /** Port / snapshot missing (fatal). */
  SNAPSHOT_MISSING: "SNAPSHOT_MISSING",
  /** Port / snapshot invalid (fatal). */
  SNAPSHOT_INVALID: "SNAPSHOT_INVALID",
});

/** @type {ReadonlySet<string>} */
export const REFEREE_ASSIGNMENT_DIAGNOSTIC_CODE_VALUES = new Set(
  Object.values(REFEREE_ASSIGNMENT_DIAGNOSTIC_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isRefereeAssignmentDiagnosticCode(value) {
  return (
    typeof value === "string" &&
    REFEREE_ASSIGNMENT_DIAGNOSTIC_CODE_VALUES.has(value)
  );
}
