/**
 * Phase 3H — Draw Runtime error codes (capability-local).
 * Shared error-registry export is Integrator-owned — handoff only.
 */

export const DRAW_RUNTIME_ERROR_CODE = Object.freeze({
  DRAW_INVALID_INPUT: "DRAW_INVALID_INPUT",
  DRAW_NOT_FOUND: "DRAW_NOT_FOUND",
  DRAW_INVALID_SOURCE: "DRAW_INVALID_SOURCE",
  DRAW_UNSUPPORTED_SOURCE: "DRAW_UNSUPPORTED_SOURCE",
  DRAW_IDENTITY_MISMATCH: "DRAW_IDENTITY_MISMATCH",
  DRAW_IDENTITY_COLLISION: "DRAW_IDENTITY_COLLISION",
  DRAW_COMPETITION_MISMATCH: "DRAW_COMPETITION_MISMATCH",
  DRAW_CONTEXT_MISMATCH: "DRAW_CONTEXT_MISMATCH",
  DRAW_CANDIDATE_REQUIRED: "DRAW_CANDIDATE_REQUIRED",
  DRAW_CANDIDATE_DUPLICATE: "DRAW_CANDIDATE_DUPLICATE",
  DRAW_CANDIDATE_INELIGIBLE: "DRAW_CANDIDATE_INELIGIBLE",
  DRAW_SEED_ASSIGNMENT_REQUIRED: "DRAW_SEED_ASSIGNMENT_REQUIRED",
  DRAW_SEED_ASSIGNMENT_DUPLICATE: "DRAW_SEED_ASSIGNMENT_DUPLICATE",
  DRAW_GROUP_COUNT_INVALID: "DRAW_GROUP_COUNT_INVALID",
  DRAW_GROUP_CAPACITY_INVALID: "DRAW_GROUP_CAPACITY_INVALID",
  DRAW_GROUP_OVERFLOW: "DRAW_GROUP_OVERFLOW",
  DRAW_GROUP_UNDERFLOW: "DRAW_GROUP_UNDERFLOW",
  DRAW_BRACKET_SIZE_INVALID: "DRAW_BRACKET_SIZE_INVALID",
  DRAW_SLOT_INVALID: "DRAW_SLOT_INVALID",
  DRAW_SLOT_DUPLICATE: "DRAW_SLOT_DUPLICATE",
  DRAW_MANUAL_PLACEMENT_INVALID: "DRAW_MANUAL_PLACEMENT_INVALID",
  DRAW_MANUAL_PLACEMENT_DUPLICATE: "DRAW_MANUAL_PLACEMENT_DUPLICATE",
  DRAW_PROTECTED_PLACEMENT_CONFLICT: "DRAW_PROTECTED_PLACEMENT_CONFLICT",
  DRAW_BYE_COUNT_INVALID: "DRAW_BYE_COUNT_INVALID",
  DRAW_POLICY_REJECTED: "DRAW_POLICY_REJECTED",
  DRAW_NON_DETERMINISTIC: "DRAW_NON_DETERMINISTIC",
  DRAW_DEPENDENCY_FAILED: "DRAW_DEPENDENCY_FAILED",
  DRAW_ADAPTER_FAILED: "DRAW_ADAPTER_FAILED",
  DRAW_PERSISTENCE_DISABLED: "DRAW_PERSISTENCE_DISABLED",
  DRAW_UNSUPPORTED_MODE: "DRAW_UNSUPPORTED_MODE",
});

/** @type {ReadonlySet<string>} */
export const DRAW_RUNTIME_ERROR_CODE_VALUES = new Set(
  Object.values(DRAW_RUNTIME_ERROR_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isDrawRuntimeErrorCode(value) {
  return typeof value === "string" && DRAW_RUNTIME_ERROR_CODE_VALUES.has(value);
}
