import { ROLES, normalizeRole } from "../constants/roles.js";
import { PERMISSIONS } from "../constants/permissions.js";

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const VENUE_OPS = [
  PERMISSIONS.VENUE_VIEW,
  PERMISSIONS.COURT_VIEW,
  PERMISSIONS.COURT_CREATE,
  PERMISSIONS.COURT_UPDATE,
  PERMISSIONS.BOOKING_VIEW,
  PERMISSIONS.BOOKING_CREATE,
  PERMISSIONS.BOOKING_UPDATE,
  PERMISSIONS.CUSTOMER_VIEW,
  PERMISSIONS.FINANCE_VIEW,
  PERMISSIONS.CLUB_VIEW,
  PERMISSIONS.PLAYER_VIEW,
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.TOURNAMENT_CREATE,
  PERMISSIONS.TOURNAMENT_UPDATE,
  PERMISSIONS.DIRECTOR_USE,
  PERMISSIONS.MATCH_UPDATE,
  PERMISSIONS.SCHEDULING_VIEW,
  PERMISSIONS.SCHEDULING_RUN,
  PERMISSIONS.STATISTICS_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
];

const COURT_OWNER_PERMISSIONS = [
  ...VENUE_OPS,
  PERMISSIONS.VENUE_UPDATE,
  PERMISSIONS.USER_MANAGE,
  PERMISSIONS.SUBSCRIPTION_VIEW,
  PERMISSIONS.BILLING_VIEW,
  PERMISSIONS.BILLING_INVOICE_VIEW,
  PERMISSIONS.BILLING_PAYMENT_VIEW,
  PERMISSIONS.BILLING_SUBSCRIPTION_VIEW,
  PERMISSIONS.FINANCE_EDIT,
  PERMISSIONS.CLUB_CREATE,
  PERMISSIONS.CLUB_UPDATE,
  PERMISSIONS.CLUB_DELETE,
  PERMISSIONS.SEASON_UPDATE,
  PERMISSIONS.LEAGUE_UPDATE,
  PERMISSIONS.PLAYER_CREATE,
  PERMISSIONS.PLAYER_UPDATE,
  PERMISSIONS.PLAYER_DELETE,
  PERMISSIONS.COURT_DELETE,
  PERMISSIONS.BOOKING_DELETE,
  PERMISSIONS.CUSTOMER_CREATE,
  PERMISSIONS.CUSTOMER_UPDATE,
  PERMISSIONS.CUSTOMER_DELETE,
  PERMISSIONS.TOURNAMENT_DELETE,
  PERMISSIONS.STATISTICS_EXPORT,
  PERMISSIONS.SYSTEM_SETTING,
  PERMISSIONS.INTEGRATION_VIEW,
  PERMISSIONS.INTEGRATION_MANAGE,
  PERMISSIONS.MARKETPLACE_VIEW,
  PERMISSIONS.MARKETPLACE_MANAGE,
  PERMISSIONS.API_MANAGE,
];

const COURT_MANAGER_PERMISSIONS = [
  ...VENUE_OPS,
  PERMISSIONS.PLAYER_CREATE,
  PERMISSIONS.PLAYER_UPDATE,
  PERMISSIONS.PLAYER_DELETE,
  PERMISSIONS.COURT_UPDATE,
  PERMISSIONS.COURT_DELETE,
  PERMISSIONS.BOOKING_UPDATE,
  PERMISSIONS.BOOKING_DELETE,
  PERMISSIONS.CUSTOMER_UPDATE,
];

const CASHIER_PERMISSIONS = [
  PERMISSIONS.COURT_VIEW,
  PERMISSIONS.BOOKING_VIEW,
  PERMISSIONS.BOOKING_CREATE,
  PERMISSIONS.CUSTOMER_VIEW,
  PERMISSIONS.FINANCE_VIEW,
  PERMISSIONS.FINANCE_EDIT,
];

const ACCOUNTANT_PERMISSIONS = [
  PERMISSIONS.BOOKING_VIEW,
  PERMISSIONS.CUSTOMER_VIEW,
  PERMISSIONS.FINANCE_VIEW,
  PERMISSIONS.FINANCE_EDIT,
  PERMISSIONS.STATISTICS_VIEW,
  PERMISSIONS.STATISTICS_EXPORT,
];

const CLUB_OWNER_PERMISSIONS = [
  PERMISSIONS.CLUB_VIEW,
  PERMISSIONS.CLUB_UPDATE,
  PERMISSIONS.SEASON_UPDATE,
  PERMISSIONS.LEAGUE_UPDATE,
  PERMISSIONS.PLAYER_VIEW,
  PERMISSIONS.PLAYER_CREATE,
  PERMISSIONS.PLAYER_UPDATE,
  PERMISSIONS.PLAYER_DELETE,
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.TOURNAMENT_CREATE,
  PERMISSIONS.TOURNAMENT_UPDATE,
  PERMISSIONS.TOURNAMENT_DELETE,
  PERMISSIONS.DIRECTOR_USE,
  PERMISSIONS.MATCH_UPDATE,
  PERMISSIONS.SCHEDULING_VIEW,
  PERMISSIONS.SCHEDULING_RUN,
  PERMISSIONS.STATISTICS_VIEW,
  PERMISSIONS.STATISTICS_EXPORT,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.MARKETPLACE_VIEW,
  PERMISSIONS.INTEGRATION_VIEW,
];

const REFEREE_PERMISSIONS = [
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.MATCH_UPDATE,
];

const PLAYER_PERMISSIONS = [
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.TOURNAMENT_CREATE,
  PERMISSIONS.STATISTICS_VIEW,
  PERMISSIONS.PLAYER_VIEW,
  PERMISSIONS.PLAYER_UPDATE,
];

/** Map canonical role → danh sách permission. */
export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.freeze([...ALL_PERMISSIONS]),
  [ROLES.COURT_OWNER]: Object.freeze(COURT_OWNER_PERMISSIONS),
  [ROLES.COURT_MANAGER]: Object.freeze(COURT_MANAGER_PERMISSIONS),
  [ROLES.CASHIER]: Object.freeze(CASHIER_PERMISSIONS),
  [ROLES.ACCOUNTANT]: Object.freeze(ACCOUNTANT_PERMISSIONS),
  [ROLES.REFEREE]: Object.freeze(REFEREE_PERMISSIONS),
  [ROLES.CLUB_OWNER]: Object.freeze(CLUB_OWNER_PERMISSIONS),
  [ROLES.PLAYER]: Object.freeze(PLAYER_PERMISSIONS),
});

export function getPermissionsForRole(role) {
  const canonical = normalizeRole(role);
  return ROLE_PERMISSIONS[canonical] || [];
}

export function roleHasPermission(role, permission) {
  return getPermissionsForRole(role).includes(permission);
}
