import { ROLES, normalizeRole } from "../constants/roles.js";
import { PERMISSIONS } from "../constants/permissions.js";
import { COURT_ENGINE_PERMISSIONS } from "../../court-engine/guards/courtEngineGuard.js";

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const SYSTEM_TECHNICIAN_PERMISSIONS = [
  PERMISSIONS.SYSTEM_HEALTH_VIEW,
  PERMISSIONS.SYSTEM_LOG_VIEW,
  PERMISSIONS.SYSTEM_CONFIG_VIEW,
  PERMISSIONS.SYSTEM_CONFIG_UPDATE_LIMITED,
  PERMISSIONS.TENANT_VIEW,
  PERMISSIONS.VENUE_VIEW,
  PERMISSIONS.USER_VIEW,
  PERMISSIONS.ROLE_VIEW,
  PERMISSIONS.PERMISSION_VIEW,
  PERMISSIONS.ACTIVITY_LOG_VIEW,
  PERMISSIONS.INTEGRATION_VIEW,
  PERMISSIONS.INTEGRATION_TEST,
  PERMISSIONS.SUPPORT_TICKET_MANAGE,
  PERMISSIONS.DATA_DIAGNOSTIC_VIEW,
  PERMISSIONS.MIGRATION_STATUS_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.SKILL_LEVEL_APPROVE,
  PERMISSIONS.SKILL_LEVEL_VERIFY_CLUB,
  PERMISSIONS.RANKING_VIEW,
  PERMISSIONS.RANKING_MANAGE,
  PERMISSIONS.TOURNAMENT_CERTIFY,
  PERMISSIONS.CLUSTER_VIEW,
  PERMISSIONS.CLUSTER_MANAGE,
  PERMISSIONS.PLAYER_VIEW,
];

const TEAM_CAPTAIN_PERMISSIONS = [
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.TEAM_VIEW,
  PERMISSIONS.TEAM_LINEUP_SUBMIT,
  PERMISSIONS.TEAM_STANDINGS_VIEW,
  PERMISSIONS.TEAM_MEMBER_VIEW,
  PERMISSIONS.TEAM_MEMBER_PROPOSE,
  PERMISSIONS.TEAM_MEMBER_MANAGE_LIMITED,
  PERMISSIONS.TEAM_LINEUP_VIEW,
  PERMISSIONS.TEAM_LINEUP_SUBMIT_V5,
  PERMISSIONS.TEAM_LINEUP_UPDATE_BEFORE_LOCK,
  PERMISSIONS.TEAM_SCHEDULE_VIEW,
  PERMISSIONS.TEAM_RESULT_VIEW,
  PERMISSIONS.TEAM_MESSAGE_SEND,
  PERMISSIONS.TEAM_CHECKIN_VIEW,
  PERMISSIONS.TEAM_CHECKIN_CONFIRM,
  PERMISSIONS.TEAM_ATTENDANCE_CONFIRM,
  PERMISSIONS.TEAM_SUBSTITUTION_REQUEST,
];

const TEAM_TOURNAMENT_MANAGE_PERMISSIONS = [
  PERMISSIONS.TEAM_EVENT_VIEW,
  PERMISSIONS.TEAM_EVENT_MANAGE,
  PERMISSIONS.EXISTING_TEAM_VIEW,
  PERMISSIONS.EXISTING_TEAM_SELECT,
  PERMISSIONS.EXISTING_TEAM_MANAGE,
  PERMISSIONS.IN_TOURNAMENT_TEAM_VIEW,
  PERMISSIONS.IN_TOURNAMENT_TEAM_CREATE,
  PERMISSIONS.IN_TOURNAMENT_TEAM_UPDATE,
  PERMISSIONS.IN_TOURNAMENT_TEAM_DELETE,
  PERMISSIONS.TEAM_MANUAL_SPLIT_VIEW,
  PERMISSIONS.TEAM_MANUAL_SPLIT_MANAGE,
  PERMISSIONS.TEAM_AUTO_DRAW_VIEW,
  PERMISSIONS.TEAM_AUTO_DRAW_MANAGE,
  PERMISSIONS.TEAM_DRAFT_VIEW,
  PERMISSIONS.TEAM_DRAFT_MANAGE,
  PERMISSIONS.TEAM_CAPTAIN_ASSIGN,
  PERMISSIONS.TEAM_CAPTAIN_REMOVE,
  PERMISSIONS.TEAM_CAPTAIN_VIEW,
  PERMISSIONS.TEAM_LINEUP_APPROVE,
  PERMISSIONS.TEAM_LINEUP_LOCK_V5,
  PERMISSIONS.TEAM_SUBSTITUTION_APPROVE,
];

const TEAM_TOURNAMENT_PERMISSIONS = [
  PERMISSIONS.TEAM_MANAGE,
  PERMISSIONS.TEAM_VIEW,
  PERMISSIONS.TEAM_LINEUP_LOCK,
  PERMISSIONS.TEAM_LINEUP_PUBLISH,
  PERMISSIONS.TEAM_LINEUP_RANDOMIZE,
  PERMISSIONS.TEAM_MATCH_RESULT_MANAGE,
  PERMISSIONS.TEAM_STANDINGS_VIEW,
  ...TEAM_TOURNAMENT_MANAGE_PERMISSIONS,
];

const VENUE_OPS = [
  PERMISSIONS.VENUE_VIEW,
  PERMISSIONS.COURT_VIEW,
  PERMISSIONS.COURT_CREATE,
  PERMISSIONS.COURT_UPDATE,
  PERMISSIONS.BOOKING_VIEW,
  PERMISSIONS.BOOKING_CREATE,
  PERMISSIONS.BOOKING_UPDATE,
  PERMISSIONS.CUSTOMER_VIEW,
  PERMISSIONS.FINANCE_VIEW,
  PERMISSIONS.CLUB_VIEW,
  PERMISSIONS.PLAYER_VIEW,
  PERMISSIONS.PLAYER_VIEW_SUMMARY,
  PERMISSIONS.PLAYER_VIEW_FOR_TOURNAMENT_INVITE,
  PERMISSIONS.SKILL_LEVEL_VIEW_PRIVATE,
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.TOURNAMENT_CREATE,
  PERMISSIONS.TOURNAMENT_UPDATE,
  PERMISSIONS.DIRECTOR_USE,
  PERMISSIONS.MATCH_UPDATE,
  PERMISSIONS.SCHEDULING_VIEW,
  PERMISSIONS.SCHEDULING_RUN,
  COURT_ENGINE_PERMISSIONS.USE,
  COURT_ENGINE_PERMISSIONS.MANAGE,
  COURT_ENGINE_PERMISSIONS.TRANSFER,
  PERMISSIONS.STATISTICS_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.RANKING_VIEW,
  ...TEAM_TOURNAMENT_PERMISSIONS,
];

const TENANT_OWNER_PERMISSIONS = [
  ...VENUE_OPS,
  PERMISSIONS.VENUE_UPDATE,
  PERMISSIONS.USER_MANAGE,
  PERMISSIONS.TENANT_ROLE_CUSTOMIZE,
  PERMISSIONS.SUBSCRIPTION_VIEW,
  PERMISSIONS.BILLING_VIEW,
  PERMISSIONS.BILLING_INVOICE_VIEW,
  PERMISSIONS.BILLING_PAYMENT_VIEW,
  PERMISSIONS.BILLING_SUBSCRIPTION_VIEW,
  PERMISSIONS.FINANCE_EDIT,
  PERMISSIONS.CLUB_CREATE,
  PERMISSIONS.CLUB_UPDATE,
  PERMISSIONS.CLUB_DELETE,
  PERMISSIONS.CLUB_GOVERNANCE_ASSIGN_OWNER,
  PERMISSIONS.CLUB_GOVERNANCE_APPROVE,
  PERMISSIONS.SEASON_UPDATE,
  PERMISSIONS.LEAGUE_UPDATE,
  PERMISSIONS.PLAYER_CREATE,
  PERMISSIONS.PLAYER_UPDATE,
  PERMISSIONS.PLAYER_DELETE,
  PERMISSIONS.COURT_DELETE,
  PERMISSIONS.BOOKING_DELETE,
  PERMISSIONS.CUSTOMER_CREATE,
  PERMISSIONS.CUSTOMER_UPDATE,
  PERMISSIONS.CUSTOMER_DELETE,
  PERMISSIONS.TOURNAMENT_DELETE,
  PERMISSIONS.STATISTICS_EXPORT,
  PERMISSIONS.SYSTEM_SETTING,
  PERMISSIONS.INTEGRATION_VIEW,
  PERMISSIONS.INTEGRATION_MANAGE,
  PERMISSIONS.MARKETPLACE_VIEW,
  PERMISSIONS.MARKETPLACE_MANAGE,
  PERMISSIONS.API_MANAGE,
  PERMISSIONS.RANKING_VIEW,
];

const VENUE_MANAGER_PERMISSIONS = [
  ...VENUE_OPS,
  PERMISSIONS.PLAYER_CREATE,
  PERMISSIONS.PLAYER_UPDATE,
  PERMISSIONS.PLAYER_DELETE,
  PERMISSIONS.COURT_UPDATE,
  PERMISSIONS.COURT_DELETE,
  PERMISSIONS.BOOKING_UPDATE,
  PERMISSIONS.BOOKING_DELETE,
  PERMISSIONS.CUSTOMER_UPDATE,
];

const TOURNAMENT_MANAGER_PERMISSIONS = [
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.TOURNAMENT_CREATE,
  PERMISSIONS.TOURNAMENT_UPDATE,
  PERMISSIONS.TOURNAMENT_DELETE,
  PERMISSIONS.DIRECTOR_USE,
  PERMISSIONS.MATCH_UPDATE,
  COURT_ENGINE_PERMISSIONS.USE,
  COURT_ENGINE_PERMISSIONS.MANAGE,
  PERMISSIONS.STATISTICS_VIEW,
  PERMISSIONS.STATISTICS_EXPORT,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.PLAYER_VIEW,
  PERMISSIONS.SKILL_LEVEL_VIEW_PRIVATE,
  PERMISSIONS.SKILL_LEVEL_VERIFY_TOURNAMENT,
  PERMISSIONS.VENUE_VIEW,
  ...TEAM_TOURNAMENT_PERMISSIONS,
];

const CASHIER_PERMISSIONS = [
  PERMISSIONS.COURT_VIEW,
  PERMISSIONS.BOOKING_VIEW,
  PERMISSIONS.BOOKING_CREATE,
  PERMISSIONS.CUSTOMER_VIEW,
  PERMISSIONS.FINANCE_VIEW,
  PERMISSIONS.FINANCE_EDIT,
];

const ACCOUNTANT_PERMISSIONS = [
  PERMISSIONS.BOOKING_VIEW,
  PERMISSIONS.CUSTOMER_VIEW,
  PERMISSIONS.FINANCE_VIEW,
  PERMISSIONS.FINANCE_EDIT,
  PERMISSIONS.STATISTICS_VIEW,
  PERMISSIONS.STATISTICS_EXPORT,
];

const CLUB_MANAGER_PERMISSIONS = [
  PERMISSIONS.CLUB_VIEW,
  PERMISSIONS.CLUB_UPDATE,
  PERMISSIONS.SEASON_UPDATE,
  PERMISSIONS.LEAGUE_UPDATE,
  PERMISSIONS.PLAYER_VIEW,
  PERMISSIONS.PLAYER_CREATE,
  PERMISSIONS.PLAYER_UPDATE,
  PERMISSIONS.PLAYER_DELETE,
  PERMISSIONS.SKILL_LEVEL_VIEW_PRIVATE,
  PERMISSIONS.SKILL_LEVEL_VERIFY_CLUB,
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.TOURNAMENT_CREATE,
  PERMISSIONS.TOURNAMENT_UPDATE,
  PERMISSIONS.TOURNAMENT_DELETE,
  PERMISSIONS.DIRECTOR_USE,
  PERMISSIONS.MATCH_UPDATE,
  PERMISSIONS.SCHEDULING_VIEW,
  PERMISSIONS.SCHEDULING_RUN,
  COURT_ENGINE_PERMISSIONS.USE,
  COURT_ENGINE_PERMISSIONS.MANAGE,
  COURT_ENGINE_PERMISSIONS.TRANSFER,
  PERMISSIONS.STATISTICS_VIEW,
  PERMISSIONS.STATISTICS_EXPORT,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.MARKETPLACE_VIEW,
  PERMISSIONS.INTEGRATION_VIEW,
  ...TEAM_TOURNAMENT_PERMISSIONS,
];

const COACH_PERMISSIONS = [
  PERMISSIONS.CLUB_VIEW,
  PERMISSIONS.PLAYER_VIEW,
  PERMISSIONS.PLAYER_UPDATE,
  PERMISSIONS.SCHEDULING_VIEW,
  PERMISSIONS.STATISTICS_VIEW,
  PERMISSIONS.TOURNAMENT_VIEW,
];

const STAFF_PERMISSIONS = [
  PERMISSIONS.COURT_VIEW,
  PERMISSIONS.BOOKING_VIEW,
  PERMISSIONS.BOOKING_CREATE,
  PERMISSIONS.BOOKING_UPDATE,
  PERMISSIONS.CUSTOMER_VIEW,
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.SCHEDULING_VIEW,
];

const REFEREE_PERMISSIONS = [
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.MATCH_UPDATE,
  PERMISSIONS.TEAM_MATCH_RESULT_MANAGE,
  PERMISSIONS.TEAM_STANDINGS_VIEW,
  PERMISSIONS.STATISTICS_VIEW,
];

const PLAYER_PERMISSIONS = [
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.STATISTICS_VIEW,
  PERMISSIONS.PLAYER_VIEW,
  PERMISSIONS.PLAYER_UPDATE,
  PERMISSIONS.SKILL_LEVEL_VIEW_PRIVATE,
  PERMISSIONS.SKILL_LEVEL_REQUEST_CHANGE,
  PERMISSIONS.TEAM_VIEW,
  PERMISSIONS.TEAM_LINEUP_SUBMIT,
  PERMISSIONS.TEAM_STANDINGS_VIEW,
];

const CUSTOMER_PERMISSIONS = [
  PERMISSIONS.BOOKING_VIEW,
  PERMISSIONS.BOOKING_CREATE,
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.PLAYER_VIEW,
  PERMISSIONS.CUSTOMER_VIEW,
];

const SUPPORT_PERMISSIONS = [
  PERMISSIONS.SUPPORT_TICKET_MANAGE,
  PERMISSIONS.USER_VIEW,
  PERMISSIONS.TENANT_VIEW,
  PERMISSIONS.ACTIVITY_LOG_VIEW,
  PERMISSIONS.INTEGRATION_VIEW,
];

/** Map canonical role → danh sách permission. */
export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.PLATFORM_ADMIN]: Object.freeze([...ALL_PERMISSIONS]),
  [ROLES.SYSTEM_TECHNICIAN]: Object.freeze(SYSTEM_TECHNICIAN_PERMISSIONS),
  [ROLES.TENANT_OWNER]: Object.freeze(TENANT_OWNER_PERMISSIONS),
  [ROLES.VENUE_MANAGER]: Object.freeze(VENUE_MANAGER_PERMISSIONS),
  [ROLES.TOURNAMENT_MANAGER]: Object.freeze(TOURNAMENT_MANAGER_PERMISSIONS),
  [ROLES.TEAM_CAPTAIN]: Object.freeze(TEAM_CAPTAIN_PERMISSIONS),
  [ROLES.CASHIER]: Object.freeze(CASHIER_PERMISSIONS),
  [ROLES.ACCOUNTANT]: Object.freeze(ACCOUNTANT_PERMISSIONS),
  [ROLES.CLUB_MANAGER]: Object.freeze(CLUB_MANAGER_PERMISSIONS),
  [ROLES.COACH]: Object.freeze(COACH_PERMISSIONS),
  [ROLES.REFEREE]: Object.freeze(REFEREE_PERMISSIONS),
  [ROLES.STAFF]: Object.freeze(STAFF_PERMISSIONS),
  [ROLES.PLAYER]: Object.freeze(PLAYER_PERMISSIONS),
  [ROLES.CUSTOMER]: Object.freeze(CUSTOMER_PERMISSIONS),
  [ROLES.SUPPORT]: Object.freeze(SUPPORT_PERMISSIONS),
});

export function getPermissionsForRole(role) {
  const canonical = normalizeRole(role);
  return ROLE_PERMISSIONS[canonical] || [];
}

export function roleHasPermission(role, permission) {
  return getPermissionsForRole(role).includes(permission);
}
