export {
  CORE13_ENGINE_ID,
  CORE13_ENGINE_VERSION,
  CORE13_SCHEMA_VERSION,
  CORE13_DETERMINISM_POLICY_ID,
  CORE13_COMPARATOR_VERSION,
  CORE13_CANONICAL_SERIALIZATION_VERSION,
  CORE13_IDENTITY,
} from "./versions.js";
