/**
 * Operator action matrix for Batch B. Class A = existing real authority,
 * B = partial existing authority (not bound when semantics differ),
 * C = no canonical authority. UI may keep the approved control location.
 */
export const BATCH_B_ACTION_MATRIX = Object.freeze([
  {
    screen: "04",
    action: "Xem trước",
    referenceAction: "Xem trước",
    currentProductionAuthority: "Existing public tournament page",
    class: "A",
    enabled: true,
    why: "Trang công khai hiện có.",
    mutationPath: null,
  },
  {
    screen: "04",
    action: "Công bố đăng ký",
    referenceAction: "Công bố đăng ký / Quản lý công bố",
    currentProductionAuthority: "None — no distinct publication state",
    class: "C",
    enabled: false,
    why: "Chưa có quyền công bố đăng ký riêng.",
    mutationPath: null,
  },
  {
    screen: "04",
    action: "Thêm VĐV",
    referenceAction: "Thêm VĐV",
    currentProductionAuthority: "Existing player registration page",
    class: "A",
    enabled: true,
    why: "Mở trang đăng ký VĐV hiện có.",
    mutationPath: null,
  },
  {
    screen: "04",
    action: "Sao chép liên kết",
    referenceAction: "Sao chép",
    currentProductionAuthority: "Public page URL copy",
    class: "A",
    enabled: true,
    why: "Sao chép đường dẫn trang công khai hiện có.",
    mutationPath: null,
  },
  {
    screen: "04",
    action: "QR đăng ký",
    referenceAction: "QR đăng ký",
    currentProductionAuthority: "None",
    class: "C",
    enabled: false,
    why: "Chưa phát hành QR đăng ký.",
    mutationPath: null,
  },
  {
    screen: "04",
    action: "Đóng đăng ký",
    referenceAction: "Đóng đăng ký",
    currentProductionAuthority: "lockRegistration conflates close + list lock + READY",
    class: "C",
    enabled: false,
    why: "Đóng đăng ký trên màn này chưa tách khỏi chốt danh sách.",
    mutationPath: null,
  },
  {
    screen: "04",
    action: "Duyệt",
    referenceAction: "Duyệt",
    currentProductionAuthority: "approveEntry exists on registration page",
    class: "B",
    enabled: false,
    why: "Duyệt trên trang đăng ký VĐV hiện có. Không duyệt tại màn này.",
    mutationPath: null,
  },
  {
    screen: "05",
    action: "Chốt danh sách",
    referenceAction: "Chốt danh sách",
    currentProductionAuthority: "None — not distinct from registration close",
    class: "C",
    enabled: false,
    why: "Chốt danh sách chưa có trên hệ thống này.",
    mutationPath: null,
  },
  {
    screen: "06",
    action: "Tạo cặp",
    referenceAction: "Tạo cặp",
    currentProductionAuthority: "None — no pair formation writer",
    class: "C",
    enabled: false,
    why: "Ghép thủ công chưa có trên hệ thống này.",
    mutationPath: null,
  },
  {
    screen: "06",
    action: "Chốt cặp / đội",
    referenceAction: "Chốt cặp / đội",
    currentProductionAuthority: "None",
    class: "C",
    enabled: false,
    why: "Chốt cặp / đội chưa có trên hệ thống này.",
    mutationPath: null,
  },
  {
    screen: "06",
    action: "Sang bốc thăm ghép",
    referenceAction: "Sang bốc thăm ghép",
    currentProductionAuthority: "Screen 07 not in this batch",
    class: "C",
    enabled: false,
    why: "Bốc thăm ghép chưa mở trên màn này.",
    mutationPath: null,
  },
]);
