/**
 * Communication Foundation — public facade.
 *
 * COMMS-01: Messaging Domain Foundation (contracts, domain, ports).
 * COMMS-02: Direct Messaging application capability (persistence-agnostic).
 * COMMS-03: Club Communication application capability (persistence-agnostic).
 * COMMS-04: Community Communication application capability (persistence-agnostic).
 * COMMS-05: Persistence & Realtime foundation (SQL package + adapters; not applied / not remote-wired).
 * COMMS-06: Messaging Experience (UI + experience gateway; demo/in-memory).
 * COMMS-07: Integration hardening & final certification (runtime/provider/production gateway).
 *
 * Consumers must import from this index — not from internal file paths —
 * once wiring begins in later phases.
 *
 * Does NOT export:
 * - raw SQL / migration text as domain contracts
 * - raw Supabase row types
 * - remote realtime connection / websocket clients
 * - notification delivery / inbox SoT
 * - Identity / Club / Player / Competition ownership surfaces
 */

export const COMMUNICATION_FOUNDATION_PHASE = Object.freeze({
  id: "COMMS-07",
  name: "integration-hardening-final-certification",
  priorPhase: "COMMS-06",
  wiredToProductionRuntime: true,
  hasPersistence: true,
  hasRealtime: true,
  persistenceApplied: false,
  realtimePublicationEnabled: false,
  clientRlsPolicy: "FAIL_CLOSED",
  hasUi: true,
  /** In-memory doubles exist for unit tests / demo gateway only — not production SoT. */
  hasInMemoryTestDoubles: true,
  /** Production-oriented adapters exist; require trusted injected client + activation gates. */
  hasProductionOrientedAdapters: true,
  /** Experience runtime selects DEMO | PRODUCTION | UNAVAILABLE — never silent demo in Prod. */
  experienceAdapterKind: "RUNTIME_RESOLVED",
  structureComplete: true,
  localDemoReady: true,
  productionBlocked: true,
});

export {
  CONVERSATION_TYPE,
  CONVERSATION_TYPE_VALUES,
  isConversationType,
  CONVERSATION_STATUS,
  CONVERSATION_STATUS_VALUES,
  CONVERSATION_TERMINAL_STATUSES,
  CONVERSATION_ALLOWED_TRANSITIONS,
  isConversationStatus,
  CONVERSATION_ROLE,
  CONVERSATION_ROLE_VALUES,
  isConversationRole,
  PARTICIPANT_STATUS,
  PARTICIPANT_STATUS_VALUES,
  PARTICIPANT_TERMINAL_STATUSES,
  PARTICIPANT_ALLOWED_TRANSITIONS,
  isParticipantStatus,
  MESSAGE_STATUS,
  MESSAGE_STATUS_VALUES,
  MESSAGE_TERMINAL_STATUSES,
  MESSAGE_ALLOWED_TRANSITIONS,
  isMessageStatus,
  MODERATION_ACTION_TYPE,
  MODERATION_ACTION_TYPE_VALUES,
  isModerationActionType,
  DIRECT_MESSAGING_ACCESS_DECISION,
  DIRECT_MESSAGING_ACCESS_DECISION_VALUES,
  DIRECT_MESSAGING_DENY_REASON,
  DIRECT_MESSAGING_DENY_REASON_VALUES,
  isDirectMessagingAccessDecision,
  isDirectMessagingDenyReason,
  CONVERSATION_REQUEST_STATUS,
  CONVERSATION_REQUEST_STATUS_VALUES,
  CONVERSATION_REQUEST_TERMINAL_STATUSES,
  CONVERSATION_REQUEST_ALLOWED_TRANSITIONS,
  isConversationRequestStatus,
  CLUB_CHANNEL_KIND,
  CLUB_CHANNEL_KIND_VALUES,
  DEFAULT_CLUB_CHANNEL_KINDS,
  isClubChannelKind,
  isDefaultClubChannelKind,
  CLUB_MEMBERSHIP_STATUS,
  CLUB_MEMBERSHIP_STATUS_VALUES,
  isClubMembershipStatus,
  isActiveClubMembership,
  CLUB_COMMUNICATION_ACCESS_DECISION,
  CLUB_COMMUNICATION_ACCESS_DECISION_VALUES,
  CLUB_COMMUNICATION_ACCESS_ACTION,
  CLUB_COMMUNICATION_ACCESS_ACTION_VALUES,
  CLUB_COMMUNICATION_DENY_REASON,
  CLUB_COMMUNICATION_DENY_REASON_VALUES,
  isClubCommunicationAccessDecision,
  isClubCommunicationAccessAction,
  isClubCommunicationDenyReason,
  COMMUNITY_CHANNEL_KIND,
  COMMUNITY_CHANNEL_KIND_VALUES,
  DEFAULT_COMMUNITY_CHANNEL_KINDS,
  isCommunityChannelKind,
  isDefaultCommunityChannelKind,
  COMMUNITY_CHANNEL_VISIBILITY,
  COMMUNITY_CHANNEL_VISIBILITY_VALUES,
  isCommunityChannelVisibility,
  COMMUNITY_CHANNEL_LIFECYCLE,
  COMMUNITY_CHANNEL_LIFECYCLE_VALUES,
  isCommunityChannelLifecycle,
  COMMUNITY_MEMBERSHIP_STATUS,
  COMMUNITY_MEMBERSHIP_STATUS_VALUES,
  isCommunityMembershipStatus,
  isActiveCommunityMembership,
  COMMUNITY_COMMUNICATION_ACCESS_DECISION,
  COMMUNITY_COMMUNICATION_ACCESS_DECISION_VALUES,
  COMMUNITY_COMMUNICATION_ACCESS_ACTION,
  COMMUNITY_COMMUNICATION_ACCESS_ACTION_VALUES,
  COMMUNITY_COMMUNICATION_DENY_REASON,
  COMMUNITY_COMMUNICATION_DENY_REASON_VALUES,
  isCommunityCommunicationAccessDecision,
  isCommunityCommunicationAccessAction,
  isCommunityCommunicationDenyReason,
  COMMUNITY_RESTRICTION_STATUS,
  COMMUNITY_RESTRICTION_STATUS_VALUES,
  COMMUNITY_RESTRICTION_SCOPE,
  COMMUNITY_RESTRICTION_SCOPE_VALUES,
  isCommunityRestrictionStatus,
  isCommunityRestrictionScope,
} from "./constants/index.js";

export {
  COMMUNICATION_FOUNDATION_ERROR_CODE,
  CommunicationFoundationError,
  isCommunicationFoundationError,
  isCommunicationFoundationErrorCode,
} from "./errors/index.js";

export {
  failContract,
  isNonEmptyString,
  isValidTimestamp,
  timestampSortValue,
  requireNonEmptyString,
  requireValidTimestamp,
  optionalNonEmptyString,
  deepFreeze,
  clonePlain,
  requireOpaqueId,
  createConversationId,
  createMessageId,
  createParticipantId,
  normalizeIdentifier,
  createConversationContract,
  isConversationContract,
  createConversationParticipantContract,
  isConversationParticipantContract,
  createReplyReferenceContract,
  createMessageContract,
  isMessageContract,
  MAX_REACTION_EMOJI_LENGTH,
  createReactionContract,
  createReadCursorContract,
  createAttachmentReferenceContract,
  createUserBlockContract,
  createMessageReportContract,
  createModerationActionContract,
  createDirectPairContract,
  buildDirectPairKey,
  isDirectPairMember,
  getDirectPairCounterpart,
  createDirectAccessDecisionContract,
  createConversationRequestContract,
  createDirectConversationSummaryContract,
  compareDirectConversationSummaries,
  buildDefaultClubChannelKey,
  buildClubChannelKey,
  createClubChannelIdentityContract,
  assertClubChannelClubImmutable,
  assertClubChannelKeyImmutable,
  createClubAccessDecisionContract,
  createClubMembershipFactContract,
  createClubChannelSummaryContract,
  compareClubChannelSummaries,
  createClubPinnedMessageContract,
  buildCommunityLobbyChannelKey,
  buildDefaultCommunityChannelKey,
  buildCommunityChannelKey,
  createCommunityChannelIdentityContract,
  assertCommunityChannelTenantImmutable,
  assertCommunityChannelKeyImmutable,
  createCommunityAccessDecisionContract,
  createCommunityMembershipFactContract,
  createCommunityRestrictionContract,
  createCommunityChannelSummaryContract,
  compareCommunityChannelSummaries,
  createCommunityPinnedMessageContract,
  createCommunitySlowModeConfigContract,
  evaluateCommunitySlowMode,
} from "./contracts/index.js";

export {
  assertConversationType,
  createValidConversation,
  transitionConversationStatus,
  addParticipant,
  updateParticipantRole,
  transitionParticipantStatus,
  suspendOrRemoveParticipant,
  assertCanSendMessage,
  findActiveParticipant,
  createMessageForConversation,
  assertReplyTargetInConversation,
  transitionMessageStatus,
  advanceReadCursor,
  validateAttachmentReference,
  validateReaction,
  validateUserBlock,
  validateMessageReport,
  validateModerationAction,
  resolveCanonicalDirectPair,
  assertActorInDirectPair,
  evaluateDirectMessagingAccess,
  assertDirectAccessAllowed,
  isConversationRequestTerminal,
  transitionConversationRequestStatus,
  acceptOrDeclineConversationRequest,
  cancelConversationRequest,
  countUnreadDirectMessages,
  buildDirectConversationSummary,
  sortDirectConversationSummaries,
  findActiveDirectParticipants,
  assertClubChannelKind,
  assertClubIdRequired,
  resolveClubChannelIdentity,
  denyReasonForMembership,
  evaluateClubChannelAccess,
  assertClubAccessAllowed,
  assertParticipantBelongsToClub,
  assertCannotMoveClubChannel,
  assertCannotChangeChannelKey,
  isExplicitActiveClubParticipant,
  isClubChannelAdminRole,
  countUnreadClubMessages,
  buildClubChannelSummary,
  sortClubChannelSummaries,
  findActiveClubParticipants,
  isPinnableClubMessage,
  assertCommunityChannelKind,
  assertCommunityChannelVisibility,
  assertTenantIdRequired,
  resolveCommunityChannelIdentity,
  denyReasonForCommunityMembership,
  evaluateCommunityChannelAccess,
  assertCommunityAccessAllowed,
  assertParticipantBelongsToTenant,
  assertCannotMoveCommunityChannel,
  assertCannotChangeCommunityChannelKey,
  isExplicitActiveCommunityParticipant,
  isCommunityChannelAdminRole,
  countUnreadCommunityMessages,
  buildCommunityChannelSummary,
  sortCommunityChannelSummaries,
  findActiveCommunityParticipants,
  isPinnableCommunityMessage,
} from "./domain/index.js";

export {
  throwPortUnimplemented,
  matchesPortMethods,
  IDENTITY_ACTOR_PORT_METHODS,
  matchesIdentityActorPort,
  createUnimplementedIdentityActorPort,
  PLAYER_DISPLAY_PORT_METHODS,
  matchesPlayerDisplayPort,
  createUnimplementedPlayerDisplayPort,
  CLUB_MEMBERSHIP_PORT_METHODS,
  matchesClubMembershipPort,
  createUnimplementedClubMembershipPort,
  TENANT_SCOPE_PORT_METHODS,
  matchesTenantScopePort,
  createUnimplementedTenantScopePort,
  NOTIFICATION_EMIT_PORT_METHODS,
  matchesNotificationEmitPort,
  createUnimplementedNotificationEmitPort,
  REALTIME_DELIVERY_PORT_METHODS,
  matchesRealtimeDeliveryPort,
  createUnimplementedRealtimeDeliveryPort,
  FILE_STORAGE_PORT_METHODS,
  matchesFileStoragePort,
  createUnimplementedFileStoragePort,
  AUDIT_EVENT_PORT_METHODS,
  matchesAuditEventPort,
  createUnimplementedAuditEventPort,
  CLOCK_PORT_METHODS,
  ID_PROVIDER_PORT_METHODS,
  matchesClockPort,
  matchesIdProviderPort,
  createUnimplementedClockPort,
  createUnimplementedIdProviderPort,
  DIRECT_CONVERSATION_REPOSITORY_METHODS,
  matchesDirectConversationRepository,
  createUnimplementedDirectConversationRepository,
  DIRECT_CONVERSATION_REQUEST_REPOSITORY_METHODS,
  matchesDirectConversationRequestRepository,
  createUnimplementedDirectConversationRequestRepository,
  DIRECT_MESSAGE_REPOSITORY_METHODS,
  matchesDirectMessageRepository,
  createUnimplementedDirectMessageRepository,
  DIRECT_READ_CURSOR_REPOSITORY_METHODS,
  matchesDirectReadCursorRepository,
  createUnimplementedDirectReadCursorRepository,
  BLOCK_STATE_READER_METHODS,
  matchesBlockStateReader,
  createUnimplementedBlockStateReader,
  DIRECT_MESSAGING_ACCESS_POLICY_METHODS,
  matchesDirectMessagingAccessPolicy,
  createUnimplementedDirectMessagingAccessPolicy,
  createAllowAllDirectMessagingAccessPolicy,
  CLUB_MEMBERSHIP_READER_METHODS,
  matchesClubMembershipReader,
  createUnimplementedClubMembershipReader,
  CLUB_COMMUNICATION_ACCESS_POLICY_METHODS,
  matchesClubCommunicationAccessPolicy,
  createUnimplementedClubCommunicationAccessPolicy,
  createDefaultClubCommunicationAccessPolicy,
  createAllowAllClubCommunicationAccessPolicy,
  TEAM_ACCESS_POLICY_METHODS,
  matchesTeamAccessPolicy,
  createUnimplementedTeamAccessPolicy,
  createDenyAllTeamAccessPolicy,
  createAllowAllTeamAccessPolicy,
  CLUB_CHANNEL_REPOSITORY_METHODS,
  matchesClubChannelRepository,
  createUnimplementedClubChannelRepository,
  CLUB_MESSAGE_REPOSITORY_METHODS,
  matchesClubMessageRepository,
  createUnimplementedClubMessageRepository,
  CLUB_READ_CURSOR_REPOSITORY_METHODS,
  matchesClubReadCursorRepository,
  createUnimplementedClubReadCursorRepository,
  CLUB_PINNED_MESSAGE_REPOSITORY_METHODS,
  matchesClubPinnedMessageRepository,
  createUnimplementedClubPinnedMessageRepository,
  COMMUNITY_CHANNEL_REPOSITORY_METHODS,
  matchesCommunityChannelRepository,
  createUnimplementedCommunityChannelRepository,
  COMMUNITY_MESSAGE_REPOSITORY_METHODS,
  matchesCommunityMessageRepository,
  createUnimplementedCommunityMessageRepository,
  COMMUNITY_READ_CURSOR_REPOSITORY_METHODS,
  matchesCommunityReadCursorRepository,
  createUnimplementedCommunityReadCursorRepository,
  COMMUNITY_PINNED_MESSAGE_REPOSITORY_METHODS,
  matchesCommunityPinnedMessageRepository,
  createUnimplementedCommunityPinnedMessageRepository,
  COMMUNITY_MEMBERSHIP_READER_METHODS,
  matchesCommunityMembershipReader,
  createUnimplementedCommunityMembershipReader,
  COMMUNITY_ACCESS_POLICY_METHODS,
  matchesCommunityAccessPolicy,
  createUnimplementedCommunityAccessPolicy,
  createDefaultCommunityAccessPolicy,
  createAllowAllCommunityAccessPolicy,
  COMMUNITY_MODERATION_POLICY_METHODS,
  matchesCommunityModerationPolicy,
  createUnimplementedCommunityModerationPolicy,
  createDenyAllCommunityModerationPolicy,
  createAllowAllCommunityModerationPolicy,
  createBypassSlowModeCommunityModerationPolicy,
  COMMUNITY_RESTRICTION_REPOSITORY_METHODS,
  matchesCommunityRestrictionRepository,
  createUnimplementedCommunityRestrictionRepository,
  COMMUNITY_REPORT_REPOSITORY_METHODS,
  matchesCommunityReportRepository,
  createUnimplementedCommunityReportRepository,
  COMMUNITY_MODERATION_ACTION_REPOSITORY_METHODS,
  matchesCommunityModerationActionRepository,
  createUnimplementedCommunityModerationActionRepository,
} from "./ports/index.js";

export {
  createDirectMessagingApplicationService,
  createDirectMessagingApplication,
  createSequentialIdProvider,
  createFixedClock,
  createMemoryIdentityActorPort,
  createClubCommunicationApplicationService,
  createClubCommunicationApplication,
  createMemoryClubMembershipReader,
  createCommunityCommunicationApplicationService,
  createCommunityCommunicationApplication,
  createMemoryCommunityMembershipReader,
} from "./application/index.js";

export {
  createInMemoryDirectMessagingRepositories,
  createInMemoryClubCommunicationRepositories,
  createInMemoryCommunityCommunicationRepositories,
} from "./repositories/index.js";

export {
  COMMUNICATION_TABLES,
  COMMUNICATION_TABLE_NAME_VALUES,
  ACTIVATION_GATES,
  COMMUNICATION_ACTIVATION_STATUS,
  getCommunicationActivationSnapshot,
  assertActivationAllowed,
  createSupabaseCommunicationRepositories,
  createFakeSupabaseCommunicationClient,
  mapSupabaseCommunicationError,
  COMMUNICATION_REALTIME_EVENT_TYPE,
  COMMUNICATION_REALTIME_EVENT_TYPE_VALUES,
  createCommunicationRealtimeEventEnvelope,
  createConversationRealtimeSubscriptionDescriptor,
  createInMemoryRealtimeDeliveryAdapter,
  createScopedRealtimeDeliveryAdapter,
  COMMUNICATION_DELIVERY_INTENT,
  COMMUNICATION_OUTBOX_INTEGRATION_GATES,
  createCommunicationPersistenceEventIntent,
  createCommunicationPersistenceEventRepository,
} from "./persistence/index.js";

export {
  MESSAGING_EXPERIENCE_PHASE,
  MESSAGING_ROUTE_PATH,
  MESSAGING_MENU_KEY,
  MESSAGING_TAB,
  MESSAGING_TAB_VALUES,
  MESSAGING_TAB_LABEL,
  MESSAGE_BODY_MAX_LENGTH,
  MESSAGE_PREVIEW_MAX_LENGTH,
  DEMO_GATEWAY_MARKER,
  COMMUNICATION_EXPERIENCE_GATEWAY_METHODS,
  matchesCommunicationExperienceGateway,
  asPlainText,
  sanitizeMessageBodyForDisplay,
  truncatePreview,
  createParticipantProjectionVm,
  createDirectConversationListItemVm,
  createDirectRequestListItemVm,
  createClubChannelListItemVm,
  createCommunityChannelListItemVm,
  createMessageItemVm,
  createAccessDecisionVm,
  createUnreadBadgeVm,
  validateComposerBody,
  assertNotRawPersistenceRow,
  createDemoMessagingExperienceGateway,
} from "./experience/publicApi.js";

export {
  COMMUNICATION_RUNTIME_MODE,
  COMMUNICATION_RUNTIME_MODE_VALUES,
  COMMUNICATION_RUNTIME_PHASE,
  PRODUCTION_GATEWAY_MARKER,
  UNAVAILABLE_GATEWAY_MARKER,
  COMMUNICATION_RUNTIME_UNAVAILABLE_USER_MESSAGE,
  COMMUNICATION_EXPERIENCE_ERROR_CODE,
  resolveCommunicationRuntimeMode,
  isCommunicationRuntimeMode,
  mapToCommunicationExperienceError,
  createSafeCommunicationDiagnosticEvent,
  createRuntimeNotActivatedError,
  createUnavailableMessagingExperienceGateway,
  createProductionMessagingExperienceGateway,
  bootstrapCommunicationRuntime,
  getCommunicationRuntimeStatus,
  getCommunicationRuntimeGateway,
  resetCommunicationRuntime,
  setCommunicationRuntimeAuthenticated,
} from "./runtime/publicApi.js";
