/**
 * Communication Foundation — public facade.
 *
 * COMMS-01: Messaging Domain Foundation (contracts, domain, ports).
 * COMMS-02: Direct Messaging application capability (persistence-agnostic).
 *
 * Consumers must import from this index — not from internal file paths —
 * once wiring begins in later phases.
 *
 * Does NOT export:
 * - SQL / migrations / Supabase clients
 * - realtime runtime wiring
 * - notification delivery / inbox SoT
 * - UI / routes / React hooks
 * - Identity / Club / Player / Competition ownership surfaces
 * - production database repositories
 */

export const COMMUNICATION_FOUNDATION_PHASE = Object.freeze({
  id: "COMMS-02",
  name: "direct-messaging",
  priorPhase: "COMMS-01",
  wiredToProductionRuntime: false,
  hasPersistence: false,
  hasRealtime: false,
  hasUi: false,
  /** In-memory doubles exist for unit tests only — not production SoT. */
  hasInMemoryTestDoubles: true,
});

export {
  CONVERSATION_TYPE,
  CONVERSATION_TYPE_VALUES,
  isConversationType,
  CONVERSATION_STATUS,
  CONVERSATION_STATUS_VALUES,
  CONVERSATION_TERMINAL_STATUSES,
  CONVERSATION_ALLOWED_TRANSITIONS,
  isConversationStatus,
  CONVERSATION_ROLE,
  CONVERSATION_ROLE_VALUES,
  isConversationRole,
  PARTICIPANT_STATUS,
  PARTICIPANT_STATUS_VALUES,
  PARTICIPANT_TERMINAL_STATUSES,
  PARTICIPANT_ALLOWED_TRANSITIONS,
  isParticipantStatus,
  MESSAGE_STATUS,
  MESSAGE_STATUS_VALUES,
  MESSAGE_TERMINAL_STATUSES,
  MESSAGE_ALLOWED_TRANSITIONS,
  isMessageStatus,
  MODERATION_ACTION_TYPE,
  MODERATION_ACTION_TYPE_VALUES,
  isModerationActionType,
  DIRECT_MESSAGING_ACCESS_DECISION,
  DIRECT_MESSAGING_ACCESS_DECISION_VALUES,
  DIRECT_MESSAGING_DENY_REASON,
  DIRECT_MESSAGING_DENY_REASON_VALUES,
  isDirectMessagingAccessDecision,
  isDirectMessagingDenyReason,
  CONVERSATION_REQUEST_STATUS,
  CONVERSATION_REQUEST_STATUS_VALUES,
  CONVERSATION_REQUEST_TERMINAL_STATUSES,
  CONVERSATION_REQUEST_ALLOWED_TRANSITIONS,
  isConversationRequestStatus,
} from "./constants/index.js";

export {
  COMMUNICATION_FOUNDATION_ERROR_CODE,
  CommunicationFoundationError,
  isCommunicationFoundationError,
  isCommunicationFoundationErrorCode,
} from "./errors/index.js";

export {
  failContract,
  isNonEmptyString,
  isValidTimestamp,
  timestampSortValue,
  requireNonEmptyString,
  requireValidTimestamp,
  optionalNonEmptyString,
  deepFreeze,
  clonePlain,
  requireOpaqueId,
  createConversationId,
  createMessageId,
  createParticipantId,
  normalizeIdentifier,
  createConversationContract,
  isConversationContract,
  createConversationParticipantContract,
  isConversationParticipantContract,
  createReplyReferenceContract,
  createMessageContract,
  isMessageContract,
  MAX_REACTION_EMOJI_LENGTH,
  createReactionContract,
  createReadCursorContract,
  createAttachmentReferenceContract,
  createUserBlockContract,
  createMessageReportContract,
  createModerationActionContract,
  createDirectPairContract,
  buildDirectPairKey,
  isDirectPairMember,
  getDirectPairCounterpart,
  createDirectAccessDecisionContract,
  createConversationRequestContract,
  createDirectConversationSummaryContract,
  compareDirectConversationSummaries,
} from "./contracts/index.js";

export {
  assertConversationType,
  createValidConversation,
  transitionConversationStatus,
  addParticipant,
  updateParticipantRole,
  transitionParticipantStatus,
  suspendOrRemoveParticipant,
  assertCanSendMessage,
  findActiveParticipant,
  createMessageForConversation,
  assertReplyTargetInConversation,
  transitionMessageStatus,
  advanceReadCursor,
  validateAttachmentReference,
  validateReaction,
  validateUserBlock,
  validateMessageReport,
  validateModerationAction,
  resolveCanonicalDirectPair,
  assertActorInDirectPair,
  evaluateDirectMessagingAccess,
  assertDirectAccessAllowed,
  isConversationRequestTerminal,
  transitionConversationRequestStatus,
  acceptOrDeclineConversationRequest,
  cancelConversationRequest,
  countUnreadDirectMessages,
  buildDirectConversationSummary,
  sortDirectConversationSummaries,
  findActiveDirectParticipants,
} from "./domain/index.js";

export {
  throwPortUnimplemented,
  matchesPortMethods,
  IDENTITY_ACTOR_PORT_METHODS,
  matchesIdentityActorPort,
  createUnimplementedIdentityActorPort,
  PLAYER_DISPLAY_PORT_METHODS,
  matchesPlayerDisplayPort,
  createUnimplementedPlayerDisplayPort,
  CLUB_MEMBERSHIP_PORT_METHODS,
  matchesClubMembershipPort,
  createUnimplementedClubMembershipPort,
  TENANT_SCOPE_PORT_METHODS,
  matchesTenantScopePort,
  createUnimplementedTenantScopePort,
  NOTIFICATION_EMIT_PORT_METHODS,
  matchesNotificationEmitPort,
  createUnimplementedNotificationEmitPort,
  REALTIME_DELIVERY_PORT_METHODS,
  matchesRealtimeDeliveryPort,
  createUnimplementedRealtimeDeliveryPort,
  FILE_STORAGE_PORT_METHODS,
  matchesFileStoragePort,
  createUnimplementedFileStoragePort,
  AUDIT_EVENT_PORT_METHODS,
  matchesAuditEventPort,
  createUnimplementedAuditEventPort,
  CLOCK_PORT_METHODS,
  ID_PROVIDER_PORT_METHODS,
  matchesClockPort,
  matchesIdProviderPort,
  createUnimplementedClockPort,
  createUnimplementedIdProviderPort,
  DIRECT_CONVERSATION_REPOSITORY_METHODS,
  matchesDirectConversationRepository,
  createUnimplementedDirectConversationRepository,
  DIRECT_CONVERSATION_REQUEST_REPOSITORY_METHODS,
  matchesDirectConversationRequestRepository,
  createUnimplementedDirectConversationRequestRepository,
  DIRECT_MESSAGE_REPOSITORY_METHODS,
  matchesDirectMessageRepository,
  createUnimplementedDirectMessageRepository,
  DIRECT_READ_CURSOR_REPOSITORY_METHODS,
  matchesDirectReadCursorRepository,
  createUnimplementedDirectReadCursorRepository,
  BLOCK_STATE_READER_METHODS,
  matchesBlockStateReader,
  createUnimplementedBlockStateReader,
  DIRECT_MESSAGING_ACCESS_POLICY_METHODS,
  matchesDirectMessagingAccessPolicy,
  createUnimplementedDirectMessagingAccessPolicy,
  createAllowAllDirectMessagingAccessPolicy,
} from "./ports/index.js";

export {
  createDirectMessagingApplicationService,
  createDirectMessagingApplication,
  createSequentialIdProvider,
  createFixedClock,
  createMemoryIdentityActorPort,
} from "./application/index.js";

export { createInMemoryDirectMessagingRepositories } from "./repositories/index.js";
