/**
 * Canonical Coaching & Training error codes (COACHING-01).
 * Persistence-neutral — no HTTP mapping here.
 */

export const COACHING_ERROR_CODES = Object.freeze({
  INVALID_INPUT: "COACHING_INVALID_INPUT",
  INVALID_REFERENCE: "COACHING_INVALID_REFERENCE",
  INVALID_STATUS: "COACHING_INVALID_STATUS",
  INVALID_TRANSITION: "COACHING_INVALID_TRANSITION",
  UNAUTHORIZED: "COACHING_UNAUTHORIZED",
  FORBIDDEN_SCOPE: "COACHING_FORBIDDEN_SCOPE",
  FORBIDDEN_ACTION: "COACHING_FORBIDDEN_ACTION",
  MISSING_ACTOR: "COACHING_MISSING_ACTOR",
  MISSING_SCOPE: "COACHING_MISSING_SCOPE",
  NOT_FOUND: "COACHING_NOT_FOUND",
  CONFLICT: "COACHING_CONFLICT",
  DUPLICATE: "COACHING_DUPLICATE",
  VERSION_CONFLICT: "COACHING_VERSION_CONFLICT",
  DEPENDENCY_UNAVAILABLE: "COACHING_DEPENDENCY_UNAVAILABLE",
  REPOSITORY_CONTRACT_VIOLATION: "COACHING_REPOSITORY_CONTRACT_VIOLATION",
  RUNTIME_NOT_CONFIGURED: "COACHING_RUNTIME_NOT_CONFIGURED",
  IMMUTABLE_RECORD: "COACHING_IMMUTABLE_RECORD",
  ENTITLEMENT_EXHAUSTED: "COACHING_ENTITLEMENT_EXHAUSTED",
});

export const COACHING_ERROR_CODE_VALUES = Object.freeze(
  Object.values(COACHING_ERROR_CODES)
);

/**
 * @param {string} code
 * @returns {boolean}
 */
export function isCoachingErrorCode(code) {
  return COACHING_ERROR_CODE_VALUES.includes(code);
}
