import { NOTIFICATION_EVENT_TYPES } from "./notificationEvents.js";
import { NOTIFICATION_CATEGORIES } from "./notificationCategories.js";
import { NOTIFICATION_PRIORITIES } from "./notificationPriorities.js";

/**
 * Default category + priority per canonical event type.
 */
export const EVENT_CLASSIFICATION = Object.freeze({
  [NOTIFICATION_EVENT_TYPES.COMPETITION_PUBLISHED]: {
    category: NOTIFICATION_CATEGORIES.COMPETITION,
    priority: NOTIFICATION_PRIORITIES.HIGH,
  },
  [NOTIFICATION_EVENT_TYPES.REGISTRATION_CONFIRMED]: {
    category: NOTIFICATION_CATEGORIES.COMPETITION,
    priority: NOTIFICATION_PRIORITIES.NORMAL,
  },
  [NOTIFICATION_EVENT_TYPES.LINEUP_DEADLINE_APPROACHING]: {
    category: NOTIFICATION_CATEGORIES.COMPETITION,
    priority: NOTIFICATION_PRIORITIES.HIGH,
  },
  [NOTIFICATION_EVENT_TYPES.LINEUP_LOCKED]: {
    category: NOTIFICATION_CATEGORIES.COMPETITION,
    priority: NOTIFICATION_PRIORITIES.HIGH,
  },
  [NOTIFICATION_EVENT_TYPES.MATCH_SCHEDULED]: {
    category: NOTIFICATION_CATEGORIES.COMPETITION,
    priority: NOTIFICATION_PRIORITIES.NORMAL,
  },
  [NOTIFICATION_EVENT_TYPES.MATCH_STARTING_SOON]: {
    category: NOTIFICATION_CATEGORIES.COMPETITION,
    priority: NOTIFICATION_PRIORITIES.HIGH,
  },
  [NOTIFICATION_EVENT_TYPES.COURT_CHANGED]: {
    category: NOTIFICATION_CATEGORIES.COMPETITION,
    priority: NOTIFICATION_PRIORITIES.HIGH,
  },
  [NOTIFICATION_EVENT_TYPES.SCORE_SUBMITTED]: {
    category: NOTIFICATION_CATEGORIES.COMPETITION,
    priority: NOTIFICATION_PRIORITIES.NORMAL,
  },
  [NOTIFICATION_EVENT_TYPES.RESULT_CONFIRMED]: {
    category: NOTIFICATION_CATEGORIES.COMPETITION,
    priority: NOTIFICATION_PRIORITIES.NORMAL,
  },
  [NOTIFICATION_EVENT_TYPES.COMPETITION_COMPLETED]: {
    category: NOTIFICATION_CATEGORIES.COMPETITION,
    priority: NOTIFICATION_PRIORITIES.NORMAL,
  },
  [NOTIFICATION_EVENT_TYPES.CLUB_INVITATION_CREATED]: {
    category: NOTIFICATION_CATEGORIES.CLUB,
    priority: NOTIFICATION_PRIORITIES.NORMAL,
  },
  [NOTIFICATION_EVENT_TYPES.CLUB_SCHEDULE_UPDATED]: {
    category: NOTIFICATION_CATEGORIES.CLUB,
    priority: NOTIFICATION_PRIORITIES.NORMAL,
  },
  [NOTIFICATION_EVENT_TYPES.PAYMENT_CONFIRMED]: {
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    priority: NOTIFICATION_PRIORITIES.HIGH,
  },
  [NOTIFICATION_EVENT_TYPES.PAYMENT_FAILED]: {
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    priority: NOTIFICATION_PRIORITIES.HIGH,
  },
  [NOTIFICATION_EVENT_TYPES.SUBSCRIPTION_EXPIRING]: {
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    priority: NOTIFICATION_PRIORITIES.CRITICAL,
  },
  [NOTIFICATION_EVENT_TYPES.BOOKING_CREATED]: {
    category: NOTIFICATION_CATEGORIES.BOOKING,
    priority: NOTIFICATION_PRIORITIES.NORMAL,
  },
  [NOTIFICATION_EVENT_TYPES.BOOKING_CANCELLED]: {
    category: NOTIFICATION_CATEGORIES.BOOKING,
    priority: NOTIFICATION_PRIORITIES.HIGH,
  },
});

export function getEventClassification(eventType) {
  return EVENT_CLASSIFICATION[eventType] || null;
}
