/**
 * Canonical notification event catalogue (Phase 1.1).
 * Contract-only in this phase — callers are not fully wired yet.
 */
export const NOTIFICATION_EVENT_TYPES = Object.freeze({
  COMPETITION_PUBLISHED: "COMPETITION_PUBLISHED",
  REGISTRATION_CONFIRMED: "REGISTRATION_CONFIRMED",
  LINEUP_DEADLINE_APPROACHING: "LINEUP_DEADLINE_APPROACHING",
  LINEUP_LOCKED: "LINEUP_LOCKED",
  MATCH_SCHEDULED: "MATCH_SCHEDULED",
  MATCH_STARTING_SOON: "MATCH_STARTING_SOON",
  COURT_CHANGED: "COURT_CHANGED",
  SCORE_SUBMITTED: "SCORE_SUBMITTED",
  RESULT_CONFIRMED: "RESULT_CONFIRMED",
  COMPETITION_COMPLETED: "COMPETITION_COMPLETED",
  CLUB_INVITATION_CREATED: "CLUB_INVITATION_CREATED",
  CLUB_SCHEDULE_UPDATED: "CLUB_SCHEDULE_UPDATED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  SUBSCRIPTION_EXPIRING: "SUBSCRIPTION_EXPIRING",
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
});

/** Ordered list for docs / QA. */
export const NOTIFICATION_EVENT_CATALOGUE = Object.freeze(
  Object.values(NOTIFICATION_EVENT_TYPES)
);

export function isKnownNotificationEventType(eventType) {
  return NOTIFICATION_EVENT_CATALOGUE.includes(eventType);
}
