/**
 * CM-07 suspension / cancellation reason codes.
 * Stable codes only — unknown codes are rejected (no silent normalize).
 */

export const COMPETITION_SUSPENSION_REASON_CODE = Object.freeze({
  SAFETY: "SAFETY",
  VENUE_UNAVAILABLE: "VENUE_UNAVAILABLE",
  WEATHER: "WEATHER",
  OPERATIONAL: "OPERATIONAL",
  COMPLIANCE_REVIEW: "COMPLIANCE_REVIEW",
  DISPUTE: "DISPUTE",
  SYSTEM_INCIDENT: "SYSTEM_INCIDENT",
  ORGANIZER_REQUEST: "ORGANIZER_REQUEST",
  OTHER: "OTHER",
});

export const COMPETITION_SUSPENSION_REASON_CODE_VALUES = Object.freeze(
  Object.values(COMPETITION_SUSPENSION_REASON_CODE)
);

export const COMPETITION_SUSPENSION_REASON_CATEGORY = Object.freeze({
  SAFETY: "SAFETY",
  VENUE: "VENUE",
  WEATHER: "WEATHER",
  OPERATIONS: "OPERATIONS",
  COMPLIANCE: "COMPLIANCE",
  DISPUTE: "DISPUTE",
  SYSTEM: "SYSTEM",
  ORGANIZER: "ORGANIZER",
  OTHER: "OTHER",
});

export const COMPETITION_SUSPENSION_REASON_CATEGORY_BY_CODE = Object.freeze({
  [COMPETITION_SUSPENSION_REASON_CODE.SAFETY]:
    COMPETITION_SUSPENSION_REASON_CATEGORY.SAFETY,
  [COMPETITION_SUSPENSION_REASON_CODE.VENUE_UNAVAILABLE]:
    COMPETITION_SUSPENSION_REASON_CATEGORY.VENUE,
  [COMPETITION_SUSPENSION_REASON_CODE.WEATHER]:
    COMPETITION_SUSPENSION_REASON_CATEGORY.WEATHER,
  [COMPETITION_SUSPENSION_REASON_CODE.OPERATIONAL]:
    COMPETITION_SUSPENSION_REASON_CATEGORY.OPERATIONS,
  [COMPETITION_SUSPENSION_REASON_CODE.COMPLIANCE_REVIEW]:
    COMPETITION_SUSPENSION_REASON_CATEGORY.COMPLIANCE,
  [COMPETITION_SUSPENSION_REASON_CODE.DISPUTE]:
    COMPETITION_SUSPENSION_REASON_CATEGORY.DISPUTE,
  [COMPETITION_SUSPENSION_REASON_CODE.SYSTEM_INCIDENT]:
    COMPETITION_SUSPENSION_REASON_CATEGORY.SYSTEM,
  [COMPETITION_SUSPENSION_REASON_CODE.ORGANIZER_REQUEST]:
    COMPETITION_SUSPENSION_REASON_CATEGORY.ORGANIZER,
  [COMPETITION_SUSPENSION_REASON_CODE.OTHER]:
    COMPETITION_SUSPENSION_REASON_CATEGORY.OTHER,
});

export const COMPETITION_CANCELLATION_REASON_CODE = Object.freeze({
  ORGANIZER_DECISION: "ORGANIZER_DECISION",
  INSUFFICIENT_PARTICIPATION: "INSUFFICIENT_PARTICIPATION",
  VENUE_UNAVAILABLE: "VENUE_UNAVAILABLE",
  SAFETY: "SAFETY",
  COMPLIANCE: "COMPLIANCE",
  FORCE_MAJEURE: "FORCE_MAJEURE",
  DUPLICATE_COMPETITION: "DUPLICATE_COMPETITION",
  OTHER: "OTHER",
});

export const COMPETITION_CANCELLATION_REASON_CODE_VALUES = Object.freeze(
  Object.values(COMPETITION_CANCELLATION_REASON_CODE)
);

export const COMPETITION_CANCELLATION_REASON_CATEGORY = Object.freeze({
  ORGANIZER: "ORGANIZER",
  PARTICIPATION: "PARTICIPATION",
  VENUE: "VENUE",
  SAFETY: "SAFETY",
  COMPLIANCE: "COMPLIANCE",
  FORCE_MAJEURE: "FORCE_MAJEURE",
  DUPLICATE: "DUPLICATE",
  OTHER: "OTHER",
});

export const COMPETITION_CANCELLATION_REASON_CATEGORY_BY_CODE = Object.freeze({
  [COMPETITION_CANCELLATION_REASON_CODE.ORGANIZER_DECISION]:
    COMPETITION_CANCELLATION_REASON_CATEGORY.ORGANIZER,
  [COMPETITION_CANCELLATION_REASON_CODE.INSUFFICIENT_PARTICIPATION]:
    COMPETITION_CANCELLATION_REASON_CATEGORY.PARTICIPATION,
  [COMPETITION_CANCELLATION_REASON_CODE.VENUE_UNAVAILABLE]:
    COMPETITION_CANCELLATION_REASON_CATEGORY.VENUE,
  [COMPETITION_CANCELLATION_REASON_CODE.SAFETY]:
    COMPETITION_CANCELLATION_REASON_CATEGORY.SAFETY,
  [COMPETITION_CANCELLATION_REASON_CODE.COMPLIANCE]:
    COMPETITION_CANCELLATION_REASON_CATEGORY.COMPLIANCE,
  [COMPETITION_CANCELLATION_REASON_CODE.FORCE_MAJEURE]:
    COMPETITION_CANCELLATION_REASON_CATEGORY.FORCE_MAJEURE,
  [COMPETITION_CANCELLATION_REASON_CODE.DUPLICATE_COMPETITION]:
    COMPETITION_CANCELLATION_REASON_CATEGORY.DUPLICATE,
  [COMPETITION_CANCELLATION_REASON_CODE.OTHER]:
    COMPETITION_CANCELLATION_REASON_CATEGORY.OTHER,
});

export const COMPETITION_RESUME_REASON_CODE = Object.freeze({
  CONDITIONS_CLEARED: "CONDITIONS_CLEARED",
  ORGANIZER_REQUEST: "ORGANIZER_REQUEST",
  AUTHORITY_APPROVED: "AUTHORITY_APPROVED",
  OTHER: "OTHER",
});

export const COMPETITION_RESUME_REASON_CODE_VALUES = Object.freeze(
  Object.values(COMPETITION_RESUME_REASON_CODE)
);

export const COMPETITION_RESUME_REASON_CATEGORY = Object.freeze({
  OPERATIONS: "OPERATIONS",
  ORGANIZER: "ORGANIZER",
  AUTHORITY: "AUTHORITY",
  OTHER: "OTHER",
});

export const COMPETITION_RESUME_REASON_CATEGORY_BY_CODE = Object.freeze({
  [COMPETITION_RESUME_REASON_CODE.CONDITIONS_CLEARED]:
    COMPETITION_RESUME_REASON_CATEGORY.OPERATIONS,
  [COMPETITION_RESUME_REASON_CODE.ORGANIZER_REQUEST]:
    COMPETITION_RESUME_REASON_CATEGORY.ORGANIZER,
  [COMPETITION_RESUME_REASON_CODE.AUTHORITY_APPROVED]:
    COMPETITION_RESUME_REASON_CATEGORY.AUTHORITY,
  [COMPETITION_RESUME_REASON_CODE.OTHER]:
    COMPETITION_RESUME_REASON_CATEGORY.OTHER,
});

export const COMPETITION_LIFECYCLE_REASON_SUMMARY_MAX_LENGTH = 280;
export const COMPETITION_LIFECYCLE_REASON_DETAIL_MAX_LENGTH = 1000;
export const COMPETITION_LIFECYCLE_REASON_OTHER_MIN_DETAIL_LENGTH = 8;

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isCompetitionSuspensionReasonCode(value) {
  return (
    typeof value === "string" &&
    COMPETITION_SUSPENSION_REASON_CODE_VALUES.includes(value)
  );
}

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isCompetitionCancellationReasonCode(value) {
  return (
    typeof value === "string" &&
    COMPETITION_CANCELLATION_REASON_CODE_VALUES.includes(value)
  );
}

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isCompetitionResumeReasonCode(value) {
  return (
    typeof value === "string" &&
    COMPETITION_RESUME_REASON_CODE_VALUES.includes(value)
  );
}
