/**
 * CORE-20 — typed audit error taxonomy (capability-local).
 * Do not reuse MATCH_* / SCORING_* / WORKFLOW_* / Identity codes.
 */

export const AUDIT_ERROR_CODE = Object.freeze({
  AUDIT_INVALID_EVENT: "AUDIT_INVALID_EVENT",
  AUDIT_DUPLICATE_EVENT_ID: "AUDIT_DUPLICATE_EVENT_ID",
  AUDIT_INVALID_SEQUENCE: "AUDIT_INVALID_SEQUENCE",
  AUDIT_MISSING_CORRELATION: "AUDIT_MISSING_CORRELATION",
  AUDIT_INVALID_CAUSATION: "AUDIT_INVALID_CAUSATION",
  AUDIT_INVALID_ACTOR: "AUDIT_INVALID_ACTOR",
  AUDIT_INVALID_SUBJECT: "AUDIT_INVALID_SUBJECT",
  AUDIT_INCOMPATIBLE_VERSION: "AUDIT_INCOMPATIBLE_VERSION",
  AUDIT_PROHIBITED_CONTENT: "AUDIT_PROHIBITED_CONTENT",
  AUDIT_NON_DETERMINISTIC_METADATA: "AUDIT_NON_DETERMINISTIC_METADATA",
  AUDIT_INTEGRITY_MISMATCH: "AUDIT_INTEGRITY_MISMATCH",
  AUDIT_ORDERING_VIOLATION: "AUDIT_ORDERING_VIOLATION",
  AUDIT_QUERY_INVALID: "AUDIT_QUERY_INVALID",
  AUDIT_ADAPTER_INPUT_INVALID: "AUDIT_ADAPTER_INPUT_INVALID",
});

/** @type {ReadonlySet<string>} */
export const AUDIT_ERROR_CODE_VALUES = new Set(Object.values(AUDIT_ERROR_CODE));

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isAuditErrorCode(value) {
  return typeof value === "string" && AUDIT_ERROR_CODE_VALUES.has(value);
}
