/**
 * Reporting & Analytics — module-local typed error / availability codes (REPORTING-01).
 * Not registered in API_ERROR_CODES in this phase (same pattern as NEWS/COMMS/ECO).
 */

export const REPORTING_ERROR_CODE = Object.freeze({
  INVALID_IDENTITY: "REPORTING_INVALID_IDENTITY",
  INVALID_CONTRACT: "REPORTING_INVALID_CONTRACT",
  INVALID_SCOPE: "REPORTING_INVALID_SCOPE",
  INVALID_PARAMETERS: "REPORTING_INVALID_PARAMETERS",
  INVALID_FILTER: "REPORTING_INVALID_FILTER",
  INVALID_SORT: "REPORTING_INVALID_SORT",
  INVALID_GROUPING: "REPORTING_INVALID_GROUPING",
  INVALID_COLUMN_SELECTION: "REPORTING_INVALID_COLUMN_SELECTION",
  INVALID_SOURCE_REFERENCE: "REPORTING_INVALID_SOURCE_REFERENCE",
  INVALID_REPORT_DEFINITION: "REPORTING_INVALID_REPORT_DEFINITION",
  INVALID_SAVED_REPORT: "REPORTING_INVALID_SAVED_REPORT",
  INVALID_SAVED_FILTER: "REPORTING_INVALID_SAVED_FILTER",
  INVALID_EXPORT_REQUEST: "REPORTING_INVALID_EXPORT_REQUEST",
  INVALID_EXPORT_FORMAT: "REPORTING_INVALID_EXPORT_FORMAT",
  DEFINITION_NOT_FOUND: "REPORTING_DEFINITION_NOT_FOUND",
  SAVED_REPORT_NOT_FOUND: "REPORTING_SAVED_REPORT_NOT_FOUND",
  SAVED_FILTER_NOT_FOUND: "REPORTING_SAVED_FILTER_NOT_FOUND",
  EXPORT_JOB_NOT_FOUND: "REPORTING_EXPORT_JOB_NOT_FOUND",
  EXECUTION_NOT_FOUND: "REPORTING_EXECUTION_NOT_FOUND",
  DUPLICATE_IDENTITY: "REPORTING_DUPLICATE_IDENTITY",
  IDEMPOTENCY_CONFLICT: "REPORTING_IDEMPOTENCY_CONFLICT",
  VERSION_CONFLICT: "REPORTING_VERSION_CONFLICT",
  AUTHORIZATION_DENIED: "REPORTING_AUTHORIZATION_DENIED",
  MISSING_ACTOR: "REPORTING_MISSING_ACTOR",
  MISSING_SCOPE: "REPORTING_MISSING_SCOPE",
  FORBIDDEN_SCOPE: "REPORTING_FORBIDDEN_SCOPE",
  FORBIDDEN_PERMISSION: "REPORTING_FORBIDDEN_PERMISSION",
  SOURCE_NOT_CONFIGURED: "REPORTING_SOURCE_NOT_CONFIGURED",
  PROJECTION_SOURCE_NOT_DEPLOYED: "REPORTING_PROJECTION_SOURCE_NOT_DEPLOYED",
  SOURCE_FAILED: "REPORTING_SOURCE_FAILED",
  REPOSITORY_UNAVAILABLE: "REPORTING_REPOSITORY_UNAVAILABLE",
  EXPORT_EXECUTOR_NOT_CONFIGURED: "REPORTING_EXPORT_EXECUTOR_NOT_CONFIGURED",
  EXPORT_STORAGE_NOT_CONFIGURED: "REPORTING_EXPORT_STORAGE_NOT_CONFIGURED",
  INVALID_STATUS_TRANSITION: "REPORTING_INVALID_STATUS_TRANSITION",
  STALE_EXECUTION: "REPORTING_STALE_EXECUTION",
  UNAVAILABLE: "REPORTING_UNAVAILABLE",
  STALE: "REPORTING_STALE",
  PORT_OPERATION_UNIMPLEMENTED: "REPORTING_PORT_OPERATION_UNIMPLEMENTED",
  PROVENANCE_MISMATCH: "REPORTING_PROVENANCE_MISMATCH",
  SILENT_FALLBACK_REJECTED: "REPORTING_SILENT_FALLBACK_REJECTED",
});

export const REPORTING_ERROR_CODE_VALUES = Object.freeze(
  Object.values(REPORTING_ERROR_CODE)
);
