/**
 * E2E-04 Player Competition Operations — constants.
 * Permission strings resolve to Identity catalog (no parallel taxonomy).
 */

export const E2E04_PLAYER_OPERATIONS_VERSION = "e2e-04-player-operations-v1";
export const E2E04_PLAYER_OPERATIONS_PHASE = "E2E-04";

/**
 * Player command action IDs (local orchestration vocabulary).
 */
export const PLAYER_ACTION = Object.freeze({
  OPERATIONS_READ: "player.operations.read",
  CHECKIN_SELF: "player.checkin.self",
  SCHEDULE_READ: "player.schedule.read",
  MATCH_READ: "player.match.read",
  STANDINGS_READ: "player.standings.read",
  QUALIFICATION_READ: "player.qualification.read",
  KNOCKOUT_READ: "player.knockout.read",
  FINAL_RESULT_READ: "player.final_result.read",
});

export const PLAYER_ACTION_VALUES = Object.freeze(Object.values(PLAYER_ACTION));

export const PLAYER_CHECKIN_MARK = Object.freeze({
  NOT_CHECKED_IN: "NOT_CHECKED_IN",
  CHECKED_IN: "CHECKED_IN",
});

export const PLAYER_BLOCKER_CODE = Object.freeze({
  MISSING_IDENTITY: "MISSING_IDENTITY",
  MISSING_TENANT: "MISSING_TENANT",
  MISSING_COMPETITION: "MISSING_COMPETITION",
  MISSING_PLAYER_MAPPING: "MISSING_PLAYER_MAPPING",
  ENTRY_NOT_OWNED: "ENTRY_NOT_OWNED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  CROSS_TENANT: "CROSS_TENANT",
  CHECKIN_NOT_OPEN: "CHECKIN_NOT_OPEN",
  CHECKIN_CLOSED: "CHECKIN_CLOSED",
  ENTRY_INELIGIBLE: "ENTRY_INELIGIBLE",
  PRIVATE_DATA_ISOLATION: "PRIVATE_DATA_ISOLATION",
  COMPETITION_STATE_BLOCKED: "COMPETITION_STATE_BLOCKED",
});

export const PLAYER_ERROR_CODE = Object.freeze({
  MISSING_IDENTITY: "E2E04_PLAYER_MISSING_IDENTITY",
  MISSING_TENANT: "E2E04_PLAYER_MISSING_TENANT",
  MISSING_COMPETITION: "E2E04_PLAYER_MISSING_COMPETITION",
  MISSING_PLAYER_MAPPING: "E2E04_PLAYER_MISSING_PLAYER_MAPPING",
  ENTRY_NOT_OWNED: "E2E04_PLAYER_ENTRY_NOT_OWNED",
  WRONG_PLAYER_ID: "E2E04_PLAYER_WRONG_PLAYER_ID",
  PERMISSION_DENIED: "E2E04_PLAYER_PERMISSION_DENIED",
  CROSS_TENANT_REJECTED: "E2E04_PLAYER_CROSS_TENANT_REJECTED",
  INVALID_STATE: "E2E04_PLAYER_INVALID_STATE",
  INVALID_INPUT: "E2E04_PLAYER_INVALID_INPUT",
  PRECONDITION_FAILED: "E2E04_PLAYER_PRECONDITION_FAILED",
  CHECKIN_NOT_OPEN: "E2E04_PLAYER_CHECKIN_NOT_OPEN",
  CHECKIN_CLOSED: "E2E04_PLAYER_CHECKIN_CLOSED",
  ENTRY_INELIGIBLE: "E2E04_PLAYER_ENTRY_INELIGIBLE",
  CLIENT_GRANT_TRUST_REJECTED: "E2E04_PLAYER_CLIENT_GRANT_TRUST_REJECTED",
  CANONICAL_CALL_FAILED: "E2E04_PLAYER_CANONICAL_CALL_FAILED",
  UNKNOWN: "E2E04_PLAYER_UNKNOWN",
});

export const PLAYER_ERROR_CODE_VALUES = Object.freeze(
  Object.values(PLAYER_ERROR_CODE)
);
