import { MATCH_STATUS } from "../../models/tournament/constants.js";
import { buildAllGroupStandings } from "./rankingEngine.js";
import {
  resolveBracketProgress,
  submitKnockoutMatchScore,
  autoSyncBracketFromGroupStandings,
} from "./bracketEngine.js";
import {
  assignMatchToCourt,
  buildCourtRuntimeStates,
  getAvailableCourts,
  setCourtLocked,
} from "./courtEngine.js";
import { startMatch, submitMatchScore } from "./matchEngine.js";
import {
  assignDailyMatchToCourt,
  getDefaultDailyPlaySettings,
  normalizeDailyPlaySettings,
  partitionDailyMatches,
  submitDailyPlayMatchScore,
} from "./dailyPlayEngine.js";

const WAITING_STATUSES = new Set([
  MATCH_STATUS.WAITING,
  MATCH_STATUS.POSTPONED,
]);

const ON_COURT_STATUSES = new Set([
  MATCH_STATUS.ASSIGNED,
  MATCH_STATUS.PLAYING,
]);

const DONE_STATUSES = new Set([
  MATCH_STATUS.COMPLETED,
  MATCH_STATUS.FORFEIT,
]);

function entryMap(entries = []) {
  return new Map((entries || []).map((entry) => [String(entry.id), entry]));
}

function playerMap(players = []) {
  return new Map((players || []).map((player) => [String(player.id), player]));
}

export function resolveEntryLabel(entryId, entries = [], players = []) {
  if (!entryId) {
    return "TBD";
  }

  const entry = entryMap(entries).get(String(entryId));
  if (entry?.name) {
    return entry.name;
  }

  const ids = entry?.playerIds || [entryId];
  const names = ids
    .map((id) => playerMap(players).get(String(id))?.name)
    .filter(Boolean);

  return names.length ? names.join(" / ") : String(entryId);
}

export function enrichMatchForDirector(match, entries = [], players = []) {
  return {
    ...match,
    entryALabel: resolveEntryLabel(match.entryAId, entries, players),
    entryBLabel: resolveEntryLabel(match.entryBId, entries, players),
    isKnockout: Boolean(match.bracketMatchId),
    stageLabel: match.bracketMatchId ? "Knock-out" : match.groupId ? "Vong bang" : "Tran",
  };
}

export function partitionTournamentMatches(matches = []) {
  const waiting = [];
  const onCourt = [];
  const completed = [];

  (matches || []).forEach((match) => {
    if (WAITING_STATUSES.has(match.status)) {
      waiting.push(match);
      return;
    }

    if (ON_COURT_STATUSES.has(match.status)) {
      onCourt.push(match);
      return;
    }

    if (DONE_STATUSES.has(match.status)) {
      completed.push(match);
    }
  });

  return { waiting, onCourt, completed };
}

export function assignTournamentMatchToAvailableCourt({
  matches = [],
  courts = [],
  matchId,
  lockedCourtIds = [],
  autoStart = true,
} = {}) {
  const match = (matches || []).find((item) => String(item.id) === String(matchId));
  if (!match) {
    return { ok: false, error: "Khong tim thay tran." };
  }

  const courtStates = buildCourtRuntimeStates(courts, matches, { lockedCourtIds });
  const availableCourts = getAvailableCourts(courtStates);
  if (!availableCourts.length) {
    return { ok: false, error: "Khong co san trong." };
  }

  const courtId = availableCourts[0].id;
  const assignResult = assignMatchToCourt(courtStates, match, courtId);
  if (!assignResult.ok) {
    return assignResult;
  }

  let nextMatch = assignResult.match;
  if (autoStart) {
    const startResult = startMatch(nextMatch);
    if (startResult.ok) {
      nextMatch = startResult.match;
    }
  }

  const nextMatches = (matches || []).map((item) =>
    String(item.id) === String(matchId) ? nextMatch : item
  );

  return {
    ok: true,
    matches: nextMatches,
    match: nextMatch,
    courtId,
    courtStates: assignResult.courtStates,
  };
}

export function submitTournamentDirectorMatchScore(event, matchId, scores = {}, options = {}) {
  const match = (event?.matches || []).find((item) => String(item.id) === String(matchId));
  if (!match) {
    return { ok: false, error: "Khong tim thay tran." };
  }

  if (match.bracketMatchId) {
    const knockoutResult = submitKnockoutMatchScore(event, matchId, scores, options);
    if (!knockoutResult.ok) {
      return knockoutResult;
    }

    return {
      ok: true,
      event: knockoutResult.event,
      match: knockoutResult.match,
      releasedCourtId: match.courtId,
      bracketAutoGenerated: false,
    };
  }

  const scoreResult = submitMatchScore(match, scores, options);
  if (!scoreResult.ok) {
    return scoreResult;
  }

  const nextMatches = (event.matches || []).map((item) =>
    String(item.id) === String(matchId) ? scoreResult.match : item
  );

  const nextEvent = {
    ...event,
    matches: nextMatches,
  };

  const autoBracket = autoSyncBracketFromGroupStandings(nextEvent, options);

  return {
    ok: true,
    event: autoBracket.generated ? autoBracket.event : nextEvent,
    match: scoreResult.match,
    releasedCourtId: match.courtId,
    bracketAutoGenerated: Boolean(autoBracket.generated),
    bracketKnockoutMatchCount: autoBracket.knockoutMatchCount || 0,
    bracketAutoWarnings: autoBracket.warnings || [],
  };
}

export function toggleTournamentDirectorCourtLock(courtStates = [], courtId, locked = true) {
  return setCourtLocked(courtStates, courtId, locked);
}

export function buildEventDirectorSnapshot({
  event,
  courts = [],
  players = [],
  lockedCourtIds = [],
} = {}) {
  const entries = event?.entries || [];
  const rawMatches = event?.matches || [];
  const enrichedMatches = rawMatches.map((match) =>
    enrichMatchForDirector(match, entries, players)
  );
  const partitioned = partitionTournamentMatches(enrichedMatches);
  const courtStates = buildCourtRuntimeStates(courts, rawMatches, { lockedCourtIds });
  const standings = buildAllGroupStandings(event || { entries: [], matches: [], groups: [] });
  const bracketProgress =
    event?.bracket?.rounds?.length > 0 ? resolveBracketProgress(event) : null;

  return {
    eventId: event?.id || "",
    eventName: event?.name || "",
    matches: partitioned,
    allMatches: enrichedMatches,
    courtStates,
    standings,
    bracketProgress,
    summary: {
      waiting: partitioned.waiting.length,
      onCourt: partitioned.onCourt.length,
      completed: partitioned.completed.length,
      courtsBusy: courtStates.filter((court) => court.currentMatchId).length,
    },
  };
}

export function buildDailyDirectorSnapshot({
  tournament,
  courts = [],
  lockedCourtIds = [],
} = {}) {
  const settings = normalizeDailyPlaySettings(
    tournament?.settings?.dailyPlay || getDefaultDailyPlaySettings()
  );
  const partitioned = partitionDailyMatches(settings.matches);
  const courtStates = buildCourtRuntimeStates(courts, settings.matches, { lockedCourtIds });

  return {
    mode: "daily_play",
    settings,
    matches: {
      waiting: partitioned.waiting,
      onCourt: partitioned.playing,
      completed: partitioned.completed,
    },
    courtStates,
    standings: [],
    bracketProgress: null,
    summary: {
      waiting: partitioned.waiting.length,
      onCourt: partitioned.playing.length,
      completed: partitioned.completed.length,
      courtsBusy: courtStates.filter((court) => court.currentMatchId).length,
    },
  };
}

export function assignDailyDirectorMatch({
  tournament,
  courts = [],
  matchId,
  lockedCourtIds = [],
} = {}) {
  const settings = normalizeDailyPlaySettings(
    tournament?.settings?.dailyPlay || getDefaultDailyPlaySettings()
  );

  return assignDailyMatchToCourt({
    settings,
    courts,
    matchId,
    lockedCourtIds,
  });
}

export function submitDailyDirectorMatchScore(tournament, matchId, scores = {}, options = {}) {
  const settings = normalizeDailyPlaySettings(
    tournament?.settings?.dailyPlay || getDefaultDailyPlaySettings()
  );

  return submitDailyPlayMatchScore(settings, matchId, scores, options);
}

export function buildTournamentDirectorSnapshot({
  tournament,
  event = null,
  courts = [],
  players = [],
  lockedCourtIds = [],
} = {}) {
  if (tournament?.mode === "daily_play") {
    return buildDailyDirectorSnapshot({ tournament, courts, players, lockedCourtIds });
  }

  return {
    mode: tournament?.mode || "event",
    ...buildEventDirectorSnapshot({
      event,
      courts,
      players,
      lockedCourtIds,
    }),
  };
}
