/**
 * CORE-09 — deterministic MatchGenerationIssue / error codes.
 * Free-text messages are diagnostic only; codes are canonical.
 */

export const MATCH_GENERATION_ISSUE_CODE = Object.freeze({
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_MATCH_PLAN: "INVALID_MATCH_PLAN",
  INVALID_LOGICAL_MATCH: "INVALID_LOGICAL_MATCH",
  INVALID_PARTICIPANT_SLOT: "INVALID_PARTICIPANT_SLOT",
  INVALID_DEPENDENCY: "INVALID_DEPENDENCY",
  FORBIDDEN_SCHEDULING_FIELD: "FORBIDDEN_SCHEDULING_FIELD",
  STRATEGY_REQUIRED: "STRATEGY_REQUIRED",
  STRATEGY_UNSUPPORTED: "STRATEGY_UNSUPPORTED",
  STRATEGY_DEFERRED: "STRATEGY_DEFERRED",
  SELF_MATCH: "SELF_MATCH",
  FORBIDDEN_DUPLICATE_PAIRING: "FORBIDDEN_DUPLICATE_PAIRING",
  MATCH_STAGE_REQUIRED: "MATCH_STAGE_REQUIRED",
  MATCH_ROUND_REQUIRED: "MATCH_ROUND_REQUIRED",
  MATCH_STAGE_AMBIGUOUS: "MATCH_STAGE_AMBIGUOUS",
  MATCH_ROUND_AMBIGUOUS: "MATCH_ROUND_AMBIGUOUS",
  DUPLICATE_LOGICAL_MATCH_KEY: "DUPLICATE_LOGICAL_MATCH_KEY",
  INVALID_LOGICAL_MATCH_KEY: "INVALID_LOGICAL_MATCH_KEY",
  DANGLING_DEPENDENCY: "DANGLING_DEPENDENCY",
  DEPENDENCY_CYCLE: "DEPENDENCY_CYCLE",
  INVALID_WINNER_PATH: "INVALID_WINNER_PATH",
  INVALID_BYE_REPRESENTATION: "INVALID_BYE_REPRESENTATION",
  DRAW_INCOMPLETE: "DRAW_INCOMPLETE",
  DRAW_FINGERPRINT_MISSING: "DRAW_FINGERPRINT_MISSING",
  DRAW_FINGERPRINT_MISMATCH: "DRAW_FINGERPRINT_MISMATCH",
  DRAW_VERSION_MISMATCH: "DRAW_VERSION_MISMATCH",
  DRAW_PLACEMENT_DUPLICATE: "DRAW_PLACEMENT_DUPLICATE",
  DRAW_PLACEMENT_MISSING: "DRAW_PLACEMENT_MISSING",
  DRAW_REFERENCE_INVALID: "DRAW_REFERENCE_INVALID",
  DRAW_MUTATION_DETECTED: "DRAW_MUTATION_DETECTED",
  RULE_FINGERPRINT_MISSING: "RULE_FINGERPRINT_MISSING",
  RULE_FINGERPRINT_MISMATCH: "RULE_FINGERPRINT_MISMATCH",
  PARTICIPANT_FINGERPRINT_MISSING: "PARTICIPANT_FINGERPRINT_MISSING",
  GENERATION_FINGERPRINT_MISMATCH: "GENERATION_FINGERPRINT_MISMATCH",
  GENERATOR_VERSION_REQUIRED: "GENERATOR_VERSION_REQUIRED",
  NON_DETERMINISTIC_INPUT: "NON_DETERMINISTIC_INPUT",
  INVALID_ENUM_VALUE: "INVALID_ENUM_VALUE",
  INVALID_ISSUE_CODE: "INVALID_ISSUE_CODE",
  INVALID_LOGICAL_MATCH_COORDINATES: "INVALID_LOGICAL_MATCH_COORDINATES",
  NON_CANONICAL_VALUE: "NON_CANONICAL_VALUE",
  DRAW_CATALOG_EMPTY: "DRAW_CATALOG_EMPTY",
  INVALID_LOSER_PATH: "INVALID_LOSER_PATH",
  /** Phase 1C: request.strategy vs evaluatedRules.generationStrategy diverge. */
  RULE_STRATEGY_MISMATCH: "RULE_STRATEGY_MISMATCH",
  /** Phase 1C: roundRobinMode not executable (e.g. CUSTOM). */
  ROUND_ROBIN_MODE_UNSUPPORTED: "ROUND_ROBIN_MODE_UNSUPPORTED",
  /** Phase 1C: encounterCount unsupported or inconsistent with mode. */
  ENCOUNTER_COUNT_UNSUPPORTED: "ENCOUNTER_COUNT_UNSUPPORTED",
  /** Phase 1C: rematch / club / bye / format policy not executable here. */
  UNSUPPORTED_GENERATION_POLICY: "UNSUPPORTED_GENERATION_POLICY",
  /** Phase 1D: fewer than two participants (or third-place with N < 4). */
  PARTICIPANT_COUNT_INSUFFICIENT: "PARTICIPANT_COUNT_INSUFFICIENT",
  /** Phase 1D: single-elimination bracket structure violated. */
  BRACKET_INVARIANT_VIOLATION: "BRACKET_INVARIANT_VIOLATION",
});

/** @type {ReadonlySet<string>} */
export const MATCH_GENERATION_ISSUE_CODE_VALUES = new Set(
  Object.values(MATCH_GENERATION_ISSUE_CODE)
);

/**
 * @param {unknown} value
 * @returns {boolean}
 */
export function isMatchGenerationIssueCode(value) {
  return (
    typeof value === "string" && MATCH_GENERATION_ISSUE_CODE_VALUES.has(value)
  );
}
