/**
 * Published-skill and related writer identifiers for freeze inventory.
 */

export const CUTOVER_02_WRITER_ID = Object.freeze({
  PICK_VN_SYNC_RATING_RPC: "PICK_VN_SYNC_RATING_RPC",
  V2_ASSESSMENT_PUBLISH: "V2_ASSESSMENT_PUBLISH",
  V5_START_ASSESSMENT: "V5_START_ASSESSMENT",
  V5_PERSIST_ASSESSMENT: "V5_PERSIST_ASSESSMENT",
  V5_INVALIDATE: "V5_INVALIDATE",
  V5_PILOT_ENROLLMENT: "V5_PILOT_ENROLLMENT",
  CC02_COMPETITION_ELO: "CC02_COMPETITION_ELO",
  BLOB_SKILL_MIRROR: "BLOB_SKILL_MIRROR",
  LOCAL_V2_MIRROR: "LOCAL_V2_MIRROR",
  CLOUD_SYNC_CLUB_BLOB: "CLOUD_SYNC_CLUB_BLOB",
  ADMIN_MANUAL_OVERRIDE: "ADMIN_MANUAL_OVERRIDE",
  IMPORT_BACKFILL: "IMPORT_BACKFILL",
  LEGACY_ELO_PUBLIC_MIRROR: "LEGACY_ELO_PUBLIC_MIRROR",
  UNRELATED_PROFILE_WRITE: "UNRELATED_PROFILE_WRITE",
});

export const WRITER_FREEZE_MODE = Object.freeze({
  OFF: "OFF",
  OBSERVE: "OBSERVE",
  ENFORCE: "ENFORCE",
});

export const WRITER_FREEZE_MODE_SET = new Set(Object.values(WRITER_FREEZE_MODE));
