/** PR-4.5 — stable simulation codes (tests must not depend on Vietnamese copy). */

export const SIMULATION_DEFAULTS = Object.freeze({
  maxCandidates: 5000,
  maxIterations: 50000,
  timeoutMs: 2000,
  topN: 10,
  teamSize: 2,
});

export const SIMULATION_CODE = Object.freeze({
  FEATURE_DISABLED: "SIMULATION_FEATURE_DISABLED",
  RUNTIME_DISABLED: "SIMULATION_RUNTIME_DISABLED",
  INVALID_INPUT: "SIMULATION_INVALID_INPUT",
  NO_ELIGIBLE_PLAYERS: "NO_ELIGIBLE_PLAYERS",
  NO_FEASIBLE_PAIRING: "NO_FEASIBLE_PAIRING",
  SEARCH_LIMIT_REACHED: "SEARCH_LIMIT_REACHED",
  RULE_BLOCKED_BY_CERTIFIED_POLICY: "RULE_BLOCKED_BY_CERTIFIED_POLICY",
  MISSING_PLAYER_RATING: "MISSING_PLAYER_RATING",
  TEAM_CAPACITY_EXCEEDED: "TEAM_CAPACITY_EXCEEDED",
  CONSTRAINT_CONFLICT: "CONSTRAINT_CONFLICT",
});

export const EXPLANATION_CODE = Object.freeze({
  BALANCED_TEAM_RATING: "BALANCED_TEAM_RATING",
  LOW_TEAM_RATING_GAP: "LOW_TEAM_RATING_GAP",
  PREFER_PARTNER_SATISFIED: "PREFER_PARTNER_SATISFIED",
  AVOID_PARTNER_SATISFIED: "AVOID_PARTNER_SATISFIED",
  PREFER_OPPONENT_SATISFIED: "PREFER_OPPONENT_SATISFIED",
  AVOID_OPPONENT_SATISFIED: "AVOID_OPPONENT_SATISFIED",
  REPEAT_PARTNER_REDUCED: "REPEAT_PARTNER_REDUCED",
  REPEAT_OPPONENT_REDUCED: "REPEAT_OPPONENT_REDUCED",
  WAIT_TIME_PRIORITY: "WAIT_TIME_PRIORITY",
  BENCH_ROTATION_FAIR: "BENCH_ROTATION_FAIR",
  DIVERSITY_IMPROVED: "DIVERSITY_IMPROVED",
  MISSING_RATING_FALLBACK: "MISSING_RATING_FALLBACK",
  NO_HARD_RULE_VIOLATION: "NO_HARD_RULE_VIOLATION",
  TOP_RANKED_CANDIDATE: "TOP_RANKED_CANDIDATE",
});

export const SIMULATION_VERSION = "pr45-simulation-1";
