/**
 * Finance event catalogue (Phase 1B).
 * SCREAMING_SNAKE_CASE — Billing PascalCase / webhook names remain unchanged elsewhere.
 */

export const FINANCE_OWNING_MODULE = "Finance";

export const FINANCE_EVENT_VERSION = 1;

export const FINANCE_EVENT_TYPE = Object.freeze({
  FINANCE_OBLIGATION_CREATED: "FINANCE_OBLIGATION_CREATED",
  INVOICE_CREATED: "INVOICE_CREATED",
  INVOICE_ISSUED: "INVOICE_ISSUED",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_CANCELLED: "PAYMENT_CANCELLED",
  PAYMENT_EXPIRED: "PAYMENT_EXPIRED",
  RECEIPT_ISSUED: "RECEIPT_ISSUED",
  REFUND_REQUESTED: "REFUND_REQUESTED",
  REFUND_APPROVED: "REFUND_APPROVED",
  REFUND_REJECTED: "REFUND_REJECTED",
  REFUND_COMPLETED: "REFUND_COMPLETED",
  RECONCILIATION_COMPLETED: "RECONCILIATION_COMPLETED",
  FINANCIAL_ADJUSTMENT_RECORDED: "FINANCIAL_ADJUSTMENT_RECORDED",
});

export const FINANCE_EVENT_TYPE_VALUES = Object.freeze(
  Object.values(FINANCE_EVENT_TYPE)
);

export const FINANCE_PRIVACY_CLASSIFICATION = Object.freeze({
  INTERNAL: "INTERNAL",
  RESTRICTED: "RESTRICTED",
  PUBLIC: "PUBLIC",
});

export const FINANCE_PRIVACY_CLASSIFICATION_VALUES = Object.freeze(
  Object.values(FINANCE_PRIVACY_CLASSIFICATION)
);

/**
 * @param {unknown} eventType
 * @returns {boolean}
 */
export function isFinanceEventType(eventType) {
  return FINANCE_EVENT_TYPE_VALUES.includes(eventType);
}

/** Event types that require amount + currency on the envelope. */
export const FINANCE_EVENTS_REQUIRING_AMOUNT = Object.freeze([
  FINANCE_EVENT_TYPE.FINANCE_OBLIGATION_CREATED,
  FINANCE_EVENT_TYPE.INVOICE_CREATED,
  FINANCE_EVENT_TYPE.INVOICE_ISSUED,
  FINANCE_EVENT_TYPE.PAYMENT_PENDING,
  FINANCE_EVENT_TYPE.PAYMENT_CONFIRMED,
  FINANCE_EVENT_TYPE.PAYMENT_FAILED,
  FINANCE_EVENT_TYPE.PAYMENT_CANCELLED,
  FINANCE_EVENT_TYPE.PAYMENT_EXPIRED,
  FINANCE_EVENT_TYPE.RECEIPT_ISSUED,
  FINANCE_EVENT_TYPE.REFUND_REQUESTED,
  FINANCE_EVENT_TYPE.REFUND_APPROVED,
  FINANCE_EVENT_TYPE.REFUND_REJECTED,
  FINANCE_EVENT_TYPE.REFUND_COMPLETED,
  FINANCE_EVENT_TYPE.FINANCIAL_ADJUSTMENT_RECORDED,
]);

/** Event types that require evidence references. */
export const FINANCE_EVENTS_REQUIRING_EVIDENCE = Object.freeze([
  FINANCE_EVENT_TYPE.PAYMENT_CONFIRMED,
  FINANCE_EVENT_TYPE.RECEIPT_ISSUED,
  FINANCE_EVENT_TYPE.REFUND_COMPLETED,
  FINANCE_EVENT_TYPE.RECONCILIATION_COMPLETED,
]);
