/**
 * CM-08 Competition Archive — stable typed error codes.
 * Module-local; not registered in API_ERROR_CODES in this phase.
 */

export const COMPETITION_ARCHIVE_ERROR_CODE = Object.freeze({
  INVALID_CONTRACT: "CM08_INVALID_CONTRACT",
  MISSING_TENANT: "CM08_MISSING_TENANT",
  MISSING_COMPETITION: "CM08_MISSING_COMPETITION",
  TENANT_MISMATCH: "CM08_TENANT_MISMATCH",
  COMPETITION_MISMATCH: "CM08_COMPETITION_MISMATCH",
  CROSS_TENANT_ACCESS: "CM08_CROSS_TENANT_ACCESS",

  INVALID_DEFINITION: "CM08_INVALID_DEFINITION",
  STALE_DEFINITION_REVISION: "CM08_STALE_DEFINITION_REVISION",

  MISSING_COMPETITION_VERSION: "CM08_MISSING_COMPETITION_VERSION",
  SOURCE_VERSION_MISMATCH: "CM08_SOURCE_VERSION_MISMATCH",
  SOURCE_VERSION_TENANT_MISMATCH: "CM08_SOURCE_VERSION_TENANT_MISMATCH",
  SOURCE_VERSION_COMPETITION_MISMATCH: "CM08_SOURCE_VERSION_COMPETITION_MISMATCH",

  MISSING_LIFECYCLE_OR_COMPLETION_CONTEXT:
    "CM08_MISSING_LIFECYCLE_OR_COMPLETION_CONTEXT",
  LIFECYCLE_STATE_NOT_ARCHIVABLE: "CM08_LIFECYCLE_STATE_NOT_ARCHIVABLE",
  CANCELLATION_EVIDENCE_MISMATCH: "CM08_CANCELLATION_EVIDENCE_MISMATCH",
  COMPLETION_EVIDENCE_MISSING: "CM08_COMPLETION_EVIDENCE_MISSING",
  INVALID_COMPLETION_EVIDENCE: "CM08_INVALID_COMPLETION_EVIDENCE",

  INVALID_ARCHIVE_POLICY: "CM08_INVALID_ARCHIVE_POLICY",
  INVALID_ARCHIVE_REASON: "CM08_INVALID_ARCHIVE_REASON",
  INVALID_UNARCHIVE_REASON: "CM08_INVALID_UNARCHIVE_REASON",
  MISSING_REASON_DETAIL: "CM08_MISSING_REASON_DETAIL",
  INVALID_REASON_SUMMARY: "CM08_INVALID_REASON_SUMMARY",
  REASON_CONTROL_CHARACTERS: "CM08_REASON_CONTROL_CHARACTERS",

  INVALID_EFFECTIVE_TIME: "CM08_INVALID_EFFECTIVE_TIME",

  MISSING_ACTOR: "CM08_MISSING_ACTOR",
  ACTOR_TENANT_MISMATCH: "CM08_ACTOR_TENANT_MISMATCH",
  AUTHORITY_DENIED: "CM08_AUTHORITY_DENIED",
  MISSING_AUTHORITY_REFERENCE: "CM08_MISSING_AUTHORITY_REFERENCE",
  ELEVATED_AUTHORITY_REQUIRED: "CM08_ELEVATED_AUTHORITY_REQUIRED",

  PUBLICATION_CONTEXT_MISMATCH: "CM08_PUBLICATION_CONTEXT_MISMATCH",
  STALE_PUBLICATION_REVISION: "CM08_STALE_PUBLICATION_REVISION",
  MISSING_PUBLICATION_CONTEXT: "CM08_MISSING_PUBLICATION_CONTEXT",

  MISSING_RETENTION_ACK: "CM08_MISSING_RETENTION_ACK",

  ALREADY_ARCHIVED: "CM08_ALREADY_ARCHIVED",
  NOT_ARCHIVED: "CM08_NOT_ARCHIVED",
  UNARCHIVE_FORBIDDEN: "CM08_UNARCHIVE_FORBIDDEN",
  INVALID_TRANSITION: "CM08_INVALID_TRANSITION",

  STALE_ARCHIVE_REVISION: "CM08_STALE_ARCHIVE_REVISION",
  MISSING_EXPECTED_ARCHIVE_REVISION: "CM08_MISSING_EXPECTED_ARCHIVE_REVISION",

  MISSING_IDEMPOTENCY_KEY: "CM08_MISSING_IDEMPOTENCY_KEY",
  IDEMPOTENCY_CONFLICT: "CM08_IDEMPOTENCY_CONFLICT",
  DUPLICATE_ARCHIVE_RECORD: "CM08_DUPLICATE_ARCHIVE_RECORD",
  REPOSITORY_CONFLICT: "CM08_REPOSITORY_CONFLICT",
  MALFORMED_ARCHIVE_RECORD: "CM08_MALFORMED_ARCHIVE_RECORD",
  MALFORMED_EFFECT_PLAN: "CM08_MALFORMED_EFFECT_PLAN",
  MALFORMED_MANIFEST: "CM08_MALFORMED_MANIFEST",
  MALFORMED_LEGACY_ARCHIVE: "CM08_MALFORMED_LEGACY_ARCHIVE",
  AMBIGUOUS_LEGACY_MAPPING: "CM08_AMBIGUOUS_LEGACY_MAPPING",
  PORT_OPERATION_UNIMPLEMENTED: "CM08_PORT_OPERATION_UNIMPLEMENTED",

  CONFIGURATION_CONTEXT_MISMATCH: "CM08_CONFIGURATION_CONTEXT_MISMATCH",
  BRANDING_CONTEXT_MISMATCH: "CM08_BRANDING_CONTEXT_MISMATCH",
  PENDING_PUBLICATION_OPERATION: "CM08_PENDING_PUBLICATION_OPERATION",
  ACTIVE_RECOVERY_OPERATION: "CM08_ACTIVE_RECOVERY_OPERATION",
  UNRESOLVED_CRITICAL_OPERATION: "CM08_UNRESOLVED_CRITICAL_OPERATION",
});
