/**
 * Stable fail-closed error codes for Canonical Competition Rules & Format.
 */

export const COMPETITION_RULES_ERROR_CODE = Object.freeze({
  INVALID_PROFILE: "COMPETITION_RULES_INVALID_PROFILE",
  INVALID_SECTION: "COMPETITION_RULES_INVALID_SECTION",
  INVALID_SCORING_POLICY: "COMPETITION_RULES_INVALID_SCORING_POLICY",
  INVALID_STAGE_OVERRIDE: "COMPETITION_RULES_INVALID_STAGE_OVERRIDE",
  INVALID_GROUP_CONFIG: "COMPETITION_RULES_INVALID_GROUP_CONFIG",
  INVALID_QUALIFICATION: "COMPETITION_RULES_INVALID_QUALIFICATION",
  IMPOSSIBLE_QUALIFICATION: "COMPETITION_RULES_IMPOSSIBLE_QUALIFICATION",
  INVALID_TIEBREAK: "COMPETITION_RULES_INVALID_TIEBREAK",
  INVALID_WILDCARD_RANKING: "COMPETITION_RULES_INVALID_WILDCARD_RANKING",
  INVALID_KNOCKOUT: "COMPETITION_RULES_INVALID_KNOCKOUT",
  INVALID_KNOCKOUT_ADMISSION: "COMPETITION_RULES_INVALID_KNOCKOUT_ADMISSION",
  IMPOSSIBLE_KNOCKOUT_ADMISSION:
    "COMPETITION_RULES_IMPOSSIBLE_KNOCKOUT_ADMISSION",
  INVALID_DIRECT_KNOCKOUT_ENTRY:
    "COMPETITION_RULES_INVALID_DIRECT_KNOCKOUT_ENTRY",
  INVALID_GROUP_STAGE_BYPASS: "COMPETITION_RULES_INVALID_GROUP_STAGE_BYPASS",
  INVALID_BYE_POLICY: "COMPETITION_RULES_INVALID_BYE_POLICY",
  DUPLICATE_ENTRANT_REF: "COMPETITION_RULES_DUPLICATE_ENTRANT_REF",
  MISSING_ENTRANT_IDENTITY: "COMPETITION_RULES_MISSING_ENTRANT_IDENTITY",
  DISPLAY_NAME_IDENTITY_FORBIDDEN:
    "COMPETITION_RULES_DISPLAY_NAME_IDENTITY_FORBIDDEN",
  INVALID_CHANGE_END: "COMPETITION_RULES_INVALID_CHANGE_END",

  INVALID_CHECK_IN: "COMPETITION_RULES_INVALID_CHECK_IN",
  INVALID_SCHEDULE: "COMPETITION_RULES_INVALID_SCHEDULE",
  INVALID_COURT_REQUIREMENT: "COMPETITION_RULES_INVALID_COURT_REQUIREMENT",
  INVALID_REFEREE_REQUIREMENT: "COMPETITION_RULES_INVALID_REFEREE_REQUIREMENT",
  INVALID_PUBLICATION: "COMPETITION_RULES_INVALID_PUBLICATION",
  RULE_MUTATION_LOCKED: "COMPETITION_RULES_MUTATION_LOCKED",
  CAPABILITY_UNSUPPORTED: "COMPETITION_RULES_CAPABILITY_UNSUPPORTED",
  CAPABILITY_EXECUTION_UNAVAILABLE: "COMPETITION_RULES_CAPABILITY_EXECUTION_UNAVAILABLE",
  UNKNOWN_RULE_CLASS: "COMPETITION_RULES_UNKNOWN_RULE_CLASS",
  UNKNOWN_STAGE: "COMPETITION_RULES_UNKNOWN_STAGE",
  TENANT_REQUIRED: "COMPETITION_RULES_TENANT_REQUIRED",
  COMPETITION_REQUIRED: "COMPETITION_RULES_COMPETITION_REQUIRED",
  MODE_LOGIC_FORBIDDEN: "COMPETITION_RULES_MODE_LOGIC_FORBIDDEN",
});
