/**
 * Consumer eligibility matrix data for dual-read instrumentation (sidecar-only).
 * No consumer is switched to V5 published read in CUTOVER-02.
 */

export const CUTOVER_02_CONSUMER_MATRIX = Object.freeze([
  Object.freeze({
    consumer: "getPlayerCurrentRating",
    currentSource: "V2 blob/helpers (current_rating → skillLevel)",
    publishedFacing: true,
    eligibleForCompare: true,
    sidecarOnly: true,
    failureBehavior: "fail-open return V2; compare errors ignored",
    requiredRegressionTests: ["compare OFF/ON still returns V2"],
  }),
  Object.freeze({
    consumer: "player_profile",
    currentSource: "V2 local + blob",
    publishedFacing: true,
    eligibleForCompare: true,
    sidecarOnly: true,
    failureBehavior: "UI keeps V2 display",
    requiredRegressionTests: ["profile rating unchanged with compare ON"],
  }),
  Object.freeze({
    consumer: "public_profile",
    currentSource: "rating stripped / no skill",
    publishedFacing: false,
    eligibleForCompare: false,
    sidecarOnly: true,
    failureBehavior: "n/a",
    requiredRegressionTests: ["no skill leak"],
  }),
  Object.freeze({
    consumer: "roster",
    currentSource: "blob level/current_rating",
    publishedFacing: true,
    eligibleForCompare: true,
    sidecarOnly: true,
    failureBehavior: "keep blob V2",
    requiredRegressionTests: ["roster card still V2"],
  }),
  Object.freeze({
    consumer: "pairing_canonicalAthleteRating",
    currentSource: "V2-first index",
    publishedFacing: false,
    eligibleForCompare: true,
    sidecarOnly: true,
    failureBehavior: "pairing continues on V2",
    requiredRegressionTests: ["pairing authority unchanged"],
  }),
  Object.freeze({
    consumer: "player_selector",
    currentSource: "Supabase V2 rows / legacy member",
    publishedFacing: false,
    eligibleForCompare: true,
    sidecarOnly: true,
    failureBehavior: "selector keeps V2",
    requiredRegressionTests: ["adapter V2 precedence"],
  }),
  Object.freeze({
    consumer: "tournament_seeding",
    currentSource: "optional V5 snapshot → elo → skill",
    publishedFacing: false,
    eligibleForCompare: true,
    sidecarOnly: true,
    failureBehavior: "no published flip",
    requiredRegressionTests: ["seed order unchanged by compare flag"],
  }),
  Object.freeze({
    consumer: "club_membership_surfaces",
    currentSource: "V2 local/RPC → blob stamp",
    publishedFacing: true,
    eligibleForCompare: true,
    sidecarOnly: true,
    failureBehavior: "stamp remains V2",
    requiredRegressionTests: ["membership hydrate V2"],
  }),
  Object.freeze({
    consumer: "rankings_vpr",
    currentSource: "VPR points domain",
    publishedFacing: false,
    eligibleForCompare: false,
    sidecarOnly: true,
    failureBehavior: "out of scope",
    requiredRegressionTests: ["VPR untouched"],
  }),
  Object.freeze({
    consumer: "season_leaderboard",
    currentSource: "blob rating/level (often mislabeled Elo)",
    publishedFacing: true,
    eligibleForCompare: true,
    sidecarOnly: true,
    failureBehavior: "export remains blob",
    requiredRegressionTests: ["CSV columns unchanged"],
  }),
  Object.freeze({
    consumer: "exports",
    currentSource: "blob skill fields",
    publishedFacing: true,
    eligibleForCompare: true,
    sidecarOnly: true,
    failureBehavior: "export V2",
    requiredRegressionTests: ["export values unchanged"],
  }),
  Object.freeze({
    consumer: "mobile_pwa_services",
    currentSource: "inherits shared pages",
    publishedFacing: true,
    eligibleForCompare: true,
    sidecarOnly: true,
    failureBehavior: "same as shared V2",
    requiredRegressionTests: ["no V5 published prefer"],
  }),
]);
