/**
 * Typed error codes for Intelligence & Analytics foundation contracts.
 */

export const ANALYTICS_ERROR_CODE = Object.freeze({
  INVALID_INPUT: "ANALYTICS_INVALID_INPUT",
  METRIC_ID_REQUIRED: "ANALYTICS_METRIC_ID_REQUIRED",
  METRIC_VERSION_REQUIRED: "ANALYTICS_METRIC_VERSION_REQUIRED",
  TENANT_CONTEXT_REQUIRED: "ANALYTICS_TENANT_CONTEXT_REQUIRED",
  TENANT_SCOPE_INVALID: "ANALYTICS_TENANT_SCOPE_INVALID",
  TIME_WINDOW_INVALID: "ANALYTICS_TIME_WINDOW_INVALID",
  QUERY_DESCRIPTOR_INVALID: "ANALYTICS_QUERY_DESCRIPTOR_INVALID",
  UNSUPPORTED_AGGREGATION: "ANALYTICS_UNSUPPORTED_AGGREGATION",
  INVALID_NUMERIC_INPUT: "ANALYTICS_INVALID_NUMERIC_INPUT",
  MISSING_DATA_POLICY_VIOLATION: "ANALYTICS_MISSING_DATA_POLICY_VIOLATION",
  PROJECTION_INVALID: "ANALYTICS_PROJECTION_INVALID",
  FACADE_WRITE_REJECTED: "ANALYTICS_FACADE_WRITE_REJECTED",
  SOURCE_REQUIRED: "ANALYTICS_SOURCE_REQUIRED",
  DEFINITION_INVALID: "ANALYTICS_DEFINITION_INVALID",
  REGISTRY_ENTRY_INVALID: "ANALYTICS_REGISTRY_ENTRY_INVALID",
  REGISTRY_CONFLICT: "ANALYTICS_REGISTRY_CONFLICT",
  REGISTRY_NOT_FOUND: "ANALYTICS_REGISTRY_NOT_FOUND",
  REGISTRY_REPLACEMENT_SELF_REFERENCE: "ANALYTICS_REGISTRY_REPLACEMENT_SELF_REFERENCE",
  REGISTRY_LIFECYCLE_INVALID: "ANALYTICS_REGISTRY_LIFECYCLE_INVALID",
  REGISTRY_FORBIDDEN_CONTRACT: "ANALYTICS_REGISTRY_FORBIDDEN_CONTRACT",
  // I&A-03 — query / projection runtime
  INVALID_QUERY: "ANALYTICS_INVALID_QUERY",
  METRIC_NOT_FOUND: "ANALYTICS_METRIC_NOT_FOUND",
  METRIC_VERSION_NOT_FOUND: "ANALYTICS_METRIC_VERSION_NOT_FOUND",
  METRIC_RETIRED: "ANALYTICS_METRIC_RETIRED",
  TENANT_SCOPE_MISMATCH: "ANALYTICS_TENANT_SCOPE_MISMATCH",
  UNSUPPORTED_DIMENSION: "ANALYTICS_UNSUPPORTED_DIMENSION",
  SOURCE_UNAVAILABLE: "ANALYTICS_SOURCE_UNAVAILABLE",
  SOURCE_FAILURE: "ANALYTICS_SOURCE_FAILURE",
  INVALID_OBSERVATION: "ANALYTICS_INVALID_OBSERVATION",
  PROJECTION_FAILURE: "ANALYTICS_PROJECTION_FAILURE",
  RESULT_LIMIT_EXCEEDED: "ANALYTICS_RESULT_LIMIT_EXCEEDED",
  ACCESS_CONTEXT_INVALID: "ANALYTICS_ACCESS_CONTEXT_INVALID",
  RUNTIME_CONTEXT_INVALID: "ANALYTICS_RUNTIME_CONTEXT_INVALID",
  // I&A-04 — dashboard / reporting data contracts
  DASHBOARD_DEFINITION_INVALID: "ANALYTICS_DASHBOARD_DEFINITION_INVALID",
  REPORT_DEFINITION_INVALID: "ANALYTICS_REPORT_DEFINITION_INVALID",
  DASHBOARD_ID_REQUIRED: "ANALYTICS_DASHBOARD_ID_REQUIRED",
  DASHBOARD_VERSION_REQUIRED: "ANALYTICS_DASHBOARD_VERSION_REQUIRED",
  REPORT_ID_REQUIRED: "ANALYTICS_REPORT_ID_REQUIRED",
  REPORT_VERSION_REQUIRED: "ANALYTICS_REPORT_VERSION_REQUIRED",
  WIDGET_DEFINITION_INVALID: "ANALYTICS_WIDGET_DEFINITION_INVALID",
  SECTION_DEFINITION_INVALID: "ANALYTICS_SECTION_DEFINITION_INVALID",
  COLUMN_DEFINITION_INVALID: "ANALYTICS_COLUMN_DEFINITION_INVALID",
  BINDING_INVALID: "ANALYTICS_BINDING_INVALID",
  PRESENTATION_INTENT_INVALID: "ANALYTICS_PRESENTATION_INTENT_INVALID",
  DATA_STATE_INVALID: "ANALYTICS_DATA_STATE_INVALID",
  PAYLOAD_INVALID: "ANALYTICS_PAYLOAD_INVALID",
  DRILL_DOWN_INVALID: "ANALYTICS_DRILL_DOWN_INVALID",
  FILTER_DEFINITION_INVALID: "ANALYTICS_FILTER_DEFINITION_INVALID",
  PARAMETER_DEFINITION_INVALID: "ANALYTICS_PARAMETER_DEFINITION_INVALID",
  EXPORT_INTENT_INVALID: "ANALYTICS_EXPORT_INTENT_INVALID",
  SCHEDULE_INTENT_INVALID: "ANALYTICS_SCHEDULE_INTENT_INVALID",
  CATALOG_ENTRY_INVALID: "ANALYTICS_CATALOG_ENTRY_INVALID",
  CATALOG_CONFLICT: "ANALYTICS_CATALOG_CONFLICT",
  CATALOG_NOT_FOUND: "ANALYTICS_CATALOG_NOT_FOUND",
  FORBIDDEN_CONTRACT: "ANALYTICS_FORBIDDEN_CONTRACT",
  ACCESS_SCOPE_INVALID: "ANALYTICS_ACCESS_SCOPE_INVALID",
  // I&A-05 — historical / trend analysis
  HISTORICAL_QUERY_INVALID: "ANALYTICS_HISTORICAL_QUERY_INVALID",
  HISTORICAL_OBSERVATION_INVALID: "ANALYTICS_HISTORICAL_OBSERVATION_INVALID",
  HISTORICAL_BUCKET_INVALID: "ANALYTICS_HISTORICAL_BUCKET_INVALID",
  HISTORICAL_MISSING_POLICY_INVALID: "ANALYTICS_HISTORICAL_MISSING_POLICY_INVALID",
  HISTORICAL_COMPARISON_INVALID: "ANALYTICS_HISTORICAL_COMPARISON_INVALID",
  HISTORICAL_TREND_INVALID: "ANALYTICS_HISTORICAL_TREND_INVALID",
  HISTORICAL_MOVING_WINDOW_INVALID: "ANALYTICS_HISTORICAL_MOVING_WINDOW_INVALID",
  HISTORICAL_CUMULATIVE_INVALID: "ANALYTICS_HISTORICAL_CUMULATIVE_INVALID",
  HISTORICAL_SOURCE_FAILURE: "ANALYTICS_HISTORICAL_SOURCE_FAILURE",
  // I&A-06 — competition analytics
  COMPETITION_CONTEXT_INVALID: "ANALYTICS_COMPETITION_CONTEXT_INVALID",
  COMPETITION_ID_REQUIRED: "ANALYTICS_COMPETITION_ID_REQUIRED",
  COMPETITION_TENANT_MISMATCH: "ANALYTICS_COMPETITION_TENANT_MISMATCH",
  COMPETITION_ID_MISMATCH: "ANALYTICS_COMPETITION_ID_MISMATCH",
  COMPETITION_VERSION_MIXED: "ANALYTICS_COMPETITION_VERSION_MIXED",
  COMPETITION_FACT_INVALID: "ANALYTICS_COMPETITION_FACT_INVALID",
  COMPETITION_SNAPSHOT_INVALID: "ANALYTICS_COMPETITION_SNAPSHOT_INVALID",
  COMPETITION_SOURCE_FAILURE: "ANALYTICS_COMPETITION_SOURCE_FAILURE",
  COMPETITION_QUERY_INVALID: "ANALYTICS_COMPETITION_QUERY_INVALID",
  COMPETITION_TIMESTAMP_INVALID: "ANALYTICS_COMPETITION_TIMESTAMP_INVALID",
  COMPETITION_DURATION_INVALID: "ANALYTICS_COMPETITION_DURATION_INVALID",
  COMPETITION_ISOLATION_VIOLATION: "ANALYTICS_COMPETITION_ISOLATION_VIOLATION",
  // I&A-07 — venue / court / club analytics
  VENUE_COURT_CLUB_CONTEXT_INVALID: "ANALYTICS_VENUE_COURT_CLUB_CONTEXT_INVALID",
  VENUE_COURT_CLUB_TENANT_MISMATCH: "ANALYTICS_VENUE_COURT_CLUB_TENANT_MISMATCH",
  VENUE_COURT_CLUB_VENUE_MISMATCH: "ANALYTICS_VENUE_COURT_CLUB_VENUE_MISMATCH",
  VENUE_COURT_CLUB_COURT_MISMATCH: "ANALYTICS_VENUE_COURT_CLUB_COURT_MISMATCH",
  VENUE_COURT_CLUB_CLUB_MISMATCH: "ANALYTICS_VENUE_COURT_CLUB_CLUB_MISMATCH",
  VENUE_COURT_CLUB_COURT_VENUE_MISMATCH:
    "ANALYTICS_VENUE_COURT_CLUB_COURT_VENUE_MISMATCH",
  VENUE_COURT_CLUB_FACT_INVALID: "ANALYTICS_VENUE_COURT_CLUB_FACT_INVALID",
  VENUE_COURT_CLUB_SNAPSHOT_INVALID: "ANALYTICS_VENUE_COURT_CLUB_SNAPSHOT_INVALID",
  VENUE_COURT_CLUB_SOURCE_FAILURE: "ANALYTICS_VENUE_COURT_CLUB_SOURCE_FAILURE",
  VENUE_COURT_CLUB_QUERY_INVALID: "ANALYTICS_VENUE_COURT_CLUB_QUERY_INVALID",
  VENUE_COURT_CLUB_TIMESTAMP_INVALID:
    "ANALYTICS_VENUE_COURT_CLUB_TIMESTAMP_INVALID",
  VENUE_COURT_CLUB_DURATION_INVALID: "ANALYTICS_VENUE_COURT_CLUB_DURATION_INVALID",
  VENUE_COURT_CLUB_ISOLATION_VIOLATION:
    "ANALYTICS_VENUE_COURT_CLUB_ISOLATION_VIOLATION",
  // I&A-08 — customer / player analytics
  CUSTOMER_PLAYER_CONTEXT_INVALID: "ANALYTICS_CUSTOMER_PLAYER_CONTEXT_INVALID",
  CUSTOMER_PLAYER_TENANT_MISMATCH: "ANALYTICS_CUSTOMER_PLAYER_TENANT_MISMATCH",
  CUSTOMER_PLAYER_CUSTOMER_MISMATCH:
    "ANALYTICS_CUSTOMER_PLAYER_CUSTOMER_MISMATCH",
  CUSTOMER_PLAYER_PLAYER_MISMATCH: "ANALYTICS_CUSTOMER_PLAYER_PLAYER_MISMATCH",
  CUSTOMER_PLAYER_LINK_TENANT_MISMATCH:
    "ANALYTICS_CUSTOMER_PLAYER_LINK_TENANT_MISMATCH",
  CUSTOMER_PLAYER_FACT_INVALID: "ANALYTICS_CUSTOMER_PLAYER_FACT_INVALID",
  CUSTOMER_PLAYER_SNAPSHOT_INVALID:
    "ANALYTICS_CUSTOMER_PLAYER_SNAPSHOT_INVALID",
  CUSTOMER_PLAYER_SOURCE_FAILURE: "ANALYTICS_CUSTOMER_PLAYER_SOURCE_FAILURE",
  CUSTOMER_PLAYER_QUERY_INVALID: "ANALYTICS_CUSTOMER_PLAYER_QUERY_INVALID",
  CUSTOMER_PLAYER_TIMESTAMP_INVALID:
    "ANALYTICS_CUSTOMER_PLAYER_TIMESTAMP_INVALID",
  CUSTOMER_PLAYER_ISOLATION_VIOLATION:
    "ANALYTICS_CUSTOMER_PLAYER_ISOLATION_VIOLATION",
  CUSTOMER_PLAYER_PRIVACY_VIOLATION:
    "ANALYTICS_CUSTOMER_PLAYER_PRIVACY_VIOLATION",
});

/**
 * @param {string} code
 * @param {string} message
 * @param {string} [field]
 * @param {Record<string, unknown>} [details]
 * @returns {Readonly<{ code: string, message: string, field?: string, details?: Readonly<Record<string, unknown>> }>}
 */
export function analyticsError(code, message, field, details) {
  /** @type {{ code: string, message: string, field?: string, details?: Readonly<Record<string, unknown>> }} */
  const error = { code, message };
  if (field !== undefined) {
    error.field = field;
  }
  if (details !== undefined) {
    error.details = Object.freeze({ ...details });
  }
  return Object.freeze(error);
}
