/**
 * Permission keys — format module.action hoặc module.resource.action.
 * Dùng chuỗi cố định để dễ audit và map sang RLS/policy sau này.
 */
export const PERMISSIONS = Object.freeze({
  // Hệ thống (SUPER_ADMIN)
  SYSTEM_MANAGE: "system.manage",
  SYSTEM_SUBSCRIPTIONS_VIEW: "system.subscriptions.view",
  SYSTEM_SUBSCRIPTIONS_MANAGE: "system.subscriptions.manage",
  SYSTEM_VENUES_VIEW: "system.venues.view",
  SYSTEM_VENUES_MANAGE: "system.venues.manage",
  SYSTEM_USERS_VIEW: "system.users.view",
  SYSTEM_USERS_MANAGE: "system.users.manage",

  // Venue / tenant
  VENUE_VIEW: "venue.view",
  VENUE_MANAGE: "venue.manage",
  VENUE_STAFF_MANAGE: "venue.staff.manage",
  VENUE_SUBSCRIPTION_VIEW: "venue.subscription.view",

  // Quản lý sân & đặt sân
  COURTS_VIEW: "courts.view",
  COURTS_MANAGE: "courts.manage",
  BOOKINGS_VIEW: "bookings.view",
  BOOKINGS_MANAGE: "bookings.manage",
  BOOKINGS_CREATE: "bookings.create",
  CUSTOMERS_VIEW: "customers.view",
  CUSTOMERS_MANAGE: "customers.manage",
  REVENUE_VIEW: "revenue.view",
  REVENUE_MANAGE: "revenue.manage",

  // Kế toán / thu ngân
  PAYMENTS_VIEW: "payments.view",
  PAYMENTS_COLLECT: "payments.collect",
  ACCOUNTING_VIEW: "accounting.view",
  ACCOUNTING_EXPORT: "accounting.export",
  ACCOUNTING_RECONCILE: "accounting.reconcile",

  // CLB
  CLUB_VIEW: "club.view",
  CLUB_MANAGE: "club.manage",
  CLUB_DELETE: "club.delete",
  SEASONS_MANAGE: "seasons.manage",
  LEAGUES_MANAGE: "leagues.manage",
  PLAYERS_VIEW: "players.view",
  PLAYERS_MANAGE: "players.manage",

  // Giải đấu & xếp sân
  TOURNAMENT_VIEW: "tournament.view",
  TOURNAMENT_MANAGE: "tournament.manage",
  TOURNAMENT_DIRECTOR: "tournament.director",
  TOURNAMENT_SCORE: "tournament.score",
  SCHEDULING_VIEW: "scheduling.view",
  SCHEDULING_RUN: "scheduling.run",

  // Thống kê & cài đặt
  STATISTICS_VIEW: "statistics.view",
  STATISTICS_EXPORT: "statistics.export",
  SETTINGS_VIEW: "settings.view",
  SETTINGS_MANAGE: "settings.manage",
  SETTINGS_CLOUD_SYNC: "settings.cloud_sync",

  // Vận động viên (self-service)
  PLAYER_SCHEDULE_VIEW: "player.schedule.view",
  PLAYER_REGISTRATION_MANAGE: "player.registration.manage",
  PLAYER_RESULTS_VIEW: "player.results.view",
  PLAYER_PROFILE_VIEW: "player.profile.view",
  PLAYER_PROFILE_EDIT: "player.profile.edit",
});

/** Phạm vi kiểm tra khi authorize. */
export const PERMISSION_SCOPE = Object.freeze({
  GLOBAL: "global",
  VENUE: "venue",
  CLUB: "club",
  SELF: "self",
});

/** Metadata: permission → scope type (dùng trong rbac.js). */
export const PERMISSION_META = Object.freeze({
  [PERMISSIONS.SYSTEM_MANAGE]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.SYSTEM_SUBSCRIPTIONS_VIEW]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.SYSTEM_SUBSCRIPTIONS_MANAGE]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.SYSTEM_VENUES_VIEW]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.SYSTEM_VENUES_MANAGE]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.SYSTEM_USERS_VIEW]: PERMISSION_SCOPE.GLOBAL,
  [PERMISSIONS.SYSTEM_USERS_MANAGE]: PERMISSION_SCOPE.GLOBAL,

  [PERMISSIONS.VENUE_VIEW]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.VENUE_MANAGE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.VENUE_STAFF_MANAGE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.VENUE_SUBSCRIPTION_VIEW]: PERMISSION_SCOPE.VENUE,

  [PERMISSIONS.COURTS_VIEW]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.COURTS_MANAGE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.BOOKINGS_VIEW]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.BOOKINGS_MANAGE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.BOOKINGS_CREATE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.CUSTOMERS_VIEW]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.CUSTOMERS_MANAGE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.REVENUE_VIEW]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.REVENUE_MANAGE]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.PAYMENTS_VIEW]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.PAYMENTS_COLLECT]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.ACCOUNTING_VIEW]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.ACCOUNTING_EXPORT]: PERMISSION_SCOPE.VENUE,
  [PERMISSIONS.ACCOUNTING_RECONCILE]: PERMISSION_SCOPE.VENUE,

  [PERMISSIONS.CLUB_VIEW]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.CLUB_MANAGE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.CLUB_DELETE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.SEASONS_MANAGE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.LEAGUES_MANAGE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.PLAYERS_VIEW]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.PLAYERS_MANAGE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.TOURNAMENT_VIEW]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.TOURNAMENT_MANAGE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.TOURNAMENT_DIRECTOR]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.TOURNAMENT_SCORE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.SCHEDULING_VIEW]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.SCHEDULING_RUN]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.STATISTICS_VIEW]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.STATISTICS_EXPORT]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.SETTINGS_VIEW]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.SETTINGS_MANAGE]: PERMISSION_SCOPE.CLUB,
  [PERMISSIONS.SETTINGS_CLOUD_SYNC]: PERMISSION_SCOPE.CLUB,

  [PERMISSIONS.PLAYER_SCHEDULE_VIEW]: PERMISSION_SCOPE.SELF,
  [PERMISSIONS.PLAYER_REGISTRATION_MANAGE]: PERMISSION_SCOPE.SELF,
  [PERMISSIONS.PLAYER_RESULTS_VIEW]: PERMISSION_SCOPE.SELF,
  [PERMISSIONS.PLAYER_PROFILE_VIEW]: PERMISSION_SCOPE.SELF,
  [PERMISSIONS.PLAYER_PROFILE_EDIT]: PERMISSION_SCOPE.SELF,
});

export function isValidPermission(permission) {
  return Object.values(PERMISSIONS).includes(permission);
}

export function getPermissionScope(permission) {
  return PERMISSION_META[permission] || PERMISSION_SCOPE.GLOBAL;
}
