import { ROLES } from "./roles.js";
import { PERMISSIONS } from "./permissions.js";

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const VENUE_OPS = [
  PERMISSIONS.VENUE_VIEW,
  PERMISSIONS.COURTS_VIEW,
  PERMISSIONS.COURTS_MANAGE,
  PERMISSIONS.BOOKINGS_VIEW,
  PERMISSIONS.BOOKINGS_MANAGE,
  PERMISSIONS.BOOKINGS_CREATE,
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.CUSTOMERS_MANAGE,
  PERMISSIONS.REVENUE_VIEW,
  PERMISSIONS.CLUB_VIEW,
  PERMISSIONS.PLAYERS_VIEW,
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.TOURNAMENT_MANAGE,
  PERMISSIONS.TOURNAMENT_DIRECTOR,
  PERMISSIONS.TOURNAMENT_SCORE,
  PERMISSIONS.SCHEDULING_VIEW,
  PERMISSIONS.SCHEDULING_RUN,
  PERMISSIONS.STATISTICS_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
];

const VENUE_OWNER_PERMISSIONS = [
  ...VENUE_OPS,
  PERMISSIONS.VENUE_MANAGE,
  PERMISSIONS.VENUE_STAFF_MANAGE,
  PERMISSIONS.VENUE_SUBSCRIPTION_VIEW,
  PERMISSIONS.REVENUE_MANAGE,
  PERMISSIONS.CLUB_MANAGE,
  PERMISSIONS.CLUB_DELETE,
  PERMISSIONS.SEASONS_MANAGE,
  PERMISSIONS.LEAGUES_MANAGE,
  PERMISSIONS.PLAYERS_MANAGE,
  PERMISSIONS.STATISTICS_EXPORT,
  PERMISSIONS.SETTINGS_MANAGE,
  PERMISSIONS.SETTINGS_CLOUD_SYNC,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.PAYMENTS_COLLECT,
  PERMISSIONS.ACCOUNTING_VIEW,
  PERMISSIONS.ACCOUNTING_EXPORT,
  PERMISSIONS.ACCOUNTING_RECONCILE,
];

const VENUE_MANAGER_PERMISSIONS = [...VENUE_OPS, PERMISSIONS.PLAYERS_MANAGE];

const CASHIER_PERMISSIONS = [
  PERMISSIONS.COURTS_VIEW,
  PERMISSIONS.BOOKINGS_VIEW,
  PERMISSIONS.BOOKINGS_CREATE,
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.PAYMENTS_COLLECT,
];

const ACCOUNTANT_PERMISSIONS = [
  PERMISSIONS.BOOKINGS_VIEW,
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.REVENUE_VIEW,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.ACCOUNTING_VIEW,
  PERMISSIONS.ACCOUNTING_EXPORT,
  PERMISSIONS.ACCOUNTING_RECONCILE,
  PERMISSIONS.STATISTICS_VIEW,
];

const CLUB_OWNER_PERMISSIONS = [
  PERMISSIONS.CLUB_VIEW,
  PERMISSIONS.CLUB_MANAGE,
  PERMISSIONS.SEASONS_MANAGE,
  PERMISSIONS.LEAGUES_MANAGE,
  PERMISSIONS.PLAYERS_VIEW,
  PERMISSIONS.PLAYERS_MANAGE,
  PERMISSIONS.TOURNAMENT_VIEW,
  PERMISSIONS.TOURNAMENT_MANAGE,
  PERMISSIONS.TOURNAMENT_DIRECTOR,
  PERMISSIONS.TOURNAMENT_SCORE,
  PERMISSIONS.SCHEDULING_VIEW,
  PERMISSIONS.SCHEDULING_RUN,
  PERMISSIONS.STATISTICS_VIEW,
  PERMISSIONS.STATISTICS_EXPORT,
  PERMISSIONS.SETTINGS_VIEW,
];

const PLAYER_PERMISSIONS = [
  PERMISSIONS.PLAYER_SCHEDULE_VIEW,
  PERMISSIONS.PLAYER_REGISTRATION_MANAGE,
  PERMISSIONS.PLAYER_RESULTS_VIEW,
  PERMISSIONS.PLAYER_PROFILE_VIEW,
  PERMISSIONS.PLAYER_PROFILE_EDIT,
];

/** Map role → danh sách permission (immutable). */
export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.freeze([...ALL_PERMISSIONS]),
  [ROLES.VENUE_OWNER]: Object.freeze(VENUE_OWNER_PERMISSIONS),
  [ROLES.VENUE_MANAGER]: Object.freeze(VENUE_MANAGER_PERMISSIONS),
  [ROLES.CASHIER]: Object.freeze(CASHIER_PERMISSIONS),
  [ROLES.ACCOUNTANT]: Object.freeze(ACCOUNTANT_PERMISSIONS),
  [ROLES.CLUB_OWNER]: Object.freeze(CLUB_OWNER_PERMISSIONS),
  [ROLES.PLAYER]: Object.freeze(PLAYER_PERMISSIONS),
});

export function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

export function roleHasPermission(role, permission) {
  return getPermissionsForRole(role).includes(permission);
}
